objects/ASI_KOR_Brand__c.object
<CustomObject>
    <description>ASI KOR</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ASI_KOR_POSM_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_KOR_Fiscal_Year__c</fullName>
        <defaultValue>IF(MONTH(TODAY()) &gt;= 7, 
				&apos;FY&apos; &amp; RIGHT(TEXT(YEAR(TODAY())), 2) &amp; RIGHT(TEXT(YEAR(ADDMONTHS(TODAY(), 12))), 2), 
				&apos;FY&apos; &amp; RIGHT(TEXT(YEAR(ADDMONTHS(TODAY(), -12))), 2) &amp; RIGHT(TEXT(YEAR(TODAY())), 2) 
			)</defaultValue>
        <label>Fiscal Year</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_POSM_TO_Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ASI_KOR_Venue</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>POSM Order Requests</relationshipLabel>
        <relationshipName>POSM_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_KOR_Sub_brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-brand</label>
        <referenceTo>ASI_KOR_Sub_Brand__c</referenceTo>
        <relationshipLabel>POSM Order Requests</relationshipLabel>
        <relationshipName>POSM_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>POSM Order Request</label>
    <nameField>
        <displayFormat>POSM-{0000}</displayFormat>
        <label>POSM Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POSM Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_KOR_Sub_Brand__c.object
<CustomObject>
    <fields>
        <fullName>ASI_KOR_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>ASI_KOR_Brand__c</referenceTo>
        <relationshipLabel>Product Items</relationshipLabel>
        <relationshipName>Sub_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Sub_Brand_Code__c</fullName>
        <externalId>true</externalId>
        <label>Sub-Brand Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Item</label>
    <nameField>
        <label>Sub-Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ASI_KOR_BarStylingWarningPageCtrl_Test.cls
/***************************************************************************************************************************
* Name:        ASI_KOR_BarStylingWarningPageController
* Description: Controller for ASI_KOR_BarStylingWarningPage
*
* Version History
* Date             Developer               Comments
* ---------------  --------------------    --------------------------------------------------------------------------------
* 2019-06-17       Wilson Chow                Created
****************************************************************************************************************************/

@isTest
public class ASI_KOR_BarStylingWarningPageCtrl_Test {

    @isTest
    static void testASI_KOR_BarStylingWarningPage() {

        map<string, id> rt_map = ASI_MFM_Function.getRecordTypeId('ASI_KOR_POSM_Order_Request__c');
        rt_map = ASI_MFM_Function.getRecordTypeId('Account');
        Account supplierAccount = new Account(
                recordTypeId = rt_map.get('ASI_KOR_Venue'),
                Name = 'Name1'
        );
        insert supplierAccount;
        String supplierAccountId = supplierAccount.Id;

        ASI_KOR_Brand__c brand = new ASI_KOR_Brand__c(
                Name = 'brand_name'
        );
        insert brand;

        ASI_KOR_Sub_Brand__c subBrand = new ASI_KOR_Sub_Brand__c(
                Name = 'TestSubBrand',
                ASI_KOR_Brand__c = brand.Id,
                ASI_KOR_Sub_Brand_Code__c = 'sub_brand_code'
        );
        insert subBrand;

        ASI_KOR_POSM_Order_Request__c posmHeader = new ASI_KOR_POSM_Order_Request__c(
                recordTypeId = Global_RecordTypeCache.getRtId('ASI_KOR_POSM_Order_Request__cASI_KOR_Bar_Styling_POSM_Request'),
                ASI_KOR_POSM_TO_Venue__c = supplierAccountId,
                ASI_KOR_Status__c = 'Draft',
                ASI_KOR_Fiscal_Year__c = 'FY0001',
                ASI_KOR_Sub_Brand__c = subBrand.Id
        );
        insert posmHeader;

        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(posmHeader);

        PageReference warningPage = Page.ASI_KOR_BarStylingWarningPage;
        Test.setCurrentPage(warningPage);
        ApexPages.currentPage().getParameters().put('id', posmHeader.Id);

        Test.setCurrentPageReference(warningPage);

        Test.startTest();
        try {
            ASI_KOR_BarStylingWarningPageController barStylingWarningPageCtrl =
                    new ASI_KOR_BarStylingWarningPageController(sc);
            barStylingWarningPageCtrl.init();
        }
        catch(Exception e) {

        }
        Test.stopTest();
    }
}