objects/ASI_MFM_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Prefix__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Prefix</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>KR Plan, KR Plan Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Prefix__c.ASI_MFM_Module__c</field>
                <operation>equals</operation>
                <value>Plan</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>KR Plan, KR Plan Read-Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Prefix__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <recordTypes>
        <fullName>ASI_MFM_PH_DF_Plan</fullName>
        <active>true</active>
        <label>PH DF Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_MFM_PH_DP_Plan</fullName>
        <active>true</active>
        <label>PH DP Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_MFM_VN_DF_Plan</fullName>
        <active>true</active>
        <label>VN DF Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_MFM_VN_DP_Plan</fullName>
        <active>true</active>
        <label>VN DP Plan</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Prefix__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check when do not want to show in the select prefix page.</description>
        <inlineHelpText>Check the box when do not want to show in the select prefix page.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Module__c</fullName>
        <label>Module</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>CN Vendor PR</fullName>
                    <label>PR(CN Vendor)</label>
                </value>
                <value>
                    <fullName>Direct Payment</fullName>
                </value>
                <value>
                    <fullName>Direct PO</fullName>
                </value>
                <value>
                    <fullName>Dummy Payment</fullName>
                </value>
                <value>
                    <fullName>Dummy PO</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Budget</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Payment</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Accrual</fullName>
                </value>
                <value>
                    <fullName>Structure Cost Rental Payment</fullName>
                </value>
                <value>
                    <fullName>Accrual PO</fullName>
                </value>
                <value>
                    <fullName>POSM Return</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_PAF_Prefix__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PAF Prefix</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_country_name__c</fullName>
        <formula>text(Owner:User.ASI_MFM_Country__c)</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>ASI MFM Prefix</label>
    <nameField>
        <label>Prefix</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASI MFM Prefixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Role_Prefix_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Prefix__c</fullName>
        <label>Prefix</label>
        <referenceTo>ASI_MFM_Prefix__c</referenceTo>
        <relationshipLabel>ASI MFM Role Prefix Relationships</relationshipLabel>
        <relationshipName>ASI_MFM_Role_Prefix_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ASI_MFM_Role_Name__c</fullName>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ASI MFM Role Prefix Relationship</label>
    <nameField>
        <displayFormat>RPR{000000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASI MFM Role Prefix Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Country__c</fullName>
        <label>ASI MFM Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TW</fullName>
                </value>
                <value>
                    <fullName>HK</fullName>
                </value>
                <value>
                    <fullName>GF</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>RM</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TR</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>PH</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>VN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_MFM_SelectPlanPrefixLWC_Cls.cls
public with sharing class ASI_MFM_SelectPlanPrefixLWC_Cls {
    //20200915:HF@introv - copy from ASI_MFM_SelectPlanPrefixController

    @AuraEnabled(cacheable = true)
	public static List<Selection> getPrefixes(Id RecordTypeId) {
        List<Selection> prefixList = new List<Selection>();
        List<Selection> errorList = new List<Selection>();
    	map<string, asi_mfm_role_prefix_relationship__c> px_map = new map<string, asi_mfm_role_prefix_relationship__c>();   

        user u = [select userRole.developerName, asi_mfm_country__c from user where id = :userInfo.getUserId()];
        if (u.userRole.developerName == null) {
            errorList.add(new Selection('','',true, 'The role of the user is not defined yet'));
            return errorList;
        }
        else if (u.asi_mfm_country__c == null) {
            errorList.add(new Selection('','',true, 'The country of the user is not defined yet'));
            return errorList;
        }
        else {
            list<asi_mfm_role_prefix_relationship__c> px_list = new list<asi_mfm_role_prefix_relationship__c>();
            for (asi_mfm_role_prefix_relationship__c px:[
                	select asi_mfm_prefix__c, asi_mfm_prefix__r.name,asi_mfm_prefix__r.RecordType.DeveloperName, asi_mfm_prefix__r.ASI_MFM_PAF_Prefix__c, asi_mfm_prefix__r.ASI_MFM_Description__c 
                	from asi_mfm_role_prefix_relationship__c
                	where asi_mfm_prefix__r.ASI_MFM_Inactive__c = false 
                	and asi_mfm_prefix__r.asi_mfm_module__c = 'Plan' 
                	and asi_mfm_role_name__c = :u.userRole.developerName 
                	and asi_mfm_prefix__r.asi_mfm_country_name__c = :u.asi_mfm_country__c 
                	order by asi_mfm_prefix__r.name]) {
                        px_map.put(px.asi_mfm_prefix__c, px);
                        px_list.add(px);
                        /*if(u.asi_mfm_country__c != 'TW'){
                                px_map.put(px.asi_mfm_prefix__c, px);
                                px_list.add(px);
                        }
                        else
                        {
                            if(px.asi_mfm_prefix__r.ASI_MFM_PAF_Prefix__c == false){
                                px_map.put(px.asi_mfm_prefix__c, px);
                                px_list.add(px); 
                            }
                        }*/
                    }
            		/*
                    if(u.asi_mfm_country__c=='KR'){//For KR User only
                        return new pageReference('/apex/ASI_MFM_KR_SelectProjectCodePage?Module=Plan'); 
                    }
					*/
            if (px_list.size() == 0) {
                errorList.add(new Selection('', '', true, 'The user is not entitled to input plans'));
                return errorList;
            }
            /*else if(u.asi_mfm_country__c=='PH' && px_list.size()>1){ 
                String Recordtypeid = ApexPages.currentPage().getParameters().get('RecordType');
                System.debug('Recordtypeid = ' +ApexPages.currentPage().getParameters());
                Map<String, id> MPlanRecType = new Map<String,id>();
                for(Recordtype r : Global_recordTypeCache.getRtList('ASI_MFM_Plan__c')){
                    MPlanRecType.put(r.developername,r.id);
                }
                if(MPlanRecType.get('ASI_MFM_PH_DP_Plan')==Recordtypeid){
                    available_prefixes = new list<selectOption>();
                    available_prefixes.add(new selectOption('', '-- None --'));
                    for (asi_mfm_role_prefix_relationship__c rp:px_list) {
                        if(rp.asi_mfm_prefix__r.name.contains('DP')){
                            available_prefixes.add(new selectOption(rp.asi_mfm_prefix__c, rp.asi_mfm_prefix__r.name));
                        }
                  }
                    
                    if(available_prefixes.size()==2){
                        selected_prefix=available_prefixes[1].getValue();
                        return proceed();
                    }else{
                        return null;
                    }
                    
                }
                 if(MPlanRecType.get('ASI_MFM_PH_DF_Plan')==Recordtypeid){
                    available_prefixes = new list<selectOption>();
                    available_prefixes.add(new selectOption('', '-- None --'));
                    for (asi_mfm_role_prefix_relationship__c rp:px_list) {
                        if(rp.asi_mfm_prefix__r.name.contains('DF')){
                            available_prefixes.add(new selectOption(rp.asi_mfm_prefix__c, rp.asi_mfm_prefix__r.name));
                        }
                  }
                    if(available_prefixes.size()==2){
                        selected_prefix=available_prefixes[1].getValue();
                        return proceed();
                    }else{
                        return null;
                    }
                }
                
                if(MPlanRecType.get('ASI_MFM_PH_DF_Plan')!=Recordtypeid && MPlanRecType.get('ASI_MFM_PH_DP_Plan')!=Recordtypeid){
                    available_prefixes = new list<selectOption>();
                    available_prefixes.add(new selectOption('', '-- None --'));
                    for (asi_mfm_role_prefix_relationship__c rp:px_list) {
                        available_prefixes.add(new selectOption(rp.asi_mfm_prefix__c, rp.asi_mfm_prefix__r.name));
                    }
                }
                
            }*/
            /*else if(u.asi_mfm_country__c=='VN' && px_list.size()>1){
                String Recordtypeid = ApexPages.currentPage().getParameters().get('RecordType');
                System.debug('Recordtypeid = ' +ApexPages.currentPage().getParameters());
                Map<String, id> MPlanRecType = new Map<String,id>();
                for(Recordtype r : Global_recordTypeCache.getRtList('ASI_MFM_Plan__c')){
                    MPlanRecType.put(r.developername,r.id);
                }
                if(MPlanRecType.get('ASI_MFM_VN_DP_Plan')==Recordtypeid){
                    available_prefixes = new list<selectOption>();
                    available_prefixes.add(new selectOption('', '-- None --'));
                    for (asi_mfm_role_prefix_relationship__c rp:px_list) {
                        if(rp.asi_mfm_prefix__r.name.contains('DP')){
                            available_prefixes.add(new selectOption(rp.asi_mfm_prefix__c, rp.asi_mfm_prefix__r.name));
                        }
                    }

                    if(available_prefixes.size()==2){
                        selected_prefix=available_prefixes[1].getValue();
                        return proceed();
                    }else{
                        return null;
                    }

                }
                if(MPlanRecType.get('ASI_MFM_VN_DF_Plan')==Recordtypeid){
                    available_prefixes = new list<selectOption>();
                    available_prefixes.add(new selectOption('', '-- None --'));
                    for (asi_mfm_role_prefix_relationship__c rp:px_list) {
                        if(rp.asi_mfm_prefix__r.name.contains('DF')){
                            available_prefixes.add(new selectOption(rp.asi_mfm_prefix__c, rp.asi_mfm_prefix__r.name));
                        }
                    }
                    if(available_prefixes.size()==2){
                        selected_prefix=available_prefixes[1].getValue();
                        return proceed();
                    }else{
                        return null;
                    }
                }

                if(MPlanRecType.get('ASI_MFM_VN_DF_Plan')!=Recordtypeid && MPlanRecType.get('ASI_MFM_VN_DP_Plan')!=Recordtypeid){
                    available_prefixes = new list<selectOption>();
                    available_prefixes.add(new selectOption('', '-- None --'));
                    for (asi_mfm_role_prefix_relationship__c rp:px_list) {
                        available_prefixes.add(new selectOption(rp.asi_mfm_prefix__c, rp.asi_mfm_prefix__r.name));
                    }
                }
                
            }*/
            else {
                prefixList = new List<Selection>();
                prefixList.add(new Selection('','-- None --',false,''));
                for (asi_mfm_role_prefix_relationship__c rp:px_list) {
                    string sTmpDesc = (rp.asi_mfm_prefix__r.ASI_MFM_Description__c == NULL?'-':rp.asi_mfm_prefix__r.ASI_MFM_Description__c);
                    prefixList.add(new Selection(rp.asi_mfm_prefix__c, rp.asi_mfm_prefix__r.name, sTmpDesc));
                }
            }
        }
        system.debug('prefixList : ' + prefixList);
        List<Selection> test = new List<Selection>();
        /*test.add(prefixList[0]);
		test.add(prefixList[1]);
        return test;*/
        return prefixList;
    }
    
    public class Selection {
        @AuraEnabled 
        public String selectionName {get; set;}
        
        @AuraEnabled
        public String selectionId {get; set;}
        
        @AuraEnabled
        public boolean error {get; set;}
        
        @AuraEnabled
        public String errorMsg {get; set;}
        
        @AuraEnabled
        public String selectionDesc {get; set;}
        
                
        public Selection(String selectionId, String selectionName, boolean error, String errorMsg) {
        	this.selectionName = selectionName;
            this.selectionId = selectionId;     
            this.error = error;  
            this.errorMsg = selectionId;  
        }
        
        public Selection(String selectionId, String selectionName, String selectionDesc) {
        	this.selectionName = selectionName;
            this.selectionId = selectionId;
            this.selectionDesc = selectionDesc;
            this.error = false;  
        }
    }
}