objects/ASI_KOR_NSD_Payment_Settlement_Header__c.object
<CustomObject>
    <description>For PRK Phase 2</description>
    <fields>
        <fullName>ASI_KOR_Month__c</fullName>
        <label>Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_SYS_Cut_off_Date__c</fullName>
        <label>Cut-off Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Year__c</fullName>
        <label>Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Settlement (NSD)</label>
    <nameField>
        <displayFormat>NPS-{00000000}</displayFormat>
        <label>NSD Payment Settlement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Settlements (NSD)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_KOR_RSD_Payment_Settlement_Header__c.object
<CustomObject>
    <description>For PRK Phase 2</description>
    <fields>
        <fullName>ASI_KOR_Month__c</fullName>
        <label>Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Region__c</fullName>
        <formula>Owner:User.ASI_KOR_User_Region_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_SYS_Cut_off_Date__c</fullName>
        <label>Cut-off Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Year__c</fullName>
        <label>Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Settlement (RSD)</label>
    <nameField>
        <displayFormat>RPS-{00000000}</displayFormat>
        <label>RSD Payment Settlement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Settlements (RSD)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_KOR_SR_Payment_Settlement_Header__c.object
<CustomObject>
    <description>For PRK Phase 2</description>
    <fields>
        <fullName>ASI_KOR_Month__c</fullName>
        <defaultValue>IF(MONTH(Today())=1, &quot;12&quot;, TEXT(MONTH(Today())-1))</defaultValue>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_KOR_Region__c</fullName>
        <formula>Owner:User.ASI_KOR_User_Region_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Year__c</fullName>
        <defaultValue>IF(MONTH(Today())=1, TEXT(YEAR(Today())-1), TEXT(YEAR(Today())))</defaultValue>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Settlement (SR)</label>
    <nameField>
        <displayFormat>SRS-{00000000}</displayFormat>
        <label>SR Payment Settlement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Settlements (SR)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ASI_KOR_User_Region_Name__c</fullName>
        <label>User Region Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_KOR_SRPaymentSettlementValidation.cls
public class ASI_KOR_SRPaymentSettlementValidation extends ASI_KOR_TriggerAbstract{

  public ASI_KOR_SRPaymentSettlementValidation() {
    super('ASI_KOR_SRPaymentSettlementValidation');
  }
  
  public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
    if (tAction == TriggerAction.BEFORE_INSERT) {
        
        integer count = 0;
        for(ASI_KOR_SR_Payment_Settlement_Header__c newValues : (List<ASI_KOR_SR_Payment_Settlement_Header__c>)sObjList){
         
         if(count==0) {
             /*
             List<ASI_KOR_NSD_Payment_Settlement_Header__c> nsd =[Select id, ASI_KOR_SYS_Cut_off_date__c From ASI_KOR_NSD_Payment_Settlement_Header__c where ASI_KOR_Month__c = :newValues.ASI_KOR_Month__c and ASI_KOR_Year__c = :newValues.ASI_KOR_Year__c];
			*/        
             user u = [select id, ASI_KOR_User_Region_Name__c from user where id = :newValues.ownerid];
             List<ASI_KOR_RSD_Payment_Settlement_Header__c> nsd =[Select id, ASI_KOR_SYS_Cut_off_date__c From ASI_KOR_RSD_Payment_Settlement_Header__c where ASI_KOR_Month__c = :newValues.ASI_KOR_Month__c and ASI_KOR_Year__c = :newValues.ASI_KOR_Year__c and ASI_KOR_Region__c = :u.ASI_KOR_User_Region_Name__c];
			if(nsd.size()>0){
                if(nsd.get(0).ASI_KOR_Sys_Cut_off_date__c==null)newValues.addError('Payment Settlement for Year: '+ newValues.ASI_KOR_Year__c + ' and Month: ' + newValues.ASI_KOR_Month__c + ' has not started.'   );
             }else{
                newValues.addError('Payment Settlement for Year: '+ newValues.ASI_KOR_Year__c + ' and Month: ' + newValues.ASI_KOR_Month__c + ' has not started.'   );
             }
         }
        
         count++;
       
       
        }

    }
    
  }

}