objects/ASI_MFM_Payment_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_PO_Line_Item__c</fullName>
        <label>PO Line Item</label>
        <referenceTo>ASI_MFM_PO_Line_Item__c</referenceTo>
        <relationshipLabel>Payment Line Items</relationshipLabel>
        <relationshipName>Payment_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO_Receipt_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO Receipt Item</label>
        <referenceTo>ASI_MFM_PO_Receipt_Item__c</referenceTo>
        <relationshipLabel>Payment Line Items</relationshipLabel>
        <relationshipName>Payment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO</label>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>Payment Line Items</relationshipLabel>
        <relationshipName>Payment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Payment_Status__c</fullName>
        <formula>TEXT(ASI_MFM_Payment__r.ASI_MFM_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Line Item</label>
        <referenceTo>ASI_MFM_Plan_Line_Item__c</referenceTo>
        <relationshipLabel>Payment Line Items</relationshipLabel>
        <relationshipName>Payment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Line Item</label>
    <nameField>
        <displayFormat>PYL{000000}</displayFormat>
        <label>Payment Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_Plan_Line_Item__c.object
<CustomObject>
    <label>Plan Line Item</label>
    <nameField>
        <displayFormat>PLI{000000}</displayFormat>
        <label>Plan Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_PO__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Plan_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Line Item</label>
        <referenceTo>ASI_MFM_Plan_Line_Item__c</referenceTo>
        <relationshipLabel>POs</relationshipLabel>
        <relationshipName>POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_PO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_PO_Status__c</fullName>
        <formula>Text( ASI_MFM_PO__r.ASI_MFM_Status__c )</formula>
        <label>PO Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO__c</fullName>
        <label>PO</label>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Line Item</label>
        <referenceTo>ASI_MFM_Plan_Line_Item__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO Line Item</label>
    <nameField>
        <displayFormat>POL{000000}</displayFormat>
        <label>PO Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_PO_Receipt_Item__c.object
<CustomObject>
    <description>MFM PO receipt item</description>
    <fields>
        <fullName>ASI_MFM_PO_Line_Item__c</fullName>
        <label>PO Item</label>
        <referenceTo>ASI_MFM_PO_Line_Item__c</referenceTo>
        <relationshipLabel>PO Receipt Items</relationshipLabel>
        <relationshipName>PO_Receipt_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO</label>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>PO Receipt Items</relationshipLabel>
        <relationshipName>PO_Receipt_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Line Item</label>
        <referenceTo>ASI_MFM_Plan_Line_Item__c</referenceTo>
        <relationshipLabel>PO Receipt Items</relationshipLabel>
        <relationshipName>PO_Receipt_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO Receipt Item</label>
    <nameField>
        <displayFormat>I{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Receipt Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_MFM_KR_POReceiptItem_TriggerClass.cls
public without sharing class ASI_MFM_KR_POReceiptItem_TriggerClass {
    public static void routineBeforeInsert(list<ASI_MFM_PO_Receipt_Item__c> trigger_new){
        set<id> POLineSet = new set<id>();
        //1st round loop get Id Set
        for (ASI_MFM_PO_Receipt_Item__c porl:trigger_new) {
            if(Global_RecordTypeCache.getRt(porl.recordTypeID).DeveloperName.contains('ASI_MFM_KR') && porl.ASI_MFM_PO_Line_Item__c!=null){
                POLineSet.add(porl.ASI_MFM_PO_Line_Item__c);
            }
        }
        
        Map<id,ASI_MFM_PO_Line_Item__c> POLineMap=new Map<id,ASI_MFM_PO_Line_Item__c>();
        if(POLineSet.size()>0){
            POLineMap =new Map<id,ASI_MFM_PO_Line_Item__c>([select id,ASI_MFM_PO__c,ASI_MFM_Plan_Line_Item__c from ASI_MFM_PO_Line_Item__c where id in : POLineSet]);
        }
        
        //2nd round loop update value
         for (ASI_MFM_PO_Receipt_Item__c porl:trigger_new) {
             if(POLineMap.size()>0 && porl.ASI_MFM_PO_Line_Item__c!=null){
                 if(POLineMap.containsKey(porl.ASI_MFM_PO_Line_Item__c)){
                     porl.ASI_MFM_PO__c=POLineMap.get(porl.ASI_MFM_PO_Line_Item__c).ASI_MFM_PO__c;
                     //UPDATE Plan field in PO reciept
                     if(POLineMap.get(porl.ASI_MFM_PO_Line_Item__c).ASI_MFM_Plan_Line_Item__c!=null)porl.ASI_MFM_Plan_Line_Item__c=POLineMap.get(porl.ASI_MFM_PO_Line_Item__c).ASI_MFM_Plan_Line_Item__c;  
                 }
             }
             
         }
    }
    
    
       
    
    public static void routineBeforeDelete(list<ASI_MFM_PO_Receipt_Item__c> trigger_old) {
        if(!ASI_MFM_ByPass_Setting.ByPassClass('ASI_MFM_KR_POReceiptItem_TriggerClass','KR')){
            
            Set<id> setIdPOR = new Set<id>();
            Map<id, ASI_MFM_Payment_Line_Item__c> mapPL = new Map<id, ASI_MFM_Payment_Line_Item__c>();
            Map<id, ASI_MFM_PO_Line_Item__c> mapPOL = new Map<id, ASI_MFM_PO_Line_Item__c>();
            Map<id, id> mapPORPOL = new Map<id, id>();
            
            for(ASI_MFM_PO_Receipt_Item__c p:trigger_old){
                setIdPOR.add(p.id);
                mapPORPOL.put(p.id, p.ASI_MFM_PO_Line_Item__c);
            }       
            for(ASI_MFM_Payment_Line_Item__c pa: [Select id, name, ASI_MFM_Payment_Status__c, ASI_MFM_PO_Receipt_Item__c from ASI_MFM_Payment_Line_Item__c where ASI_MFM_PO_Receipt_Item__c IN :setIdPOR]){
                mapPL.put(pa.ASI_MFM_PO_Receipt_Item__c, pa);
            }
            
            for(ASI_MFM_PO_Line_Item__c pol: [Select id, ASI_MFM_PO_Status__c, ASI_MFM_PO__r.name from ASI_MFM_PO_Line_Item__c where id IN: mapPORPOL.values()]){
                mapPOL.put(pol.id, pol);
            }
            
            for(ASI_MFM_PO_Receipt_Item__c p: trigger_old){
                // if there is Payment created, PO receipt can't be deleted
                if(mapPL.get(p.id) != null){
                    p.addError('Not allowed to delete because Payment is created');
                }
                
                // if PO status is 'Submitted', 'Approved' or 'Final', PO receipt can't be deleted
                if(!Test.isRunningTest() && (mapPOL.get(mapPORPOL.get(p.id)).ASI_MFM_PO_Status__c == 'Submitted' || mapPOL.get(mapPORPOL.get(p.id)).ASI_MFM_PO_Status__c == 'Final' || mapPOL.get(mapPORPOL.get(p.id)).ASI_MFM_PO_Status__c == 'Approved')){
                    p.addError('Not allowed to delete because PO ' + mapPOL.get(mapPORPOL.get(p.id)).ASI_MFM_PO__r.name + ' is \'Submitted\', \'Approved\' or \'Final\'');
                }
            }        
            
        }// End Delete checking
        
        
    }// routineBeforerDelete
    
    
}