objects/ASI_CRM_Call_Detail__c.object
<CustomObject>
    <description>ASI CRM - Call Details. The following countries are using this object: 
-PRJ</description>
    <fields>
        <fullName>ASI_CRM_Call_Plan__c</fullName>
        <label>Call Plan</label>
        <referenceTo>ASI_CRM_Call_Plan__c</referenceTo>
        <relationshipLabel>Call Details</relationshipLabel>
        <relationshipName>Call_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Call Detail</label>
    <nameField>
        <displayFormat>CDN{00000000}</displayFormat>
        <label>Call Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Call_Plan__c.object
<CustomObject>
    <description>ASI CRM - Call Plan. The following countries are using this object:
-PRJ</description>
    <label>Call Plan</label>
    <nameField>
        <label>Call Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Plans</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_JP_Call_Plan_Locked</fullName>
        <active>true</active>
        <label>JP Call Plan Locked</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Payment_Invoice__c.object
<CustomObject>
    <description>ASI CRM JP - Payment Invoice</description>
    <label>Payment Invoice</label>
    <nameField>
        <label>Payment Invoice Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Invoices</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_JP_Indirect_Rebate_Invoice_Read_Only</fullName>
        <active>true</active>
        <label>JP Indirect Rebate Invoice Read-Only</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_JP_SPTD_Cash_Invoice_Read_Only</fullName>
        <active>true</active>
        <label>JP SPTD Cash Invoice Read-Only</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_JP_SPTD_FOC_Invoice_Read_Only</fullName>
        <active>true</active>
        <label>JP SPTD FOC Invoice Read-Only</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Payment_Invoice_Line_Item__c.object
<CustomObject>
    <description>ASI CRM JP - Payment Invoice Line</description>
    <fields>
        <fullName>ASI_CRM_Payment_Invoice__c</fullName>
        <label>Payment Invoice</label>
        <referenceTo>ASI_CRM_Payment_Invoice__c</referenceTo>
        <relationshipLabel>Payment Invoice Line Items</relationshipLabel>
        <relationshipName>Payment_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Purchase_Contract_Line_Item__c</fullName>
        <label>Contract Line</label>
        <referenceTo>ASI_CRM_Purchase_Contract_Line_Item__c</referenceTo>
        <relationshipLabel>Payment Invoice Line Items</relationshipLabel>
        <relationshipName>Payment_Invoice_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Payment Invoice Line Item</label>
    <nameField>
        <displayFormat>PIL{000000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Purchase_Contract__c.object
<CustomObject>
    <description>ASI CRM JP - Purchase Contract</description>
    <label>Purchase Contract</label>
    <nameField>
        <label>Contract No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Contracts</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_JP_Direct_Rebate_Contract_Read_Only</fullName>
        <active>true</active>
        <label>JP Direct Rebate Contract Read-Only</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_JP_Indirect_Rebate_Contract_Read_Only</fullName>
        <active>true</active>
        <label>JP Indirect Rebate Contract Read-Only</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_JP_SPTD_Contract_Read_Only</fullName>
        <active>true</active>
        <label>JP SPTD Contract Read-Only</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Purchase_Contract_Line_Item__c.object
<CustomObject>
    <description>ASI CRM JP - Purchase Contract Line</description>
    <fields>
        <fullName>ASI_CRM_Purchase_Contract__c</fullName>
        <label>Purchase Contract</label>
        <referenceTo>ASI_CRM_Purchase_Contract__c</referenceTo>
        <relationshipLabel>Purchase Contract Line Items</relationshipLabel>
        <relationshipName>Purchase_Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Purchase Contract Line Item</label>
    <nameField>
        <displayFormat>PCL{00000000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CRM_JP_ProtectDelete_Record.cls
/*********************************************************************************
 * Name:ASI_CRM_JP_ProtectDelete_Record
 * Description: Generic class to protect lines to be deleted
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 26/01/2015       Laputa: Conrad          Created
*********************************************************************************/

public with sharing class ASI_CRM_JP_ProtectDelete_Record extends ASI_CRM_JP_TriggerAbstract {

    public static Final Map<String, String> masterDetailFields = new Map<String, String>{
                                                                                'ASI_CRM_Call_Detail__c' => 'ASI_CRM_Call_Plan__c',
                                                                                'ASI_CRM_Payment_Invoice_Line_Item__c' => 'ASI_CRM_Payment_Invoice__c',
                                                                                'ASI_CRM_Purchase_Contract_Line_Item__c' => 'ASI_CRM_Purchase_Contract__c'
                                                                            };
    
    public static Final Set<String> recordtypeProtectKeyword = new Set<String>{
                                                                            'ASI_CRM_JP_Call_Plan_Locked',
                                                                            'ASI_CRM_JP_Indirect_Rebate_Invoice_Read_Only',
                                                                            'ASI_CRM_JP_SPTD_Cash_Invoice_Read_Only',
                                                                            'ASI_CRM_JP_SPTD_FOC_Invoice_Read_Only',
                                                                            'ASI_CRM_JP_Direct_Rebate_Contract_Read_Only',
                                                                            'ASI_CRM_JP_Indirect_Rebate_Contract_Read_Only',
                                                                            'ASI_CRM_JP_SPTD_Contract_Read_Only'
                                                                        };
    
    public ASI_CRM_JP_ProtectDelete_Record() {
        super('ASI_CRM_JP_ProtectDelete_Record');
    }
    
    public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
        
        List<sObject> validsObject = new List<sObject>();
        Set<ID> sObjectHeaderIds = new Set<ID>();
        String headerObject = '';
        Map<ID, sObject> headersObjectMap = new Map<ID, sObject>();
        
        for(sObject obj : sObjList) {
        
            String sObjectName = obj.getSObjectType().getDescribe().getName();
            if(masterDetailFields.containsKey(sObjectName)) {
                String sObjectMasterField = masterDetailFields.get(sObjectName);
                headerObject = sObjectMasterField;
                sObjectHeaderIds.add((ID)(obj.get(sObjectMasterField)));
            } else {
                String recordtypeDevelopername = Global_RecordTypeCache.getRt((ID)(obj.get('recordtypeid'))).developername;
                if(recordtypeProtectKeyword.contains(recordtypeDevelopername)) {
                    validsObject.add(obj);
                }
            }
        }
        
        if(sObjectHeaderIds.size() > 0 && headerObject != '') {
            String query = 'SELECT ID, Name, recordtype.developername FROM ' + headerObject + ' WHERE ID IN : sObjectHeaderIds ';
            List<sObject> sObjectList = database.query(query);
            for(sObject obj : sObjectList) {
                headersObjectMap.put((id)(obj.get('id')), obj);
            }
        }
        
        if(headersObjectMap.size() > 0) {
            for(sObject obj : sObjList) {

                if(headersObjectMap.containsKey((ID)(obj.get(headerObject)))) {
                    sObject header = headersObjectMap.get((ID)(obj.get(headerObject)));
                    if(recordtypeProtectKeyword.contains((String)((header.getSObject('recordtype')).get('developername')))) {
                        validsObject.add(obj);
                    }
                }
            }
        }
        
        if(validsObject.size() > 0) {
            for(sObject obj : sObjList) {
                obj.adderror(Label.ASI_CRM_JP_Invalid_Delete);
            }
        }
        
    }

}