objects/ASI_CRM_Physical_Inventory_Check__c.object
<CustomObject>
    <label>Physical Inventory Check</label>
    <nameField>
        <displayFormat>PIC-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physical Inventory Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Physical_Inventory_Check_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Date_of_Checking__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date of Checking</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Inventory_Btl__c</fullName>
        <label>Inventory (Btl)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Inventory_Btl_from_WS__c</fullName>
        <label>Inventory (Btl) from WS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN Physical Inventory Check Item</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Item_Group__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN CRM Item Group</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Item_Group__c.ASI_MFM_Item_Group_Code__c</field>
                <operation>equals</operation>
                <valueField>ASI_MFM_Item_Group__c.ASI_CRM_CN_Consumer_web_Code_C__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Physical Inventory Check Items</relationshipLabel>
        <relationshipName>Physical_Inventory_Check_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Physical_Inventory_Check__c</fullName>
        <label>Physical Inventory Check</label>
        <referenceTo>ASI_CRM_Physical_Inventory_Check__c</referenceTo>
        <relationshipLabel>Physical Inventory Check Items</relationshipLabel>
        <relationshipName>Physical_Inventory_Check_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Physical Inventory Check Item</label>
    <nameField>
        <displayFormat>PICI-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physical Inventory Check Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_PhysicalICI_Upsert.cls
@RestResource(UrlMapping='/ASI_CRM_CN_PhysicalICI_Upsert/*')
global without sharing class ASI_CRM_CN_PhysicalICI_Upsert {

    global Class PhysicalInventoryLI{
        global list <PhysicalInventoryItemStructure> PhysicalInventoryItemList { set; get; }
    }
    
    /* Sample Json Format
	{"jsonString":"{\"PhysicalInventoryItemList\":[{\"recordID\":\"aCqM00000008QBg\",\"DateOfChecking\":\"2015/08/31\",\"InventoryBtl\":\"1\",\"InventoryBtlFromWS\":\"2\",\"itemGroup\":\"a7GM00000008Sj7\",\"PhysicalInventoryCheck\":\"\"},{\"recordID\":\"\",\"DateOfChecking\":\"2015/05/21\",\"InventoryBtl\":\"1\",\"InventoryBtlFromWS\":\"2\",\"itemGroup\":\"a7GM00000008Sgv\",\"PhysicalInventoryCheck\":\"aCpM00000008OO2\"}]}"}
    */
    
    @HttpPost
    global static string upsertPhysicalInventoryItem (String jsonString ){
        
        PhysicalInventoryLI PhysicalInventoryLIList = (PhysicalInventoryLI)JSON.deserialize(jsonString,PhysicalInventoryLI.class);
        
        List<ASI_CRM_Physical_Inventory_Check_Item__c> physicalInventoryItem = new List<ASI_CRM_Physical_Inventory_Check_Item__c>();
        
        for(PhysicalInventoryItemStructure obj : PhysicalInventoryLIList.PhysicalInventoryItemList) {
            
            ASI_CRM_Physical_Inventory_Check_Item__c b = New ASI_CRM_Physical_Inventory_Check_Item__c();
            
            if(obj.recordID == NULL || obj.recordID == ''){
                b.ASI_CRM_Date_of_Checking__c = date.newInstance(integer.valueOf(obj.DateOfChecking.subString(0,4)), integer.valueOf(obj.DateOfChecking.subString(5,7)), integer.valueOf(obj.DateOfChecking.subString(8)));
                b.ASI_CRM_Inventory_Btl__c = obj.InventoryBtl;
                b.RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Physical_Inventory_Check_Item__cASI_CRM_CN_Physical_Inventory_Check_Item');
                b.ASI_CRM_Inventory_Btl_from_WS__c = obj.InventoryBtlFromWS;
                b.ASI_CRM_Item_Group__c = obj.itemGroup;
                b.ASI_CRM_Physical_Inventory_Check__c = obj.PhysicalInventoryCheck;
                
                physicalInventoryItem.add(b);
            }else if(obj.recordID != NULL && obj.recordID != ''){
                
                b.id = obj.recordID;
                b.ASI_CRM_Date_of_Checking__c = date.newInstance(integer.valueOf(obj.DateOfChecking.subString(0,4)), integer.valueOf(obj.DateOfChecking.subString(5,7)), integer.valueOf(obj.DateOfChecking.subString(8)));
                b.ASI_CRM_Inventory_Btl__c = obj.InventoryBtl;
                b.RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Physical_Inventory_Check_Item__cASI_CRM_CN_Physical_Inventory_Check_Item');
                b.ASI_CRM_Inventory_Btl_from_WS__c = obj.InventoryBtlFromWS;
                b.ASI_CRM_Item_Group__c = obj.itemGroup;
                
                physicalInventoryItem.add(b);
            }
        }
        upsert physicalInventoryItem;
        
        return 'success';
    }
    
	global with sharing class PhysicalInventoryItemStructure{
        
        global String recordID { set; get; }
        global String DateOfChecking { set; get; }
        global Decimal InventoryBtl { set; get; }
        global Decimal InventoryBtlFromWS { set; get; }
        global String itemGroup { set; get; }
        global String PhysicalInventoryCheck { set; get; }
        
    }
}