objects/ASI_MFM_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_TP_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO</label>
        <referenceTo>ASI_TH_CRM_Contract__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Estimated_Total_Amount__c</fullName>
        <label>Estimated Promotion Amount</label>
        <summarizedField>ASI_MFM_Plan_Line_Item__c.ASI_CRM_CN_TP_Estimated_Amount__c</summarizedField>
        <summaryForeignKey>ASI_MFM_Plan_Line_Item__c.ASI_MFM_Plan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_KA_Banner__c</fullName>
        <label>KA Banner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Total_Fixed_Cost__c</fullName>
        <label>Estimated Fixed Cost</label>
        <summarizedField>ASI_MFM_Plan_Line_Item__c.ASI_CRM_CN_TP_Fixed_Cost__c</summarizedField>
        <summaryForeignKey>ASI_MFM_Plan_Line_Item__c.ASI_MFM_Plan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Original_Plan_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Plan No,</label>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Complete (CAPEX)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_CN_TP_Trade_Plan_Read_Only</fullName>
        <active>true</active>
        <description>for cn trade plan</description>
        <label>CN Trade Plan Read-Only</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_Contract__c.object
<CustomObject>
    <description>ASI TH CRM Contract</description>
    <fields>
        <fullName>ASI_CRM_CN_Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Outlet_WS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5) OR (4 AND 7) OR (8 AND 10) OR (6 AND 9)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM MY Contract, ASI CRM MY Contract (Final)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (MY), Potential Outlet (MY)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.ASI_CRM_CN_Inactive_Flag__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (SG)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM SG 2. Contract, ASI CRM SG Contract (Read-Only), ASI CRM SG Contract (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer (KH)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM SG 1. Proposal, ASI CRM SG Proposal (Read-Only), ASI CRM SG Proposal (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM SG 2. Contract, ASI CRM MY Contract, ASI CRM MY Contract (Final), ASI CRM SG Contract (Read-Only), ASI CRM SG 1. Proposal, ASI CRM SG Proposal (Read-Only), ASI CRM SG Proposal (Snapshot), ASI CRM SG Contract (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM KH Contract, ASI CRM KH Contract (Read-Only)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM KH Contract, ASI CRM KH Contract (Read-Only)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipName>Contracts_CN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>FY landing Archive</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_TP_PO_Add_TP_Ctrl.cls
public with sharing class ASI_CRM_CN_TP_PO_Add_TP_Ctrl {
	public String contractId;
	public Boolean isCanEdit {get; set;}
	public List<PlanWapper> finalPlans {get; set;}

    public ASI_CRM_CN_TP_PO_Add_TP_Ctrl(ApexPages.StandardController controller) {
        contractId = controller.getId();
        finalPlans = new List<PlanWapper>();
        isCanEdit = true;
        init();
    }

    public void init() {
    	Set<Id> oldTPIds = new Set<Id>();
    	ASI_TH_CRM_Contract__c contract = [SELECT ASI_CRM_CN_Outlet_WS__c, ASI_CRM_CN_Status__c, ASI_CRM_CN_Description__c,(SELECT Id FROM Plans__r) FROM ASI_TH_CRM_Contract__c WHERE Id = :contractId];
    	if (contract.ASI_CRM_CN_Status__c == 'Archived' || contract.ASI_CRM_CN_Status__c == 'Submitted') {
    		isCanEdit = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'The PO is Archived or Submitted.'));
            return;
    	}
    	for (ASI_MFM_Plan__c plan : contract.Plans__r) {
    		oldTPIds.add(plan.Id);
    	}

    	List<ASI_MFM_Plan__c> finalPlanList = [SELECT Name, ASI_CRM_CN_TP_Customer__c, ASI_MFM_Status__c, ASI_CRM_CN_TP_KA_Banner__c, Owner.Name, 
                                                    CreatedDate, ASI_CRM_CN_TP_Estimated_Total_Amount__c, ASI_CRM_CN_TP_Total_Fixed_Cost__c 
                                              FROM ASI_MFM_Plan__c
						    				  WHERE ASI_CRM_CN_TP_Customer__c = :contract.ASI_CRM_CN_Outlet_WS__c 
						    				  AND RecordType.DeveloperName = 'ASI_CRM_CN_TP_Trade_Plan_Read_Only'
						    				  AND ASI_MFM_Status__c = 'Final' 
                                              AND Id NOT IN :oldTPIds
                                              AND ASI_CRM_CN_TP_Contract__c = null
                                              AND ASI_MFM_Remarks__c = :contract.ASI_CRM_CN_Description__c];
		for (ASI_MFM_Plan__c plan : finalPlanList) {
			PlanWapper planw = new PlanWapper();
			planw.selected = false;
			planw.plan = plan;
			finalPlans.add(planw);
		}
    }

    public PageReference saveTPs(){
    	System.debug(LoggingLevel.INFO, '*** saveTPs: ' );
    	List<ASI_MFM_Plan__c> updatePlans = new List<ASI_MFM_Plan__c>();
    	for (PlanWapper planw : finalPlans) {
    		if (planw.selected) {
    			planw.plan.ASI_CRM_CN_TP_Contract__c = contractId;
    			updatePlans.add(planw.plan);
    		}
    	}
    	if (!updatePlans.isEmpty()) {
    		update updatePlans;
            ASI_CRM_CN_TP_Plan_TriggerClass.POModification(new Set<Id>{contractId});
            ASI_TH_CRM_Contract__c con = new ASI_TH_CRM_Contract__c(Id = contractId);
            con.ASI_CRM_CN_Status__c = 'Archived';
            update con;
    	}
    	
    	return new PageReference('/' + contractId);
    }

    class PlanWapper{
    	public Boolean selected {get; set;}
    	public ASI_MFM_Plan__c plan {get; set;}
    }
}