objects/ASI_CRM_MY_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ASI_CRM_MY_RT_PaymentRequests__c</fullName>
        <label>RT - Payment Request</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>ASI CRM MY Settings</label>
</CustomObject>

objects/ASI_TH_CRM_Contract__c.object
<CustomObject>
    <description>ASI TH CRM Contract</description>
    <fields>
        <fullName>ASI_CRM_CN_Outlet_WS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5) OR (4 AND 7) OR (8 AND 10) OR (6 AND 9)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM MY Contract, ASI CRM MY Contract (Final)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (MY), Potential Outlet (MY)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.ASI_CRM_CN_Inactive_Flag__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (SG)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM SG 2. Contract, ASI CRM SG Contract (Read-Only), ASI CRM SG Contract (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer (KH)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM SG 1. Proposal, ASI CRM SG Proposal (Read-Only), ASI CRM SG Proposal (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM SG 2. Contract, ASI CRM MY Contract, ASI CRM MY Contract (Final), ASI CRM SG Contract (Read-Only), ASI CRM SG 1. Proposal, ASI CRM SG Proposal (Read-Only), ASI CRM SG Proposal (Snapshot), ASI CRM SG Contract (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM KH Contract, ASI CRM KH Contract (Read-Only)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM KH Contract, ASI CRM KH Contract (Read-Only)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipName>Contracts_CN</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_NewPR_On_Contract_ctrl.cls
public class ASI_CRM_NewPR_On_Contract_ctrl {
	@AuraEnabled
    public static String getRecordType(){
      String rTypeId =   ASI_CRM_MY_Settings__c.getInstance().ASI_CRM_MY_RT_PaymentRequests__c;
        if(rTypeId == null){
            rTypeId =   ASI_CRM_MY_Settings__c.getOrgDefaults().ASI_CRM_MY_RT_PaymentRequests__c;
        }
        return rTypeId;
    }
    
    @AuraEnabled
    public static ASI_TH_CRM_Contract__c getContract(String recordId){
        return [Select id, ASI_CRM_CN_Outlet_WS__c from ASI_TH_CRM_Contract__c where id = :recordId limit 1];
    }
}