objects/ASI_TH_CRM_Contract__c.object
<CustomObject>
    <description>ASI TH CRM Contract</description>
    <fields>
        <fullName>ASI_CRM_CN_Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>RMB</fullName>
                    <default>true</default>
                    <label>RMB</label>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Exchange_Rate__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Obsolete_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Obsolete Version</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Remarks__c</fullName>
        <label>Remarks</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Version__c</fullName>
        <label>Version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Contract_Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Editing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>New Contract</fullName>
                </value>
                <value>
                    <fullName>Renewal Contract</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Contract Approved</fullName>
                </value>
                <value>
                    <fullName>Contract Rejected</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>SM Approved</fullName>
                </value>
                <value>
                    <fullName>HF Approved</fullName>
                </value>
                <value>
                    <fullName>Mktg Approved</fullName>
                </value>
                <value>
                    <fullName>MD Approved</fullName>
                </value>
                <value>
                    <fullName>GCMD Approved</fullName>
                </value>
                <value>
                    <fullName>Proposal Approved</fullName>
                </value>
                <value>
                    <fullName>Proposal Rejected</fullName>
                </value>
                <value>
                    <fullName>Proposal Converted</fullName>
                </value>
                <value>
                    <fullName>Terminate</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Outlet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR (2 AND 3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM MO Contract</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM MO Contract</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (HK)</value>
            </filterItems>
            <filterItems>
                <field>Account.ASI_HK_CRM_Location__c</field>
                <operation>equals</operation>
                <value>#_MACDPLOC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>ASI_TH_CRM_Contract_Outlet</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_MO_ContractCopyCtl.cls
public with sharing class ASI_CRM_MO_ContractCopyCtl{

    public string pid;
    public ASI_TH_CRM_Contract__c Con {get; set;}
    private ASI_CRM_MO_ContractCommon clsContract;

    //public ASI_CRM_MO_ContractCopyCtl(ApexPages.StandardController controller) {
        
    //}
    
    public ASI_CRM_MO_ContractCopyCtl(ApexPages.StandardSetController controller){
        
        clsContract = new ASI_CRM_MO_ContractCommon();
        pid = apexpages.currentPage().getParameters().get('id');
        
        List <ASI_TH_CRM_Contract__c> lstCon = [
			SELECT id,
				ASI_TH_CRM_Outlet__c,
            	OwnerID,
                Name,
                RecordTypeID,
                ASI_TH_CRM_Start_Date__c,
                ASI_TH_CRM_End_Date__c,
                ASI_CRM_Version__c,
                ASI_TH_CRM_Contract_Status__c,
                ASI_CRM_CN_Currency__c,
                ASI_CRM_CN_Exchange_Rate__c,
                ASI_CRM_CN_Description__c,
                ASI_CRM_Remarks__c,
                ASI_CRM_Obsolete_Version__c
            FROM ASI_TH_CRM_Contract__c
            WHERE id = :pid
        ];
        Con = lstCon[0];
        Con.Ownerid = UserInfo.getUserId();
        system.debug(Con);
    }
    
    public PageReference save() {
        PageReference p;
        System.Savepoint sp = database.setSavepoint();
        try {
            id idRes = clsContract.copySingleContract(pid, Con.ASI_TH_CRM_Outlet__c, Con.Ownerid, Con.ASI_TH_CRM_Start_Date__c, Con.ASI_TH_CRM_End_Date__c);
            p = new PageReference('/' + ((idRes == null) ? pid : idRes));
        } catch (Exception e) {
        
            System.debug('Upsert Error: ' + e);
            String strError = e.getMessage();    
            //String strError = e.getMessage() +'|'+ String.valueOf(e.getLineNumber());
            System.debug('Flag- Saving Error Info: getTypeName: ' + e.getTypeName() + ' getDmlType: '+e.getDmlType(0));
            system.debug('-------------Error------------' + strError);
            if(e.getTypeName() == 'System.DmlException' && e.getDmlType(0) == System.Statuscode.FIELD_CUSTOM_VALIDATION_EXCEPTION){
                String s = e.getDmlMessage(0); 
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, s));
            }else if(e.getTypeName() == 'System.DmlException' && (e.getDmlType(0) == System.Statuscode.INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY || e.getDmlType(0) == System.Statuscode.INSUFFICIENT_ACCESS_OR_READONLY)) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Insufficient Privileges: You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary.'));
            }else{    
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, strError));
            }
                
            database.rollback(sp);
        }
        return p;
    }
}