objects/ASI_MFM_Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Base_Currency__c</fullName>
        <label>Base Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>7AU</fullName>
                </value>
                <value>
                    <fullName>7EU</fullName>
                </value>
                <value>
                    <fullName>7GB</fullName>
                </value>
                <value>
                    <fullName>7US</fullName>
                </value>
                <value>
                    <fullName>8AU</fullName>
                </value>
                <value>
                    <fullName>8EU</fullName>
                </value>
                <value>
                    <fullName>8GB</fullName>
                </value>
                <value>
                    <fullName>8US</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>SGD</fullName>
                </value>
                <value>
                    <fullName>TWD</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>IDR</fullName>
                </value>
                <value>
                    <fullName>BHT</fullName>
                </value>
                <value>
                    <fullName>THB</fullName>
                </value>
                <value>
                    <fullName>KRW</fullName>
                </value>
                <value>
                    <fullName>NZD</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>VND</fullName>
                </value>
                <value>
                    <fullName>SEK</fullName>
                </value>
                <value>
                    <fullName>AED</fullName>
                </value>
                <value>
                    <fullName>RUB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_Counter_Currency__c</fullName>
        <label>Counter_Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>7AU</fullName>
                </value>
                <value>
                    <fullName>7EU</fullName>
                </value>
                <value>
                    <fullName>7GB</fullName>
                </value>
                <value>
                    <fullName>7US</fullName>
                </value>
                <value>
                    <fullName>8AU</fullName>
                </value>
                <value>
                    <fullName>8EU</fullName>
                </value>
                <value>
                    <fullName>8GB</fullName>
                </value>
                <value>
                    <fullName>8US</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>SGD</fullName>
                </value>
                <value>
                    <fullName>TWD</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
                <value>
                    <fullName>BHT</fullName>
                </value>
                <value>
                    <fullName>THB</fullName>
                </value>
                <value>
                    <fullName>SEK</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>KRW</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>NZD</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>VND</fullName>
                </value>
                <value>
                    <fullName>RMB</fullName>
                </value>
                <value>
                    <fullName>AED</fullName>
                </value>
                <value>
                    <fullName>RUB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TW</fullName>
                </value>
                <value>
                    <fullName>HK</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>RM</fullName>
                </value>
                <value>
                    <fullName>GF</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>TR</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
                <value>
                    <fullName>PH</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>VN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <displayFormat>EXR{000000}</displayFormat>
        <label>Exchange Rate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ASI_MFM_PO__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Exchange_Rate__c</fullName>
        <inlineHelpText>System retrieves the value from exchange rate table if this field is blank</inlineHelpText>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_T_E_Amount_Posted__c</fullName>
        <label>T&amp;E Amount Posted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_T_E_Amount__c</fullName>
        <label>T&amp;E Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PO</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TnE_ClaimDetail__c.object
<CustomObject>
    <fields>
        <fullName>ASI_TnE_HK_Payment_Amount__c</fullName>
        <formula>ASI_TnE_Receipt_Amount__c * ASI_TnE_FX_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_MFM_PO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MFM PO</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4 AND 5) OR (6 AND 7) OR (1 AND 8)</booleanFilter>
            <filterItems>
                <field>ASI_MFM_PO__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Final</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>TH PO, TH PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>TH PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.ASI_MFM_T_E__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Complete</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Final, Complete, Partial Paid</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>HK PO, HK PO Read-Only, TR PO, TR PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_PO__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>SG PO, SG PO Read-Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>Travel &amp; Entertainment Claims Detail</relationshipLabel>
        <relationshipName>Travel_Entertainment_Claims_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Travel &amp; Entertainment Claim Detail</label>
    <nameField>
        <displayFormat>TED-{YY}-{00000}</displayFormat>
        <label>Claim Detail No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel &amp; Entertainment Claims Detail</pluralLabel>
    <recordTypes>
        <fullName>ASI_TnE_HK_Claim_Detail</fullName>
        <active>true</active>
        <label>TnE HK Claim Detail</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_TnE_SG_Claim_Detail</fullName>
        <active>true</active>
        <label>ASI TnE SG Claim Detail</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Country__c</fullName>
        <label>ASI MFM Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TW</fullName>
                </value>
                <value>
                    <fullName>HK</fullName>
                </value>
                <value>
                    <fullName>GF</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>RM</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TR</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>PH</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>VN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_TnE_ClaimsDetailUpdatePO.cls
/*********************************************************************************
 * Name:ASI_TnE_ClaimsDetailUpdatePO
 * Description: Update PO
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------
 * 24/06/2015       Laputa: Hank            Created
*********************************************************************************/

public without sharing class ASI_TnE_ClaimsDetailUpdatePO extends ASI_TnE_TriggerAbstract {

    public ASI_TnE_ClaimsDetailUpdatePO() {
        super('ASI_TnE_ClaimsDetailUpdatePO');
    }
    
    public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
        
        String CurrentClassName = String.valueOf(this).substring(0,String.valueOf(this).indexOf(':'));
        System.Debug('Execution Start := ' + CurrentClassName);

        System.Debug('Start Getting Exchange Rate Map');
        System.debug('Current Number of SOQL Queries in this apex code context: ' +  Limits.getQueries());
        
		//Vincent 20161221 Initialize PO Exchange Rate Map
		//Contains USD-SGD, SGD-USD, SG Market
		Map<String, ASI_MFM_Exchange_Rate__c> map_ExRate = new Map<String, ASI_MFM_Exchange_Rate__c>();
		List <ASI_MFM_Exchange_Rate__c> List_ExRate = [SELECT id, name, ASI_MFM_Base_Currency__c, ASI_MFM_Counter_Currency__c, ASI_MFM_Country__c, ASI_MFM_Exchange_Rate__c from ASI_MFM_Exchange_Rate__c where ASI_MFM_Base_Currency__c in ('USD', 'SGD') and ASI_MFM_Counter_Currency__c in ('SGD', 'USD') AND ASI_MFM_Effective_Date__c <= :System.today() and ASI_MFM_Country__c = 'SG' ORDER BY ASI_MFM_Effective_Date__c DESC];
		for (ASI_MFM_Exchange_Rate__c idx : List_ExRate) {
            if (!map_ExRate.containsKey(idx.ASI_MFM_Base_Currency__c+idx.ASI_MFM_Counter_Currency__c)) {
				map_ExRate.put(idx.ASI_MFM_Base_Currency__c+idx.ASI_MFM_Counter_Currency__c, idx);
            }
		}
        
        System.Debug('End Getting Exchange Rate Map');
        System.debug('Current Number of SOQL Queries in this apex code context: ' +  Limits.getQueries()); 
        
        System.Debug('Start Retrieve PO Id of the TnE Lines');
        System.debug('Current Number of SOQL Queries in this apex code context: ' +  Limits.getQueries());
        
        List<ASI_TnE_ClaimDetail__c> detailList = (List<ASI_TnE_ClaimDetail__c>)sObjList;
        Set<Id> poIdSet = new Set<Id>();
        if(oldMap == null){
            for(ASI_TnE_ClaimDetail__c detail:detailList){
                if(detail.ASI_TnE_HK_Payment_Amount__c != null && detail.ASI_TnE_MFM_PO__c != null){
                    poIdSet.add(detail.ASI_TnE_MFM_PO__c);
                }   
            }
        }else if(sObjList !=null){
            Map<Id, ASI_TnE_ClaimDetail__c> detailOldMap = (Map<Id, ASI_TnE_ClaimDetail__c>)oldMap;
            for(ASI_TnE_ClaimDetail__c detail:detailList){
                if((detail.ASI_TnE_HK_Payment_Amount__c != null &&
                       detail.ASI_TnE_HK_Payment_Amount__c != detailOldMap.get(detail.Id).ASI_TnE_HK_Payment_Amount__c) ||
                       (detail.ASI_TnE_MFM_PO__c != null &&
                       detail.ASI_TnE_MFM_PO__c != detailOldMap.get(detail.Id).ASI_TnE_MFM_PO__c)){
                    poIdSet.add(detail.ASI_TnE_MFM_PO__c);    
                }
                if(detail.ASI_TnE_MFM_PO__c != detailOldMap.get(detail.Id).ASI_TnE_MFM_PO__c && detail.ASI_TnE_MFM_PO__c == null){
                    poIdSet.add(detailOldMap.get(detail.Id).ASI_TnE_MFM_PO__c); 
                }
            }
        }else{
            Map<Id, ASI_TnE_ClaimDetail__c> detailOldMap = (Map<Id, ASI_TnE_ClaimDetail__c>)oldMap;
            for(ASI_TnE_ClaimDetail__c detail:detailOldMap.values()){
                poIdSet.add(detail.ASI_TnE_MFM_PO__c);
            }
        }
        
		System.Debug('End Retrieve PO Id of the TnE Lines');
        System.debug('Current Number of SOQL Queries in this apex code context: ' +  Limits.getQueries());
        
		System.Debug('Start Retrieve All TnE Line of PO Lines');
        System.debug('Current Number of SOQL Queries in this apex code context: ' +  Limits.getQueries());
        
        List<ASI_MFM_PO__c> poList = [Select ASI_MFM_T_E_Amount__c,ASI_MFM_T_E_Amount_Posted__c,ASI_MFM_Sys_Local_Currency__c, (Select recordtypeid, ASI_TnE_HK_Payment_Amount__c,ASI_TnE_ClaimHeader__r.ASI_TnE_Status__c,ASI_TnE_ClaimHeader__r.ASI_TnE_Export_to_AP_Voucher_GL__c,ASI_TnE_ClaimHeader__r.ASI_TnE_Currency__c,ASI_TnE_Currency__c,ASI_TnE_ClaimHeader__r.ASI_TnE_HK_Submission_Date__c From Travel_Entertainment_Claims_Detail__r) From ASI_MFM_PO__c Where Id In :poIdSet];
        //String UserId = UserInfo.getUserId();
        //String sUserMFMCountry = [SELECT ASI_MFM_Country__c FROM user WHERE id = :UserId].ASI_MFM_Country__c;
        //System.debug('sUserMFMCountry := ' + sUserMFMCountry);
        Double nExchangeRate = null;
        Map<Id, ASI_TnE_ClaimDetail__c> TnEUpdateMap = new Map<Id, ASI_TnE_ClaimDetail__c>();
        
		System.Debug('End Retrieve All TnE Line of PO Lines');
        System.debug('Current Number of SOQL Queries in this apex code context: ' +  Limits.getQueries());
        
        for(ASI_MFM_PO__c po:poList){
            po.ASI_MFM_T_E_Amount__c = 0;
            date dFXRateRef = null;
           // po.ASI_MFM_T_E_Amount_Posted__c =0;
            for(ASI_TnE_ClaimDetail__c detail:po.Travel_Entertainment_Claims_Detail__r){
                if (detail.ASI_TnE_ClaimHeader__r.ASI_TnE_HK_Submission_Date__c == null) {
                    dFXRateRef = detail.ASI_TnE_ClaimHeader__r.ASI_TnE_HK_Submission_Date__c;
                }else{
                    dFXRateRef = System.today();
                }
                System.debug('TnE Base Currency := ' + detail.ASI_TnE_ClaimHeader__r.ASI_TnE_Currency__c);
                System.debug('PO Base Currency := ' + po.ASI_MFM_Sys_Local_Currency__c);
			//	if (po.ASI_MFM_Sys_Local_Currency__c <> detail.ASI_TnE_Currency__c) {
				
                //if (Global_RecordTypeCache.getRt(detail.recordTypeid).developerName.contains('ASI_TnE_SG_Claim_Detail')) {
                    //Map is only available for SGD-USD, and USD-SGD. Not available for SGD-SGD, USD-USD
                    try {
                        nExchangeRate = map_ExRate.get(detail.ASI_TnE_ClaimHeader__r.ASI_TnE_Currency__c+po.ASI_MFM_Sys_Local_Currency__c).ASI_MFM_Exchange_Rate__c;
                        System.Debug('PO Exchange Rate := ' + nExchangeRate);
                    }catch(Exception e) {
                        nExchangeRate = 1;
                    }
                //}
                if (nExchangeRate == null) {
                    nExchangeRate = 1;
                }
				
                
                if (Global_RecordTypeCache.getRt(detail.recordTypeid).developerName.contains('ASI_TnE_HK_Claim_Detail')){
					//Vincent@2017/10/12 To omit 'Draft' T&E in T&E Amount field in linked MFM PO
                    if (detail.ASI_TnE_ClaimHeader__r.ASI_TnE_Status__c != 'Draft') {
						po.ASI_MFM_T_E_Amount__c += detail.ASI_TnE_HK_Payment_Amount__c;
                    }
                }else if (nExchangeRate != null) {
                    po.ASI_MFM_T_E_Amount__c = po.ASI_MFM_T_E_Amount__c + (detail.ASI_TnE_HK_Payment_Amount__c / nExchangeRate);
                }else {
					po.ASI_MFM_T_E_Amount__c += detail.ASI_TnE_HK_Payment_Amount__c;
				}
                //detail.ASI_TnE_Exchange_Rate_to_VND__c = nExchangeRate;
                TnEUpdateMap.put(detail.Id, detail);
                System.debug('TnE Amount := ' + po.ASI_MFM_T_E_Amount__c);
					//if(detail.ASI_TnE_ClaimHeader__r.ASI_TnE_Export_to_AP_Voucher_GL__c){
				   //     po.ASI_MFM_T_E_Amount_Posted__c+=detail.ASI_TnE_HK_Payment_Amount__c;
					//}
			//	}
            }
        }
		System.Debug('Start Update TnE Amount');
        System.debug('Current Number of SOQL Queries in this apex code context: ' +  Limits.getQueries());
        
        update poList;
        //update TnEUpdateMap.values();
        
		System.Debug('End Update TnE Amount');
        System.debug('Current Number of SOQL Queries in this apex code context: ' +  Limits.getQueries());
        
        System.Debug('Execution Start := ' + CurrentClassName);
    }
}