objects/ASI_MFM_A_C_Code__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_A_C_Code__c</fullName>
        <label>A/C Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>A/C Code</label>
    <nameField>
        <label>A/C</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A/C Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_AP_Code__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_AP_Code__c</fullName>
        <label>AP Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_A_C_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>A/C</label>
        <referenceTo>ASI_MFM_A_C_Code__c</referenceTo>
        <relationshipLabel>AP Codes</relationshipLabel>
        <relationshipName>AP_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AP Code</label>
    <nameField>
        <label>AP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Plan_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_AP_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AP Code</label>
        <referenceTo>ASI_MFM_AP_Code__c</referenceTo>
        <relationshipLabel>Plan Line Items</relationshipLabel>
        <relationshipName>Plan_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_A_C_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>A/C Code</label>
        <referenceTo>ASI_MFM_A_C_Code__c</referenceTo>
        <relationshipLabel>Plan Line Items</relationshipLabel>
        <relationshipName>Plan_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_BU_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BU Code</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select an active BU Code.</errorMessage>
            <filterItems>
                <field>ASI_MFM_BU__c.ASI_MFM_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_BU__c</referenceTo>
        <relationshipLabel>Plan Line Items</relationshipLabel>
        <relationshipName>Plan_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7 OR (8 AND 9)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (HK)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>TR Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>GF Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>RM Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI JP Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>MY Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN Outlet,TH Customer,Outlet (SG),  Wholesaler (SG), SG Customer, PH DF Customer, PH DP Customer, VN DF Customer, VN DP Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>TW Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.ASI_HK_CRM_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plan Line Items</relationshipLabel>
        <relationshipName>Plan_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>Plan Line Items</relationshipLabel>
        <relationshipName>Plan_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan Line Item</label>
    <nameField>
        <displayFormat>PLI{000000}</displayFormat>
        <label>Plan Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_PO__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_BU_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BU Code</label>
        <referenceTo>ASI_MFM_BU__c</referenceTo>
        <relationshipLabel>POs</relationshipLabel>
        <relationshipName>POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO_Raised_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>PO Raised Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Line Item</label>
        <referenceTo>ASI_MFM_Plan_Line_Item__c</referenceTo>
        <relationshipLabel>POs</relationshipLabel>
        <relationshipName>POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>3 OR (1 AND 2) OR (4 AND 5) OR (6 AND 7)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DP PO, PH DP PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DP Plan, PH DP Plan Read-Only</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>PH DF PO, PH DF PO Read-Only, PH DP PO, PH DP PO Read-Only, KR PO, KR PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DF PO, PH DF PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DF Plan, PH DF Plan Read-Only</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>KR PO, KR PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Approved, Closed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>POs</relationshipLabel>
        <relationshipName>POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_PO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_AP_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AP Code</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <errorMessage>Please select an active A&amp;P Code</errorMessage>
            <filterItems>
                <field>ASI_MFM_AP_Code__c.ASI_MFM_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_AP_Code__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_A_C_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>A/C Code</label>
        <referenceTo>ASI_MFM_A_C_Code__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_BU_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BU Code</label>
        <referenceTo>ASI_MFM_BU__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3) OR (4 AND 5) OR (6 AND 7) OR 8</booleanFilter>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN Outlet, RM Customer, ASI JP Customer, GF Customer, MY Customer, Outlet (SG), Wholesaler (SG), SG Customer, TH Customer, PH DF Customer, PH DP Customer, KH Customer,, VN DF Customer, VN DP Customer, VN Supplier, SC Supplier</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>TR Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Account.ASI_HK_CRM_Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>TW Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (HK)</value>
            </filterItems>
            <filterItems>
                <field>Account.ASI_HK_CRM_IsDeliveryAccount__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$User.BypassVR__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_G_L_Date__c</fullName>
        <label>G/L Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO__c</fullName>
        <label>PO</label>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Line Item</label>
        <referenceTo>ASI_MFM_Plan_Line_Item__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO Line Item</label>
    <nameField>
        <displayFormat>POL{000000}</displayFormat>
        <label>PO Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Line Items</pluralLabel>
    <recordTypes>
        <fullName>ASI_MFM_HK_PO_Line_Item</fullName>
        <active>true</active>
        <label>HK PO Line Item</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_MFM_HK_GenPOItemsController.cls
public with sharing class ASI_MFM_HK_GenPOItemsController {
    ASI_MFM_PO__c po = new ASI_MFM_PO__c();

    public ASI_MFM_HK_GenPOItemsController (apexpages.standardController sc) {
        po = [select ASI_MFM_Plan__c, ASI_MFM_PO_Raised_Date__c from ASI_MFM_PO__c where id = :sc.getId()];
    }

    public string buildPlanItemSoql() {
        string qs = 'select ';      
        boolean start = true;
        for (string f:schema.sobjectType.ASI_MFM_Plan_Line_Item__c.fields.getMap().keySet()) {
            if (start) {
                qs = qs + f;
                start = false;
            }
            else {
                qs = qs + ', ' + f;
            }
        }
        qs = qs + ' from ASI_MFM_Plan_Line_Item__c where ASI_MFM_Plan__c = :po_id';
        return qs;
    }
    
    public pageReference genPOItems() {
        string mode = apexpages.currentPage().getParameters().get('mode');  
        id po_id = po.ASI_MFM_Plan__c;
        list<ASI_MFM_Plan_Line_Item__c> pni_list = database.query(buildPlanItemSoql());
        list<ASI_MFM_PO_Line_Item__c> poi_list = new list<ASI_MFM_PO_Line_Item__c>();
        map<string, id> rt_map = ASI_MFM_Function.getRecordTypeId('ASI_MFM_PO_Line_Item__c');
        for (ASI_MFM_Plan_Line_Item__c pni:pni_list) {
            ASI_MFM_PO_Line_Item__c poi = new ASI_MFM_PO_Line_Item__c();
            poi.ASI_MFM_A_C_Code__c = pni.ASI_MFM_A_C_Code__c;
            poi.ASI_MFM_AP_Code__c = pni.ASI_MFM_AP_Code__c;
            poi.ASI_MFM_BU_Code__c = pni.ASI_MFM_BU_Code__c;
            poi.ASI_MFM_customer_name__c = pni.ASI_MFM_customer_name__c;
            poi.ASI_MFM_G_L_Date__c = po.ASI_MFM_PO_Raised_Date__c;
            poi.ASI_MFM_PO__c = po.id;
            poi.ASI_MFM_SKU_Code__c = pni.ASI_MFM_SKU_Code__c;
            poi.ASI_MFM_Sub_brand_Code__c = pni.ASI_MFM_Sub_brand_Code__c;
            poi.ASI_MFM_List_Item_Description__c = pni.ASI_MFM_List_Item_Description__c;
            if (mode == 'full') {
                poi.ASI_MFM_Quantity__c = pni.ASI_MFM_Quantity__c;
                poi.ASI_MFM_Unit_Price__c = pni.ASI_MFM_Unit_Cost__c;
                poi.ASI_MFM_Amount__c = pni.ASI_MFM_Total_Cost__c;
                poi.ASI_MFM_Original_Amount__c = pni.ASI_MFM_Original_Total_Cost__c;                                                                    
            }
            //if (test.isRunningTest()) {
            //Wilken: 20130816 Always need to assign Record Type for PO Line item as Permission Set cannot grant default record type
                poi.recordTypeId = rt_map.get('ASI_MFM_HK_PO_Line_Item');
            //}           
            System.debug('PO Line Item Record Type ID: ' + poi.recordTypeId);
            poi_list.add(poi);          
        }
        if (poi_list.size() > 0) {
            insert poi_list;
        }
        return new pageReference('/apex/ASI_MFM_HK_InputPOItemsPage?id=' + po.id);
    }
}