objects/ASI_KOR_POSM_Order_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>ASI_KOR_POSM_Order_Request__c</fullName>
        <label>POSM Order Request</label>
        <referenceTo>ASI_KOR_POSM_Order_Request__c</referenceTo>
        <relationshipLabel>POSM Order Attachments</relationshipLabel>
        <relationshipName>POSM_Order_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>POSM Order Attachment</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>POSM Order Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POSM Order Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_KOR_POSM_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_KOR_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>POSM Order Request</label>
    <nameField>
        <displayFormat>POSM-{0000}</displayFormat>
        <label>POSM Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POSM Order Requests</pluralLabel>
    <recordTypes>
        <fullName>ASI_KOR_Finalized_Bar_Styling_Item_Request</fullName>
        <active>true</active>
        <label>Finalized Bar-Styling Item Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_KOR_POSM_Order_Att_TriggerClass.cls
/***************************************************************************************************************************
* Name:        ASI_KOR_POSM_Order_Att_TriggerClass
* Description: Trigger class for ASI_KOR_POSM_Order_Attachment's trigger(s)
*
* Version History
* Date             Developer               Comments
* ---------------  --------------------    --------------------------------------------------------------------------------
* 2018-11-27       Alan Lau                Created
****************************************************************************************************************************/

public without sharing class ASI_KOR_POSM_Order_Att_TriggerClass {

    public static void blockAttachmentForFinalizedRequest(List<ASI_KOR_POSM_Order_Attachment__c> triggerNew) {
        final List<String> recordTypeBlockList = new List<String>{
                'ASI_KOR_Finalized_Bar_Styling_Item_Request'
        };
        List<String> posmHeaderIdList = ASI_KOR_CommonUtils.getStringFieldList(triggerNew, 'ASI_KOR_POSM_Order_Request__c');
        Map<Id, ASI_KOR_POSM_Order_Request__c> mapOfIdToPOSMHeader = new Map<Id, ASI_KOR_POSM_Order_Request__c>([
                SELECT Id,
                        ASI_KOR_Status__c,
                        RecordType.DeveloperName
                FROM ASI_KOR_POSM_Order_Request__c
                WHERE Id IN :posmHeaderIdList
        ]);

        for (ASI_KOR_POSM_Order_Attachment__c attachment : triggerNew) {
            if (mapOfIdToPOSMHeader.containsKey(attachment.ASI_KOR_POSM_Order_Request__c)
                    && recordTypeBlockList.contains(mapOfIdToPOSMHeader.get(attachment.ASI_KOR_POSM_Order_Request__c).RecordType.DeveloperName)) {
                attachment.addError('Attachment editing is blocked when the status is Final.');
            }
        }

    }

}