objects/ASI_MFM_Payment__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AED</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>BHT</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>INR</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>KRW</fullName>
                </value>
                <value>
                    <fullName>MMK</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>NTD</fullName>
                </value>
                <value>
                    <fullName>NZD</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>RMB</fullName>
                </value>
                <value>
                    <fullName>SEK</fullName>
                </value>
                <value>
                    <fullName>SGD</fullName>
                </value>
                <value>
                    <fullName>THB</fullName>
                </value>
                <value>
                    <fullName>TWD</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>VND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ASI_MFM_PO__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>TW PO, TW PO Read-Only, KR PO, KR PO Read-Only, CN Structure Cost, SC PO, SC PO Read-Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAPEX</fullName>
                </value>
                <value>
                    <fullName>OPEX</fullName>
                </value>
                <value>
                    <fullName>Brand Owner Invoice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>ASI_MFM_Payment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>5 OR (1 AND (2 OR 3 OR 4))</booleanFilter>
            <filterItems>
                <field>ASI_MFM_Plan__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Final</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.RecordType.DeveloperName</field>
                <operation>startsWith</operation>
                <value>ASI_MFM_CAP</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.RecordType.DeveloperName</field>
                <operation>startsWith</operation>
                <value>ASI_MFM_TW</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.RecordType.DeveloperName</field>
                <operation>startsWith</operation>
                <value>ASI_MFM_GF</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>KR Plan Read-Only, KR Plan</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Payment_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Currency__c</fullName>
        <formula>Text(ASI_MFM_Payment__r.ASI_MFM_Currency__c)</formula>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO_Line_Item__c</fullName>
        <label>PO Line Item</label>
        <referenceTo>ASI_MFM_PO_Line_Item__c</referenceTo>
        <relationshipLabel>Payment Line Items</relationshipLabel>
        <relationshipName>Payment_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO</label>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>Payment Line Items</relationshipLabel>
        <relationshipName>Payment_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Payment_Type__c</fullName>
        <formula>TEXT(ASI_MFM_Payment__r.ASI_MFM_Payment_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>ASI_MFM_Payment__c</referenceTo>
        <relationshipLabel>Payment Line Items</relationshipLabel>
        <relationshipName>Payment_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Line Item</label>
    <nameField>
        <displayFormat>PYL{000000}</displayFormat>
        <label>Payment Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>BHT</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>KHR</fullName>
                </value>
                <value>
                    <fullName>KRW</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>RMB</fullName>
                </value>
                <value>
                    <fullName>SGD</fullName>
                </value>
                <value>
                    <fullName>THB</fullName>
                </value>
                <value>
                    <fullName>TWD</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>VND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_PO__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>3 OR (1 AND 2) OR (4 AND 5) OR (6 AND 7)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DP PO, PH DP PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DP Plan, PH DP Plan Read-Only</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>PH DF PO, PH DF PO Read-Only, PH DP PO, PH DP PO Read-Only, KR PO, KR PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DF PO, PH DF PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>PH DF Plan, PH DF Plan Read-Only</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>KR PO, KR PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Plan__c.ASI_MFM_Status__c</field>
                <operation>equals</operation>
                <value>Approved, Closed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>POs</relationshipLabel>
        <relationshipName>POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_PO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_PO__c</fullName>
        <label>PO</label>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PO Line Item</label>
    <nameField>
        <displayFormat>POL{000000}</displayFormat>
        <label>PO Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_MFM_CAP_ConvertAccrual_Test.cls
@isTest
public class ASI_MFM_CAP_ConvertAccrual_Test {

    static testMethod void testController_ConvertToAccrual(){
        ASI_MFM_CAP_TestClassHelper.createMFMDefaultValues();
        
        Account acc1 = ASI_MFM_CAP_TestClassHelper.createAccSupplier();
        
        ASI_MFM_PO__c PO = ASI_MFM_CAP_TestClassHelper.createPO();
        ASI_MFM_PO_Line_Item__c poLine = ASI_MFM_CAP_TestClassHelper.createPoLines(po);
        
        ASI_MFM_Payment__c py = new ASI_MFM_Payment__c
        (
            ASI_MFM_Payment_Type__c = 'OPEX',
            ASI_MFM_Plan__c = PO.ASI_MFM_Plan__c,
            ASI_MFM_Currency__c = 'HKD',
            ASI_MFM_Prefix__c= ASI_MFM_CAP_TestClassHelper.createPrefixPayment().id,
            ASI_MFM_Supplier_Name__c = ASI_MFM_CAP_TestClassHelper.createAccSupplier().id,
            recordTypeId = Global_RecordTypeCache.getRtId('ASI_MFM_Payment__cASI_MFM_CAP_Payment'),
            ASI_MFM_Is_Direct_Payment__c = true,
            ASI_MFM_Status__c = 'Draft',
            ASI_MFM_Invoice_Date__c = date.today(),
            ASI_MFM_Invoice_Number__c = '123Tesyt',
            ASI_MFM_OCR__c = true
        );
        insert py;
        
        Test.StartTest();
        
        ASI_MFM_Payment_Line_Item__c pyi = ASI_MFM_CAP_TestClassHelper.createPaymentLines(py, poLine);
        
        //Test convert to accrual
        PageReference testPage = Page.ASI_MFM_CAP_ConvertAccrual_Page;
        Map<String, String> pageParams = testPage.getParameters();
        pageParams.put('id', py.Id);
        pageParams.put('actionType', 'ConvertToAccrual');
        Test.setCurrentPageReference(testPage);
        
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(py);
        ASI_MFM_CAP_ConvertAccrual_Controller controller = new ASI_MFM_CAP_ConvertAccrual_Controller(stdController);
        controller.Convert(); 
        
        //Test convert to T&E
        PageReference testPage2 = Page.ASI_MFM_CAP_ConvertAccrual_Page;
        Map<String, String> pageParams2 = testPage2.getParameters();
        pageParams2.put('id', py.Id);
        pageParams2.put('actionType', 'ConvertToTnE');
        Test.setCurrentPageReference(testPage2);
        controller.Convert(); 
    }

     static testMethod void testController_ConvertToTnE(){
        ASI_MFM_CAP_TestClassHelper.createMFMDefaultValues();
        
        Account acc1 = ASI_MFM_CAP_TestClassHelper.createAccSupplier();
        
        ASI_MFM_PO__c PO = ASI_MFM_CAP_TestClassHelper.createPO();
        ASI_MFM_PO_Line_Item__c poLine = ASI_MFM_CAP_TestClassHelper.createPoLines(po);
        
        ASI_MFM_Payment__c py = new ASI_MFM_Payment__c
        (
            ASI_MFM_Payment_Type__c = 'OPEX',
            ASI_MFM_Plan__c = PO.ASI_MFM_Plan__c,
            ASI_MFM_Currency__c = 'HKD',
            ASI_MFM_Prefix__c= ASI_MFM_CAP_TestClassHelper.createPrefixPayment().id,
            ASI_MFM_Supplier_Name__c = ASI_MFM_CAP_TestClassHelper.createAccSupplier().id,
            recordTypeId = Global_RecordTypeCache.getRtId('ASI_MFM_Payment__cASI_MFM_CAP_Payment'),
            ASI_MFM_Is_Direct_Payment__c = true,
            ASI_MFM_Status__c = 'Draft',
            ASI_MFM_Invoice_Date__c = date.today(),
            ASI_MFM_Invoice_Number__c = '123Tesyt',
            ASI_MFM_OCR__c = true
        );
        insert py;
        
        Test.StartTest();
        
        ASI_MFM_Payment_Line_Item__c pyi = ASI_MFM_CAP_TestClassHelper.createPaymentLines(py, poLine);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(py);
        ASI_MFM_CAP_ConvertAccrual_Controller controller = new ASI_MFM_CAP_ConvertAccrual_Controller(stdController);
        
        //Test convert to T&E
        PageReference testPage2 = Page.ASI_MFM_CAP_ConvertAccrual_Page;
        Map<String, String> pageParams2 = testPage2.getParameters();
        pageParams2.put('id', py.Id);
        pageParams2.put('actionType', 'ConvertToTnE');
        Test.setCurrentPageReference(testPage2);
        controller.Convert(); 
    }
}