objects/ASI_CRM_Call_Detail__c.object
<CustomObject>
    <description>ASI CRM - Call Details. The following countries are using this object: 
-PRJ</description>
    <fields>
        <fullName>ASI_CRM_Attendees_BS__c</fullName>
        <label>Attendees BS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Attendees_Other__c</fullName>
        <label>Attendees Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Attendees_PRJ__c</fullName>
        <label>Attendees PRJ</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Call_Plan__c</fullName>
        <label>Call Plan</label>
        <referenceTo>ASI_CRM_Call_Plan__c</referenceTo>
        <relationshipLabel>Call Details</relationshipLabel>
        <relationshipName>Call_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_JP_All_Attendees__c</fullName>
        <label>All Attendees</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Number_of_Attendees_BS__c</fullName>
        <label>Number of Attendees BS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Number_of_Attendees_Other__c</fullName>
        <label>Number of Attendees Other</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Number_of_PRJ_Other_Attendees__c</fullName>
        <label>Number of PRJ Other Attendees</label>
        <summaryFilterItems>
            <field>ASI_CRM_Employee_Attendee__c.ASI_CRM_Department_Code__c</field>
            <operation>notEqual</operation>
            <value>1</value>
        </summaryFilterItems>
        <summaryForeignKey>ASI_CRM_Employee_Attendee__c.ASI_CRM_Call_Detail__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Number_of_PRJ_Sales_Attendees__c</fullName>
        <label>Number of PRJ Sales Attendees</label>
        <summaryFilterItems>
            <field>ASI_CRM_Employee_Attendee__c.ASI_CRM_Department_Code__c</field>
            <operation>equals</operation>
            <value>1</value>
        </summaryFilterItems>
        <summaryForeignKey>ASI_CRM_Employee_Attendee__c.ASI_CRM_Call_Detail__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Reminder_Id__c</fullName>
        <label>Reminder Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Achieved</fullName>
                </value>
                <value>
                    <fullName>TnE Created</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Tax_Rate_Area__c</fullName>
        <label>Tax Rate/Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CP0</fullName>
                </value>
                <value>
                    <fullName>CP8</fullName>
                </value>
                <value>
                    <fullName>CP8R</fullName>
                </value>
                <value>
                    <fullName>CP10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Visit_Date_Formula__c</fullName>
        <formula>DATEVALUE( ASI_CRM_Visit_Date_From__c )</formula>
        <label>Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Visit_Date_From__c</fullName>
        <label>Visit Date (From)</label>
        <type>DateTime</type>
    </fields>
    <label>Call Detail</label>
    <nameField>
        <displayFormat>CDN{00000000}</displayFormat>
        <label>Call Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Call_Plan__c.object
<CustomObject>
    <description>ASI CRM - Call Plan. The following countries are using this object:
-PRJ</description>
    <label>Call Plan</label>
    <nameField>
        <label>Call Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Employee_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Employee_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Call_Detail__c</fullName>
        <label>Call Detail</label>
        <referenceTo>ASI_CRM_Call_Detail__c</referenceTo>
        <relationshipLabel>Employee Attendees</relationshipLabel>
        <relationshipName>Employee_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Department_Code__c</fullName>
        <label>Department Category Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Employee Attendee</label>
    <nameField>
        <displayFormat>AID{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_JP_TnE_Tax_Date_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ASI_JP_TnE_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_JP_TnE_IsDefault_Tax_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Tax Rate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_JP_TnE_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_JP_TnE_Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_Tax_Area__c</fullName>
        <label>Tax Area</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>ASI TnE JP Tax Date Mapping</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ASI_JP_TnE_Department_Category_Code__c</fullName>
        <label>ASI TnE JP Department Category Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>1D</fullName>
                </value>
                <value>
                    <fullName>2D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_CRM_JP_CallDetailCalcNumOfAttendees.cls
/*********************************************************************************
 * Name:ASI_CRM_JP_CallDetailCalcNumOfAttendees
 * Description: Trigger Handler for calculating number of attendees of CRM JP
 * Test Class: ASI_CRM_JP_CallDetail_Test3
 * 
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 28/11/2014       Laputa: Hank          Created
 * 08/10/2019       Wilken Lee          	[WL 1.0] Add Tax Rate/Area picklist and default Tax Rate
*********************************************************************************/

public with sharing class ASI_CRM_JP_CallDetailCalcNumOfAttendees extends ASI_CRM_JP_TriggerAbstract {
    
    
    public ASI_CRM_JP_CallDetailCalcNumOfAttendees() {
        super('ASI_CRM_JP_CallDetailCalcNumOfAttendees');
    }
    
    public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
        
        List<ASI_CRM_Call_Detail__c> detailList = (List<ASI_CRM_Call_Detail__c>)sObjList;
        Map<Id, User> ownerMap = new Map<Id, User>();
        Map<Id, ASI_CRM_Call_Detail__c> detailMap = new Map<Id, ASI_CRM_Call_Detail__c>();
        Set<Id> headerIdSet = new Set<Id>();
        Set<Id> ownerIdSet = new Set<Id>();
        Set<Id> detailIdSet = new Set<Id>();
        List<ASI_JP_TnE_Tax_Date_Mapping__c> taxDtMapList = ASI_JP_TnE_Tax_Date_Mapping__c.getAll().values();
        
		/*[WL 1.0] BEGIN*/
		for (ASI_CRM_Call_Detail__c detail:detailList){
			//Default Tax Rate/Area if blank
			if (detail.ASI_CRM_Tax_Rate_Area__c == null){
				for (ASI_JP_TnE_Tax_Date_Mapping__c taxmap:taxDtMapList){
					if (taxmap.ASI_JP_TnE_Start_Date__c <= detail.ASI_CRM_Visit_Date_From__c && detail.ASI_CRM_Visit_Date_From__c <= taxmap.ASI_JP_TnE_End_Date__c && taxmap.ASI_JP_TnE_IsDefault_Tax_Rate__c){
						detail.ASI_CRM_Tax_Rate_Area__c = taxmap.ASI_TnE_Tax_Area__c;
					}
				}
			}
			
			//Default Tax Rate % based on assigned Tax Rate/Area
			if (detail.ASI_CRM_Tax_Rate_Area__c == 'CP0')
				detail.ASI_CRM_Tax_Rate__c = 0;
			else if (detail.ASI_CRM_Tax_Rate_Area__c == 'CP8' || detail.ASI_CRM_Tax_Rate_Area__c == 'CP8R')
				detail.ASI_CRM_Tax_Rate__c = 8;
			else if (detail.ASI_CRM_Tax_Rate_Area__c == 'CP10')
				detail.ASI_CRM_Tax_Rate__c = 10;
		}
		/*[WL 1.0] END*/
		
        if (oldMap == null) {
            for (ASI_CRM_Call_Detail__c detail: detailList) {
                headerIdSet.add(detail.ASI_CRM_Call_Plan__c);
                for(ASI_JP_TnE_Tax_Date_Mapping__c t:taxDtMapList){
                    if(t.ASI_JP_TnE_Start_Date__c <= detail.ASI_CRM_Visit_Date_Formula__c && detail.ASI_CRM_Visit_Date_Formula__c <= t.ASI_JP_TnE_End_Date__c){
                        detail.ASI_CRM_Tax_Rate__c = 100 * t.ASI_JP_TnE_Tax_Rate__c;
                    }
                }
            }
            for(ASI_CRM_Call_Plan__c plan: [Select OwnerId From ASI_CRM_Call_Plan__c Where Id In:headerIdSet]){
                ownerIdSet.add(plan.OwnerId);
            }
            ownerMap = new Map<Id, User>([Select Id, Name, ASI_JP_TnE_Department_Category_Code__c From User Where Id In :ownerIdSet]);
            for(ASI_CRM_Call_Plan__c plan: [Select OwnerId From ASI_CRM_Call_Plan__c Where Id In:headerIdSet]){
                ownerMap.put(plan.Id, ownerMap.get(plan.OwnerId));
            }
        }
        else {
            Map<ID, ASI_CRM_Call_Detail__c> oldDetailMap = (Map<ID, ASI_CRM_Call_Detail__c>) oldMap;
            for (ASI_CRM_Call_Detail__c detail: detailList) {
                detailIdSet.add(detail.Id);
                // If Status is Cancelled, remove the Reminder Id and Reminder checkbox
                if (detail.ASI_CRM_Status__c == 'Cancelled' && detail.ASI_CRM_Reminder_Id__c != null && (detail.ASI_CRM_Status__c != oldDetailMap.get(detail.Id).ASI_CRM_Status__c)) {
                    //detail.ASI_CRM_Reminder_Id__c = null;
                    detail.ASI_CRM_Reminder__c = false;
                }
                if(detail.ASI_CRM_Visit_Date_Formula__c != oldDetailMap.get(detail.Id).ASI_CRM_Visit_Date_Formula__c){
                    for(ASI_JP_TnE_Tax_Date_Mapping__c t:taxDtMapList){
                        if(t.ASI_JP_TnE_Start_Date__c <= detail.ASI_CRM_Visit_Date_Formula__c && detail.ASI_CRM_Visit_Date_Formula__c <= t.ASI_JP_TnE_End_Date__c){
                            detail.ASI_CRM_Tax_Rate__c = 100 * t.ASI_JP_TnE_Tax_Rate__c;
                        }
                    }
                }
            }
            
            detailMap = new Map<Id, ASI_CRM_Call_Detail__c>([Select Id, (Select ASI_CRM_Attendee__r.Name, ASI_CRM_Department_Code__c From Employee_Attendees__r) From ASI_CRM_Call_Detail__c Where Id In: detailIdSet ]);
        }
        
        if (oldMap == null) {
            for (ASI_CRM_Call_Detail__c detail: detailList) {
                allAttendees ='';
                allAttendees = ownerMap.get(detail.ASI_CRM_Call_Plan__c).Name;
                if(ownerMap.get(detail.ASI_CRM_Call_Plan__c).ASI_JP_TnE_Department_Category_Code__c == '1'){
                    PRJAttendees = ownerMap.get(detail.ASI_CRM_Call_Plan__c).Name;
                }
                detail.ASI_CRM_Number_of_Attendees_BS__c = calcNumOfAttendees(detail.ASI_CRM_Attendees_BS__c);
                detail.ASI_CRM_Number_of_Attendees_Other__c= calcNumOfAttendees(detail.ASI_CRM_Attendees_Other__c) + detail.ASI_CRM_Number_of_PRJ_Other_Attendees__c;
                detail.ASI_CRM_JP_All_Attendees__c = allAttendees;
                detail.ASI_CRM_Attendees_PRJ__c = PRJAttendees;
                //Verify the number of Attendees is the same with the field Total Number Of Attendess
                /*
                if (calcNumOfAttendees(detail.ASI_CRM_JP_All_Attendees__c) != (detail.ASI_CRM_Number_of_Attendees_Other__c + detail.ASI_CRM_Number_of_Attendees_BS__c + detail.ASI_CRM_Number_of_PRJ_Sales_Attendees__c) + 1) {
                    detail.addError(System.Label.ASI_CRM_JP_Call_Detail_NumOfAttendeesError);
                }
                */
            }
        }
        else {
            Map<ID, ASI_CRM_Call_Detail__c> oldDetailMap = (Map<ID, ASI_CRM_Call_Detail__c>) oldMap;
            for (ASI_CRM_Call_Detail__c detail: detailList) {
                allAttendees = '';
                PRJAttendees = '';
                for (ASI_CRM_Employee_Attendee__c att: detailMap.get(detail.id).Employee_Attendees__r) {
                    if (allAttendees == ''){
                        allAttendees += att.ASI_CRM_Attendee__r.Name;
                    }else{
                        allAttendees += ';' + att.ASI_CRM_Attendee__r.Name;
                    }
                    if(att.ASI_CRM_Department_Code__c == '1'){
                        if(PRJAttendees == ''){
                            PRJAttendees += att.ASI_CRM_Attendee__r.Name;
                        }else{
                            PRJAttendees += ';' + att.ASI_CRM_Attendee__r.Name; 
                        }
                    }
                }
                detail.ASI_CRM_Number_of_Attendees_BS__c = calcNumOfAttendees(detail.ASI_CRM_Attendees_BS__c);
                detail.ASI_CRM_Number_of_Attendees_Other__c = calcNumOfAttendees(detail.ASI_CRM_Attendees_Other__c) + detail.ASI_CRM_Number_of_PRJ_Other_Attendees__c;
                detail.ASI_CRM_JP_All_Attendees__c = allAttendees;
                detail.ASI_CRM_Attendees_PRJ__c = PRJAttendees;
            }
        }
    }
    
    private String allAttendees ='';
    private String PRJAttendees = '';
    
    private decimal calcNumOfAttendees(String attendees){
        decimal numOfAttendees = 0;
        if (attendees == null) {
            return 0;
        } 
        String att = attendees.trim().replaceAll('(\\s+)', '');
        String[] attendeeArray = att.split(';');
        for (String str:attendeeArray ) {
            if(str != ''){
                numOfAttendees += 1;
                if (allAttendees != '') {
                    allAttendees += ';' + str;
                } else {
                    allAttendees += str;
                }
            }
        }
        return numOfAttendees;
    }
}