objects/ASI_FOC_Free_Goods_Request__c.object
<CustomObject>
    <description>used by PR China FOC</description>
    <fields>
        <fullName>ASI_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Not Converted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Submit for Cancel</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Free Goods Request &amp; POSM</label>
    <nameField>
        <displayFormat>FG-{00000000}</displayFormat>
        <label>Request Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free Goods Request &amp; POSM</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_MY_Change_Draft_FOC_Light_ctrl.cls
public class ASI_CRM_MY_Change_Draft_FOC_Light_ctrl {
	@AuraEnabled
    public static ASI_FOC_Free_Goods_Request__c getRecord(Id recordId){
        return [Select Id,ASI_CRM_Status__c from ASI_FOC_Free_Goods_Request__c where Id = :recordId limit 1];
    }
    
    @AuraEnabled
    public static string updatToDraft(Id recordId){
        try{
        	ASI_FOC_Free_Goods_Request__c foc = new ASI_FOC_Free_Goods_Request__c();
        	foc.Id = recordId;
        	foc.ASI_CRM_Status__c  = 'Draft';
            update foc;
            return 'Success';
        }catch(Exception e){
            return e.getMessage();
        }
    }
}