objects/ASI_CRM_ContractTarget__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Subbrand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-brand</label>
        <referenceTo>ASI_MFM_Sub_brand__c</referenceTo>
        <relationshipLabel>Contract Targets</relationshipLabel>
        <relationshipName>ASI_CRM_Subbrand</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Target</label>
    <nameField>
        <displayFormat>CTID{00000000}</displayFormat>
        <label>Contract Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_GiftBox_Request_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Subbrand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-brand</label>
        <referenceTo>ASI_MFM_Sub_brand__c</referenceTo>
        <relationshipName>Gift_Box_POSM_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_GiftBox_Request_Id__c</fullName>
        <label>Request Reference</label>
        <referenceTo>ASI_GiftBox_Request_Header__c</referenceTo>
        <relationshipName>Gift_Box_Request_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ASI_GiftBox_Request_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Item</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI VN POSM Request Item</value>
            </filterItems>
            <filterItems>
                <field>ASI_GiftBox_Inventory_Master__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI GiftBox VN GiftBox Master</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM VN FOC Request Item, ASI CRM VN FOC Request Item, ASI CRM VN Display Listing Request Item</value>
            </filterItems>
            <filterItems>
                <field>ASI_GiftBox_Inventory_Master__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI FOC VN Master</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_GiftBox_Inventory_Master__c</referenceTo>
        <relationshipLabel>All Payment Request Items</relationshipLabel>
        <relationshipName>Gift_Box_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>All Payment Request Item</label>
    <nameField>
        <displayFormat>GBRI-{0000000}</displayFormat>
        <label>Request Item Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>All Payment Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_Sub_brand__c.object
<CustomObject>
    <label>Sub-brand</label>
    <nameField>
        <label>Sub-brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_VN_CapsuleCSRequestItemTableCtrl.cls
/*********************************************************************************
 * Name: ASI_CRM_VN_CapsuleCSRequestItemTableCtrl
 * Description: Controller for ASI_CRM_VN_CapsuleCSRequestItemTableCmp
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 26/11/2017       Hugo Cheung             Created          
*/
public class ASI_CRM_VN_CapsuleCSRequestItemTableCtrl {
    
    private final static Map<String, Schema.SObjectField> REQUEST_ITEM_FIELD_MAP = Schema.SObjectType.ASI_GiftBox_Request_Item__c.fields.getMap();
    
    public String requestId {get; set;}
    
    //Page Parameters
    public Boolean isPageInit {get { if(isPageInit != true) {isPageInit = init();} return isPageInit;} set;}
    
    public List<ASI_GiftBox_Request_Item__c> requestItemList {get; set;}
    
    public ASI_CRM_VN_CapsuleCSRequestItemTableCtrl() {
    	System.debug(requestId);
    }
    
    private Boolean init() {
        requestItemList = retrieveRequestItemList(requestId);
        System.debug(requestItemList);
        return true;
    }
    
    /***************
    Data Retrievement Function
    ***************/
    private List<ASI_GiftBox_Request_Item__c> retrieveRequestItemList(Id requestId) {
        String query = 'SELECT ' + genQueryField(REQUEST_ITEM_FIELD_MAP) + 
                       ', ASI_CRM_Subbrand__r.Name ' + 
                       ', RecordType.DeveloperName ' + 
                       'FROM ASI_GiftBox_Request_Item__c ' + 
                       'Where ASI_GiftBox_Request_Id__c = :requestId ';
        
        return (List<ASI_GiftBox_Request_Item__c>) Database.query(query);
    }
    
    /***************
    Tools Function
    ***************/
    private String genQueryField(Map<String, Schema.SObjectField> fieldMap) {
      String queryField = '';
      for(String fields : fieldMap.keySet()) {
      	queryField += fields + ',';
      }
    	return queryField.subString(0, queryField.length() - 1);
    }
}