objects/ASI_HK_CRM_Pre_Approval_Form__c.object
<CustomObject>
    <fields>
        <fullName>ASI_HK_CRM_PAF_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending for Workflow</fullName>
                </value>
                <value>
                    <fullName>SA Rejected</fullName>
                </value>
                <value>
                    <fullName>SA Reviewed</fullName>
                </value>
                <value>
                    <fullName>First Reject</fullName>
                </value>
                <value>
                    <fullName>Reject Final</fullName>
                </value>
                <value>
                    <fullName>Date changed</fullName>
                </value>
                <value>
                    <fullName>FD Approved</fullName>
                </value>
                <value>
                    <fullName>FD Rejected</fullName>
                </value>
                <value>
                    <fullName>FM Approved</fullName>
                </value>
                <value>
                    <fullName>FM Rejected</fullName>
                </value>
                <value>
                    <fullName>MD Final</fullName>
                </value>
                <value>
                    <fullName>MD Rejected</fullName>
                </value>
                <value>
                    <fullName>MKTD Approved</fullName>
                </value>
                <value>
                    <fullName>MKTD Rejected</fullName>
                </value>
                <value>
                    <fullName>HS Approved</fullName>
                </value>
                <value>
                    <fullName>HS Rejected</fullName>
                </value>
                <value>
                    <fullName>Supervisor Approved</fullName>
                </value>
                <value>
                    <fullName>Supervisor Rejected</fullName>
                </value>
                <value>
                    <fullName>Confirmed with Customer</fullName>
                </value>
                <value>
                    <fullName>Approve Final</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Approval Form</label>
    <nameField>
        <label>Pre-Approval Form Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Approval Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_HK_CRM_PAFConfirmByCustomerCON.cls
public with sharing class ASI_HK_CRM_PAFConfirmByCustomerCON {
	
	private static final String CONFIRM_STATUS = 'Confirmed with Customer';
	private static final Set<String> ALLOW_STATUS = new Set<String>{
		'FM Approved'
		, 'MKTD Approved'
		, 'MD Final'
		, 'Approve Final'
	};
	
	public ID pafId { get; set; }
	private ASI_HK_CRM_Pre_Approval_Form__c paf;
	
	public ASI_HK_CRM_PAFConfirmByCustomerCON(ApexPages.StandardController stdCon) {
		this.pafId = stdCon.getId();
		if (pafId != null)
			this.paf = [SELECT Id, ASI_HK_CRM_PAF_Status__c FROM ASI_HK_CRM_Pre_Approval_Form__c WHERE Id = :pafId];
	}
	
	public PageReference confirm() {
		PageReference resultPage = null;
		try {
			if (this.paf == null)
				throw new ASI_HK_CRM_CustomException('Record not found');
			else if (!ALLOW_STATUS.contains(paf.ASI_HK_CRM_PAF_Status__c))
				throw new ASI_HK_CRM_CustomException('The current status is not allowed to confirm');
			paf.ASI_HK_CRM_PAF_Status__c = CONFIRM_STATUS;
			update paf;
			return new PageReference('/' + paf.Id);
		} catch (DmlException dmle) {
			Integer numOfErr = dmle.getNumDml();
			for (Integer i = 0; i < numOfErr; i++)
				paf.addError(dmle.getDmlMessage(i));
		} catch (Exception e) {
			paf.addError(e.getMessage());
		}
		return null;
	}
}