objects/ASI_MFM_Fiscal_Year__c.object
<CustomObject>
    <description>Used in MFM plan to control the available FY that can be selected by user</description>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Year</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_TP_Promotion_Mode__c</fullName>
        <label>Promotion mechanism</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Fiscal_year__c</fullName>
        <label>Fiscal year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY1011</fullName>
                </value>
                <value>
                    <fullName>FY1112</fullName>
                </value>
                <value>
                    <fullName>FY1213</fullName>
                </value>
                <value>
                    <fullName>FY1314</fullName>
                </value>
                <value>
                    <fullName>FY1415</fullName>
                </value>
                <value>
                    <fullName>FY1516</fullName>
                </value>
                <value>
                    <fullName>FY1617</fullName>
                </value>
                <value>
                    <fullName>FY1718</fullName>
                </value>
                <value>
                    <fullName>FY1819</fullName>
                </value>
                <value>
                    <fullName>FY1920</fullName>
                </value>
                <value>
                    <fullName>FY2021</fullName>
                </value>
                <value>
                    <fullName>FY2122</fullName>
                </value>
                <value>
                    <fullName>FY2223</fullName>
                </value>
                <value>
                    <fullName>FY2324</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_Start_Date__c</fullName>
        <defaultValue>IF($RecordType.DeveloperName =&apos;ASI_MFM_SC_Plan&apos;,today(),null)</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Plan_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_TP_Promotion_Mode__c</fullName>
        <label>Promotion mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>intake price verification</fullName>
                </value>
                <value>
                    <fullName>scan data</fullName>
                </value>
                <value>
                    <fullName>scan data tax included</fullName>
                </value>
                <value>
                    <fullName>intake price verification tax included</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>Plan Line Items</relationshipLabel>
        <relationshipName>Plan_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan Line Item</label>
    <nameField>
        <displayFormat>PLI{000000}</displayFormat>
        <label>Plan Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_TP_MOTTradePlanListCtrl.cls
public with sharing class ASI_CRM_CN_TP_MOTTradePlanListCtrl {
    public Decimal taxRate {get;set;}
    public String proModeOptions {get; set;}
    public String planStatusOptions {get; set;}
    public String poStatusOptions {get; set;}
    public Decimal estAmountLimit {get; set;}
    public String bpListViewURL {get; set;}

    public ASI_CRM_CN_TP_MOTTradePlanListCtrl(){
      this.taxRate = ASI_CRM_CN_TP_Utils.getCNTaxRate();
      ASI_CRM_CN_TP_BudgetPlanUpload bpUpload = new ASI_CRM_CN_TP_BudgetPlanUpload();
      bpListViewURL = bpUpload.listViewURL(bpUpload.prefixList(),'ASI_MFM_Plan__c','CN Budget Plan');
      
      Schema.DescribeFieldResult proModeFieldResult = ASI_MFM_Plan_Line_Item__c.ASI_CRM_CN_TP_Promotion_Mode__c.getDescribe();
      this.proModeOptions = JSON.serialize(ASI_CRM_CN_TP_Utils.getPickListValuesIntoList(proModeFieldResult, 'promotionMode'));
      this.planStatusOptions = JSON.serialize(ASI_CRM_CN_TP_Utils.getSettingValuesIntoList(Label.ASI_CRM_CN_TP_Trade_Plan_Status));
      this.poStatusOptions = JSON.serialize(ASI_CRM_CN_TP_Utils.getSettingValuesIntoList(Label.ASI_CRM_CN_TP_PO_Status_CN));
      estAmountLimit = Decimal.valueOf(Label.ASI_CRM_CN_TP_Estimate_Amount_Limit);
    }

    //query Record in database
    @RemoteAction
    public static List<PlanLineItem> queryRecord(List<Id> tpItemIds){
      List<PlanLineItem> result = new List<PlanLineItem>();
      List<ASI_MFM_Plan_Line_Item__c> tempTPList = ASI_CRM_CN_TP_Utils.getTradePlanListByIds(tpItemIds);
        
      //Data Handling
        for (ASI_MFM_Plan_Line_Item__c tempTP : tempTPList) {
            String startDate_Str = DateTime.newInstance(tempTP.ASI_MFM_Plan__r.ASI_MFM_Start_Date__c.year(),tempTP.ASI_MFM_Plan__r.ASI_MFM_Start_Date__c.month(),tempTP.ASI_MFM_Plan__r.ASI_MFM_Start_Date__c.day(), 0,0,0).format('yyyy/MM/dd');
            String endDate_Str = DateTime.newInstance(tempTP.ASI_MFM_Plan__r.ASI_MFM_End_Date__c.year(),tempTP.ASI_MFM_Plan__r.ASI_MFM_End_Date__c.month(),tempTP.ASI_MFM_Plan__r.ASI_MFM_End_Date__c.day(), 0,0,0).format('yyyy/MM/dd');
            result.add(new PlanLineItem(tempTP, startDate_Str, endDate_Str));
        }

        return result;
    }
    @RemoteAction
    public static Map<String,String> generate999(String jsonData){
        List<Object> pLItemList = (List<Object>)JSON.deserializeUntyped(jsonData);
        Map<String,String> msgMap = ASI_CRM_CN_TP_Utils.generate999(pLItemList);
        return msgMap;
    }
    @RemoteAction
    public static Map<String,String> deleteItems(String jsonData){
        List<Object> pLItemList = (List<Object>)JSON.deserializeUntyped(jsonData);
        Map<String,String> msgMap = ASI_CRM_CN_TP_Utils.deletePlans(pLItemList);
        return msgMap;
    }
    @RemoteAction
    public static Map<String,String> save(String jsonData){
      system.debug('jsonData*** '+jsonData);
      List<Object> pLItemList = (List<Object>)JSON.deserializeUntyped(jsonData);
      Map<String,String> msgMap = ASI_CRM_CN_TP_Utils.savePLItem(pLItemList);
      return msgMap;
    }

    @RemoteAction
    public static Map<String,String> submitApproval(String remarks, String jsonData){
      List<Object> pLItemList = (List<Object>)JSON.deserializeUntyped(jsonData);
      Map<String,String> msgMap = ASI_CRM_CN_TP_Utils.saveTPApprovalAndUpdateTp(remarks, pLItemList);
      return msgMap;
    }

    @RemoteAction
    public static Map<String,String> generatePo(String jsonData){
      List<Object> pLItemList = (List<Object>)JSON.deserializeUntyped(jsonData);
      Map<String,String> msgMap = ASI_CRM_CN_TP_Utils.savePo(pLItemList);
      return msgMap;
    }

    @RemoteAction
    public static Map<String,String> generatePayment(String jsonData){
      List<Object> pLItemList = (List<Object>)JSON.deserializeUntyped(jsonData);
      Map<String,String> msgMap = ASI_CRM_CN_TP_Utils.savePayment(pLItemList);
      return msgMap;
    }

    @RemoteAction
    @ReadOnly
    public static List<Id> queryTpItemIds (){
        List<Id> tpItemIds = new List<Id>();//order by CreatedDate DESC
        Set<String> fYSet = ASI_CRM_CN_TP_Utils.getFYContainsPreNextCurrent();
        for(ASI_MFM_Plan_Line_Item__c tpItem : [SELECT Id FROM ASI_MFM_Plan_Line_Item__c WHERE RecordType.developerName =:ASI_CRM_CN_TP_Utils.TP_LINE_ITEM_RTNAME AND ASI_MFM_Plan__r.ASI_MFM_Fiscal_year__c in:fYSet ORDER BY CreatedDate DESC LIMIT 20000]){
            tpItemIds.add(tpItem.Id);
        }
        return tpItemIds;
    }


    public without sharing class PlanLineItem{
        public ASI_MFM_Plan_Line_Item__c item2 {Get; Set;}
        public String dateScope_str {Get; Set;}{dateScope_str='';} 
        public String startDate_str {Get; Set;}{dateScope_str='';} 
        public String endDate_str {Get; Set;}{dateScope_str='';} 
        public String promotionMode_label {Get; Set;}{promotionMode_label='';} 
        public String ischeckedToPay {Get; Set;}{ischeckedToPay='false';} 
        public Decimal fixedCost {Get; Set;}{fixedCost=0;} 
        public Decimal promotionAmount {Get; Set;}{promotionAmount=0;} 
         public planLineItem (ASI_MFM_Plan_Line_Item__c item){
            this.item2 = item;
        }

        public planLineItem (ASI_MFM_Plan_Line_Item__c item, String startDate, String endDate){
            this.item2 = item;
            this.startDate_str = startDate;
            this.endDate_str = endDate;
            this.promotionMode_label = ASI_CRM_CN_TP_Utils.getPicklistLabels('ASI_MFM_Plan_Line_Item__c', 'ASI_CRM_CN_TP_Promotion_Mode__c').get(item.ASI_CRM_CN_TP_Promotion_Mode__c);
        }

        public planLineItem (){}
    }
}