objects/ASI_MFM_A_C_Code__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_A_C_Code__c</fullName>
        <label>A/C Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>A/C Code</label>
    <nameField>
        <label>A/C</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A/C Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_BatchLog__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Log_Detail__c</fullName>
        <label>Log Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch Log</label>
    <nameField>
        <displayFormat>B-{0000000}</displayFormat>
        <label>Batch Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_MFM_PO_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_A_C_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>A/C Code</label>
        <referenceTo>ASI_MFM_A_C_Code__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_CN_Paid_Amount__c</fullName>
        <label>Paid Amount</label>
        <summarizedField>ASI_MFM_Payment_Line_Item__c.ASI_MFM_Payment_Amount_Net_of_Tax__c</summarizedField>
        <summaryForeignKey>ASI_MFM_Payment_Line_Item__c.ASI_MFM_PO_Line_Item__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Currency__c</fullName>
        <formula>Text( ASI_MFM_PO__r.ASI_MFM_Currency__c )</formula>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Receipt_Date__c</fullName>
        <label>Receipt Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sub_brand_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-brand Code</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3) OR (4 AND 5 AND 6) OR 7</booleanFilter>
            <errorMessage>Sub-brand Code Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>TW Sub-brand, TH CRM Sub-brand, TnE MY Sub-brand</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>TH CRM Sub-brand</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.ASI_MFM_Active_for_MFM__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.ASI_CRM_TW_Company__c</field>
                <operation>contains</operation>
                <value>PRT</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>TW Sub-brand</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.ASI_TH_CRM_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$User.BypassVR__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Sub_brand__c</referenceTo>
        <relationshipLabel>PO Line Items</relationshipLabel>
        <relationshipName>PO_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO Line Item</label>
    <nameField>
        <displayFormat>POL{000000}</displayFormat>
        <label>PO Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_PO_Receipt__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Amount__c</fullName>
        <label>Amount</label>
        <summarizedField>ASI_MFM_PO_Receipt_Item__c.ASI_MFM_Amount__c</summarizedField>
        <summaryForeignKey>ASI_MFM_PO_Receipt_Item__c.ASI_MFM_PO_Receipt__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Receipt_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Receipt Date</label>
        <type>Date</type>
    </fields>
    <label>PO Receipt</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>PO Receipt ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Receipts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_PO_Receipt_Item__c.object
<CustomObject>
    <description>MFM PO receipt item</description>
    <fields>
        <fullName>ASI_MFM_A_C_Code__c</fullName>
        <formula>ASI_MFM_PO_Line_Item__r.ASI_MFM_A_C_Code__r.ASI_MFM_A_C_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>A/C Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_A_C_Code_temp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>A/C Code</label>
        <referenceTo>ASI_MFM_A_C_Code__c</referenceTo>
        <relationshipLabel>PO Receipt Items</relationshipLabel>
        <relationshipName>PO_Receipt_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Amount__c</fullName>
        <label>Receipt Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Currency_Temp__c</fullName>
        <label>Currency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Currency__c</fullName>
        <formula>ASI_MFM_PO_Line_Item__r.ASI_MFM_Currency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO_Line_Item__c</fullName>
        <label>PO Item</label>
        <referenceTo>ASI_MFM_PO_Line_Item__c</referenceTo>
        <relationshipLabel>PO Receipt Items</relationshipLabel>
        <relationshipName>PO_Receipt_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO_Receipt__c</fullName>
        <label>PO Receipt</label>
        <referenceTo>ASI_MFM_PO_Receipt__c</referenceTo>
        <relationshipLabel>PO Receipt Items</relationshipLabel>
        <relationshipName>PO_Receipt_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Receipt_Date__c</fullName>
        <label>Receipt Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sub_Brand_Code__c</fullName>
        <formula>ASI_MFM_PO_Line_Item__r.ASI_MFM_Sub_brand_Code__r.ASI_MFM_Sub_brand_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub-Brand Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sub_brand_temp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-brand</label>
        <referenceTo>ASI_MFM_Sub_brand__c</referenceTo>
        <relationshipLabel>PO Receipt Items</relationshipLabel>
        <relationshipName>PO_Receipt_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO Receipt Item</label>
    <nameField>
        <displayFormat>I{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Receipt Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_MFM_CN_ClosePO_Batch.cls
Global class ASI_MFM_CN_ClosePO_Batch implements Database.Batchable<sObject>, Database.Stateful{
    
    private static Final Id PO_RECEIPT_RT = Global_RecordTypeCache.getRtId('ASI_MFM_PO_Receipt__cASI_MFM_CN_PO_Receipt');
    private static Final Id PO_RECEIPT_ITEM_RT = Global_RecordTypeCache.getRtId('ASI_MFM_PO_Receipt_Item__cASI_MFM_CN_PO_Receipt_item');
    private static Final Integer LOG_DETAIL_SIZE = 4000;
    private ASI_MFM_PO_Receipt__c insertPOReceiptHeader;
    
	public Id LogId;
    public String strSql;
        
    Global ASI_MFM_CN_ClosePO_Batch(){}
    Global ASI_MFM_CN_ClosePO_Batch(Id log, String str){
        this.LogId = log;
        this.strSql = str;
        if(this.insertPOReceiptHeader==null) {
            this.insertPOReceiptHeader = new ASI_MFM_PO_Receipt__c(ASI_MFM_Receipt_Date__c = date.today(), recordTypeId = PO_RECEIPT_RT);
            insert this.insertPOReceiptHeader;
        }
    }
    
    Global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(strSql);
    }
    
    Global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<ASI_MFM_PO_Line_Item__c> poLineList = (List<ASI_MFM_PO_Line_Item__c>) scope;
        List<ASI_MFM_PO_Receipt_Item__c> insertPOReceiptItemList = new List<ASI_MFM_PO_Receipt_Item__c>();
        if(insertPOReceiptHeader==null) {
            insertPOReceiptHeader = new ASI_MFM_PO_Receipt__c(ASI_MFM_Receipt_Date__c = date.today(), recordTypeId = PO_RECEIPT_RT);
            insert insertPOReceiptHeader;
        }
        
        for(ASI_MFM_PO_Line_Item__c obj : poLineList){
            insertPOReceiptItemList.add(new ASI_MFM_PO_Receipt_Item__c(ASI_MFM_Amount__c = obj.ASI_MFM_CN_Paid_Amount__c
                                                                       , recordTypeId = PO_RECEIPT_ITEM_RT
                                                                       , ASI_MFM_PO_Line_Item__c = obj.id
                                                                       , ASI_MFM_Sub_brand_temp__c = obj.ASI_MFM_Sub_brand_Code__c
                                                                       , ASI_MFM_A_C_Code_temp__c = obj.ASI_MFM_A_C_Code__c
                                                                       , ASI_MFM_PO_Receipt__c = insertPOReceiptHeader.id
                                                                       , ASI_MFM_Receipt_Date__c = date.today()
                                                                       , ASI_MFM_Currency_Temp__c = obj.ASI_MFM_Currency__c
                                                                      ));
        }
        
        String errMsg = '';
        if(insertPOReceiptItemList.size()>0) {
            Database.SaveResult[] insertResults = Database.insert(insertPOReceiptItemList, false);
            for(Integer i=0;i<insertResults.size();i++){
                Database.SaveResult sr = insertResults.get(i);
                if(sr.isSuccess()){
                    // success updated record;
                } else {
                    if(errMsg.length()<LOG_DETAIL_SIZE) {
                        errMsg += 'Receipt Item for PO Line('+insertPOReceiptItemList.get(i).ASI_MFM_PO_Line_Item__c+')\n';
                        for(Database.Error err : sr.getErrors()) {
                            errMsg += err.getStatusCode() + ': ' + err.getMessage() + err.getFields()+'\n';
                        }
                    }
                }
            }
        }
        if(errMsg!='' && LogId!=null) {
            ASI_MFM_BatchLog__c logger = [SELECT id, ASI_MFM_Log_Detail__c  FROM ASI_MFM_BatchLog__c WHERE id =:LogId];
            if(logger.ASI_MFM_Log_Detail__c==null) logger.ASI_MFM_Log_Detail__c='';
            if(logger.ASI_MFM_Log_Detail__c.length()+errMsg.length() < LOG_DETAIL_SIZE ) {
                logger.ASI_MFM_Log_Detail__c += errMsg;
            } else {
                logger.ASI_MFM_Log_Detail__c = (logger.ASI_MFM_Log_Detail__c+errMsg).substring(0, LOG_DETAIL_SIZE)+'...';
            }
            update logger;
        }        
    }
    
    Global void finish(Database.BatchableContext BC){
        if(insertPOReceiptHeader != null){
            Integer itemCount = [SELECT count() FROM ASI_MFM_PO_Receipt_Item__c WHERE ASI_MFM_PO_Receipt__c = :insertPOReceiptHeader.id];
            if(itemCount == 0) delete insertPOReceiptHeader;
        }
        if(LogId!=null) {
            ASI_MFM_BatchLog__c logger = [SELECT id, ASI_MFM_Log_Detail__c  FROM ASI_MFM_BatchLog__c WHERE id =:LogId];
            if(logger.ASI_MFM_Log_Detail__c==null || logger.ASI_MFM_Log_Detail__c=='') {
                delete logger;
            }
        }
    }
    
}