objects/ASI_CRM_Price_And_Discount__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Estimated_annual_order_amount__c</fullName>
        <formula>ASI_CRM_Customer__r.ASI_CRM_CN_Estimated_annual_order_amount__c</formula>
        <label>Estimated Annual Order Amount in CNY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Total_Gross_Sales_Impact__c</fullName>
        <label>Total Gross Sales Impact</label>
        <summarizedField>ASI_CRM_Price_And_Discount_Detail__c.ASI_CRM_CN_Gross_Sales_Impact_RollUp__c</summarizedField>
        <summaryForeignKey>ASI_CRM_Price_And_Discount_Detail__c.ASI_CRM_Price_And_Discount__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Channel__c</fullName>
        <formula>ASI_CRM_Customer__r.ASI_CRM_CN_Channel_CN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Customer_Region__c</fullName>
        <formula>ASI_CRM_Customer__r.ASI_CRM_CN_Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Price And Discounts</relationshipLabel>
        <relationshipName>Price_And_Discounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Effective_From__c</fullName>
        <label>Effective From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Effective_To__c</fullName>
        <defaultValue>DATE(2050,12,31)</defaultValue>
        <label>Effective To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_IHBR_Price_Type__c</fullName>
        <label>IHBR Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract Price</fullName>
                </value>
                <value>
                    <fullName>Promotion Price</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_JDE_Code__c</fullName>
        <formula>ASI_CRM_Customer__r.ASI_CRM_CN_JDE_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>JDE Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_ReasonForThePriceIsLowerThanT1__c</fullName>
        <label>Reason For The Price Is Lower Than T1:</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Reason_for_Investment__c</fullName>
        <label>Reason for Investment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Remark__c</fullName>
        <inlineHelpText>请使用英语填写价格申请的原因以及目的</inlineHelpText>
        <label>Remark</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NPL T1 Price Request</fullName>
                </value>
                <value>
                    <fullName>Repacking Price Request</fullName>
                </value>
                <value>
                    <fullName>T1 Price Adjustment Request</fullName>
                </value>
                <value>
                    <fullName>Customer Price and Discount Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Volume_Based_Mechanics__c</fullName>
        <label>Volume Based Mechanics</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Volume_Based__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Volume Based</label>
        <type>Checkbox</type>
    </fields>
    <label>Price And Discount</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Price and Discount Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price And Discounts</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_CN_Customer_Price_and_Discount_Request</fullName>
        <active>true</active>
        <label>CN Customer Price and Discount Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Price_And_Discount_Detail__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Buy_X__c</fullName>
        <formula>ASI_CRM_Promotion_Code__r.ASI_CRM_Buy_X__c</formula>
        <label>Buy X</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Current_T1_Price_BT_with_VAT__c</fullName>
        <label>Current T1 Price - BT (with VAT)</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Get_Y__c</fullName>
        <formula>ASI_CRM_Promotion_Code__r.ASI_CRM_Get_Y__c</formula>
        <label>Get Y</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Gross_Sales_Impact__c</fullName>
        <formula>/* modify VAT rate from 1.17 to 1.16 */
/* modify VAT rate from 1.16 to 1.13 */
ABS( IF(
(( ASI_CRM_Price_And_Discount__r.RecordType.DeveloperName = &quot;ASI_CRM_CN_Customer_Price_and_Discount_Request&quot; || ASI_CRM_Price_And_Discount__r.RecordType.DeveloperName = &quot;ASI_CRM_CN_Customer_Price_and_Discount_Request_RO&quot;))
, IF( NOT(ISBLANK(ASI_CRM_Promotion_Code__c ) ) &amp;&amp;  ASI_CRM_Buy_X__c &gt; 0 &amp;&amp;  ASI_CRM_Get_Y__c &gt; 0, IF( ASI_CRM_Total_Estimated_Vol_BT__c * ( (ASI_CRM_New_Price_BT_non_VAT__c * ( ASI_CRM_Buy_X__c/ (ASI_CRM_Buy_X__c + ASI_CRM_Get_Y__c ) ) ) - (ASI_CRM_Current_T1_Price_BT_with_VAT__c/IF( ASI_CRM_CN_Tax_Rate__c == 0 , 1.13,1+ASI_CRM_CN_Tax_Rate__c ))) &lt; 0
, ASI_CRM_Total_Estimated_Vol_BT__c * ( (ASI_CRM_New_Price_BT_non_VAT__c * ( ASI_CRM_Buy_X__c/(ASI_CRM_Buy_X__c + ASI_CRM_Get_Y__c ) ) ) - (ASI_CRM_Current_T1_Price_BT_with_VAT__c/IF( ASI_CRM_CN_Tax_Rate__c == 0 , 1.13,1+ASI_CRM_CN_Tax_Rate__c ))), 0)
, IF( ( ASI_CRM_New_Price_BT_non_VAT__c &lt; (ASI_CRM_Current_T1_Price_BT_with_VAT__c/IF( ASI_CRM_CN_Tax_Rate__c == 0 , 1.13,1+ASI_CRM_CN_Tax_Rate__c )) )
, ASI_CRM_Total_Estimated_Vol_BT__c * ( (ASI_CRM_New_Price_BT_non_VAT__c ) - (ASI_CRM_Current_T1_Price_BT_with_VAT__c/IF( ASI_CRM_CN_Tax_Rate__c == 0 , 1.13,1+ASI_CRM_CN_Tax_Rate__c ))), 0)), 0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Sales Impact</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Item_Group_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Price And Discount Details</relationshipLabel>
        <relationshipName>Price_And_Discount_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_New_Price_BT_non_VAT__c</fullName>
        <formula>ASI_CRM_New_Price_BT_with_VAT__c/ IF(ASI_CRM_CN_Tax_Rate__c == 0, 1.13, 1+ASI_CRM_CN_Tax_Rate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New Price - BT (non-VAT)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_New_Price_BT_with_VAT__c</fullName>
        <label>New Price - BT (with VAT)</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Price_And_Discount__c</fullName>
        <label>Price And Discount</label>
        <referenceTo>ASI_CRM_Price_And_Discount__c</referenceTo>
        <relationshipLabel>Price And Discount Details</relationshipLabel>
        <relationshipName>Price_And_Discount_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Promotion_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Code</label>
        <referenceTo>ASI_CRM_Promotion_Master__c</referenceTo>
        <relationshipLabel>Price And Discount Details</relationshipLabel>
        <relationshipName>Price_And_Discount_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Total_Estimated_Vol_BT__c</fullName>
        <label>Total Estimated Vol - BT</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_vs_Current_T1_with_VAT_Percent__c</fullName>
        <formula>IF(ASI_CRM_Current_T1_Price_BT_with_VAT__c &gt; 0, IF( NOT(ISBLANK( ASI_CRM_Promotion_Code__c )) &amp;&amp; NOT(ISBLANK(ASI_CRM_Buy_X__c)) &amp;&amp;  NOT(ISBLANK(ASI_CRM_Get_Y__c)), ((ASI_CRM_New_Price_BT_with_VAT__c * (ASI_CRM_Buy_X__c/(ASI_CRM_Buy_X__c+ASI_CRM_Get_Y__c)))/ASI_CRM_Current_T1_Price_BT_with_VAT__c) - 1, ( ( ASI_CRM_New_Price_BT_with_VAT__c / ASI_CRM_Current_T1_Price_BT_with_VAT__c ) - 1 )), 0)</formula>
        <label>vs Current T1 (with VAT) (%)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_vs_Current_T1_with_VAT__c</fullName>
        <formula>IF(( ASI_CRM_Price_And_Discount__r.RecordType.DeveloperName = &quot;ASI_CRM_CN_Customer_Price_and_Discount_Request&quot; || ASI_CRM_Price_And_Discount__r.RecordType.DeveloperName = &quot;ASI_CRM_CN_Customer_Price_and_Discount_Request_RO&quot; )
, IF( NOT(ISBLANK( ASI_CRM_Promotion_Code__c )) &amp;&amp; ASI_CRM_Buy_X__c &gt; 0 &amp;&amp; ASI_CRM_Get_Y__c &gt; 0 &amp;&amp; NOT(ISBLANK(ASI_CRM_Current_T1_Price_BT_with_VAT__c))
, ((ASI_CRM_New_Price_BT_with_VAT__c * (ASI_CRM_Buy_X__c/(ASI_CRM_Buy_X__c+ASI_CRM_Get_Y__c))) - ASI_CRM_Current_T1_Price_BT_with_VAT__c)
, ( ( ASI_CRM_New_Price_BT_with_VAT__c - ASI_CRM_Current_T1_Price_BT_with_VAT__c )))
, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>vs Current T1 (with VAT)</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Price And Discount Detail</label>
    <nameField>
        <displayFormat>PDD-{00000000}</displayFormat>
        <label>Price And Discount Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price And Discount Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Promotion_Master__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Buy_X__c</fullName>
        <label>Buy X</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Get_Y__c</fullName>
        <label>Get Y</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Buy X Get Y</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion Master</label>
    <nameField>
        <label>Promotion Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Item_Group__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Remark__c</fullName>
        <label>Remark</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Item_Group_Code__c</fullName>
        <label>Item Group Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item Group</label>
    <nameField>
        <label>Item Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_PriceDiscount_EmailController.cls
public class ASI_CRM_CN_PriceDiscount_EmailController {
    public Boolean dummyVar { get { if (dummyVar != true) {dummyVar = init();} return dummyVar; } set; }
    public String currentHeaderID {set;get;}
    public Integer RTnumbetr {get;set;}  
    public ASI_CRM_Price_And_Discount__c PDCurrent{get;set;}
    public List<ASI_CRM_Price_And_Discount_Detail__c> lineItem{get;set;}
    public String SpaceStr {get;set;}
    
    public boolean init(){
        PDCurrent=[select id,name,RecordType.DeveloperName,RecordType.name,
                   ASI_CRM_Type__c,ASI_CRM_Remark__c,ASI_CRM_Effective_From__c,ASI_CRM_Effective_To__c,ASI_CRM_JDE_Code__c,ASI_CRM_Customer__r.name,
                   ASI_CRM_Customer_Region__c,ASI_CRM_Volume_Based__c,ASI_CRM_Volume_Based_Mechanics__c,ASI_CRM_Channel__c,ASI_CRM_ReasonForThePriceIsLowerThanT1__c,
                   ASI_CRM_Reason_for_Investment__c,ASI_CRM_CN_Total_Gross_Sales_Impact__c,ASI_CRM_IHBR_Price_Type__c
                   , ASI_CRM_CN_Estimated_annual_order_amount__c //20161104, Leo@Elufa
                   from ASI_CRM_Price_And_Discount__c where id= : currentHeaderID];
        lineItem=[select id,name,ASI_CRM_Item_Group_Description__c,ASI_CRM_Current_T1_Price_BT_with_VAT__c,ASI_CRM_Item_Group_Description__r.name,
                  ASI_CRM_Item_Group_Description__r.ASI_MFM_Item_Group_Code__c,ASI_CRM_New_Price_BT_non_VAT__c,ASI_CRM_vs_Current_T1_with_VAT__c,ASI_CRM_Total_Estimated_Vol_BT__c,
                  ASI_CRM_Gross_Sales_Impact__c,ASI_CRM_Promotion_Code__r.Name,ASI_CRM_Buy_X__c,ASI_CRM_Get_Y__c,
                  ASI_CRM_New_Price_BT_with_VAT__c,ASI_CRM_vs_Current_T1_with_VAT_Percent__c
                  ,ASI_CRM_Promotion_Code__r.ASI_CRM_Description__c //20160822, added by Leo
                  from ASI_CRM_Price_And_Discount_Detail__c where ASI_CRM_Price_And_Discount__c=: currentHeaderID];
        
        if(PDCurrent.RecordType.DeveloperName.contains('ASI_CRM_CN_Customer_Price_and_Discount_Request')){
            RTnumbetr=2;
        }else{
            RTnumbetr=1;
        }       
        SpaceStr='                       ';
        return true;
    }

}