objects/ASI_CRM_Anti_Bribery__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Approval_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_DynamicApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DynamicApproval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_FixApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FixApproval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Anti-Bribery Request</label>
    <nameField>
        <displayFormat>AB-{0000000}</displayFormat>
        <label>AB Policy Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Anti-Bribery Request</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_CN_Receiving_Cash</fullName>
        <active>true</active>
        <description>including cash and cash equivalent 此处包括现金和现金等价物</description>
        <label>CN Receiving Cash</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_AntiBribery_SubmitController.cls
public class ASI_CRM_CN_AntiBribery_SubmitController {

    ASI_CRM_Anti_Bribery__c header;
    Map<id,recordType> mapRT = new Map<id,recordType>([SELECT id,DeveloperName FROM RecordType WHERE sObjectType='ASI_CRM_Anti_Bribery__c']);
    public ASI_CRM_CN_AntiBribery_SubmitController(ApexPages.StandardController stdController){
        header = (ASI_CRM_Anti_Bribery__c) stdController.getRecord();
    }
    
    public PageReference submitForApproval(){

        ASI_CRM_Anti_Bribery__c obj = [SELECT id, ASI_CRM_FixApproval__c, ASI_CRM_DynamicApproval__c FROM ASI_CRM_Anti_Bribery__c WHERE id = : header.id];
        
        if(mapRT.get(header.RecordTypeId).DeveloperName!='ASI_CRM_CN_Receiving_Cash' && (obj.ASI_CRM_DynamicApproval__c==true || obj.ASI_CRM_FixApproval__c==true)){
            header.ASI_CRM_Approval_Checkbox__c = true;
            update header;
            //Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        	//req.setObjectId(header.id);
        	//Approval.ProcessResult result = Approval.process(req);
        	return new pageReference('/apex/ASI_SubmitApprovalPage?id=' + header.id);
            
        }else{
            header.ASI_CRM_Status__c = 'Archived';
            
            try{
                update header;
                return new pageReference('/'+ header.id);
            }catch(dmlException dmle){
                
                return Null;
            }
        }
    }
    public PageReference cancel(){
        return new pageReference('/'+ header.id);
    }
}