objects/ASI_CN_NPL_NPL_Request__c.object
<CustomObject>
    <description>ASI CN New Product Launch Request</description>
    <fields>
        <fullName>ASI_CN_NPL_Approval_In_Progress__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System field for sending approval email with attachment</description>
        <label>Approval In Progress</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CN_NPL_Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COGNAC</fullName>
                </value>
                <value>
                    <fullName>WHISKY</fullName>
                </value>
                <value>
                    <fullName>WINE</fullName>
                </value>
                <value>
                    <fullName>OTHERS</fullName>
                </value>
                <value>
                    <fullName>CHAMPAGNE</fullName>
                </value>
                <value>
                    <fullName>RTD</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CN_NPL_Classification_Text__c</fullName>
        <description>Classification fill in using Trigger after insert</description>
        <label>Classification Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CN_NPL_Deputy_Managing_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Auto fill in by system</inlineHelpText>
        <label>Managing Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>New_Product_Launch_Requests4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CN_NPL_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Waiting for Pre-Approval</fullName>
                </value>
                <value>
                    <fullName>Pre-Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting to Fill in Price Scenario</fullName>
                </value>
                <value>
                    <fullName>Waiting to Fill in Profit and Loss</fullName>
                </value>
                <value>
                    <fullName>Waiting to Fill in Final Proposed Selling Price</fullName>
                </value>
                <value>
                    <fullName>Waiting to Fill in Launch Plan</fullName>
                </value>
                <value>
                    <fullName>Waiting to Fill in Vol Estimation</fullName>
                </value>
                <value>
                    <fullName>Waiting for S&amp;OP Alignment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Final Approval</fullName>
                </value>
                <value>
                    <fullName>Final Approved</fullName>
                </value>
                <value>
                    <fullName>Final Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Close</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Final Approval (TP is Pending)</fullName>
                </value>
                <value>
                    <fullName>Final Approval (TP is Approved)</fullName>
                </value>
                <value>
                    <fullName>Final Approval (TP is Rejected)</fullName>
                </value>
                <value>
                    <fullName>Final Approval (Domestic TP is Approved)</fullName>
                </value>
                <value>
                    <fullName>Final Approval (MM TP is Approved)</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Waiting to Fill in Profit and Loss (Approval)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>New Product Launch Request</label>
    <nameField>
        <displayFormat>NPL-{YY}-{0000}</displayFormat>
        <label>New Product Launch Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Product Launch Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CN_NPL_Product_Document__c.object
<CustomObject>
    <description>ASI CN NPL Product Document, for attaching product photo of NPL Request</description>
    <fields>
        <fullName>ASI_CN_NPL_Attach_in_Approval__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Attach in Approval Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CN_NPL_Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Photo</fullName>
                </value>
                <value>
                    <fullName>Packing Photo</fullName>
                </value>
                <value>
                    <fullName>Base Volume Forecast</fullName>
                </value>
                <value>
                    <fullName>NPL Info Before S&amp;OP Meeting</fullName>
                </value>
                <value>
                    <fullName>NPL Info After S&amp;OP Meeting</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>P&amp;L</fullName>
                </value>
                <value>
                    <fullName>Letter of Intent(LOI)</fullName>
                </value>
                <value>
                    <fullName>Launch Background Material</fullName>
                </value>
                <value>
                    <fullName>Value Chain</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CN_NPL_Parent__c</fullName>
        <label>New Product Launch Request</label>
        <referenceTo>ASI_CN_NPL_NPL_Request__c</referenceTo>
        <relationshipName>NPL_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>NPL Product Photo and Packing Photo</label>
    <nameField>
        <displayFormat>NPLA-{YY}-{00000}</displayFormat>
        <label>Attachment No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPL Product Photos and Packing Photos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ASI_CN_NPL_Receive_Approval_Request__c</fullName>
        <label>Receive Approval Request Emails(Files)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>If I am an approver or delegated approver</fullName>
                    <default>true</default>
                    <label>If I am an approver or delegated approver</label>
                </value>
                <value>
                    <fullName>Only if I am an approver</fullName>
                </value>
                <value>
                    <fullName>Only if I am a delegated approver</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_CN_NPL_Approval_Email_Test_Class.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class ASI_CN_NPL_Approval_Email_Test_Class {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        test.startTest();
        //testNPLApprovalEmail();
        test.stopTest();
    }
    
    static void testNPLApprovalEmail(){
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        user u = [SELECT id,ASI_CN_NPL_Receive_Approval_Request__c,DelegatedApproverId from user where profileid = :p.id and isactive = true limit 1];
        user delU = [SELECT id,ASI_CN_NPL_Receive_Approval_Request__c,DelegatedApproverId from user where profileid = :p.id and isactive = true and id != :u.id limit 1];
        u.ASI_CN_NPL_Receive_Approval_Request__c = 'If I am an approver or delegated approver';
        u.DelegatedApproverId = delU.id;
        update u;
        delU.ASI_CN_NPL_Receive_Approval_Request__c = 'If I am an approver or delegated approver';
        delU.DelegatedApproverId = u.id;
        update delU;
        
        System.runAs(u){
          
            List<ASI_CN_NPL_NPL_Request__c> LNpl = new List<ASI_CN_NPL_NPL_Request__c>();
            ASI_CN_NPL_NPL_Request__c npl = new ASI_CN_NPL_NPL_Request__c(ASI_CN_NPL_Approval_In_Progress__c = false,
                ASI_CN_NPL_Deputy_Managing_Director__c = u.id,
                ASI_CN_NPL_Status__c  = 'Open',
                ASI_CN_NPL_Classification_Text__c = 'Class A',
                ownerid = u.id
                );
            LNpl.add(npl);
            npl = new ASI_CN_NPL_NPL_Request__c(ASI_CN_NPL_Approval_In_Progress__c = false,
                ASI_CN_NPL_Deputy_Managing_Director__c = u.id,
                ASI_CN_NPL_Status__c  = 'Open',
                ASI_CN_NPL_Classification_Text__c = 'Class A',
                ownerid = u.id
                );
            LNpl.add(npl);
            npl = new ASI_CN_NPL_NPL_Request__c(ASI_CN_NPL_Approval_In_Progress__c = false,
                ASI_CN_NPL_Deputy_Managing_Director__c = u.id,
                ASI_CN_NPL_Status__c  = 'Open',
                ASI_CN_NPL_Classification_Text__c = 'Class A',
                ownerid = u.id
                );
            LNpl.add(npl);          
            insert LNpl;
            
            List<ASI_CN_NPL_Product_Document__c> LNplPhoto = new List<ASI_CN_NPL_Product_Document__c>();
            ASI_CN_NPL_Product_Document__c nplPhoto = new ASI_CN_NPL_Product_Document__c(ASI_CN_NPL_Attach_in_Approval__c = true,
                ASI_CN_NPL_Category__c  = 'Product Photo', ASI_CN_NPL_Parent__c = LNpl[0].id);
            LNplPhoto.add(nplPhoto);
            nplPhoto = new ASI_CN_NPL_Product_Document__c(ASI_CN_NPL_Attach_in_Approval__c = true,
                ASI_CN_NPL_Category__c  = 'Packing Photo', ASI_CN_NPL_Parent__c = LNpl[0].id);
            LNplPhoto.add(nplPhoto);
            nplPhoto = new ASI_CN_NPL_Product_Document__c(ASI_CN_NPL_Attach_in_Approval__c = true,
                ASI_CN_NPL_Category__c  = 'Product Photo', ASI_CN_NPL_Parent__c = LNpl[1].id);
            LNplPhoto.add(nplPhoto);
            nplPhoto = new ASI_CN_NPL_Product_Document__c(ASI_CN_NPL_Attach_in_Approval__c = true,
                ASI_CN_NPL_Category__c  = 'Packing Photo', ASI_CN_NPL_Parent__c = LNpl[1].id);
            LNplPhoto.add(nplPhoto);
            nplPhoto = new ASI_CN_NPL_Product_Document__c(ASI_CN_NPL_Attach_in_Approval__c = true,
                ASI_CN_NPL_Category__c  = 'Product Photo', ASI_CN_NPL_Parent__c = LNpl[2].id);
            LNplPhoto.add(nplPhoto);
            nplPhoto = new ASI_CN_NPL_Product_Document__c(ASI_CN_NPL_Attach_in_Approval__c = true,
                ASI_CN_NPL_Category__c  = 'Packing Photo', ASI_CN_NPL_Parent__c = LNpl[2].id);
            LNplPhoto.add(nplPhoto);
            
            insert LNplPhoto;
            //npl.ASI_CN_NPL_Approval_In_Progress__c = true;
            //update npl;
            
            List<id> Lid = new List<id>{LNpl[0].id};
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setObjectId(LNpl[0].id);
            req.setNextApproverIds(new List<id>{u.id});
            Approval.process(req);
            Lid = new List<id>{LNpl[1].id};
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setObjectId(LNpl[1].id);
            req1.setNextApproverIds(new List<id>{u.id});
            Approval.process(req1);
            Lid = new List<id>{LNpl[2].id};
            Approval.ProcessSubmitRequest req2 = new Approval.ProcessSubmitRequest();
            req2.setObjectId(LNpl[2].id);
            req2.setNextApproverIds(new List<id>{u.id});
            Approval.process(req2);
            
            ASI_CN_NPL_HandleApprovalEmail.sendEmail(Lid,'ASI_CN_NPL_NPL_Request__c'); 
            ASI_CN_NPL_HandleApprovalEmail a = new ASI_CN_NPL_HandleApprovalEmail();
            
 
              // create a new email and envelope object
              Messaging.InboundEmail email = new Messaging.InboundEmail() ;
              Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
             
              // setup the data for the email
              email.subject = String.valueof(LNpl[0].id).substring(0,15);
              email.fromname = 'Testing';
              email.plainTextBody = 'yes\n comment ';
              env.fromAddress = 'admin@testorg.com';
              
              ASI_CN_NPL_ProcessApprovalEmail app = new ASI_CN_NPL_ProcessApprovalEmail();
              app.handleInboundEmail(email, env);
              
              email.subject = String.valueof(LNpl[1].id).substring(0,15);
              email.plainTextBody = 'no\n comment ';
              app.handleInboundEmail(email, env);
              
              email.plainTextBody = 'Invalid\n comment ';
              app.handleInboundEmail(email, env);
              
              email.subject = String.valueof(LNpl[2].id).substring(0,15);
              email.plainTextBody = 'Invalid\n comment ';
              app.handleInboundEmail(email, env);
              
              
        }
    }
}