objects/ASI_CRM_CN_Channel__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Channel_Code__c</fullName>
        <label>Channel Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_MY_SKUPriceCost__c.object
<CustomObject>
    <description>WS to Outlet Min SP, or IntoGodownCost (IGC)</description>
    <fields>
        <fullName>ASI_CRM_Applied_To__c</fullName>
        <label>Applied To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LS</fullName>
                </value>
                <value>
                    <fullName>HBR</fullName>
                </value>
                <value>
                    <fullName>TOT</fullName>
                </value>
                <value>
                    <fullName>CSE</fullName>
                </value>
                <value>
                    <fullName>CFA</fullName>
                </value>
                <value>
                    <fullName>SWE</fullName>
                </value>
                <value>
                    <fullName>HRT</fullName>
                </value>
                <value>
                    <fullName>HAM</fullName>
                </value>
                <value>
                    <fullName>HCO</fullName>
                </value>
                <value>
                    <fullName>HCA</fullName>
                </value>
                <value>
                    <fullName>MOT</fullName>
                </value>
                <value>
                    <fullName>WR</fullName>
                </value>
                <value>
                    <fullName>NBD</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>CVS</fullName>
                </value>
                <value>
                    <fullName>RTM</fullName>
                </value>
                <value>
                    <fullName>HYP</fullName>
                </value>
                <value>
                    <fullName>SUP</fullName>
                </value>
                <value>
                    <fullName>SWS</fullName>
                </value>
                <value>
                    <fullName>WS</fullName>
                </value>
                <value>
                    <fullName>WD</fullName>
                </value>
                <value>
                    <fullName>HIK</fullName>
                </value>
                <value>
                    <fullName>HTS</fullName>
                </value>
                <value>
                    <fullName>SSM</fullName>
                </value>
                <value>
                    <fullName>COK</fullName>
                </value>
                <value>
                    <fullName>SCA</fullName>
                </value>
                <value>
                    <fullName>CHL</fullName>
                </value>
                <value>
                    <fullName>SHO</fullName>
                </value>
                <value>
                    <fullName>WHO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>SKU Prices/Costs</relationshipLabel>
        <relationshipName>SKU_Prices_Costs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKU Price/Cost</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SKU PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SKU Prices/Costs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Pre_Approval_Form__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel</label>
        <referenceTo>ASI_CRM_CN_Channel__c</referenceTo>
        <relationshipLabel>Pre-Approval Forms</relationshipLabel>
        <relationshipName>Pre_Approval_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Sub_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-Channel</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>ASI_MFM_Sub_Channel__c.ASI_CRM_CN_Channel__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.ASI_CRM_Channel__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Sub_Channel__c</referenceTo>
        <relationshipLabel>Pre-Approval Forms</relationshipLabel>
        <relationshipName>Pre_Approval_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pre-Approval Form</label>
    <nameField>
        <label>Pre-Approval Form Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Approval Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Pre_Approval_Form_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Cash_per_Bottle_A_D_Budget__c</fullName>
        <label>Cash per Bottle (A&amp;D Budget)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Contracted_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contracted Item</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Pre-Approval Form Items</relationshipLabel>
        <relationshipName>Pre_Approval_Form_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <referenceTo>ASI_KOR_Item_Group__c</referenceTo>
        <relationshipLabel>Pre-Approval Form Items</relationshipLabel>
        <relationshipName>Pre_Approval_Form_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Mechanic__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Mechanic</label>
        <referenceTo>ASI_HK_CRM_Pre_Approval_Form_Mechanic__c</referenceTo>
        <relationshipLabel>Pre-Approval Form Items</relationshipLabel>
        <relationshipName>Pre_Approval_Form_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Pre_Approval_Form_Lookup__c</fullName>
        <label>Pre-Approval Form Lookup</label>
        <referenceTo>ASI_HK_CRM_Pre_Approval_Form__c</referenceTo>
        <relationshipLabel>Pre-Approval Form Items</relationshipLabel>
        <relationshipName>Pre_Approval_Form_Items_Link_To_PAF_Form</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pre-Approval Form Item</label>
    <nameField>
        <displayFormat>PAF Item -{00000000}</displayFormat>
        <label>Pre-Approval Form Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Approval Form Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Pre_Approval_Form_Mechanic__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_A_C_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>A/C Code</label>
        <referenceTo>ASI_MFM_A_C_Code__c</referenceTo>
        <relationshipLabel>Pre-Approval Form Mechanics</relationshipLabel>
        <relationshipName>Pre_Approval_Form_Mechanics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pre-Approval Form Mechanic</label>
    <nameField>
        <label>PAF Mechanic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Approval Form Mechanics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ASI_MFM_A_C_Code__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_A_and_P_Tree__c</fullName>
        <label>A and P Tree</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TOTAL A&amp;P</fullName>
                </value>
                <value>
                    <fullName>Total A&amp;D</fullName>
                </value>
                <value>
                    <fullName>A&amp;D+A&amp;P</fullName>
                </value>
                <value>
                    <fullName>TOTAL A&amp;P+DISCOUNT</fullName>
                </value>
                <value>
                    <fullName>Legal Contract</fullName>
                </value>
                <value>
                    <fullName>P&amp;L Account</fullName>
                </value>
                <value>
                    <fullName>B/S Account</fullName>
                </value>
                <value>
                    <fullName>CONSUMER SPEND TOTAL</fullName>
                </value>
                <value>
                    <fullName>CUSTOMER SPEND TOTAL</fullName>
                </value>
                <value>
                    <fullName>CONSUMER SPEND + CUSTOMER SPEND</fullName>
                </value>
                <value>
                    <fullName>TOTAL SALES REDUCTION</fullName>
                </value>
                <value>
                    <fullName>Structure Cost</fullName>
                </value>
                <value>
                    <fullName>Capex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_GL_Class__c</fullName>
        <label>GL Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Reporting_Category__c</fullName>
        <label>Reporting Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ASI_MFM_A_and_P_Tree__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>E. Yearend Commitment</fullName>
                </value>
                <value>
                    <fullName>F. Exclude COA</fullName>
                </value>
                <value>
                    <fullName>A. Total Consumer A&amp;P</fullName>
                </value>
                <value>
                    <fullName>A&amp;D Accrual</fullName>
                </value>
                <value>
                    <fullName>A&amp;D</fullName>
                </value>
                <value>
                    <fullName>A&amp;P Accrual</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Trade</fullName>
                </value>
                <value>
                    <fullName>TOTAL OTHER CONSUMER A&amp;P</fullName>
                </value>
                <value>
                    <fullName>TOTAL MEDIA</fullName>
                </value>
                <value>
                    <fullName>TOTAL TRADE</fullName>
                </value>
                <value>
                    <fullName>B. Total Trade A&amp;P</fullName>
                </value>
                <value>
                    <fullName>D. Total Services Paid to Distrbutors</fullName>
                </value>
                <value>
                    <fullName>C. Total Allowance &amp; Disc</fullName>
                </value>
                <value>
                    <fullName>Agency Fee</fullName>
                </value>
                <value>
                    <fullName>General Expense</fullName>
                </value>
                <value>
                    <fullName>Trade A&amp;P</fullName>
                </value>
                <value>
                    <fullName>TOTAL MEDIA A&amp;P</fullName>
                </value>
                <value>
                    <fullName>TOTAL TRADE A&amp;P</fullName>
                </value>
                <value>
                    <fullName>Consumers A&amp;P</fullName>
                </value>
                <value>
                    <fullName>Service Paid to Distributor</fullName>
                </value>
                <value>
                    <fullName>Allowances and Disc</fullName>
                </value>
                <value>
                    <fullName>TOTAL ATL CONSUMER A&amp;P (INCL. MEDIA)</fullName>
                </value>
                <value>
                    <fullName>TOTAL CONSUMER A&amp;P</fullName>
                </value>
                <value>
                    <fullName>Total A&amp;P Expense</fullName>
                </value>
                <value>
                    <fullName>TOTAL A&amp;P</fullName>
                </value>
                <value>
                    <fullName>TOTAL SERVICE TO DISTRIBUTORS</fullName>
                </value>
                <value>
                    <fullName>PL Item</fullName>
                </value>
                <value>
                    <fullName>BS Item</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>A/C Code</label>
    <nameField>
        <label>A/C</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A/C Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Sub_Channel__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Sub_Channel_Code__c</fullName>
        <label>Sub-Channel Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sub-Channel</label>
    <nameField>
        <label>Sub-Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Channel</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_TW_PAFItems_TriggerCls.cls
public without sharing class ASI_CRM_TW_PAFItems_TriggerCls{
    public static void routineBeforeUpsert(list<ASI_HK_CRM_Pre_Approval_Form_Item__c> trigger_new, map<id, ASI_HK_CRM_Pre_Approval_Form_Item__c> trigger_oldMap) {
        Set<Id> setPAFId = new Set<Id>();
        Set<Id> setContractItmId = new Set<Id>();
        Set<Id> setMechanicId = new Set<Id>();
        
        Map<Id, ASI_HK_CRM_Pre_Approval_Form__c> mapPAF;
        Map<Id, ASI_HK_CRM_Pre_Approval_Form_Mechanic__c> mapPAFMechanic;
        
        List<String> strChannels = new List<String>();
        
        for(ASI_HK_CRM_Pre_Approval_Form_Item__c itm : trigger_new){
            if(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c != NULL)
                setPAFId.add(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c);
            if(itm.ASI_HK_CRM_Mechanic__c != NULL)
                setMechanicId.add(itm.ASI_HK_CRM_Mechanic__c);
            if(itm.RecordTypeId == Global_RecordTypeCache.getRTId('ASI_HK_CRM_Pre_Approval_Form_Item__cASI_CRM_TW_Variable_Investment') &&
               itm.ASI_CRM_Contracted_Item__c != NULL)
                setContractItmId.add(itm.ASI_CRM_Contracted_Item__c);
        }
        
        mapPAFMechanic = new Map<Id, ASI_HK_CRM_Pre_Approval_Form_Mechanic__c>([SELECT id, Name, ASI_CRM_A_C_Code__r.ASI_MFM_A_and_P_Tree__c, ASI_CRM_A_C_Code__r.ASI_MFM_Reporting_Category__c, ASI_CRM_A_C_Code__r.ASI_MFM_GL_Class__c FROM ASI_HK_CRM_Pre_Approval_Form_Mechanic__c WHERE Id IN: setMechanicId]);
        mapPAF = new Map<Id, ASI_HK_CRM_Pre_Approval_Form__c>([SELECT Id, ASI_CRM_Channel__c, ASI_CRM_Channel__r.ASI_CRM_CN_Channel_Code__c, ASI_CRM_Sub_Channel__r.ASI_CRM_CN_Sub_Channel_Code__c FROM ASI_HK_CRM_Pre_Approval_Form__c WHERE Id IN: setPAFId]);
        system.debug('mapPAF: '+mapPAF);
        
        for(String pafId : mapPAF.KeySet()){
            if(mapPAF.get(pafId).ASI_CRM_Channel__c != NULL){
                if(mapPAF.get(pafId).ASI_CRM_Channel__c != NULL){
                    strChannels.add('\''+ mapPAF.get(pafId).ASI_CRM_Channel__r.ASI_CRM_CN_Channel_Code__c +'\'');
                    //setChannels.add(mapPAF.get(pafId).ASI_CRM_Channel__r.ASI_CRM_CN_Channel_Code__c);
                }
                if(mapPAF.get(pafId).ASI_CRM_Sub_Channel__c != NULL){
                    strChannels.add('\''+ mapPAF.get(pafId).ASI_CRM_Sub_Channel__r.ASI_CRM_CN_Sub_Channel_Code__c +'\'');
                    //setChannels.add(mapPAF.get(pafId).ASI_CRM_Sub_Channel__r.ASI_CRM_CN_Sub_Channel_Code__c);
                }
            }
        }
        
        //Map effective SKU Cost/Price for Item Group
        List<String> listType = new List<String>();
        listType.add('A&D Budget (w/VAT)');
        Map<String, ASI_CRM_MY_SKUPriceCost__c> mapSKUpc = new Map<String, ASI_CRM_MY_SKUPriceCost__c>();
        ASI_CRM_TW_ItemGroup_UtilityCls utilityCls = new ASI_CRM_TW_ItemGroup_UtilityCls();
        for(ASI_CRM_MY_SKUPriceCost__c skupc : utilityCls.getAllEffectiveSKUpc(strChannels, setContractItmId, listType, Date.today())){
            for(String channel : strChannels){
                if(skupc.ASI_CRM_Applied_To__c.contains(channel))
                    mapSKUpc.put(skupc.ASI_CRM_Item_Group__c+channel, skupc);
            }
        }
        system.debug('Contract Item Id: '+setContractItmId);
        system.debug('Channels: '+strChannels);
        system.debug('mapSKUpc: '+mapSKUpc);
           
        for(ASI_HK_CRM_Pre_Approval_Form_Item__c itm : trigger_new){
            //update Cash per Bottle (A&D Budget)
            if(itm.RecordTypeId == Global_RecordTypeCache.getRTId('ASI_HK_CRM_Pre_Approval_Form_Item__cASI_CRM_TW_Variable_Investment')){
                if(mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c) != NULL && 
                   mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c).ASI_CRM_Channel__c != NULL &&
                   mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c).ASI_CRM_Channel__r.ASI_CRM_CN_Channel_Code__c != NULL &&
                   mapSKUpc.get(itm.ASI_CRM_Contracted_Item__c+mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c).ASI_CRM_Channel__r.ASI_CRM_CN_Channel_Code__c) != NULL &&
                   mapSKUpc.get(itm.ASI_CRM_Contracted_Item__c+mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c).ASI_CRM_Channel__r.ASI_CRM_CN_Channel_Code__c).ASI_CRM_Cost__c != NULL)
                    itm.ASI_CRM_Cash_per_Bottle_A_D_Budget__c = Math.abs(mapSKUpc.get(itm.ASI_CRM_Contracted_Item__c+mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c).ASI_CRM_Channel__r.ASI_CRM_CN_Channel_Code__c).ASI_CRM_Cost__c);
                else if(mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c) != NULL && 
                        mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c).ASI_CRM_Sub_Channel__c != NULL &&
                        mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c).ASI_CRM_Sub_Channel__r.ASI_CRM_CN_Sub_Channel_Code__c != NULL &&
                        mapSKUpc.get(itm.ASI_CRM_Contracted_Item__c+mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c).ASI_CRM_Sub_Channel__r.ASI_CRM_CN_Sub_Channel_Code__c) != NULL &&
                        mapSKUpc.get(itm.ASI_CRM_Contracted_Item__c+mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c).ASI_CRM_Sub_Channel__r.ASI_CRM_CN_Sub_Channel_Code__c).ASI_CRM_Cost__c != NULL)
                    itm.ASI_CRM_Cash_per_Bottle_A_D_Budget__c = Math.abs(mapSKUpc.get(itm.ASI_CRM_Contracted_Item__c+mapPAF.get(itm.ASI_HK_CRM_Pre_Approval_Form_Lookup__c).ASI_CRM_Sub_Channel__r.ASI_CRM_CN_Sub_Channel_Code__c).ASI_CRM_Cost__c);
                else
                    itm.ASI_CRM_Cash_per_Bottle_A_D_Budget__c = NULL;
            }
               
            if(itm.RecordTypeId == Global_RecordTypeCache.getRTId('ASI_HK_CRM_Pre_Approval_Form_Item__cASI_CRM_TW_Conditional_Investment') ||
               itm.RecordTypeId == Global_RecordTypeCache.getRTId('ASI_HK_CRM_Pre_Approval_Form_Item__cASI_CRM_TW_Fixed_Investment')){
               
               //validate if selected A/C Code of PAF Mechanic has GL Class
               if(mapPAFMechanic.get(itm.ASI_HK_CRM_Mechanic__c).ASI_CRM_A_C_Code__c != null && mapPAFMechanic.get(itm.ASI_HK_CRM_Mechanic__c).ASI_CRM_A_C_Code__r.ASI_MFM_GL_Class__c == null){
                   itm.addError('Please setup GL Class of A/C Code for selected PAF Mechanic '+mapPAFMechanic.get(itm.ASI_HK_CRM_Mechanic__c).Name);
               }
               
               //update A&D or A&P value of Conditional/Fixed PAF itm
               if(mapPAFMechanic != null && mapPAFMechanic.get(itm.ASI_HK_CRM_Mechanic__c) != null && mapPAFMechanic.get(itm.ASI_HK_CRM_Mechanic__c).ASI_CRM_A_C_Code__c != null){
                   if(mapPAFMechanic.get(itm.ASI_HK_CRM_Mechanic__c).ASI_CRM_A_C_Code__r.ASI_MFM_A_and_P_Tree__c == 'Total A&D')
                       itm.ASI_CRM_AD_or_AP__c = 'A&D';
                   else if(mapPAFMechanic.get(itm.ASI_HK_CRM_Mechanic__c).ASI_CRM_A_C_Code__r.ASI_MFM_Reporting_Category__c == 'Trade')
                       itm.ASI_CRM_AD_or_AP__c = 'Trade A&P';    
                   else if(mapPAFMechanic.get(itm.ASI_HK_CRM_Mechanic__c).ASI_CRM_A_C_Code__r.ASI_MFM_A_and_P_Tree__c == 'TOTAL A&P' )
                       itm.ASI_CRM_AD_or_AP__c = 'MKT A&P';
                   
               }
            }
        }
    }
}