objects/ASI_CRM_Payment_Invoice__c.object
<CustomObject>
    <description>ASI CRM JP - Payment Invoice</description>
    <fields>
        <fullName>ASI_CRM_Delivery_Time__c</fullName>
        <label>Delivery Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0000-0000</fullName>
                </value>
                <value>
                    <fullName>0000-1200</fullName>
                </value>
                <value>
                    <fullName>1200-0000</fullName>
                </value>
                <value>
                    <fullName>1400-1600</fullName>
                </value>
                <value>
                    <fullName>1600-1800</fullName>
                </value>
                <value>
                    <fullName>1800-2000</fullName>
                </value>
                <value>
                    <fullName>1900-2100</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approval In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Shipment Cancelled</fullName>
                </value>
                <value>
                    <fullName>Partial Complete</fullName>
                </value>
                <value>
                    <fullName>Verified by SA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Invoice</label>
    <nameField>
        <label>Payment Invoice Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Invoices</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_JP_Cash_Invoice</fullName>
        <active>true</active>
        <label>JP Cash Invoice</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_JP_SPTD_FOC_Invoice</fullName>
        <active>true</active>
        <label>JP SPTD FOC Invoice</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Payment_Invoice_Line_Item__c.object
<CustomObject>
    <description>ASI CRM JP - Payment Invoice Line</description>
    <fields>
        <fullName>ASI_CRM_AP_Code__c</fullName>
        <label>AP Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Actual_Quantity__c</fullName>
        <label>Actual Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Actual_Unit_Cost__c</fullName>
        <label>Actual Unit Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <label>Item Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Payment_Invoice__c</fullName>
        <label>Payment Invoice</label>
        <referenceTo>ASI_CRM_Payment_Invoice__c</referenceTo>
        <relationshipLabel>Payment Invoice Line Items</relationshipLabel>
        <relationshipName>Payment_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Purchase_Contract_Line_Item__c</fullName>
        <label>Contract Line</label>
        <referenceTo>ASI_CRM_Purchase_Contract_Line_Item__c</referenceTo>
        <relationshipLabel>Payment Invoice Line Items</relationshipLabel>
        <relationshipName>Payment_Invoice_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU_Selection__c</fullName>
        <label>SKU Selection</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Representative SKU</fullName>
                    <default>true</default>
                    <label>Representative SKU</label>
                </value>
                <value>
                    <fullName>Alternative SKU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Payment Invoice Line Items</relationshipLabel>
        <relationshipName>Payment_Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Status__c</fullName>
        <formula>TEXT(ASI_CRM_Payment_Invoice__r.ASI_CRM_Status__c)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Payment Invoice Line Item</label>
    <nameField>
        <displayFormat>PIL{000000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Purchase_Contract__c.object
<CustomObject>
    <description>ASI CRM JP - Purchase Contract</description>
    <fields>
        <fullName>ASI_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Contract</label>
    <nameField>
        <label>Contract No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Purchase_Contract_Line_Item__c.object
<CustomObject>
    <description>ASI CRM JP - Purchase Contract Line</description>
    <fields>
        <fullName>ASI_CRM_AP_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>A&amp;P Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ASI_MFM_AP_Code__c.ASI_MFM_Inactive__c</field>
                <operation>notEqual</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_AP_Code__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>CRM JP AP Code</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_AP_Code__c</referenceTo>
        <relationshipLabel>Purchase Contract Line Items</relationshipLabel>
        <relationshipName>Purchase_Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ASI_MFM_Item_Group__c.ASI_CRM_CN_Not_In_Use__c</field>
                <operation>notEqual</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Item_Group__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>JP CRM Item Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Purchase Contract Line Items</relationshipLabel>
        <relationshipName>Purchase_Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Buyback w/o condition</fullName>
                </value>
                <value>
                    <fullName>Buyback w. condition</fullName>
                </value>
                <value>
                    <fullName>FOC w/o condition</fullName>
                </value>
                <value>
                    <fullName>FOC w. condition</fullName>
                </value>
                <value>
                    <fullName>Promotion fee with target</fullName>
                </value>
                <value>
                    <fullName>Gift Coupon</fullName>
                </value>
                <value>
                    <fullName>Other Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Purchase_Contract__c</fullName>
        <label>Purchase Contract</label>
        <referenceTo>ASI_CRM_Purchase_Contract__c</referenceTo>
        <relationshipLabel>Purchase Contract Line Items</relationshipLabel>
        <relationshipName>Purchase_Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Unit_Price__c</fullName>
        <label>Unit Price/Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase Contract Line Item</label>
    <nameField>
        <displayFormat>PCL{00000000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Running_Number__c.object
<CustomObject>
    <description>ASI HK CRM - used to keep track of various auto number running numbers</description>
    <fields>
        <fullName>ASI_HK_CRM_First_Month_of_Fiscal_Year__c</fullName>
        <label>First Month of Fiscal Year</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Format__c</fullName>
        <label>Format</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Running_Number__c</fullName>
        <label>Running Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Running Number</label>
    <nameField>
        <displayFormat>RN-{000000}</displayFormat>
        <label>Running  Number ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Running Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_MFM_AP_Code__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_AP_Code__c</fullName>
        <label>AP Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AP Code</label>
    <nameField>
        <label>AP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Item_Group__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Lowest_1__c</fullName>
        <label>MAX 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Lowest_2__c</fullName>
        <label>MAX 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Representative_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Representative SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Item Groups</relationshipLabel>
        <relationshipName>Item_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item Group</label>
    <nameField>
        <label>Item Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_CRM_Representative_SKU__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Representative SKU</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>SKUs</relationshipLabel>
        <relationshipName>SKUs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_JP_InvoiceLineItem_Test.cls
/*********************************************************************************
 * Name:ASI_CRM_JP_InvoiceLineItem_Test
 * Description: Test Class for Invoice Line Item of JP CRM
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 6/1/2015       Laputa: Hank          Created
*********************************************************************************/
@isTest
private class ASI_CRM_JP_InvoiceLineItem_Test {
    
    @TestSetup
    public static void setupTestData() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles', UserName='test1@laputa.com');
        insert u1;
        
        system.runAs(u1){
            insert new ASI_HK_CRM_Running_Number__c(ASI_HK_CRM_Object_Name__c = 'ASI_CRM_JP_PaymentInvoice_No', ASI_HK_CRM_First_Month_of_Fiscal_Year__c = 1, ASI_HK_CRM_Format__c = 'INV{YY}{00000}', ASI_HK_CRM_Running_Number__c = 2);
            insert new ASI_HK_CRM_Running_Number__c(ASI_HK_CRM_Object_Name__c = 'ASI_CRM_JP_PaymentInvoice_Cash_No', ASI_HK_CRM_First_Month_of_Fiscal_Year__c = 1, ASI_HK_CRM_Format__c = 'INV{YY}{00000}', ASI_HK_CRM_Running_Number__c = 2);
            insert new ASI_HK_CRM_Running_Number__c(ASI_HK_CRM_Object_Name__c = 'ASI_CRM_JP_Contract_No', ASI_HK_CRM_First_Month_of_Fiscal_Year__c = 1, ASI_HK_CRM_Format__c = 'R{YY}{00000}', ASI_HK_CRM_Running_Number__c = 2);
            ASI_MFM_AP_Code__c ap = new ASI_MFM_AP_Code__c(Name='testAP', RecordTypeId = Global_RecordTypeCache.getRtId('ASI_MFM_AP_Code__cASI_CRM_JP_AP_Code'));
            insert ap;
            ASI_MFM_SKU_Code__c sku = new ASI_MFM_SKU_Code__c(Name = 'TestSKU', RecordTypeId = Global_RecordTypeCache.getRtId('ASI_MFM_SKU_Code__cASI_CRM_JP_SKU'));
            insert sku;
            ASI_MFM_Item_Group__c itemGroup = new ASI_MFM_Item_Group__c(Name = 'Test', ASI_CRM_Lowest_1__c = 100, ASI_CRM_Lowest_2__c = 100, recordtypeid = Global_RecordTypeCache.getRtId('ASI_MFM_Item_Group__cASI_CRM_JP_Item_Group'), ASI_CRM_Representative_SKU__c = sku.id);
        	insert itemGroup;
            
            List<ASI_CRM_Payment_Invoice__c> invoiceList = new List<ASI_CRM_Payment_Invoice__c>();
            ASI_CRM_Payment_Invoice__c invoice1 = new ASI_CRM_Payment_Invoice__c(ASI_CRM_Delivery_Time__c = '0000-1200', ownerId = u1.Id, RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Payment_Invoice__cASI_CRM_JP_SPTD_FOC_Invoice'));
            ASI_CRM_Payment_Invoice__c invoice2 = new ASI_CRM_Payment_Invoice__c(ASI_CRM_Delivery_Time__c = '0000-1200', ownerId = u1.Id, RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Payment_Invoice__cASI_CRM_JP_Cash_Invoice'));
            invoiceList.add(invoice1);
            invoiceList.add(invoice2);
            insert invoiceList;
            
        }
    }
    
    //Test for Class ASI_CRM_JP_PaymentInvoiceItemTgrHdlr
    static testMethod void ASI_CRM_JP_PaymentInvoiceItemTgrHdlr_Test(){
        User u1 = [SELECT Id FROM USER WHERE UserName='test1@laputa.com' LIMIT 1];
        ASI_CRM_Payment_Invoice__c focInvoice = [SELECT Id FROM ASI_CRM_Payment_Invoice__c WHERE RecordType.DeveloperName = 'ASI_CRM_JP_SPTD_FOC_Invoice' LIMIT 1];
        ASI_CRM_Payment_Invoice__c cashInvoice = [SELECT Id FROM ASI_CRM_Payment_Invoice__c WHERE RecordType.DeveloperName = 'ASI_CRM_JP_Cash_Invoice' LIMIT 1];
        ASI_MFM_AP_Code__c ap = [SELECT Id FROM ASI_MFM_AP_Code__c];
        ASI_MFM_Item_Group__c itemGroup = [SELECT Id FROM ASI_MFM_Item_Group__c];
        ASI_MFM_SKU_Code__c sku = [SELECT Id FROM ASI_MFM_SKU_Code__c];
       	system.runAs(u1){
            ASI_CRM_Purchase_Contract__c contract1 = new ASI_CRM_Purchase_Contract__c(ownerId = u1.Id, RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Purchase_Contract__cASI_CRM_JP_SPTD_Contract'));
            insert contract1;
            
            test.startTest();
            List<ASI_CRM_Purchase_Contract_Line_Item__c> contractLineList = new List<ASI_CRM_Purchase_Contract_Line_Item__c>();
            ASI_CRM_Purchase_Contract_Line_Item__c contractLine1 = new ASI_CRM_Purchase_Contract_Line_Item__c(RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Purchase_Contract_Line_Item__cASI_CRM_JP_SPTD_Contract_Line_Item'), ASI_CRM_Purchase_Contract__c = contract1.Id, ASI_CRM_Unit_Price__c  = 100, ASI_CRM_Quantity__c = 100, ASI_CRM_Item_Group__c = itemGroup.id, ASI_CRM_Payment_Method__c='Buyback w/o condition', ASI_CRM_AP_Code__c = ap.Id);        
            contractLineList.add(contractLine1);
            ASI_CRM_Purchase_Contract_Line_Item__c contractLine2 = new ASI_CRM_Purchase_Contract_Line_Item__c(RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Purchase_Contract_Line_Item__cASI_CRM_JP_SPTD_Contract_Line_Item'), ASI_CRM_Purchase_Contract__c = contract1.Id, ASI_CRM_Unit_Price__c  = 200, ASI_CRM_Quantity__c = 200, ASI_CRM_Item_Group__c = itemGroup.id, ASI_CRM_Payment_Method__c='Buyback w/o condition', ASI_CRM_AP_Code__c = ap.Id);        
            contractLineList.add(contractLine2);
            insert contractLineList;
            
            List<ASI_CRM_Payment_Invoice_Line_Item__c> lineItemList = new List<ASI_CRM_Payment_Invoice_Line_Item__c>();
            ASI_CRM_Payment_Invoice_Line_Item__c line1 = new ASI_CRM_Payment_Invoice_Line_Item__c(RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Payment_Invoice_Line_Item__cASI_CRM_JP_Indirect_Rebate_Invoice_Line_Item'), ASI_CRM_Payment_Invoice__c = focInvoice.Id, ASI_CRM_Actual_Unit_Cost__c  = 100, ASI_CRM_Actual_Quantity__c  = 100, ASI_CRM_Purchase_Contract_Line_Item__c = contractLineList.get(0).Id, ASI_CRM_SKU_Selection__c = 'Alternative SKU');
            ASI_CRM_Payment_Invoice_Line_Item__c line2 = new ASI_CRM_Payment_Invoice_Line_Item__c(RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Payment_Invoice_Line_Item__cASI_CRM_JP_SPTD_FOC_Invoice_Line_Item'), ASI_CRM_Payment_Invoice__c = focInvoice.Id, ASI_CRM_Purchase_Contract_Line_Item__c = contractLineList.get(0).Id, ASI_CRM_SKU__c = sku.Id);
            ASI_CRM_Payment_Invoice_Line_Item__c line3 = new ASI_CRM_Payment_Invoice_Line_Item__c(RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Payment_Invoice_Line_Item__cASI_CRM_JP_Indirect_Rebate_Invoice_Line_Item'), ASI_CRM_Payment_Invoice__c = cashInvoice.Id, ASI_CRM_Actual_Unit_Cost__c  = 100, ASI_CRM_Actual_Quantity__c  = 100, ASI_CRM_Purchase_Contract_Line_Item__c = contractLineList.get(0).Id, ASI_CRM_SKU_Selection__c = 'Alternative SKU');
            ASI_CRM_Payment_Invoice_Line_Item__c line4 = new ASI_CRM_Payment_Invoice_Line_Item__c(RecordTypeId = Global_RecordTypeCache.getRtId('ASI_CRM_Payment_Invoice_Line_Item__cASI_CRM_JP_SPTD_FOC_Invoice_Line_Item'), ASI_CRM_Payment_Invoice__c = cashInvoice.Id, ASI_CRM_Purchase_Contract_Line_Item__c = contractLineList.get(0).Id, ASI_CRM_SKU__c = sku.Id);
            lineItemList.add(line1);
            lineItemList.add(line2);
            lineItemList.add(line3);
            lineItemList.add(line4);
            insert lineItemList;
            
            line1.ASI_CRM_Purchase_Contract_Line_Item__c = contractLineList.get(1).Id;
            line1.ASI_CRM_SKU_Selection__c = 'Representative SKU';
            line2.ASI_CRM_SKU_Selection__c = 'Alternative SKU';
            
            test.stopTest();
            
            try{
                update lineItemList;
            }catch(Exception e){
            
            }
            
            try{
                delete line1;
            }catch(Exception e){
            
            }
            //For auto close contract
            try{
                focInvoice.ASI_CRM_Status__c = 'Complete';
                update focInvoice;
            }catch(Exception e){
            
            }
        }
        
    }
}