objects/ASI_FOC_Free_Goods_Request__c.object
<CustomObject>
    <description>used by PR China FOC</description>
    <fields>
        <fullName>ASI_CRM_MY_JDE_SO_Type__c</fullName>
        <label>JDE SO Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SY</fullName>
                    <label>SY-Barter Trade GST</label>
                </value>
                <value>
                    <fullName>SN</fullName>
                    <label>SN-Barter Trade Non-GST</label>
                </value>
                <value>
                    <fullName>J5</fullName>
                    <label>J5-Free Issue</label>
                </value>
                <value>
                    <fullName>SG</fullName>
                    <label>SG-Free Issue</label>
                </value>
                <value>
                    <fullName>P5</fullName>
                    <label>P5-Free Issue</label>
                </value>
                <value>
                    <fullName>K5</fullName>
                    <label>K5-Free Issue</label>
                </value>
                <value>
                    <fullName>M5</fullName>
                    <label>M5-Free Issue</label>
                </value>
                <value>
                    <fullName>I5</fullName>
                    <label>I5-Free Issue</label>
                </value>
                <value>
                    <fullName>FY</fullName>
                    <label>Free Issues - FY</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Not Converted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Submit for Cancel</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Free Goods Request &amp; POSM</label>
    <nameField>
        <displayFormat>FG-{00000000}</displayFormat>
        <label>Request Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Free Goods Request &amp; POSM</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_MY_Submit_FOC_Light_Ctrl.cls
public class ASI_CRM_MY_Submit_FOC_Light_Ctrl {
	@AuraEnabled
    public static ASI_FOC_Free_Goods_Request__c validateRecord(Id recordId){
        ASI_FOC_Free_Goods_Request__c foc = [Select Id,ASI_CRM_MY_JDE_SO_Type__c,ASI_CRM_Status__c from ASI_FOC_Free_Goods_Request__c where Id = :recordId limit 1];
        return foc;
    }
    
    @AuraEnabled
    public static String updateRecord(String recordId){
        try{
			ASI_FOC_Free_Goods_Request__c foc = new ASI_FOC_Free_Goods_Request__c();
            foc.Id = recordId;
			foc.ASI_CRM_Status__c ='Sent';
            update foc;
            return 'Success';
        }catch(Exception e){
            return e.getMessage();
        }
    }
}