objects/ASI_HK_CRM_Visitation_Plan__c.object
<CustomObject>
    <description>ASI HK CRM - Visitation Plan</description>
    <fields>
        <fullName>ASI_HK_CRM_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <label>Visitation Plan</label>
    <nameField>
        <label>Visitation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitation Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Visitation_Plan_Detail__c.object
<CustomObject>
    <description>ASI HK CRM - Visitation Plan Detail</description>
    <fields>
        <fullName>ASI_HK_CRM_Visitation_Plan__c</fullName>
        <label>Visitation Plan</label>
        <referenceTo>ASI_HK_CRM_Visitation_Plan__c</referenceTo>
        <relationshipName>ASI_HK_CRM_Visitation_Plan_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visitation Plan Detail</label>
    <nameField>
        <displayFormat>VPD-{00000}</displayFormat>
        <label>Visitation Plan Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visitation Plan Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_Sub_brand__c.object
<CustomObject>
    <label>Sub-brand</label>
    <nameField>
        <label>Sub-brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_VN_VisitDetailTimeCtrlTest.cls
/*********************************************************************************
 * Name: ASI_CRM_VN_VisitDetailTimeCtrlTest
 * Description: Test class for ASI_CRM_VN_VisitDetailTimeCtrl
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 13/07/2017       Hugo Cheung             Created          
*/
@isTest
public class ASI_CRM_VN_VisitDetailTimeCtrlTest {
    
    @TestSetup
    public static void setupData() {
        ASI_CRM_VN_TestClassHelper.createRunningNumber();
        
        ASI_MFM_Sub_brand__c subBrand = ASI_CRM_VN_TestClassHelper.createSubBrand();
        insert subBrand;
        
        ASI_CRM_AccountsAdditionalField__c offTradeCustomer = ASI_CRM_VN_TestClassHelper.createOffTradeCustomer();
    	insert offTradeCustomer;
       
        insert ASI_CRM_VN_TestClassHelper.createKeyCustomerSubBrand(offTradeCustomer.Id, subBrand.Id);
        insert ASI_CRM_VN_TestClassHelper.createCompetitorCustomerSubBrand(offTradeCustomer.Id, subBrand.Id);
        
        ASI_HK_CRM_Visitation_Plan__c visitationPlan = ASI_CRM_VN_TestClassHelper.createVisitationPlan();
        visitationPlan.ASI_HK_CRM_Confirmed__c = true;
        insert visitationPlan;
        
        ASI_HK_CRM_Visitation_Plan_Detail__c visitationPlanDetail = ASI_CRM_VN_TestClassHelper.createVisitationPlanDetail(visitationPlan.Id, offTradeCustomer.Id);
		insert visitationPlanDetail;
    }
    
    public static testMethod void testCtrl() {
        ASI_HK_CRM_Visitation_Plan_Detail__c visitationPlanDetail = [SELECT Id FROM ASI_HK_CRM_Visitation_Plan_Detail__c LIMIT 1];


        ApexPages.StandardController sc = new ApexPages.StandardController(visitationPlanDetail);
        ASI_CRM_VN_VisitDetailTimeCtrl visitDetailTimeCtrl = new ASI_CRM_VN_VisitDetailTimeCtrl(sc);
        visitDetailTimeCtrl.setTimeIn();
        visitDetailTimeCtrl.setTimeOut();
  	}
}