objects/ASI_CRM_Payment_Invoice__c.object
<CustomObject>
    <description>ASI CRM JP - Payment Invoice</description>
    <fields>
        <fullName>ASI_CRM_Line_Total_Amount__c</fullName>
        <formula>ASI_CRM_Actual_Taxable_Amount__c* (1+ASI_CRM_Tax_Rate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line Total Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_No_of_A_P_Line__c</fullName>
        <label>No. of A&amp;P/SPTD Line</label>
        <summaryFilterItems>
            <field>ASI_CRM_Payment_Invoice_Line_Item__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>JP SPTD Cash Invoice Line Item</value>
        </summaryFilterItems>
        <summaryForeignKey>ASI_CRM_Payment_Invoice_Line_Item__c.ASI_CRM_Payment_Invoice__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Rebate_Invoice_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rebate Invoice Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Total_Invoice_Amount__c</fullName>
        <label>Total Invoice Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Total_Taxable_Amount__c</fullName>
        <formula>IF( CONTAINS(RecordType.DeveloperName, &quot;ASI_CRM_JP_SPTD_Cash_Invoice&quot;) || CONTAINS(RecordType.DeveloperName, &quot;ASI_CRM_JP_Cash_Invoice&quot;)  , ROUND(ASI_CRM_Total_Invoice_Amount__c /(1+ ASI_CRM_Tax_Rate__c), 0),  ASI_CRM_Actual_Taxable_Amount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Taxable Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Invoice</label>
    <nameField>
        <label>Payment Invoice Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Invoices</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_JP_Cash_Invoice</fullName>
        <active>true</active>
        <label>JP Cash Invoice</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_JP_Indirect_Rebate_Invoice</fullName>
        <active>true</active>
        <label>JP Indirect Rebate Invoice</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_JP_SPTD_FOC_Invoice</fullName>
        <active>true</active>
        <label>JP SPTD FOC Invoice</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Payment_Invoice_Line_Item__c.object
<CustomObject>
    <description>ASI CRM JP - Payment Invoice Line</description>
    <fields>
        <fullName>ASI_CRM_Final_Amount__c</fullName>
        <formula>ROUND(ASI_CRM_Actual_Amount__c  +  ASI_CRM_Adjustment_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Final Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Line_Total_Amount__c</fullName>
        <formula>ASI_CRM_Final_Amount__c + ASI_CRM_Tax_Amount__c</formula>
        <label>Line Total Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Payment_Invoice__c</fullName>
        <label>Payment Invoice</label>
        <referenceTo>ASI_CRM_Payment_Invoice__c</referenceTo>
        <relationshipLabel>Payment Invoice Line Items</relationshipLabel>
        <relationshipName>Payment_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Invoice Line Item</label>
    <nameField>
        <displayFormat>PIL{000000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Invoice Line Items</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_JP_Indirect_Rebate_Invoice_Line_Item</fullName>
        <active>true</active>
        <label>JP Indirect Rebate Invoice Line Item</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_JP_SPTD_Cash_Invoice_Line_Item</fullName>
        <active>true</active>
        <label>JP SPTD Cash Invoice Line Item</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_JP_SPTD_FOC_Invoice_Line_Item</fullName>
        <active>true</active>
        <label>JP SPTD FOC Invoice Line Item</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CRM_JP_RollUp_Amount_PayInvoiceLine.cls
/*********************************************************************************
 * Name:ASI_CRM_JP_RollUp_Amount_PayInvoiceLine 
 * Description: Roll up the Line Total Amount
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 18/03/2015       Laputa: Conrad          Created
 * 01/10/2019       Wilken Lee            [WL 1.0] Change security to without sharing to cater approver need to edit line item
*********************************************************************************/

public without sharing class ASI_CRM_JP_RollUp_Amount_PayInvoiceLine extends ASI_CRM_JP_TriggerAbstract {//WL 1.0


    public ASI_CRM_JP_RollUp_Amount_PayInvoiceLine() {
        super('ASI_CRM_JP_RollUp_Amount_PayInvoiceLine');
    }
    
    public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
        List<ASI_CRM_Payment_Invoice_Line_Item__c> paymentLinesList = (List<ASI_CRM_Payment_Invoice_Line_Item__c>)sObjList;
        Set<ID> paymentIdSet = new Set<ID>();
        
        for(ASI_CRM_Payment_Invoice_Line_Item__c paymentLine : paymentLinesList) {
            if(Global_RecordTypeCache.getRt(paymentLine.recordTypeid).developerName.contains('ASI_CRM_JP_Indirect_Rebate_Invoice_Line_Item') || Global_RecordTypeCache.getRt(paymentLine.recordTypeid).developerName.contains('ASI_CRM_JP_SPTD_FOC_Invoice_Line_Item')){
                paymentIdSet.add(paymentLine.ASI_CRM_Payment_Invoice__c);
            }
        }
        
        if(paymentIdSet.size() > 0) {
            
            Map<ID, ASI_CRM_Payment_Invoice__c> paymentInvoiceMap = new Map<ID, ASI_CRM_Payment_Invoice__c>([SELECT ID, Name, ASI_CRM_Rebate_Invoice_Amount__c,ASI_CRM_Total_Invoice_Amount__c, ASI_CRM_No_of_A_P_Line__c, ASI_CRM_Total_Taxable_Amount__c, RecordType.DeveloperName, (SELECT ID FROM Payment_Invoice_Lines__r WHERE RecordType.DeveloperName = 'ASI_CRM_JP_SPTD_Cash_Invoice_Line_Item') FROM ASI_CRM_Payment_Invoice__c
                                                                                                                WHERE ID IN : paymentIdSet]);
            
            List<AggregateResult> resultAggregateList = [SELECT ASI_CRM_Payment_Invoice__c,
                SUM(ASI_CRM_Line_Total_Amount__c) totalLineAmount,
                SUM(ASI_CRM_Final_Amount__c) totalFinalAmount
                FROM ASI_CRM_Payment_Invoice_Line_Item__c
                WHERE ASI_CRM_Payment_Invoice__c IN: paymentIdSet
                AND (
                    RecordType.DeveloperName Like '%ASI_CRM_JP_Indirect_Rebate_Invoice_Line_Item%'
                    OR
                    RecordType.DeveloperName Like '%ASI_CRM_JP_SPTD_FOC_Invoice_Line_Item%')
                GROUP BY ASI_CRM_Payment_Invoice__c];
            
            List<ASI_CRM_Payment_Invoice__c> paymentInvoiceToUpdateList = new List<ASI_CRM_Payment_Invoice__c>();
            Set<ID> tempPaymentIdSet = paymentIdSet.clone();
            
            for(AggregateResult result : resultAggregateList){
                ASI_CRM_Payment_Invoice__c tempPayment = paymentInvoiceMap.get((ID)result.get('ASI_CRM_Payment_Invoice__c'));
                Integer apLineCount = tempPayment.Payment_Invoice_Lines__r != null ? tempPayment.Payment_Invoice_Lines__r.size() : 0;
                system.debug('Debug1 total amount: ' + (Decimal)result.get('totalLineAmount'));
                if(tempPayment.ASI_CRM_Total_Invoice_Amount__c != (Decimal)result.get('totalLineAmount') && (tempPayment.RecordType.DeveloperName.contains('ASI_CRM_JP_Indirect_Rebate_Invoice') || tempPayment.RecordType.DeveloperName.contains('ASI_CRM_JP_SPTD_FOC_Invoice'))) {
                    system.debug('Debug2 total amount: ' + (Decimal)result.get('totalLineAmount'));
                    tempPayment.ASI_CRM_Total_Invoice_Amount__c = (Decimal)result.get('totalLineAmount');
                    paymentInvoiceToUpdateList.add(tempPayment);
                }
                if(tempPayment.ASI_CRM_Rebate_Invoice_Amount__c != (Decimal)result.get('totalLineAmount') && tempPayment.RecordType.DeveloperName.contains('ASI_CRM_JP_Cash_Invoice')) {
                    tempPayment.ASI_CRM_Rebate_Invoice_Amount__c = (Decimal)result.get('totalLineAmount');
                    if(apLineCount == 0 && (Decimal)result.get('totalFinalAmount') == tempPayment.ASI_CRM_Total_Taxable_Amount__c){
                    tempPayment.ASI_CRM_Rebate_Invoice_Amount__c = tempPayment.ASI_CRM_Total_Invoice_Amount__c;    
                    }                             
                    paymentInvoiceToUpdateList.add(tempPayment);
                }
                tempPaymentIdSet.remove(tempPayment.id);
            }
            
            if(tempPaymentIdSet.size() > 0) {
                for(ID paymentID : tempPaymentIdSet) {
                    ASI_CRM_Payment_Invoice__c tempPayment = paymentInvoiceMap.get(paymentID);
                    if(tempPayment.ASI_CRM_Total_Invoice_Amount__c != null && tempPayment.RecordType.DeveloperName.contains('ASI_CRM_JP_Indirect_Rebate_Invoice') || tempPayment.RecordType.DeveloperName.contains('ASI_CRM_JP_SPTD_FOC_Invoice')) {
                        tempPayment.ASI_CRM_Total_Invoice_Amount__c = 0;
                        paymentInvoiceToUpdateList.add(tempPayment);
                    }
                    if(tempPayment.ASI_CRM_Rebate_Invoice_Amount__c != null && tempPayment.RecordType.DeveloperName.contains('ASI_CRM_JP_Cash_Invoice')) {
                        tempPayment.ASI_CRM_Rebate_Invoice_Amount__c= 0;
                        paymentInvoiceToUpdateList.add(tempPayment);
                    }
                }
            }
            
            if(paymentInvoiceToUpdateList.size() > 0) {
                update paymentInvoiceToUpdateList;
            }
            
        }
        
    }
}