objects/ASI_eForm_Return_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_eForm_Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>R41 선물 세트 반품</fullName>
                </value>
                <value>
                    <fullName>R42 품질 이슈 - 소비자 클레임</fullName>
                </value>
                <value>
                    <fullName>R43 품질 이슈 - 제품 리콜</fullName>
                </value>
                <value>
                    <fullName>R44 RFID Tag 불량, 미부착 / 기타 상표 법규 관련 이슈테그 이슈 / 기타 상표 법규 관련 등</fullName>
                </value>
                <value>
                    <fullName>R45 주문 오류 (거래처 또는 회사의 주문처리 오류)</fullName>
                </value>
                <value>
                    <fullName>R46 제품 반품 및 교환 (거래선 이탈, 도매장 재고 불균형)</fullName>
                </value>
                <value>
                    <fullName>R47 제품 교환 (PRK 재고 부족으로 인한 도매장간 재고 이동)</fullName>
                </value>
                <value>
                    <fullName>R48 제품 교환 (각종 프로모션 : NPD, 7 packs, In-packs, DC PM, etc.)</fullName>
                </value>
                <value>
                    <fullName>R49 미결채권을 제품으로 회수</fullName>
                </value>
                <value>
                    <fullName>R50 도매장 폐업으로 인한 반품</fullName>
                </value>
                <value>
                    <fullName>R51 기타 (구체적으로 사유를 명시해주세요)</fullName>
                </value>
                <value>
                    <fullName>R52 CJ 배송착지오류</fullName>
                </value>
                <value>
                    <fullName>R53 CJ 배송지연</fullName>
                </value>
                <value>
                    <fullName>R54 CJ 고객요청사항 미준수</fullName>
                </value>
                <value>
                    <fullName>R55 파손</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_eForm_Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <label>Return Order Request</label>
    <nameField>
        <displayFormat>RO-{000000}</displayFormat>
        <label>Return Order Request No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_eForm_Return_Order_Request_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_eForm_Amount_Replace__c</fullName>
        <label>Amount(Replace)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Amount_Return__c</fullName>
        <label>Amount(Return)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Channel_Replace__c</fullName>
        <label>Channel(Replace)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>유흥</fullName>
                </value>
                <value>
                    <fullName>가정</fullName>
                </value>
                <value>
                    <fullName>할인</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_eForm_Channel_Return__c</fullName>
        <label>Channel(Return)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>유흥</fullName>
                </value>
                <value>
                    <fullName>가정</fullName>
                </value>
                <value>
                    <fullName>할인</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_eForm_Complaint_Category__c</fullName>
        <label>Complaint Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Blocking (블로킹)</fullName>
                </value>
                <value>
                    <fullName>Bottle (병)</fullName>
                </value>
                <value>
                    <fullName>Cap (마개)</fullName>
                </value>
                <value>
                    <fullName>Capsule (금속 캡슐)</fullName>
                </value>
                <value>
                    <fullName>Counterfeit (위조품)</fullName>
                </value>
                <value>
                    <fullName>Foreign matter (이물)</fullName>
                </value>
                <value>
                    <fullName>Label (상표)</fullName>
                </value>
                <value>
                    <fullName>Leakage (누주)</fullName>
                </value>
                <value>
                    <fullName>Low fill (용량 부족)</fullName>
                </value>
                <value>
                    <fullName>Taste (맛이상)</fullName>
                </value>
                <value>
                    <fullName>Others (기타)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_eForm_Complaint_Details__c</fullName>
        <label>Complaint Details</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ASI_eForm_Complaint_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Blocking (블로킹)</fullName>
                </value>
                <value>
                    <fullName>Bottle appearance (병외관 불량)</fullName>
                </value>
                <value>
                    <fullName>Broken bottle (파손)</fullName>
                </value>
                <value>
                    <fullName>Crack (금)</fullName>
                </value>
                <value>
                    <fullName>Scratch (병 긁힘)</fullName>
                </value>
                <value>
                    <fullName>Capping defect (마개 장착 불량)</fullName>
                </value>
                <value>
                    <fullName>Cork defect (코르크 마개 불량)</fullName>
                </value>
                <value>
                    <fullName>Damaged cap (마개 손상)</fullName>
                </value>
                <value>
                    <fullName>Cap assembly defect (마개 조립 불량)</fullName>
                </value>
                <value>
                    <fullName>Not operated genuine mark (정품표시 작동불량)</fullName>
                </value>
                <value>
                    <fullName>Spinning cap (공회전)</fullName>
                </value>
                <value>
                    <fullName>Too loose (너무 쉽게 열림 / 이지 오픈)</fullName>
                </value>
                <value>
                    <fullName>Turned genuine mark (개봉전 정품표시 보임)</fullName>
                </value>
                <value>
                    <fullName>Unable/Hard to open (개봉불가 / 개봉어려움)</fullName>
                </value>
                <value>
                    <fullName>Wrong cap (마개 상이)</fullName>
                </value>
                <value>
                    <fullName>Capsule printing defect (금속캡슐 인쇄 불량)</fullName>
                </value>
                <value>
                    <fullName>Damaged capsule (금속캡슐 손상)</fullName>
                </value>
                <value>
                    <fullName>Loose capsule (금속캡슐 성형불량)</fullName>
                </value>
                <value>
                    <fullName>Counterfeit (위조품)</fullName>
                </value>
                <value>
                    <fullName>Foreign matter (이물)</fullName>
                </value>
                <value>
                    <fullName>Contaminated Label (상표 오염)</fullName>
                </value>
                <value>
                    <fullName>Damaged label (상표 손상)</fullName>
                </value>
                <value>
                    <fullName>Label printing defect (상표 인쇄불량)</fullName>
                </value>
                <value>
                    <fullName>Missing label (상표 없슴)</fullName>
                </value>
                <value>
                    <fullName>Leakage (누주)</fullName>
                </value>
                <value>
                    <fullName>Low fill (용량 부족)</fullName>
                </value>
                <value>
                    <fullName>Taste (맛이상)</fullName>
                </value>
                <value>
                    <fullName>Deterioration (내용물 품질 저하)</fullName>
                </value>
                <value>
                    <fullName>Floc (플로킹)</fullName>
                </value>
                <value>
                    <fullName>Others (기타)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_eForm_Item_Group_Replace__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group(Replace)</label>
        <referenceTo>ASI_KOR_Item_Group__c</referenceTo>
        <relationshipLabel>Return Order Request Line Items (Item Group(Replace))</relationshipLabel>
        <relationshipName>Return_Order_Request_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Item_Group_Return__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group(Return)</label>
        <referenceTo>ASI_KOR_Item_Group__c</referenceTo>
        <relationshipLabel>Return Order Request Line Items</relationshipLabel>
        <relationshipName>Return_Order_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Lot_Number__c</fullName>
        <label>Lot Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Production_Date__c</fullName>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Production_Time__c</fullName>
        <label>Production Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Quantity_Replace__c</fullName>
        <label>Quantity(Replace)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Quantity_Return__c</fullName>
        <label>Quantity(Return)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Return_Order_Request__c</fullName>
        <label>Return Order Request</label>
        <referenceTo>ASI_eForm_Return_Order_Request__c</referenceTo>
        <relationshipLabel>Return Order Request Line Items</relationshipLabel>
        <relationshipName>Return_Order_Request_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_UOM_Replace__c</fullName>
        <label>UOM(Replace)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                    <default>true</default>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>Bottle</fullName>
                </value>
                <value>
                    <fullName>Set</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_eForm_UOM_Return__c</fullName>
        <label>UOM(Return)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                    <default>true</default>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>Bottle</fullName>
                </value>
                <value>
                    <fullName>Set</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_eForm_Unit_Price_Replace__c</fullName>
        <label>Unit Price(Replace)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Unit_Price_Return__c</fullName>
        <label>Unit Price(Return)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Return Order Request Line Items</relationshipLabel>
        <relationshipName>Return_Order_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Return Order Request Line Item</label>
    <nameField>
        <displayFormat>ROL-{000000}</displayFormat>
        <label>Return Order Request Line Items No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Order Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_KOR_Item_Group__c.object
<CustomObject>
    <fields>
        <fullName>ASI_KOR_Name_Kor__c</fullName>
        <label>Name-Kor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item Group</label>
    <nameField>
        <label>Item Group Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ASI_eForm_KR_ReturnOrder_MgtAllCtrl.cls
public class ASI_eForm_KR_ReturnOrder_MgtAllCtrl {
    public ASI_eForm_Return_Order_Request__c ReturnOrderRequest { get; set; } {ReturnOrderRequest = new ASI_eForm_Return_Order_Request__c();} 
    public  String DetailLineJSON {set;get;}{DetailLineJSON=null;}
    public  String VenueJSON {set;get;}{VenueJSON=null;}
    public string RecordTypeID {get;set;}
    public boolean ROEdit {set;get;} {ROEdit=true;}
    public Boolean IsR42 {set;get;} {IsR42 = False;}
    public String ComplaintCategoryPickListJSON {set;get;}{ComplaintCategoryPickListJSON=null;}
    public String ChannelReturnOptionJSON {set;get;}
    public String ChannelReplaceOptionJSON {set;get;}

    //By SharSolutions
    public class MyPickListInfo{
        public String validFor;
    }
    
    
    public ASI_eForm_KR_ReturnOrder_MgtAllCtrl(apexpages.standardController sc) {
        String RecordId = ApexPages.currentPage().getParameters().get('id');
        this.ReturnOrderRequest=[select Id,RecordType.DeveloperName,ASI_eForm_Reason__c from ASI_eForm_Return_Order_Request__c where Id = : RecordId ];
    }
    
    public pageReference init(){
        RecordTypeID=Global_RecordTypeCache.getRtId('ASI_eForm_Donation_Request_Line_Items__cASI_eForm_KR_Donation_Request_Line');
        if(this.ReturnOrderRequest !=null && this.ReturnOrderRequest.Id !=null){
            List<ASI_eForm_Return_Order_Request_Line_Item__c> ReturnOrderRequestLineList = [
                select Id,
                    ASI_eForm_Complaint_Category__c,
                    ASI_eForm_Complaint_Details__c,
                    ASI_eForm_Lot_Number__c,
                    ASI_eForm_Venue__c,
                    ASI_eForm_Venue__r.Name,
                    ASI_eForm_Production_Date__c,
                    ASI_eForm_Production_Time__c,
                    ASI_eForm_Unit_Price_Replace__c,
                    ASI_eForm_Unit_Price_Return__c,
                    ASI_eForm_Remarks__c,
                    ASI_eForm_Amount_Replace__c,
                    ASI_eForm_Amount_Return__c,
                    ASI_eForm_Item_Group_Replace__r.Name,
                    ASI_eForm_UOM_Replace__c,
                    ASI_eForm_UOM_Return__c,
                    ASI_eForm_Item_Group_Replace__r.ASI_KOR_Name_Kor__c,
                    ASI_eForm_Item_Group_Return__r.ASI_KOR_Name_Kor__c,
                    ASI_eForm_Item_Group_Return__r.Name,
                    ASI_eForm_Item_Group_Replace__c,
                    ASI_eForm_Item_Group_Return__c,
                    ASI_eForm_Quantity_Replace__c,
                    ASI_eForm_Quantity_Return__c,
                    ASI_eForm_Channel_Replace__c,
                    ASI_eForm_Channel_Return__c
                from ASI_eForm_Return_Order_Request_Line_Item__c
                where ASI_eForm_Return_Order_Request__c = :ReturnOrderRequest.Id
            ];
            DetailLineJSON=JSON.serialize(ReturnOrderRequestLineList);
        }
        
        Map<String, List<String>> ComplaintCategoryPickList = getFieldDependencies('ASI_eForm_Return_Order_Request_Line_Item__c','ASI_eForm_Complaint_Category__c','ASI_eForm_Complaint_Details__c');
        ComplaintCategoryPickListJSON=JSON.serialize(ComplaintCategoryPickList);
        ChannelReturnOptionJSON = JSON.serialize(getPickListValue('ASI_eForm_Return_Order_Request_Line_Item__c', 'ASI_eForm_Channel_Return__c'));
        ChannelReplaceOptionJSON = JSON.serialize(getPickListValue('ASI_eForm_Return_Order_Request_Line_Item__c', 'ASI_eForm_Channel_Replace__c'));
        if(ReturnOrderRequest.ASI_eForm_Reason__c.contains('R42')){
            IsR42=true;
        }
        return null;
    }
    
    
    public PageReference BackHeader() {
        return  new PageReference('/' + ReturnOrderRequest.Id); 
    }
    
    public static Map<String, List<String>> getFieldDependencies(String objectName, String controllingField, String dependentField)
    {
        Map<String, List<String>> controllingInfo = new Map<String, List<String>>();
        
        Schema.SObjectType objType = Schema.getGlobalDescribe().get(objectName);
        
        Schema.DescribeSObjectResult describeResult = objType.getDescribe();
        Schema.DescribeFieldResult controllingFieldInfo = describeResult.fields.getMap().get(controllingField).getDescribe();
        Schema.DescribeFieldResult dependentFieldInfo = describeResult.fields.getMap().get(dependentField).getDescribe();
        
        List<Schema.PicklistEntry> controllingValues = controllingFieldInfo.getPicklistValues();
        List<Schema.PicklistEntry> dependentValues = dependentFieldInfo.getPicklistValues();
        
        for(Schema.PicklistEntry currControllingValue : controllingValues)
        {
            System.debug('ControllingField: Label:' + currControllingValue.getLabel());
            controllingInfo.put(currControllingValue.getLabel(), new List<String>());
        }
        
        for(Schema.PicklistEntry currDependentValue : dependentValues)
        {
            String jsonString = JSON.serialize(currDependentValue);
            
            MyPickListInfo info = (MyPickListInfo) JSON.deserialize(jsonString, MyPickListInfo.class);
            
            String hexString = EncodingUtil.convertToHex(EncodingUtil.base64Decode(info.validFor)).toUpperCase();
            
            System.debug('DependentField: Label:' + currDependentValue.getLabel() + ' ValidForInHex:' + hexString + ' JsonString:' + jsonString);
            
            Integer baseCount = 0;
            
            for(Integer curr : hexString.getChars())
            {
                Integer val = 0;
                
                if(curr >= 65){
                    val = curr - 65 + 10;
                }else{
                    val = curr - 48;
                }
                
                if((val & 8) == 8){
                    System.debug('Dependent Field: ' + currDependentValue.getLabel() + ' Partof ControllingField:' + controllingValues[baseCount + 0].getLabel());
                    controllingInfo.get(controllingValues[baseCount + 0].getLabel()).add(currDependentValue.getLabel());
                }
                
                if((val & 4) == 4){
                    System.debug('Dependent Field: ' + currDependentValue.getLabel() + ' Partof ControllingField:' + controllingValues[baseCount + 1].getLabel());
                    controllingInfo.get(controllingValues[baseCount + 1].getLabel()).add(currDependentValue.getLabel());                    
                }
                
                if((val & 2) == 2){
                    System.debug('Dependent Field: ' + currDependentValue.getLabel() + ' Partof ControllingField:' + controllingValues[baseCount + 2].getLabel());
                    controllingInfo.get(controllingValues[baseCount + 2].getLabel()).add(currDependentValue.getLabel());                    
                }
                
                if((val & 1) == 1){
                    System.debug('Dependent Field: ' + currDependentValue.getLabel() + ' Partof ControllingField:' + controllingValues[baseCount + 3].getLabel());
                    controllingInfo.get(controllingValues[baseCount + 3].getLabel()).add(currDependentValue.getLabel());                    
                }
                
                baseCount += 4;
            }            
        } 
        
        System.debug('ControllingInfo: ' + controllingInfo);
        
        return controllingInfo;
    }
    

    
    @RemoteAction
    public static string UpdateLineItem(string LinelistJson,List<string> deletelist){
		system.debug(LinelistJson);
        List<ASI_eForm_Return_Order_Request_Line_Item__c> Linelist = (List < ASI_eForm_Return_Order_Request_Line_Item__c > ) fromJsonString(LinelistJson, List < ASI_eForm_Return_Order_Request_Line_Item__c > .class);
		
		string Mesg ='Save Success !';
        set<string> DeletelineIdSet =new set<string>();
        for(string pid:deletelist){
            DeletelineIdSet.add(pid);
        }
        system.debug('Linelist');
        system.debug(Linelist);
        List<ASI_eForm_Return_Order_Request_Line_Item__c> DeleteLines=[select Id,Name from ASI_eForm_Return_Order_Request_Line_Item__c where id in : DeletelineIdSet];
        if(DeleteLines.size()>0){
            delete DeleteLines;
        }
        upsert Linelist;
        return Mesg;
    }
    
    @RemoteAction
    public static List<sObject> findList(string obj,string statement, string qry)
    {
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Schema.SObjectType sot = gd.get(obj);
        if (sot == null) return null;
        String filter = qry;
        String soql='';
        if(filter != '' || filter != null)
            soql = 'select '+statement+' from ' + obj + filter +' order by Name';
        else
            soql = 'select '+statement+' from ' + obj +' order by Name';
        
        List<sObject> sobjs = new List<sObject>();
        List<String> results = new List<String>();
        sobjs = Database.query(soql);
        return sobjs;
    }
	
	private static Object fromJsonString(String jsonString, System.Type apexType) {
        if (String.isBlank(jsonString)) {
            return null;
        }
        return System.JSON.deserialize(jsonString, apexType);
    }

    /**
     * Return list of objects with label and value
     *
     * @param objectName
     * @param fieldName
     *
     * @return [{label: 'label1', value:'value1'}]
     */
    public List<Map<String,String>> getPickListValue(String objectName, String fieldName){
        List<Map<String,String>> options = new List<Map<String,String>>();

        List<Schema.PicklistEntry> ple = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap().get(fieldName).getDescribe().getPicklistValues();
        for( Schema.PicklistEntry entry : ple){
            options.add( new Map<String,String>{
                    'label' => entry.getLabel(),
                    'value' => entry.getValue()
                });
        }
        return options;
    }
}