objects/ASI_MFM_Payment__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_PO_Type__c</fullName>
        <label>PO Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>VAP Brand Owner</fullName>
                </value>
                <value>
                    <fullName>VAP FOC</fullName>
                </value>
                <value>
                    <fullName>Event FOC</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>I1</fullName>
                </value>
                <value>
                    <fullName>I0</fullName>
                </value>
                <value>
                    <fullName>I3</fullName>
                </value>
                <value>
                    <fullName>I6</fullName>
                </value>
                <value>
                    <fullName>I7</fullName>
                </value>
                <value>
                    <fullName>I9</fullName>
                </value>
                <value>
                    <fullName>O3</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
                <value>
                    <fullName>2P</fullName>
                </value>
                <value>
                    <fullName>2A</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>O7</fullName>
                </value>
                <value>
                    <fullName>1H</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ASI_MFM_PO__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>TW PO, TW PO Read-Only, KR PO, KR PO Read-Only, CN Structure Cost, SC PO, SC PO Read-Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>ASI_MFM_Payment__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Supplier_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Supplier Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 8) OR 2 OR 3 OR 4 OR 6 OR (5 AND 7) OR 9 OR 10</booleanFilter>
            <errorMessage>Please select correct supplier.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI KR Supplier</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>HK Supplier, OPEX HK Supplier, SC Supplier, CAP JP Supplier</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN Supplier, CN Structure Cost Supplier</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>TW Supplier, RM Supplier, GF Supplier</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>TH Supplier, MFM TH Supplier</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>VN Supplier, OPEX SG Supplier, OPEX TH Supplier, Supplier (SG),MY Supplier, PH Supplier, ASI JP Supplier</value>
            </filterItems>
            <filterItems>
                <field>Account.ASI_KOR_Customer_Code__c</field>
                <operation>contains</operation>
                <value>THS</value>
            </filterItems>
            <filterItems>
                <field>Account.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>TR Supplier</value>
            </filterItems>
            <filterItems>
                <field>$User.BypassVR__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_PO__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CTY_CN_Vendor_Fill_Sir__c</fullName>
        <formula>IF((ASI_MFM_Total_Quantity__c-ASI_CTY_CN_Vendor_SirEd_Quantity__c)&gt;0, false, true)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASI CTY CN Vendor Fill Sir</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CTY_CN_Vendor_IsPayoff__c</fullName>
        <description>判断po是否已全部申请付款</description>
        <formula>IF(ASI_MFM_PO_Amount__c&lt;&gt;ASI_MFM_Total_Paid_Amount__c, false, true)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASI CTY CN Vendor IsPayoff</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_PO_Type__c</fullName>
        <label>PO Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Image Outlet</fullName>
                </value>
                <value>
                    <fullName>In Channel Event</fullName>
                </value>
                <value>
                    <fullName>Out Channel Event</fullName>
                </value>
                <value>
                    <fullName>Memo</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>Advance Payment</fullName>
                </value>
                <value>
                    <fullName>VAP Brand Owner</fullName>
                </value>
                <value>
                    <fullName>VAP FOC</fullName>
                </value>
                <value>
                    <fullName>Event FOC</fullName>
                </value>
                <value>
                    <fullName>CAPEX</fullName>
                </value>
                <value>
                    <fullName>OPEX</fullName>
                </value>
                <value>
                    <fullName>Event Memo</fullName>
                </value>
                <value>
                    <fullName>Other Memo</fullName>
                </value>
                <value>
                    <fullName>RTMK POSM</fullName>
                </value>
                <value>
                    <fullName>IT Capex</fullName>
                </value>
                <value>
                    <fullName>IT Opex</fullName>
                </value>
                <value>
                    <fullName>RTMK Image</fullName>
                </value>
                <value>
                    <fullName>RTMK Event</fullName>
                </value>
                <value>
                    <fullName>RTMK IMO</fullName>
                </value>
                <value>
                    <fullName>RTMK Image Outlet</fullName>
                </value>
                <value>
                    <fullName>IT Capex Hardware Region</fullName>
                </value>
                <value>
                    <fullName>IT Capex Hardware HQ</fullName>
                </value>
                <value>
                    <fullName>IT Capex Software</fullName>
                </value>
                <value>
                    <fullName>IT Capex Renovation</fullName>
                </value>
                <value>
                    <fullName>Tmall</fullName>
                    <label>Tmall EC-TAP</label>
                </value>
                <value>
                    <fullName>JD</fullName>
                    <label>JD EC-TAP</label>
                </value>
                <value>
                    <fullName>JX</fullName>
                    <label>JX EC-TAP</label>
                </value>
                <value>
                    <fullName>Other EC</fullName>
                    <label>Other EC-TAP</label>
                </value>
                <value>
                    <fullName>Gift material</fullName>
                    <label>Gift material礼品物料</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_Supplier_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 9 AND 4) OR 3 OR 5 OR 6 OR 7 OR (8 AND 10)</booleanFilter>
            <errorMessage>Please input correct Supplier Name.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI JP Supplier, Supplier, PH Supplier, VN DF Customer, VN DP Customer,VN Supplier,TW Supplier, Supplier (SG), MY Supplier, RM Supplier, CN Supplier,ASI JP Supplier, Supplier, PH Supplier, VN DF Customer, VN DP Customer,VN Supplier,CN Supplier, SC Supplier</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>HK Supplier, ASI KR Supplier, OPEX SG Supplier</value>
            </filterItems>
            <filterItems>
                <field>$User.BypassVR__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>TR PO, TR PO Read-Only, RM PO, RM PO Read-Only</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI JP Supplier, Supplier, PH Supplier, VN DF Customer, VN DP Customer,VN Supplier</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>GF Supplier</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>TR Supplier</value>
            </filterItems>
            <filterItems>
                <field>Account.ASI_KOR_Customer_Code__c</field>
                <operation>contains</operation>
                <value>THS</value>
            </filterItems>
            <filterItems>
                <field>Account.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>TH Supplier, MFM TH Supplier</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>POs</relationshipLabel>
        <relationshipName>POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PO</label>
    <nameField>
        <label>PO Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_PO_POSM_Line__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_PO__c</fullName>
        <label>PO</label>
        <referenceTo>ASI_MFM_PO__c</referenceTo>
        <relationshipLabel>PO POSM Lines</relationshipLabel>
        <relationshipName>PO_POSM_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PO POSM Line</label>
    <nameField>
        <displayFormat>PPL-{YY}{000000}</displayFormat>
        <label>PO POSM Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO POSM Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_Stock_In_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_PO_POSM_Line_Number__c</fullName>
        <label>PO POSM Line Number</label>
        <referenceTo>ASI_MFM_PO_POSM_Line__c</referenceTo>
        <relationshipLabel>Stock In Requests</relationshipLabel>
        <relationshipName>Stock_In_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stock In Request</label>
    <nameField>
        <displayFormat>SIR-{YY}{MM}{0000}</displayFormat>
        <label>Stock In Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock In Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CTY_CN_Vendor_ComDashboardCtrl.cls
/*********************************************************************************
 * Name: ASI_CTY_CN_Vendor_ComDashboardCtrl
 * Description: Statistics of Po report data
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 28/08/2020       wangzhiqiang             Created          
*/
public without sharing class ASI_CTY_CN_Vendor_ComDashboardCtrl {


     @AuraEnabled
     public static CountPoNums getPoDataCount(String typeName)
     {
        // type：1-By Quantity；2-By Amount
        Date endDate = Date.today();
        Date beginDate = endDate.addMonths(-24);
        System.debug(LoggingLevel.INFO, '*** beginDate: ' + beginDate);
        Date endMonthDate = Date.newInstance(endDate.year(),  endDate.month()+1, 1);
        Date beginMonthDate = Date.newInstance(endDate.year(),  endDate.month()-5, 1);
        CountPoNums poNum = new CountPoNums();

        //Get the supplier customer corresponding to the current user
        Id accountId = ASI_CTY_CN_Vendor_Util.getAccountId();
        if(typeName.equals('1'))
        {
            // Query Po statistics in the past 24 months
            poNum.poCounts = getNumsByYear(beginDate,endDate,accountId);
            poNum.pendingPayment = getPendingPaymentsByYear(beginDate,endDate,accountId);
            poNum.noFillSir = getNoFillSirsByYear(beginDate,endDate,accountId);

            // Statistics of the total contract data of each month in the past six months
            poNum.cuPoCounts =getNumsByMonths(beginMonthDate,endMonthDate,accountId);

            // Statistics of the total amount of payment applied for each month in the past six months
            poNum.pendingPaymentCounts =getPendingPaymentsByMonths(beginMonthDate,endMonthDate,accountId);
           
            // The total Sir data of each month in the past six months were counted
            poNum.noFillSirs =getNoFillSirsByMonths(beginMonthDate,endMonthDate,accountId);
        }
        else
        {
            // Query Po statistics in the past 24 months
            poNum.poCounts = getAmountByYear(beginDate,endDate,accountId);
            poNum.pendingPayment = getPendingPaymentsAmountByYear(beginDate,endDate,accountId);
            poNum.noFillSir = getNoFillSirsAmountByYear(beginDate,endDate,accountId);

            // The total contract amount of each month in the past six months shall be counted respectively
            poNum.cuPoCounts =getAmountByMonths(beginMonthDate,endMonthDate,accountId);

            // The total amount of contract with application for payment in each month in the past 6 months was counted respectively
            poNum.pendingPaymentCounts =getPendingPaymentsAmountByMonths(beginMonthDate,endMonthDate,accountId);

            // The total amount to be filled in the contract in each month in the past 6 months is counted respectively
            poNum.noFillSirs =getNoFillSirsAmountByMonths(beginMonthDate,endMonthDate,accountId);
        }


        poNum.months = getMonths();
        return poNum;
     }

     public static Decimal getNumsByYear(Date beginDate,Date endDate,Id accountId)
     {
        List<AggregateResult> pos= [SELECT count(Id) FROM ASI_MFM_PO__c WHERE  CreatedDate>=:beginDate AND CreatedDate<=:endDate
                                    AND (RecordType.Name ='CN PO' OR RecordType.Name='CN PO Read-Only') AND ASI_MFM_PO_Type__c='eMarket' AND
                                    ASI_MFM_Supplier_Name__c = :accountId ]; 
        AggregateResult aggr = pos.get(0);
        Decimal poCounts = (Decimal)aggr.get('expr0');
        return poCounts;
     }

     public static Decimal getPendingPaymentsByYear(Date beginDate,Date endDate,Id accountId)
     {
        List<AggregateResult> pos= [SELECT count(Id) FROM ASI_MFM_PO__c WHERE  CreatedDate>=:beginDate AND CreatedDate<=:endDate
                                    AND ASI_CTY_CN_Vendor_IsPayoff__c = false AND (RecordType.Name ='CN PO' OR RecordType.Name='CN PO Read-Only')
                                    AND ASI_MFM_PO_Type__c='eMarket' AND
                                    ASI_MFM_Supplier_Name__c = :accountId ];
        AggregateResult aggr = pos.get(0);
        Decimal pendingPayment = (Decimal)aggr.get('expr0');
        return pendingPayment;
     }

     public static Decimal getNoFillSirsByYear(Date beginDate,Date endDate,Id accountId)
     {
        List<AggregateResult> pos= [SELECT count(Id) FROM ASI_MFM_PO__c WHERE  CreatedDate>=:beginDate AND CreatedDate<=:endDate
                                    AND ASI_CTY_CN_Vendor_Fill_Sir__c  = false AND (RecordType.Name ='CN PO' OR RecordType.Name='CN PO Read-Only') 
                                    AND ASI_MFM_PO_Type__c='eMarket' AND
                                    ASI_MFM_Supplier_Name__c = :accountId];
        AggregateResult aggr = pos.get(0);
        Decimal noFillSir = (Decimal)aggr.get('expr0');
        return noFillSir;
     }

     public static List<Decimal> getNumsByMonths(Date beginDate,Date endDate,Id accountId)
     { 
        
        List<AggregateResult> pos= [SELECT  calendar_month(CreatedDate) m,count(Id) FROM ASI_MFM_PO__c WHERE  CreatedDate>=:beginDate AND CreatedDate<:endDate
                                    AND (RecordType.Name ='CN PO' OR RecordType.Name='CN PO Read-Only') 
                                    AND ASI_MFM_PO_Type__c='eMarket' AND ASI_MFM_Supplier_Name__c = :accountId  
                                    group by calendar_month(CreatedDate)];
        System.debug(LoggingLevel.INFO, '*** pos: ' + pos);
        return handleDate(pos,beginDate);
     }

     

     public static List<Decimal> getPendingPaymentsByMonths(Date beginDate,Date endDate,Id accountId)
     { 
        
        List<AggregateResult> pos= [SELECT calendar_month(CreatedDate) m,count(Id) FROM ASI_MFM_Payment__c WHERE  CreatedDate>=:beginDate AND CreatedDate<=:endDate
                                    AND (RecordType.Name ='CN Payment' OR RecordType.Name='CN Payment Read-Only') 
                                    AND ASI_MFM_Supplier_Name__c =:accountId 
                                    group by calendar_month(CreatedDate)
                                    ];
       return handleDate(pos,beginDate);
     }

     public static List<Decimal> getNoFillSirsByMonths(Date beginDate,Date endDate,Id accountId)
     { 
        
        List<AggregateResult> pos= [SELECT calendar_month(CreatedDate) m,count(Id) FROM ASI_MFM_Stock_In_Request__c WHERE  CreatedDate>=:beginDate AND CreatedDate<=:endDate
                                    AND ASI_MFM_PO_POSM_Line_Number__r.ASI_MFM_PO__r.ASI_MFM_Supplier_Name__c =:accountId 
                                    AND (ASI_MFM_PO_POSM_Line_Number__r.ASI_MFM_PO__r.RecordType.Name ='CN PO' OR ASI_MFM_PO_POSM_Line_Number__r.ASI_MFM_PO__r.RecordType.Name ='CN PO Read-Only')
                                    AND  ASI_MFM_PO_POSM_Line_Number__r.ASI_MFM_PO__r.ASI_MFM_PO_Type__c ='eMarket' 
                                    group by calendar_month(CreatedDate)];
        return handleDate(pos,beginDate);
     }


     // 获取金额
     public static Decimal getAmountByYear(Date beginDate,Date endDate,Id accountId)
     {
        List<AggregateResult> pos= [SELECT sum(ASI_MFM_PO_Amount__c) FROM ASI_MFM_PO__c WHERE  CreatedDate>=:beginDate AND CreatedDate<=:endDate
                                    AND (RecordType.Name ='CN PO' OR RecordType.Name='CN PO Read-Only') 
                                    AND ASI_MFM_PO_Type__c='eMarket' AND
                                    ASI_MFM_Supplier_Name__c = :accountId];
        AggregateResult aggr = pos.get(0);
        Decimal  poCounts = (Decimal)aggr.get('expr0');
        if(null == poCounts)
        {
            poCounts = 0;
        }
        poCounts = (poCounts/10000).setScale(2);
        return poCounts;
     }

     public static Decimal getPendingPaymentsAmountByYear(Date beginDate,Date endDate,Id accountId)
     {
        List<AggregateResult> pos= [SELECT sum(ASI_CTY_CN_Vendor_Pending_Amount__c) FROM ASI_MFM_PO__c WHERE  CreatedDate>=:beginDate AND CreatedDate<=:endDate
                                    AND ASI_CTY_CN_Vendor_IsPayoff__c = false AND (RecordType.Name ='CN PO' OR RecordType.Name='CN PO Read-Only') 
                                    AND ASI_MFM_PO_Type__c='eMarket' AND
                                    ASI_MFM_Supplier_Name__c = :accountId];
        AggregateResult aggr = pos.get(0);
        Decimal pendingPayment = (Decimal)aggr.get('expr0');
        if(null == pendingPayment)
        {
            pendingPayment = 0;
        }
        pendingPayment = (pendingPayment/10000).setScale(2);
        return pendingPayment;
     }

     public static Decimal getNoFillSirsAmountByYear(Date beginDate,Date endDate,Id accountId)
     {
        List<AggregateResult> pos= [SELECT sum(ASI_CTY_CN_Vendor_No_Fill_SirAmount__c ) FROM ASI_MFM_PO__c WHERE  CreatedDate>=:beginDate AND CreatedDate<=:endDate
                                    AND ASI_CTY_CN_Vendor_Fill_Sir__c  = false AND (RecordType.Name ='CN PO' OR RecordType.Name='CN PO Read-Only') 
                                    AND ASI_MFM_PO_Type__c='eMarket' AND
                                    ASI_MFM_Supplier_Name__c = :accountId];
        AggregateResult aggr = pos.get(0);
        Decimal noFillSir = (Decimal)aggr.get('expr0');
        if(null == noFillSir)
        {
            noFillSir = 0;
        }
        noFillSir = (noFillSir/10000).setScale(2);
        return noFillSir;
     }

     public static  List<Decimal> getAmountByMonths(Date beginDate,Date endDate,Id accountId)
     { 
        
        List<AggregateResult> pos= [SELECT calendar_month(CreatedDate) m,sum(ASI_MFM_PO_Amount__c) FROM ASI_MFM_PO__c WHERE  CreatedDate>=:beginDate AND CreatedDate<:endDate
                                    AND (RecordType.Name ='CN PO' OR RecordType.Name='CN PO Read-Only') 
                                    AND ASI_MFM_PO_Type__c='eMarket' AND
                                    ASI_MFM_Supplier_Name__c = :accountId group by calendar_month(CreatedDate)];
        return  handleAmountDate(pos,beginDate);
     }

     public static  List<Decimal> getPendingPaymentsAmountByMonths(Date beginDate,Date endDate,Id accountId)
     { 
        
        List<AggregateResult> pos= [SELECT calendar_month(CreatedDate) m,sum(ASI_MFM_Payment_Amount__c) FROM ASI_MFM_Payment__c WHERE  CreatedDate>=:beginDate AND CreatedDate<=:endDate
                                    AND (RecordType.Name ='CN Payment' OR RecordType.Name='CN Payment Read-Only') 
                                    AND ASI_MFM_Supplier_Name__c =:accountId 
                                    group by calendar_month(CreatedDate)];
        return  handleAmountDate(pos,beginDate);
     }

     public static  List<Decimal> getNoFillSirsAmountByMonths(Date beginDate,Date endDate,Id accountId)
     { 
        List<AggregateResult> pos= [SELECT calendar_month(CreatedDate) m,sum(ASI_CTY_CN_Vendor_Amount__c) FROM ASI_MFM_Stock_In_Request__c WHERE  CreatedDate>=:beginDate AND CreatedDate<=:endDate
                                    AND ASI_MFM_PO_POSM_Line_Number__r.ASI_MFM_PO__r.ASI_MFM_Supplier_Name__c =:accountId 
                                    AND (ASI_MFM_PO_POSM_Line_Number__r.ASI_MFM_PO__r.RecordType.Name ='CN PO' OR ASI_MFM_PO_POSM_Line_Number__r.ASI_MFM_PO__r.RecordType.Name ='CN PO Read-Only')
                                    AND  ASI_MFM_PO_POSM_Line_Number__r.ASI_MFM_PO__r.ASI_MFM_PO_Type__c ='eMarket'
                                    group by calendar_month(CreatedDate)
                                    ];
        System.debug(LoggingLevel.INFO, '*** pos: ' + pos);
        return  handleAmountDate(pos,beginDate);
     }

     public static  List<String> getMonths()
     {
        List<String> months = new List<String>();
        Date tempDate = Date.today();
        for(Integer i=5;i>=0;i--)
        {
            months.add(tempDate.addMonths(-i).month()+'月');
        }
       return months;
     }

     public static List<Decimal> handleDate(List<AggregateResult> pos,Date beginDate)
     {
        System.debug(LoggingLevel.INFO, '*** pos: ' + pos);
        Map<Integer,Decimal> monthValueMap = new Map<Integer,Decimal>();
        List<Decimal> summarydDate = new List<Decimal>();
        if(pos.size()>0)
        {
            for(AggregateResult po:pos)
            {
              monthValueMap.put((Integer)po.get('m'),(Decimal)po.get('expr0'));
            }
            System.debug(LoggingLevel.INFO, '*** monthValueMap: ' + monthValueMap);
            Date tempDate = Date.today();

            for(Integer i=5;i>=0;i--)
            {
               Integer newMonth = tempDate.addMonths(-i).month();
               if(null == monthValueMap.get(newMonth))
                {
                  summarydDate.add(0);
                }
                else
                {
                  summarydDate.add(monthValueMap.get(newMonth));
                }
            }
        }
        System.debug(LoggingLevel.INFO, '*** summarydDate: ' + summarydDate);
        
        return summarydDate;
      }

     public static List<Decimal> handleAmountDate(List<AggregateResult> pos,Date beginDate)
     {
        Map<Integer,Decimal> monthValueMap = new Map<Integer,Decimal>();
        List<Decimal> summarydDate = new List<Decimal>();
        if(pos.size()>0)
        {
            for(AggregateResult po:pos)
            {
              monthValueMap.put((Integer)po.get('m'),(Decimal)po.get('expr0'));
            }
            System.debug(LoggingLevel.INFO, '*** monthValueMap: ' + monthValueMap);
            Date tempDate = Date.today();
            for(Integer i=5;i>=0;i--)
            {
                Integer newMonth = tempDate.addMonths(-i).month();
                if(null == monthValueMap.get(newMonth))
                {
                  summarydDate.add(0);
                }
                else
                {
                  Decimal poCounts =  monthValueMap.get(newMonth);
                  poCounts = (poCounts/10000).setScale(2);
                  summarydDate.add(poCounts);
                }
            }
        }
        
        return summarydDate;
      }


     
     public class CountPoNums{
        @AuraEnabled
        public Decimal poCounts;
        @AuraEnabled
        public List<Decimal> cuPoCounts;
        @AuraEnabled
        public Decimal pendingPayment;
        @AuraEnabled
        public List<Decimal> pendingPaymentCounts;
        @AuraEnabled
        public Decimal noFillSir;
        @AuraEnabled
        public List<Decimal> noFillSirs;
        @AuraEnabled
        public List<String> months;
     }
    
}