objects/ASI_CRM_VN_Contract__c.object
<CustomObject>
    <description>This contract object is only for PRVN</description>
    <fields>
        <fullName>ASI_CRM_Contract_Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Verification</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed(Terminated)</fullName>
                </value>
                <value>
                    <fullName>Submit for Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract (VN)</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contract Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts (VN)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_VN_Contract_Expenditure__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_VN_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>ASI_CRM_VN_Contract__c</referenceTo>
        <relationshipLabel>Contract Expenditures</relationshipLabel>
        <relationshipName>Contract_Expenditures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Expenditure</label>
    <nameField>
        <displayFormat>VNER-{00000}</displayFormat>
        <label>Expenditure Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Expenditures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CRM_VN_ContractExpendCheckDelete.cls
/*********************************************************************************
 * Name: ASI_CRM_VN_ContractExpendCheckDelete
 * Description: Check can contract expenditure record be deleted
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 31/07/2017       Hugo Cheung             Created          
*/
public class ASI_CRM_VN_ContractExpendCheckDelete {
    
    private final static Map<String, Schema.SObjectField> CONTRACT_FIELD_MAP     = Schema.SObjectType.ASI_CRM_VN_Contract__c.fields.getMap();
	private final static String CONTRACT_STATUS_ALLOW_DELETE = 'Draft'; 
    
    public ASI_CRM_VN_ContractExpendCheckDelete() {
    }
    
    public void executeTrigger(List<sObject> newList, Map<Id, sObject> oldMap) {
    	List<ASI_CRM_VN_Contract_Expenditure__c> contractExpenditureList   = (List<ASI_CRM_VN_Contract_Expenditure__c>) newList;
        Map<Id, ASI_CRM_VN_Contract_Expenditure__c> contractExpenditureMap = (Map<Id, ASI_CRM_VN_Contract_Expenditure__c>) oldMap;
        
        List<ASI_CRM_VN_Contract_Expenditure__c> filteredContractExpenditureList = filterContractExpenditure(contractExpenditureList, contractExpenditureMap);
        checkDelete(filteredContractExpenditureList);
    }
    
    private List<ASI_CRM_VN_Contract_Expenditure__c> filterContractExpenditure(List<ASI_CRM_VN_Contract_Expenditure__c> contractExpenditureList, Map<Id, ASI_CRM_VN_Contract_Expenditure__c> contractExpenditureMap) {
    	return contractExpenditureMap.values();
    }
    
    private void checkDelete(List<ASI_CRM_VN_Contract_Expenditure__c> contractExpenditureList) {
    	Set<Id> contractIdSet = new Set<Id>();
        for(ASI_CRM_VN_Contract_Expenditure__c contractExpenditure : contractExpenditureList) {
            contractIdSet.add(contractExpenditure.ASI_CRM_VN_Contract__c);
        }
        
        Map<Id, ASI_CRM_VN_Contract__c> contractIdMap = new Map<Id, ASI_CRM_VN_Contract__c>(retrieveContractList(contractIdSet));
        for(ASI_CRM_VN_Contract_Expenditure__c contractExpenditure : contractExpenditureList) {
            ASI_CRM_VN_Contract__c tempContract = contractIdMap.get(contractExpenditure.ASI_CRM_VN_Contract__c);
            if(tempContract.ASI_CRM_Contract_Status__c == CONTRACT_STATUS_ALLOW_DELETE) {
            	continue;
            } else {
            	contractExpenditure.addError(Label.ASI_CRM_VN_Contract_Expend_Cannot_Be_Deleted);
            }
        }
    }
    
    /***************
  	Data Retrievement Function
  	***************/
    private List<ASI_CRM_VN_Contract__c> retrieveContractList(Set<Id> contractIdSet) {
    	String query = 'SELECT ' + genQueryField(CONTRACT_FIELD_MAP) + 
                       ', RecordType.DeveloperName ' + 
                       'FROM ASI_CRM_VN_Contract__c ' + 
                       'Where Id in :contractIdSet';
        
    	return (List<ASI_CRM_VN_Contract__c>) Database.query(query);
  	}
    
    /***************
  	Tools Function
  	***************/
	private String genQueryField(Map<String, Schema.SObjectField> fieldMap) {
      	String queryField = '';
      	for(String fields : fieldMap.keySet()) {
       		queryField += fields + ',';
   		}
    	return queryField.subString(0, queryField.length() - 1);
    }
}