objects/ASI_JP_TnE_Expense_Classification__c.object
<CustomObject>
    <fields>
        <fullName>ASI_JP_TnE_Account_Mapping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Mapping</label>
        <referenceTo>ASI_TnE_Account_Mapping__c</referenceTo>
        <relationshipName>TnE_JP_Expense_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ASI TnE Expense Classification</label>
    <nameField>
        <label>Expense Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ASI TnE Expense Classifications</pluralLabel>
    <recordTypes>
        <fullName>ASI_TnE_KR_Expense_Classification</fullName>
        <active>true</active>
        <description>KR Expense Classification</description>
        <label>ASI_TnE_KR_Expense_Classification</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TnE_Account_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>ASI_TnE_KR_CO_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ASI_TnE_Account_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ASI TnE Account Mapping</label>
    <nameField>
        <displayFormat>TnE-ACC-{0000}</displayFormat>
        <label>ASI TnE Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASI TnE Account Mappings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TnE_ClaimDetail__c.object
<CustomObject>
    <fields>
        <fullName>ASI_TnE_ClaimHeader__c</fullName>
        <label>Travel &amp; Entertainment Claim</label>
        <referenceTo>ASI_TnE_ClaimHeader__c</referenceTo>
        <relationshipLabel>Travel &amp; Entertainment Claims Detail</relationshipLabel>
        <relationshipName>ASI_TnE_ClaimDetail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_Expense_Classification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense Classification</label>
        <referenceTo>ASI_JP_TnE_Expense_Classification__c</referenceTo>
        <relationshipLabel>Travel &amp; Entertainment Claims Detail (Expense Classification)</relationshipLabel>
        <relationshipName>Travel_Entertainment_Claims_Detail1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_KR_Co_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Travel_Entertainment_Claims_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_KR_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.ASI_KOR_Commission_Code__c</field>
                <operation>notEqual</operation>
                <value>null</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Travel_Entertainment_Claims_Detail1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_Receipt_Number__c</fullName>
        <label>Rpt No.</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_Status__c</fullName>
        <formula>TEXT(ASI_TnE_ClaimHeader__r.ASI_TnE_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Travel &amp; Entertainment Claim Detail</label>
    <nameField>
        <displayFormat>TED-{YY}-{00000}</displayFormat>
        <label>Claim Detail No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel &amp; Entertainment Claims Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_TnE_ClaimHeader__c.object
<CustomObject>
    <fields>
        <fullName>ASI_TnE_KR_CoApprover_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>T&amp;E/A&amp;P외 기타비용 집행시 각 예산 담당자가 해당 비용의 승인권자로 자동 지정 됩니다.
(ex: 지점 비품-&gt;총무팀 담당자 / 교육훈련비-&gt;인사팀 담당자)</inlineHelpText>
        <label>Co-Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Travel_Entertainment_ClaimsHAXO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_KR_CoApprover_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Travel_Entertainment_ClaimsHAXY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_KR_CoApprover_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Travel_Entertainment_ClaimsHAXi</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_KR_CoApprover_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Approver 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Travel_Entertainment_ClaimsHAXs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_KR_CoApprover_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Co-Approver 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Travel_Entertainment_ClaimsHAY7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TnE_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Waiting for Department Head Approval</fullName>
                </value>
                <value>
                    <fullName>Waiting for Finance Verification</fullName>
                </value>
                <value>
                    <fullName>Waiting for Finance Approval</fullName>
                </value>
                <value>
                    <fullName>Waiting for Finance Director Review</fullName>
                </value>
                <value>
                    <fullName>Finance Director Approved</fullName>
                </value>
                <value>
                    <fullName>Release</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Finance Verified</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>PRA Final Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Travel &amp; Entertainment Claim</label>
    <nameField>
        <displayFormat>TE-{YY}-{00000}</displayFormat>
        <label>Travel &amp; Entertainment Claim Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel &amp; Entertainment Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_TnE_KR_CoApprover_Mapping.cls
public without sharing class ASI_TnE_KR_CoApprover_Mapping {
    
    static set<id> budgetOwnerSet = new Set<id>();
    static set<id> coApproverSet = new set<id>();
    static set<id> headerID = new set<id>();
    private static String statusDraft = 'Draft';
    private static String statusSubmitted = 'Submitted';
    private static String statusApproved = 'Approved';
    private static String statusCompleted = 'Complete';
    private static String statusFinal = 'Final';
    private static String statusReject = 'Rejected';
    
    
    public static void coApprover(list<ASI_TnE_ClaimDetail__c> triggerNew,map<id,ASI_TnE_ClaimDetail__c> triggerNewMap){
        
        list<id> sortedCoApprover = new list<id>();
        list<id> sortedBudgetOwner = new list<id>();
        list<id> coApprover = new list<id>();
        list<id> budgetOwner = new list<id>();
        String budgetOwnerStr;
        String coApproverStr;
    
    Map<id, ASI_JP_TnE_Expense_Classification__c> Classifications = new Map<id, ASI_JP_TnE_Expense_Classification__c>([select id,ASI_JP_TnE_Account_Mapping__r.ASI_TnE_KR_CO_Approver__c from ASI_JP_TnE_Expense_Classification__c where recordType.DeveloperName = 'ASI_TnE_KR_Expense_Classification']);
    
        for(ASI_TnE_ClaimDetail__c obj : triggerNew){
            
            /*if(obj.ASI_TnE_Receipt_Number__c==null){
                    obj.ASI_TnE_Receipt_Number__c=0;
                }else{
                    obj.ASI_TnE_Receipt_Number__c += 1;
                }*/
            
            budgetOwnerSet.add(obj.ASI_TnE_KR_Owner__c);
            
            if(obj.ASI_TnE_Expense_Classification__c!=null){
                //for(ASI_JP_TnE_Expense_Classification__c Classification : Classifications){
                    system.debug('checkaaa ' + Classifications);
                    
                    //if(obj.ASI_TnE_Expense_Classification__c==Classification.id){
                        obj.ASI_TnE_KR_Co_Approver__c=Classifications.get(obj.ASI_TnE_Expense_Classification__c).ASI_JP_TnE_Account_Mapping__r.ASI_TnE_KR_CO_Approver__c;
                        coApproverSet.add(Classifications.get(obj.ASI_TnE_Expense_Classification__c).ASI_JP_TnE_Account_Mapping__r.ASI_TnE_KR_CO_Approver__c);
                        headerID.add(obj.ASI_TnE_ClaimHeader__c);
                    //}
                //}
            }
        }        
			budgetOwner.addall(budgetOwnerSet);
            coApprover.addall(coApproverSet);
        	coApprover.sort();
        	budgetOwner.sort();
        
        for(integer i=coApprover.size()-1;i>=0;i--){
            sortedCoApprover.add(coApprover[i]);
        }
        for(integer i = budgetOwner.size()-1;i>=0;i--){
        	sortedBudgetOwner.add(budgetOwner[i]);
        }
        
        list<ASI_TnE_ClaimHeader__c> claimHeader = [SELECT id,ASI_TnE_KR_CoApprover_1__c,
                                                    ASI_TnE_KR_CoApprover_2__c,
                                                    ASI_TnE_KR_CoApprover_3__c,
                                                    ASI_TnE_KR_CoApprover_4__c,
                                                    ASI_TnE_KR_CoApprover_5__c
                                                    from ASI_TnE_ClaimHeader__c where id in : headerID
                                                   	AND (ASI_TnE_Status__c =: statusDraft
                                                         OR ASI_TnE_Status__c =: statusReject)];
		list<ASI_TnE_ClaimHeader__c> updateHeader = new list<ASI_TnE_ClaimHeader__c>();        
        
        for(ASI_TnE_ClaimHeader__c obj: claimHeader){
			for(integer i = 1;i<=5;i++){
                
                budgetOwnerStr = 'ASI_TnE_KR_Budget_Owner_'+i+'__c';
                coApproverStr = 'ASI_TnE_KR_CoApprover_'+i+'__c';
                
                if(i<=sortedCoApprover.size()){
                	obj.put(coApproverStr,sortedCoApprover[i-1]);
                }else{
                    obj.put(coApproverStr,null);
                }

                if(i<=sortedBudgetOwner.size()){
                	obj.put(budgetOwnerStr,sortedBudgetOwner[i-1]);
                }else{
                    obj.put(budgetOwnerStr,null);
                }
            }
            updateHeader.add(obj);
        }
        update updateHeader;
    }
}