objects/ASI_KOR_Item_Group__c.object
<CustomObject>
    <fields>
        <fullName>ASI_KOR_Item_Group_Code__c</fullName>
        <externalId>true</externalId>
        <label>Item Group Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Item Group</label>
    <nameField>
        <label>Item Group Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_KOR_Sales_Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_KOR_Wholesaler_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wholesaler Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Order Requests</relationshipLabel>
        <relationshipName>Sales_Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Request</label>
    <nameField>
        <displayFormat>SOR-{00000000}</displayFormat>
        <label>Sales Order Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_KOR_Sales_Order_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ASI_KOR_Item_Group_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group Code</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Item Groups no longer Active!</errorMessage>
            <filterItems>
                <field>ASI_KOR_Item_Group__c.ASI_KOR_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_KOR_Item_Group__c</referenceTo>
        <relationshipLabel>Sales Order Request Items</relationshipLabel>
        <relationshipName>Sales_Order_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Order_Qty__c</fullName>
        <label>Order Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_KOR_Product_Usage__c</fullName>
        <label>Product Usage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Export</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>On Trade</fullName>
                </value>
                <value>
                    <fullName>Discount Store</fullName>
                </value>
                <value>
                    <fullName>Off Trade</fullName>
                </value>
                <value>
                    <fullName>Army Tax Paid</fullName>
                </value>
                <value>
                    <fullName>Domestic DF</fullName>
                </value>
                <value>
                    <fullName>Army Tax Free</fullName>
                </value>
                <value>
                    <fullName>E-mart</fullName>
                </value>
                <value>
                    <fullName>Giftset</fullName>
                </value>
                <value>
                    <fullName>Home Plus</fullName>
                </value>
                <value>
                    <fullName>Promotional Items</fullName>
                </value>
                <value>
                    <fullName>POS Items</fullName>
                </value>
                <value>
                    <fullName>Normal product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_KOR_SOT_UOM__c</fullName>
        <label>Unit Of Measure (UOM)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Bottle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_KOR_Sales_Order_Request__c</fullName>
        <label>Sales Order Request</label>
        <referenceTo>ASI_KOR_Sales_Order_Request__c</referenceTo>
        <relationshipName>ASI_KOR_Sales_Order_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Order Request Item</label>
    <nameField>
        <displayFormat>SOT-{00000000}</displayFormat>
        <label>Sales Order Request Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_KOR_SalesOrderRequestGenerator.cls
public with sharing class ASI_KOR_SalesOrderRequestGenerator {
	public static final Decimal DEF_VALUE_DETAIL_QUANTITY = 5;
	public static final String DEF_VALUE_PD_USAGE = 'General';
	public static final String DEF_VALUE_UOM = 'Case';
	
	public ASI_KOR_Sales_Order_Request__c generateBasicRequest(Account acct) {
		return new ASI_KOR_Sales_Order_Request__c(
			ASI_KOR_Wholesaler_Name__c = acct.Id
		);
	}

	public ASI_KOR_Sales_Order_Request__c generateRequest(Account acct) {
		return generateBasicRequest(acct);
	}
	
	public ASI_KOR_Sales_Order_Transaction__c generateBasicDetail(ASI_KOR_Sales_Order_Request__c header, ASI_KOR_Item_Group__c itemGroup) {
		return new ASI_KOR_Sales_Order_Transaction__c(
			ASI_KOR_Sales_Order_Request__c = header.Id
			, ASI_KOR_Item_Group_Code__c = itemGroup.Id
			, ASI_KOR_Order_Qty__c = DEF_VALUE_DETAIL_QUANTITY
			, ASI_KOR_Product_Usage__c = DEF_VALUE_PD_USAGE
			, ASI_KOR_SOT_UOM__c = DEF_VALUE_UOM
		);
	}

	public ASI_KOR_Sales_Order_Transaction__c generateDetail(ASI_KOR_Sales_Order_Request__c header, ASI_KOR_Item_Group__c itemGroup) {
		return generateBasicDetail(header, itemGroup);
	}
	
}