objects/ASI_CRM_CN_Channel__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Channel_Chi_Name__c</fullName>
        <label>Channel Chi Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Criteria_Set__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_SG_Name__c</fullName>
        <label>Criteria Set Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Criteria Set</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Criteria Set No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Criteria Sets</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_TH_Image_Level_Criteria</fullName>
        <active>true</active>
        <label>TH Image Level Criteria</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Criteria_Threshold__c.object
<CustomObject>
    <description>ASI</description>
    <label>Criteria Threshold</label>
    <nameField>
        <displayFormat>CT-{0000000000}</displayFormat>
        <label>Criteria Threshold Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Criteria Thresholds</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_TH_Picklist</fullName>
        <active>true</active>
        <label>TH Picklist</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Group_Outlet_Type__c.object
<CustomObject>
    <description>ASI PROS Group Outlet type</description>
    <fields>
        <fullName>ASI_CRM_Region__c</fullName>
        <label>Region</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SG_Group_Outlet_Name__c</fullName>
        <label>Group Outlet Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CR (中餐)</fullName>
                </value>
                <value>
                    <fullName>CRB</fullName>
                </value>
                <value>
                    <fullName>Family KTV (FK)</fullName>
                </value>
                <value>
                    <fullName>HEB</fullName>
                </value>
                <value>
                    <fullName>High Energy Bar</fullName>
                </value>
                <value>
                    <fullName>High Energy Bar (HEB)</fullName>
                </value>
                <value>
                    <fullName>Japanese Style Night Club (JNC)</fullName>
                </value>
                <value>
                    <fullName>Karaoke (KO)</fullName>
                </value>
                <value>
                    <fullName>LEB</fullName>
                </value>
                <value>
                    <fullName>Low Energy Bar</fullName>
                </value>
                <value>
                    <fullName>Low Energy Bar (LEB)</fullName>
                </value>
                <value>
                    <fullName>LS (菸專)</fullName>
                </value>
                <value>
                    <fullName>LSM</fullName>
                </value>
                <value>
                    <fullName>LSW</fullName>
                </value>
                <value>
                    <fullName>MM</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>Nightclub</fullName>
                </value>
                <value>
                    <fullName>Night Club (NC)</fullName>
                </value>
                <value>
                    <fullName>Offtrade</fullName>
                </value>
                <value>
                    <fullName>Piano Bar (PB)</fullName>
                </value>
                <value>
                    <fullName>RES</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Restaurant (WR)</fullName>
                </value>
                <value>
                    <fullName>Subwholesaler</fullName>
                </value>
                <value>
                    <fullName>Taiwanese Style Night Club (TNC)</fullName>
                </value>
                <value>
                    <fullName>TOT</fullName>
                </value>
                <value>
                    <fullName>Traditional On-Trade (TOT)</fullName>
                </value>
                <value>
                    <fullName>Uniform Night Club (UNC)</fullName>
                </value>
                <value>
                    <fullName>WL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_SG_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Group Outlet Type</label>
    <nameField>
        <displayFormat>GO-{00000}</displayFormat>
        <label>Group Outlet Type No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Outlet Types</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_TH_Group_Outlet_Type</fullName>
        <active>true</active>
        <label>ASI CRM TH Group Outlet Type</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Pros_Segmentation__c.object
<CustomObject>
    <label>Pros Segmentation</label>
    <nameField>
        <displayFormat>PS-{0000000000}</displayFormat>
        <label>PROS ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pros Segmentations</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_TH_Pros_Segmentation</fullName>
        <active>true</active>
        <label>ASI CRM TH Pros Segmentation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Pros_Volume_Potential__c.object
<CustomObject>
    <label>Pros Volume Potential</label>
    <nameField>
        <displayFormat>VP-{00000}</displayFormat>
        <label>Pros Volume Potential No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pros Volume Potentials</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_TH_Pros_Volume_Potential</fullName>
        <active>true</active>
        <label>ASI CRM TH Pros Volume Potential</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Region__c.object
<CustomObject>
    <description>ASI_CRM_Region</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_MFM_Sub_Channel__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel</label>
        <referenceTo>ASI_CRM_CN_Channel__c</referenceTo>
        <relationshipLabel>Sub-Channel</relationshipLabel>
        <relationshipName>Sub_Channel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Group_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Outlet Type</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>ASI_CRM_Group_Outlet_Type__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM TW Group Outlet Type</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_Group_Outlet_Type__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM TH Group Outlet Type</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_Group_Outlet_Type__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM MY Group Outlet Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_CRM_Group_Outlet_Type__c</referenceTo>
        <relationshipLabel>Sub-Channel</relationshipLabel>
        <relationshipName>Sub_Channel</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub-Channel</label>
    <nameField>
        <label>Sub-Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Channel</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_OutletType__c.object
<CustomObject>
    <description>ASI CRM Outlet Type</description>
    <fields>
        <fullName>ASI_CRM_Group_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Outlet Type</label>
        <referenceTo>ASI_CRM_Group_Outlet_Type__c</referenceTo>
        <relationshipName>Outlet_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Sub_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-Channel</label>
        <referenceTo>ASI_MFM_Sub_Channel__c</referenceTo>
        <relationshipName>Outlet_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Outlet Type</label>
    <nameField>
        <label>Outlet Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outlet Type</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_TH_TestVolPotentialHandler.cls
/*********************************************************************************
 * Name: ASI_CRM_TH_TestVolPotentialHandler 
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 04/03/2016       Introv: Twinkle LI      Cloned from ASI_CRM_TW_TestVolPotentialHandler 
*********************************************************************************/
@isTest (SeeAllData = true)
public with sharing class ASI_CRM_TH_TestVolPotentialHandler {

    private static ASI_CRM_AccountsAdditionalField__c accountASI; 
    private static ASI_CRM_Pros_Segmentation__c prosSegmentation;
    private static ASI_CRM_Group_Outlet_Type__c grpOutletType;
    private static ASI_CRM_Criteria_Threshold__c criteriaThreshold;
    private static ASI_CRM_Pros_Segmentation__c prosSegmentation2;
    private static ASI_CRM_Criteria_Threshold__c criteriaThreshold2;
    
    static testmethod void dataInsert(){
        
        ASI_CRM_AccountsAdditionalField__c accASIList = new ASI_CRM_AccountsAdditionalField__c();
        accASIList = ASI_CRM_TH_TestClassUtilityHelperPROS.createAccountsASI(1, 'ASI_TH_CRM_Outlet')[0];
        accASIList.ASI_CRM_Region__c = 'Second Tier';
        insert accASIList;
        
        system.assert(accASIList.Id<>null);
        
        List<ASI_CRM_Group_Outlet_Type__c> grpOutletTypeList = new List<ASI_CRM_Group_Outlet_Type__c>();
        //grpOutletTypeList = ASI_CRM_TH_TestClassUtilityHelperPROS.createGroupOutletType(1, 'ASI_CRM_TH_Group_Outlet_Type', 'THB', null, null);
        grpOutletTypeList.add(new ASI_CRM_Group_Outlet_Type__c(RecordTypeId = Global_RecordTypeCache.getRTId('ASI_CRM_Group_Outlet_Type__cASI_CRM_TH_Group_Outlet_Type'),
                                                               ASI_CRM_SG_Name__c = 'TEST NAME', ASI_CRM_SG_Group_Outlet_Name__c='test 1'));
        insert grpOutletTypeList;
        
        grpOutletType = grpOutletTypeList[0];
        
        system.assert(grpOutletTypeList[0].Id<>null);
        
        List<ASI_CRM_Pros_Segmentation__c>  proSegmentationList = new List<ASI_CRM_Pros_Segmentation__c>();
        proSegmentationList = ASI_CRM_TH_TestClassUtilityHelperPROS.createProsSegmentation(1, 'ASI_CRM_TH_PROS_Segmentation', 'THB', accASIList.Id, null, null, null, null);
        insert proSegmentationList;
        
        system.assert(proSegmentationList[0].Id<>null);
        
        prosSegmentation = proSegmentationList[0];
        
        List<ASI_CRM_Criteria_Set__c> criteriaSetList = new List<ASI_CRM_Criteria_Set__c>();
        criteriaSetList = ASI_CRM_TH_TestClassUtilityHelperPROS.createCriteriaSet(1, 'ASI_CRM_TH_Image_Level_Criteria');
        insert criteriaSetList;
        
        system.assert(criteriaSetList[0].Id<>null);
        
        List<ASI_CRM_Criteria_Threshold__c> criteriaThresholdList = new List<ASI_CRM_Criteria_Threshold__c>();
        criteriaThresholdList = ASI_CRM_TH_TestClassUtilityHelperPROS.createCriteriaThreshold(1, 'ASI_CRM_TH_Picklist', criteriaSetList[0].Id);

        insert criteriaThresholdList;
        
        system.assert(proSegmentationList[0].Id<>null);
        
        criteriaThreshold = criteriaThresholdList[0];
        
        
    }
    static testmethod void dataInsert2(){
        
        List<ASI_CRM_AccountsAdditionalField__c> accASIList = new List<ASI_CRM_AccountsAdditionalField__c>();
        Account acc = new Account(Name='TestAccount', RecordTypeId = Global_RecordTypeCache.getRTId('AccountASI_TH_CRM_Outlet'));     
        insert acc;
        
        ASI_CRM_CN_Channel__c ch = new ASI_CRM_CN_Channel__c();
        ch.ASI_CRM_CN_Channel_Chi_Name__c = 'Channel';
        insert ch;
        
        ASI_MFM_Sub_Channel__c sc = new ASI_MFM_Sub_Channel__c();
        sc.ASI_CRM_CN_Channel__c = ch.id;
        insert sc;
        
        ASI_TH_CRM_OutletType__c ot = new ASI_TH_CRM_OutletType__c();
        ot.ASI_CRM_Sub_Channel__c = sc.id;
        insert ot;
          
        accASIList.add(new ASI_CRM_AccountsAdditionalField__c(Name = 'Test', RecordTypeId = Global_RecordTypeCache.getRTId('ASI_CRM_AccountsAdditionalField__cASI_TH_CRM_Outlet'),
                                                         ASI_CRM_Account__c = acc.id, ASI_TH_CRM_OutletType__c = ot.id, ASI_CRM_Region__c = 'Second Tier'));
        insert accASIList;
        
        system.assert(accASIList[0].Id<>null);
        
        List<ASI_CRM_Group_Outlet_Type__c> grpOutletTypeList = new List<ASI_CRM_Group_Outlet_Type__c>();
        grpOutletTypeList = ASI_CRM_TH_TestClassUtilityHelperPROS.createGroupOutletType(1, 'ASI_CRM_TH_Group_Outlet_Type', 'THB', null, null);
        insert grpOutletTypeList;
        
        grpOutletType = grpOutletTypeList[0];
        
        system.assert(grpOutletTypeList[0].Id<>null);
        
        List<ASI_CRM_Pros_Segmentation__c>  proSegmentationList = new List<ASI_CRM_Pros_Segmentation__c>();
        proSegmentationList = ASI_CRM_TH_TestClassUtilityHelperPROS.createProsSegmentation(1, 'ASI_CRM_TH_PROS_Segmentation', 'THB', accASIList[0].Id, null, null, null, null);
        insert proSegmentationList;
        
        system.assert(proSegmentationList[0].Id<>null);
        
        prosSegmentation2 = proSegmentationList[0];
        
        List<ASI_CRM_Criteria_Set__c> criteriaSetList = new List<ASI_CRM_Criteria_Set__c>();
        criteriaSetList = ASI_CRM_TH_TestClassUtilityHelperPROS.createCriteriaSet(1, 'ASI_CRM_TH_Image_Level_Criteria');
        insert criteriaSetList;
        
        system.assert(criteriaSetList[0].Id<>null);
        
        List<ASI_CRM_Criteria_Threshold__c> criteriaThresholdList = new List<ASI_CRM_Criteria_Threshold__c>();
        criteriaThresholdList = ASI_CRM_TH_TestClassUtilityHelperPROS.createCriteriaThreshold(1, 'ASI_CRM_TH_Picklist', criteriaSetList[0].Id);

        insert criteriaThresholdList;
        
        system.assert(proSegmentationList[0].Id<>null);
        
        criteriaThreshold2 = criteriaThresholdList[0];
        
        
    }
    static testmethod void testHandler1(){
        //AFTER INSERT
        Test.startTest();
        dataInsert();
        prosSegmentation = [Select Id, Name from ASI_CRM_Pros_Segmentation__c where Id =: prosSegmentation.Id];
        System.debug('@@PROSSEGCOUNTRY: '+prosSegmentation);
        List<ASI_CRM_Pros_Volume_Potential__c> prosVolPotentialList = new List<ASI_CRM_Pros_Volume_Potential__c>();
        prosVolPotentialList = ASI_CRM_TH_TestClassUtilityHelperPROS.createProsVolumePotential(1, 'ASI_CRM_TH_Pros_Volume_Potential', 'THB', prosSegmentation.Id, criteriaThreshold.Id);

        insert prosVolPotentialList;
        
        system.assert(prosVolPotentialList[0].Id<>null);
        
        Test.stopTest();
    }
    static testmethod void testHandler2(){
        //AFTER INSERT
        Test.startTest();
        dataInsert2();
        prosSegmentation2 = [Select Id, Name from ASI_CRM_Pros_Segmentation__c where Id =: prosSegmentation2.Id];
        System.debug('@@PROSSEGCOUNTRY: '+prosSegmentation2);
        List<ASI_CRM_Pros_Volume_Potential__c> prosVolPotentialList = new List<ASI_CRM_Pros_Volume_Potential__c>();
        prosVolPotentialList = ASI_CRM_TH_TestClassUtilityHelperPROS.createProsVolumePotential(1, 'ASI_CRM_TH_Pros_Volume_Potential', 'THB', prosSegmentation2.Id, criteriaThreshold2.Id);

        insert prosVolPotentialList;
        
        system.assert(prosVolPotentialList[0].Id<>null);
        
        Test.stopTest();
    }
    static testmethod void testHandler3(){
        //AFTER UPDATE
        
        dataInsert();
        prosSegmentation = [Select Id, Name from ASI_CRM_Pros_Segmentation__c where Id =: prosSegmentation.Id];
        System.debug('@@PROSSEGCOUNTRY: '+prosSegmentation);
        List<ASI_CRM_Pros_Volume_Potential__c> prosVolPotentialList = new List<ASI_CRM_Pros_Volume_Potential__c>();
        prosVolPotentialList = ASI_CRM_TH_TestClassUtilityHelperPROS.createProsVolumePotential(1, 'ASI_CRM_TH_Pros_Volume_Potential', 'THB', prosSegmentation.Id, criteriaThreshold.Id);

        insert prosVolPotentialList;
        
        system.assert(prosVolPotentialList[0].Id<>null);
        Test.startTest();
        update prosVolPotentialList;
        Test.stopTest();
    }
    static testmethod void testHandler4(){
        //AFTER UPDATE
        
        dataInsert2();
        prosSegmentation2 = [Select Id, Name from ASI_CRM_Pros_Segmentation__c where Id =: prosSegmentation2.Id];
        System.debug('@@PROSSEGCOUNTRY: '+prosSegmentation2);
        List<ASI_CRM_Pros_Volume_Potential__c> prosVolPotentialList = new List<ASI_CRM_Pros_Volume_Potential__c>();
        prosVolPotentialList = ASI_CRM_TH_TestClassUtilityHelperPROS.createProsVolumePotential(1, 'ASI_CRM_TH_Pros_Volume_Potential', 'THB', prosSegmentation2.Id, criteriaThreshold2.Id);

        insert prosVolPotentialList;
        
        system.assert(prosVolPotentialList[0].Id<>null);
        Test.startTest();
        update prosVolPotentialList;
        Test.stopTest();
    }
    
}