objects/ASI_CRM_Payment_Invoice__c.object
<CustomObject>
    <description>ASI CRM JP - Payment Invoice</description>
    <label>Payment Invoice</label>
    <nameField>
        <label>Payment Invoice Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Payment_Invoice_Line_Item__c.object
<CustomObject>
    <description>ASI CRM JP - Payment Invoice Line</description>
    <fields>
        <fullName>ASI_CRM_AP_Code__c</fullName>
        <label>AP Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Contract_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract No.</label>
        <referenceTo>ASI_CRM_Purchase_Contract__c</referenceTo>
        <relationshipLabel>Payment Invoice Line Items</relationshipLabel>
        <relationshipName>Payment_Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <label>Item Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Payment_Invoice_Item_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Payment_Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Payment_Invoice__c</fullName>
        <label>Payment Invoice</label>
        <referenceTo>ASI_CRM_Payment_Invoice__c</referenceTo>
        <relationshipLabel>Payment Invoice Line Items</relationshipLabel>
        <relationshipName>Payment_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Purchase_Contract_Line_Item__c</fullName>
        <label>Contract Line</label>
        <referenceTo>ASI_CRM_Purchase_Contract_Line_Item__c</referenceTo>
        <relationshipLabel>Payment Invoice Line Items</relationshipLabel>
        <relationshipName>Payment_Invoice_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ASI_CRM_Representative_SKU_Code__c</fullName>
        <label>2nd Item Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU_Selection__c</fullName>
        <label>SKU Selection</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Representative SKU</fullName>
                    <default>true</default>
                    <label>Representative SKU</label>
                </value>
                <value>
                    <fullName>Alternative SKU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Payment Invoice Line Items</relationshipLabel>
        <relationshipName>Payment_Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Invoice Line Item</label>
    <nameField>
        <displayFormat>PIL{000000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Invoice Line Items</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_JP_SPTD_Cash_Invoice_Line_Item</fullName>
        <active>true</active>
        <label>JP SPTD Cash Invoice Line Item</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_JP_SPTD_FOC_Invoice_Line_Item</fullName>
        <active>true</active>
        <label>JP SPTD FOC Invoice Line Item</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_Purchase_Contract__c.object
<CustomObject>
    <description>ASI CRM JP - Purchase Contract</description>
    <label>Purchase Contract</label>
    <nameField>
        <label>Contract No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Purchase_Contract_Line_Item__c.object
<CustomObject>
    <description>ASI CRM JP - Purchase Contract Line</description>
    <fields>
        <fullName>ASI_CRM_AP_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>A&amp;P Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ASI_MFM_AP_Code__c.ASI_MFM_Inactive__c</field>
                <operation>notEqual</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_AP_Code__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>CRM JP AP Code</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_AP_Code__c</referenceTo>
        <relationshipLabel>Purchase Contract Line Items</relationshipLabel>
        <relationshipName>Purchase_Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ASI_MFM_Item_Group__c.ASI_CRM_CN_Not_In_Use__c</field>
                <operation>notEqual</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Item_Group__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>JP CRM Item Group</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Purchase Contract Line Items</relationshipLabel>
        <relationshipName>Purchase_Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Purchase_Contract__c</fullName>
        <label>Purchase Contract</label>
        <referenceTo>ASI_CRM_Purchase_Contract__c</referenceTo>
        <relationshipLabel>Purchase Contract Line Items</relationshipLabel>
        <relationshipName>Purchase_Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Purchase Contract Line Item</label>
    <nameField>
        <displayFormat>PCL{00000000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_AP_Code__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Exclusive_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclusive Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>AP Code</label>
    <nameField>
        <label>AP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Item_Group__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Alternative_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Alternative SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Item Groups (Alternative SKU)</relationshipLabel>
        <relationshipName>Item_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Representative_SKU_Code__c</fullName>
        <label>Representative SKU (Indirect)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Representative_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Representative SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Item Groups</relationshipLabel>
        <relationshipName>Item_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item Group</label>
    <nameField>
        <label>Item Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_JP_PaymentInvoiceItemTgrHdlr.cls
/*********************************************************************************
 * Name:ASI_CRM_JP_PaymentInvoiceItemTgrHdlr
 * Description: Payment Invoice Line Item Trigger Handler for CRM JP
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 20/11/2014       Laputa: Hank          Created
*********************************************************************************/

public with sharing class ASI_CRM_JP_PaymentInvoiceItemTgrHdlr extends ASI_CRM_JP_TriggerAbstract {

    public ASI_CRM_JP_PaymentInvoiceItemTgrHdlr() {
        super('ASI_CRM_JP_PaymentInvoiceItemTgrHdlr');
    }
    
    public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap) {
        
        List<ASI_CRM_Payment_Invoice_Line_Item__c> itemList = (List<ASI_CRM_Payment_Invoice_Line_Item__c>)sObjList;
        Set<Id> contItemIdSet = new Set<Id>();
        Set<Id> itemGroupIdSet = new Set<Id>();
        Set<Id> headerIdSet = new Set<Id>();
        if (oldMap == null) {
            for (ASI_CRM_Payment_Invoice_Line_Item__c item: itemList) {
                if (Global_RecordTypeCache.getRt(item.recordTypeid).developerName.contains('ASI_CRM_JP_SPTD_Cash_Invoice_Line_Item') ||
                    Global_RecordTypeCache.getRt(item.recordTypeid).developerName.contains('ASI_CRM_JP_SPTD_FOC_Invoice_Line_Item')) {
                    item.ASI_CRM_Payment_Invoice_Item_Owner__c = UserInfo.getUserId();
                }
                if (Global_RecordTypeCache.getRt(item.recordTypeid).developerName.contains('FOC') && !headerIdSet.Contains(item.ASI_CRM_Payment_Invoice__c)) {
                    headerIdSet.add(item.ASI_CRM_Payment_Invoice__c);
                }
                contItemIdSet.add(item.ASI_CRM_Purchase_Contract_Line_Item__c);
            }
        }
        else {
            Map<ID, ASI_CRM_Payment_Invoice_Line_Item__c> oldItemMap = (Map<ID, ASI_CRM_Payment_Invoice_Line_Item__c>) oldMap;
            for (ASI_CRM_Payment_Invoice_Line_Item__c item: itemList) {
                if (item.ASI_CRM_Purchase_Contract_Line_Item__c != oldItemMap.get(item.id).ASI_CRM_Purchase_Contract_Line_Item__c || 
                        item.ASI_CRM_SKU_Selection__c != oldItemMap.get(item.id).ASI_CRM_SKU_Selection__c) {
                    contItemIdSet.add(item.ASI_CRM_Purchase_Contract_Line_Item__c);
                }
                if (item.ASI_CRM_Purchase_Contract_Line_Item__c != oldItemMap.get(item.id).ASI_CRM_Purchase_Contract_Line_Item__c && 
                        Global_RecordTypeCache.getRt(item.recordTypeid).developerName.contains('FOC') && !headerIdSet.Contains(item.ASI_CRM_Payment_Invoice__c)) {
                    headerIdSet.add(item.ASI_CRM_Payment_Invoice__c);
                }
            }
        }
        Map<Id, ASI_CRM_Purchase_Contract_Line_Item__c> contItemMap = new Map<Id, ASI_CRM_Purchase_Contract_Line_Item__c>([Select ASI_CRM_Purchase_Contract__c, 
                                                                                                                                  ASI_CRM_Item_Group__c,
                                                                                                                                  ASI_CRM_Item_Group__r.ASI_CRM_Representative_SKU__c,
                                                                                                                                  ASI_CRM_AP_Code__r.ASI_CRM_Exclusive_Flag__c,
                                                                                                                                  ASI_CRM_Item_Group__r.ASI_CRM_Alternative_SKU__c
                                                                                                                                  From ASI_CRM_Purchase_Contract_Line_Item__c 
                                                                                                                                  Where Id In :contItemIdSet]);
        Map<Id, ASI_CRM_Payment_Invoice__c> paymentMap = new Map<Id, ASI_CRM_Payment_Invoice__c>([Select Id,
                                                                                                         (Select ASI_CRM_Purchase_Contract_Line_Item__r.ASI_CRM_AP_Code__r.ASI_CRM_Exclusive_Flag__c
                                                                                                          From Payment_Invoice_Lines__r)
                                                                                                  From ASI_CRM_Payment_Invoice__c
                                                                                                  Where Id In :headerIdSet]);
        for(ASI_CRM_Purchase_Contract_Line_Item__c item:contItemMap.values()){
            itemGroupIdSet.add(item.ASI_CRM_Item_Group__c);    
        }
        Map<Id, String> skuMap = new Map<Id, String>();
        for(ASI_MFM_Item_Group__c grp:[Select Id, ASI_CRM_Representative_SKU_Code__c From ASI_MFM_Item_Group__c Where Id In :itemGroupIdSet]){
            skuMap.put(grp.Id, grp.ASI_CRM_Representative_SKU_Code__c);    
        }
        if (oldMap == null) {
            Boolean previousAP = null;
            for (ASI_CRM_Payment_Invoice_Line_Item__c item: itemList) {
                item.ASI_CRM_Contract_No__c = contItemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_Purchase_Contract__c;
                item.ASI_CRM_Representative_SKU_Code__c = skuMap.get(contItemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_Item_Group__c);
                if(item.ASI_CRM_SKU_Selection__c == 'Representative SKU'){
                    item.ASI_CRM_SKU__c = contItemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_Item_Group__r.ASI_CRM_Representative_SKU__c;
                }else if(item.ASI_CRM_SKU_Selection__c == 'Alternative SKU'){
                    item.ASI_CRM_SKU__c = contItemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_Item_Group__r.ASI_CRM_Alternative_SKU__c;
                }
                if(Global_RecordTypeCache.getRt(item.recordTypeid).developerName.contains('FOC') && !checkFocAPCode(item.ASI_CRM_Payment_Invoice__c, paymentMap,item,contItemMap)) {
                    item.addError(System.Label.ASI_CRM_JP_APCodeError);
                    break;
                }
                if(previousAP == null){
                    previousAP = contItemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_AP_Code__r.ASI_CRM_Exclusive_Flag__c;
                }else if(previousAP != contItemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_AP_Code__r.ASI_CRM_Exclusive_Flag__c){
                    item.addError(System.Label.ASI_CRM_JP_APCodeError);
                    break;
                }
            }
        }
        else {
            Map<ID, ASI_CRM_Payment_Invoice_Line_Item__c> oldItemMap = (Map<ID, ASI_CRM_Payment_Invoice_Line_Item__c>) oldMap;
            Boolean previousAP = null;
            for (ASI_CRM_Payment_Invoice_Line_Item__c item: itemList) {
                if (item.ASI_CRM_Purchase_Contract_Line_Item__c != oldItemMap.get(item.id).ASI_CRM_Purchase_Contract_Line_Item__c) {
                    item.ASI_CRM_Contract_No__c = contItemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_Purchase_Contract__c;    
                }
                if(item.ASI_CRM_SKU_Selection__c != oldItemMap.get(item.id).ASI_CRM_SKU_Selection__c ||
                        item.ASI_CRM_Purchase_Contract_Line_Item__c != oldItemMap.get(item.id).ASI_CRM_Purchase_Contract_Line_Item__c){
                    if(item.ASI_CRM_SKU_Selection__c == 'Representative SKU'){
                        item.ASI_CRM_SKU__c = contItemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_Item_Group__r.ASI_CRM_Representative_SKU__c;
                    }else if(item.ASI_CRM_SKU_Selection__c == 'Alternative SKU'){
                        item.ASI_CRM_SKU__c = contItemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_Item_Group__r.ASI_CRM_Alternative_SKU__c;
                    }
                }
                if (item.ASI_CRM_Purchase_Contract_Line_Item__c != oldItemMap.get(item.id).ASI_CRM_Purchase_Contract_Line_Item__c && 
                        Global_RecordTypeCache.getRt(item.recordTypeid).developerName.contains('FOC') && 
                        !checkFocAPCode(item.ASI_CRM_Payment_Invoice__c, paymentMap,item,contItemMap)) {
                    item.addError(System.Label.ASI_CRM_JP_APCodeError);
                    break;
                }
                if (item.ASI_CRM_Purchase_Contract_Line_Item__c != oldItemMap.get(item.id).ASI_CRM_Purchase_Contract_Line_Item__c && 
                        Global_RecordTypeCache.getRt(item.recordTypeid).developerName.contains('FOC') && !headerIdSet.Contains(item.ASI_CRM_Payment_Invoice__c)) {
                    if(previousAP == null){
                        previousAP = contItemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_AP_Code__r.ASI_CRM_Exclusive_Flag__c;
                    }else if(previousAP != contItemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_AP_Code__r.ASI_CRM_Exclusive_Flag__c){
                        item.addError(System.Label.ASI_CRM_JP_APCodeError);
                        break;
                    }
                }
            }
        }
    }
    
    Public Boolean checkFocAPCode(Id pmtID, Map<Id, ASI_CRM_Payment_Invoice__c> pmtMap,ASI_CRM_Payment_Invoice_Line_Item__c item,Map<Id, ASI_CRM_Purchase_Contract_Line_Item__c> itemMap){
        Boolean previousApCode = null;
        system.debug('Line List: ' + pmtMap.get(pmtId).Payment_Invoice_Lines__r);
        for(ASI_CRM_Payment_Invoice_Line_Item__c pmt:pmtMap.get(pmtId).Payment_Invoice_Lines__r){
            if(previousApCode == null){
                previousApCode = pmt.ASI_CRM_Purchase_Contract_Line_Item__r.ASI_CRM_AP_Code__r.ASI_CRM_Exclusive_Flag__c;
            }else if(previousApCode != pmt.ASI_CRM_Purchase_Contract_Line_Item__r.ASI_CRM_AP_Code__r.ASI_CRM_Exclusive_Flag__c){
                return false;
            }
        }
        if(previousApCode != null && previousApCode != itemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_AP_Code__r.ASI_CRM_Exclusive_Flag__c){
            system.debug('Previous: ' + previousApCode + ' Current: ' + itemMap.get(item.ASI_CRM_Purchase_Contract_Line_Item__c).ASI_CRM_AP_Code__r.ASI_CRM_Exclusive_Flag__c);
            return false;
        }
        return true;
    }
}