objects/ASI_CRM_CN_T1_Price__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Item_Group__c</fullName>
        <label>Item Group</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>T1 Price</relationshipLabel>
        <relationshipName>T1_Price</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_T1_Price__c</fullName>
        <label>T1 Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>T1 Price</label>
    <nameField>
        <displayFormat>T1P-{0000000}</displayFormat>
        <label>T1 Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T1 Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_T2_Selling_Price__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_TP_Bottle_Size__c</fullName>
        <label>Bottle Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel</label>
        <referenceTo>ASI_CRM_CN_Channel__c</referenceTo>
        <relationshipLabel>CN LPPs</relationshipLabel>
        <relationshipName>ASI_CRM_CN_TP_LPPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_T1_Price__c</fullName>
        <label>T1 Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>T2 Selling Price</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>T2 Selling Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T2 Selling Prices</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_CN_TP_LPP</fullName>
        <active>true</active>
        <description>CN Trade Plan LPP</description>
        <label>ASI_CRM_CN_TP_LPP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Item_Group__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_Converion9L_C__c</fullName>
        <label>Conversion Factor Bottle to 9L</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Bottle_Size__c</fullName>
        <formula>IF( CONTAINS(ASI_CRM_CN_BT_Size_C__c, &apos;cl&apos;) , value( LEFT(ASI_CRM_CN_BT_Size_C__c,  LEN(ASI_CRM_CN_BT_Size_C__c) - 2) ), value(ASI_CRM_CN_BT_Size_C__c))</formula>
        <label>Bottle Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sub_brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-brand</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN New POSM Item Group - Region, CN POSM Item Group, CN New POSM Item Group - HQ</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN FOC Sub-brand</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.ASI_MFM_Active_for_POSM__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>CN New POSM Item Group - Region, CN POSM Item Group, CN New POSM Item Group - HQ</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Sub_brand__c</referenceTo>
        <relationshipLabel>Item Groups</relationshipLabel>
        <relationshipName>Item_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item Group</label>
    <nameField>
        <label>Item Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_CN_CRM_Item_Group</fullName>
        <active>true</active>
        <label>CN CRM Item Group</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_TP_Approval_Step2_Rule1__c</fullName>
        <label>Approval Step2 Rule1</label>
        <summarizedField>ASI_MFM_Plan_Line_Item__c.ASI_CRM_CN_TP_Approval_Step2_Rule1__c</summarizedField>
        <summaryForeignKey>ASI_MFM_Plan_Line_Item__c.ASI_MFM_Plan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Approval_Step2_Rule2__c</fullName>
        <label>Approval Step2 Rule2</label>
        <summarizedField>ASI_MFM_Plan_Line_Item__c.ASI_CRM_CN_TP_Approval_Step2_Rule2__c</summarizedField>
        <summaryForeignKey>ASI_MFM_Plan_Line_Item__c.ASI_MFM_Plan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Approval_Step2_Rule3__c</fullName>
        <label>Approval Step2 Rule3</label>
        <summarizedField>ASI_MFM_Plan_Line_Item__c.ASI_CRM_CN_TP_Approval_Step2_Rule3__c</summarizedField>
        <summaryForeignKey>ASI_MFM_Plan_Line_Item__c.ASI_MFM_Plan__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Approval__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade Plan Approval</label>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>Approval Trade Plans</relationshipLabel>
        <relationshipName>Approval_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Head_Approval_Step2__c</fullName>
        <label>Trade Plan Head Approval Step2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Head_Approval_Step3__c</fullName>
        <label>Trade Plan Head Approval Step3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Complete (CAPEX)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Plan_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_CN_TP_Approval_Step2_Rule1__c</fullName>
        <formula>IF(ASI_CRM_CN_TP_Promotion_Unit_Price__c &lt; ASI_CRM_CN_TP_LPP_Price_App__c, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Step2 Rule1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Approval_Step2_Rule2__c</fullName>
        <formula>IF( NOT(ISBLANK(ASI_CRM_CN_TP_Benchmark__c)) &amp;&amp; ASI_CRM_CN_TP_Plan_Fee_Percent__c &gt;  ASI_CRM_CN_TP_Benchmark__c , 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Step2 Rule2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Approval_Step2_Rule3__c</fullName>
        <formula>IF( ASI_CRM_CN_TP_Estimated_Amount__c &gt; 100000, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Step2 Rule3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Bottle_Size__c</fullName>
        <label>Bottle Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Converion9L__c</fullName>
        <label>Conversion Factor Bottle to 9L</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_Promotion_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion Product</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>Plan Line Items</relationshipLabel>
        <relationshipName>Plan_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_TP_T1_Price__c</fullName>
        <label>T1 Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>ASI_MFM_Plan__c</referenceTo>
        <relationshipLabel>Plan Line Items</relationshipLabel>
        <relationshipName>Plan_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sub_brand_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub-brand Code</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3 AND 4) OR (5 AND 6 AND 7 AND 8) OR (9 AND 10)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>TH Plan Line Item,TW Plan Line Item, MY Plan Line Item</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>TH CRM Sub-brand</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.ASI_MFM_Active_for_MFM__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>TH Plan Line Item</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>TW Sub-brand</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.ASI_TH_CRM_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.ASI_CRM_TW_Company__c</field>
                <operation>equals</operation>
                <value>PRT</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>TW Plan Line Item</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>MY Plan Line Item</value>
            </filterItems>
            <filterItems>
                <field>ASI_MFM_Sub_brand__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>MY Sub brand</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_MFM_Sub_brand__c</referenceTo>
        <relationshipLabel>Plan Line Items</relationshipLabel>
        <relationshipName>Plan_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sub_brand_Name__c</fullName>
        <formula>ASI_MFM_Sub_brand_Code__r.ASI_MFM_Sub_brand_Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub-brand Name</label>
        <type>Text</type>
    </fields>
    <label>Plan Line Item</label>
    <nameField>
        <displayFormat>PLI{000000}</displayFormat>
        <label>Plan Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_Sub_brand__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Sub_brand_Code__c</fullName>
        <label>Sub-brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sub-brand</label>
    <nameField>
        <label>Sub-brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_TP_PlanLineItem_TriggerClass.cls
/**************************************************************************************************
 * Name: ASI_CRM_CN_TP_PlanLineItem_TriggerClass
 * Object: ASI_MFM_Plan_Line_Item__c
 * Purpose: 
 * Author:  (jack yuan)
 * Create Date: 2020-3-18
 * Modify History:
 * 2020-3-18        Create this class
 **************************************************************************************************/
public without sharing class ASI_CRM_CN_TP_PlanLineItem_TriggerClass {

    public static Boolean EXECUTEFLAG = false;
    public static void routineBeforeUpsert(List<ASI_MFM_Plan_Line_Item__c> trigger_new, Map<Id,ASI_MFM_Plan_Line_Item__c> trigger_oldMap) {

        Set<Id> subIdSet = new Set<Id>();
        List<Decimal> bottleSizeList = new List<Decimal>();
        
        for (ASI_MFM_Plan_Line_Item__c planItem : trigger_new) {
            subIdSet.add(planItem.ASI_MFM_Sub_brand_Code__c);
            if (planItem.ASI_CRM_CN_TP_Bottle_Size__c != null) {
                bottleSizeList.add(Decimal.valueOf( planItem.ASI_CRM_CN_TP_Bottle_Size__c));
            }
        }

        // Item group Map
        Map<String, ASI_MFM_Item_Group__c> keyItemGroupMap = new Map<String, ASI_MFM_Item_Group__c>();
        // Set<Id> itemGroupIdSet = new Set<Id>();
        List<ASI_MFM_Item_Group__c> itemGroups = [SELECT ASI_MFM_Sub_brand__c, ASI_CRM_CN_TP_Bottle_Size__c, ASI_CRM_CN_Converion9L_C__c
                                                  FROM ASI_MFM_Item_Group__c
                                                  WHERE ASI_MFM_Sub_brand__c IN :subIdSet
                                                  AND ASI_CRM_CN_TP_Bottle_Size__c IN :bottleSizeList
                                                  AND RecordType.DeveloperName = 'ASI_CRM_CN_CRM_Item_Group'
                                                  ORDER BY CreatedDate DESC];
        for (ASI_MFM_Item_Group__c itemGroup : itemGroups) {
            String subKey = itemGroup.ASI_MFM_Sub_brand__c + '-' + itemGroup.ASI_CRM_CN_TP_Bottle_Size__c;
            if (!keyItemGroupMap.containsKey(subKey)) {
                keyItemGroupMap.put(subKey, itemGroup);
                // itemGroupIdSet.add(itemGroup.Id);
            }
        }
        // System.debug(LoggingLevel.INFO, '*** itemGroupIdSet: ' + itemGroupIdSet);
        // Key t1 price map
        Map<String, Decimal> keyPriceMap = new Map<String, Decimal>();
        List<ASI_CRM_CN_T1_Price__c> t1PriceList = [SELECT ASI_CRM_CN_Item_Group__r.ASI_MFM_Sub_brand__c,
                                                           ASI_CRM_CN_Item_Group__r.ASI_CRM_CN_TP_Bottle_Size__c,
                                                           ASI_CRM_CN_T1_Price__c
                                                    FROM ASI_CRM_CN_T1_Price__c
                                                    WHERE ASI_CRM_CN_Item_Group__r.ASI_MFM_Sub_brand__c IN : subIdSet
                                                    AND ASI_CRM_CN_Item_Group__r.ASI_CRM_CN_TP_Bottle_Size__c IN :bottleSizeList
                                                    AND ASI_CRM_CN_Item_Group__r.RecordType.DeveloperName = 'ASI_CRM_CN_CRM_Item_Group'
                                                    ORDER BY ASI_CRM_CN_Effective_Date__c DESC];
        for (ASI_CRM_CN_T1_Price__c t1Price : t1PriceList) {
            String subKey = t1Price.ASI_CRM_CN_Item_Group__r.ASI_MFM_Sub_brand__c 
                            + '-' + t1Price.ASI_CRM_CN_Item_Group__r.ASI_CRM_CN_TP_Bottle_Size__c;
            if (!keyPriceMap.containsKey(subKey)) {
                keyPriceMap.put(subKey, t1Price.ASI_CRM_CN_T1_Price__c);
            }
        }
        System.debug(LoggingLevel.INFO, '*** keyPriceMap: ' + keyPriceMap);

        // Fill t1 price and related LPP
        for (ASI_MFM_Plan_Line_Item__c planItem : trigger_new) {
            String subKey = '';
            if (planItem.ASI_CRM_CN_TP_Bottle_Size__c != null) {
                subKey = planItem.ASI_MFM_Sub_brand_Code__c + '-' + Decimal.valueOf(planItem.ASI_CRM_CN_TP_Bottle_Size__c).setScale(2);
            }
            System.debug(LoggingLevel.INFO, '*** subKey: ' + subKey);
            if (keyPriceMap.containsKey(subKey) && planItem.ASI_CRM_CN_TP_T1_Price__c == null) {
                planItem.ASI_CRM_CN_TP_T1_Price__c = keyPriceMap.get(subKey);
            }
            if (keyItemGroupMap.containsKey(subKey)) {
                planItem.ASI_CRM_CN_TP_Converion9L__c = keyItemGroupMap.get(subKey) == null ? 0 : keyItemGroupMap.get(subKey).ASI_CRM_CN_Converion9L_C__c;
            }
        }
    }

    public static void routineAfterUpsert(List<ASI_MFM_Plan_Line_Item__c> trigger_new, Map<Id,ASI_MFM_Plan_Line_Item__c> trigger_oldMap) {
        // if (EXECUTEFLAG) return;
        // EXECUTEFLAG = true;
        
         Set<Id> subIdSet = new Set<Id>();
        List<String> bottleSizeList = new List<String>();
        Set<Id> lineItemIdSet = new Set<Id>();
        Set<Id> itemGroupIdSet = new Set<Id>();

        Set<String> upTPIds = new Set<String>();
        Set<Id> tpIds = new Set<Id>();

        for (ASI_MFM_Plan_Line_Item__c planItem : trigger_new) {
            if (trigger_oldMap == null) {
                subIdSet.add(planItem.ASI_MFM_Sub_brand_Code__c);
                bottleSizeList.add(planItem.ASI_CRM_CN_TP_Bottle_Size__c);
                lineItemIdSet.add(planItem.Id);
            } else if (trigger_oldMap != null 
                       && (planItem.ASI_MFM_Sub_brand_Code__c != trigger_oldMap.get(planItem.Id).ASI_MFM_Sub_brand_Code__c
                       || planItem.ASI_CRM_CN_TP_Bottle_Size__c != trigger_oldMap.get(planItem.Id).ASI_CRM_CN_TP_Bottle_Size__c)) {
                subIdSet.add(planItem.ASI_MFM_Sub_brand_Code__c);
                bottleSizeList.add(planItem.ASI_CRM_CN_TP_Bottle_Size__c);
                lineItemIdSet.add(planItem.Id);
            }
            
            if (planItem.ASI_CRM_CN_TP_Promotion_Product__c != null) {
                itemGroupIdSet.add(planItem.ASI_CRM_CN_TP_Promotion_Product__c);
            }
            
            if ((trigger_oldMap != null && (planItem.ASI_CRM_CN_TP_Approval_Step2_Rule1__c != trigger_oldMap.get(planItem.Id).ASI_CRM_CN_TP_Approval_Step2_Rule1__c
                     || planItem.ASI_CRM_CN_TP_Approval_Step2_Rule2__c != trigger_oldMap.get(planItem.Id).ASI_CRM_CN_TP_Approval_Step2_Rule2__c
                     || planItem.ASI_CRM_CN_TP_Approval_Step2_Rule3__c != trigger_oldMap.get(planItem.Id).ASI_CRM_CN_TP_Approval_Step2_Rule3__c))
                    || trigger_oldMap == null) {
                upTPIds.add(planItem.ASI_MFM_Plan__c);
            }
            // Set plan status to draft when plan line item changed
            if (trigger_oldMap != null) {
                List<Schema.FieldSetMember> fieldList = SObjectType.ASI_MFM_Plan_Line_Item__c.FieldSets.ASI_CRM_CN_TP_PlanLineItem_Change.getFields();
                Boolean flag = false;
                for (Schema.FieldSetMember f : fieldList) {
                    if (planItem.get(f.getFieldPath()) != trigger_oldMap.get(planItem.Id).get(f.getFieldPath())) {
                        flag = true;
                        break;
                    }
                }
                if (flag) {
                    tpIds.add(planItem.ASI_MFM_Plan__c);
                }
            }
        }

        // Set plan status to draft when plan line item changed
        List<ASI_MFM_Plan__c> tpList = [SELECT ASI_MFM_Status__c FROM ASI_MFM_Plan__c WHERE Id IN :tpIds];
        for (ASI_MFM_Plan__c tp : tpList) {

            tp.ASI_MFM_Status__c = ASI_CRM_CN_TP_Utils.TPSTATUSDRAFT;
        }
        if (!tpList.isEmpty()) {
            update tpList;
        }
        
        Approval.unlock(tpList, false);

        if (trigger_new[0].ASI_MFM_Sub_brand_Name__c == '999') return;
        
        Set<Id> headIds = new Set<Id>();
        if (!upTPIds.isEmpty()) {
            for (ASI_MFM_Plan__c tp : [SELECT ASI_CRM_CN_TP_Approval__c FROM ASI_MFM_Plan__c WHERE Id IN :upTPIds]) {
                headIds.add(tp.ASI_CRM_CN_TP_Approval__c);
            }
        }
        
        if (!headIds.isEmpty()) {
            // Summary the child tp step2  number
            List<AggregateResult> tplanList = [SELECT ASI_MFM_Plan__r.ASI_CRM_CN_TP_Approval__c headId, 
                                                       sum(ASI_CRM_CN_TP_Approval_Step2_Rule1__c) sumRule1,
                                                       sum(ASI_CRM_CN_TP_Approval_Step2_Rule2__c) sumRule2,
                                                       sum(ASI_CRM_CN_TP_Approval_Step2_Rule3__c) sumRule3 
                                                FROM ASI_MFM_Plan_Line_Item__c
                                                WHERE ASI_MFM_Plan__r.ASI_CRM_CN_TP_Approval__c IN :headIds
                                                AND ASI_MFM_Plan__r.ASI_CRM_CN_TP_Approval__c != null
                                                GROUP BY ASI_MFM_Plan__r.ASI_CRM_CN_TP_Approval__c];
            List<ASI_MFM_Plan__c> headTPList = new List<ASI_MFM_Plan__c>();
            for (AggregateResult tplan : tplanList) {
                ASI_MFM_Plan__c newTPHead = new ASI_MFM_Plan__c(Id = (String)tplan.get('headId'));
                newTPHead.ASI_CRM_CN_TP_Head_Approval_Step2__c = (Decimal)tplan.get('sumRule1') + 
                                                                 (Decimal)tplan.get('sumRule2') + 
                                                                 (Decimal)tplan.get('sumRule3');
                newTPHead.ASI_CRM_CN_TP_Head_Approval_Step3__c = (Decimal)tplan.get('sumRule1');
                headTPList.add(newTPHead);
            }
            System.debug(LoggingLevel.INFO, '*** headTPList: ' + headTPList.size());
            if (!headTPList.isEmpty()) {
                update headTPList;
            }
            
        }
        if (lineItemIdSet.isEmpty()) return;
        List<ASI_MFM_Plan_Line_Item__c> planItemList = [SELECT ASI_MFM_Sub_brand_Code__c, ASI_CRM_CN_TP_Bottle_Size__c,
                                                               ASI_MFM_Plan__r.ASI_CRM_CN_TP_Channel__c,
                                                               ASI_MFM_Plan__r.ASI_CRM_CN_TP_Region__c,
                                                               ASI_CRM_CN_TP_Promotion_Product__c
                                                        FROM ASI_MFM_Plan_Line_Item__c
                                                        WHERE Id IN :lineItemIdSet];

        // LPP Map
        Map<String, ASI_CRM_T2_Selling_Price__c> keyLPPIdMap = new Map<String, ASI_CRM_T2_Selling_Price__c>();
        System.debug(LoggingLevel.INFO, '*** subIdSet: ' + subIdSet.size());
        System.debug(LoggingLevel.INFO, '*** bottleSizeList: ' + bottleSizeList.size());
        List<ASI_CRM_T2_Selling_Price__c> lppList = [SELECT ASI_CRM_CN_TP_Sub_Brand__c,
                                                            ASI_CRM_CN_TP_Bottle_Size__c,
                                                            ASI_CRM_CN_TP_LPP_Price__c,
                                                            ASI_CRM_CN_TP_Region__c,
                                                            ASI_CRM_CN_TP_Channel__c,
                                                            ASI_CRM_CN_TP_Benchmark__c,
                                                            ASI_CRM_CN_TP_T1_Price__c,
                                                            ASI_CRM_Item_Group__c
                                                    FROM ASI_CRM_T2_Selling_Price__c
                                                    WHERE ((ASI_CRM_CN_TP_Sub_Brand__c IN :subIdSet AND ASI_CRM_CN_TP_Bottle_Size__c IN :bottleSizeList)
                                                            OR ASI_CRM_Item_Group__c IN :itemGroupIdSet)
                                                    AND RecordType.DeveloperName = 'ASI_CRM_CN_TP_LPP'];
        System.debug(LoggingLevel.INFO, '*** lppList: ' + lppList.size());
        for (ASI_CRM_T2_Selling_Price__c lpp : lppList) {
            // String subKey = lpp.ASI_CRM_CN_TP_Sub_Brand__c + '-' + lpp.ASI_CRM_CN_TP_Bottle_Size__c + '-' + lpp.ASI_CRM_CN_TP_Region__c + '-' + lpp.ASI_CRM_CN_TP_Channel__c;
            String subKey = lpp.ASI_CRM_CN_TP_Sub_Brand__c + '-' + lpp.ASI_CRM_CN_TP_Bottle_Size__c;
            if (lpp.ASI_CRM_Item_Group__c != null) {
                subKey = lpp.ASI_CRM_Item_Group__c;
            }
            if (!keyLPPIdMap.containsKey(subKey)) {
                keyLPPIdMap.put(subKey, lpp);
            }
        }
        System.debug(LoggingLevel.INFO, '*** keyLPPIdMap: ' + keyLPPIdMap.size());

        for (ASI_MFM_Plan_Line_Item__c planItem : planItemList) {
            // String subKey = planItem.ASI_MFM_Sub_brand_Code__c + '-' + 
            //                 planItem.ASI_CRM_CN_TP_Bottle_Size__c + '-' + 
            //                 planItem.ASI_MFM_Plan__r.ASI_CRM_CN_TP_Region__c + '-' + 
            //                 planItem.ASI_MFM_Plan__r.ASI_CRM_CN_TP_Channel__c;
            String subKey = planItem.ASI_MFM_Sub_brand_Code__c + '-' + 
                            planItem.ASI_CRM_CN_TP_Bottle_Size__c;
            if (planItem.ASI_CRM_CN_TP_Promotion_Product__c != null) {
                subKey = planItem.ASI_CRM_CN_TP_Promotion_Product__c;
            }
            System.debug(LoggingLevel.INFO, '*** subKey: ' + subKey);
            if (keyLPPIdMap.containsKey(subKey)) {
                planItem.ASI_CRM_CN_TP_LPP__c = keyLPPIdMap.get(subKey).Id;
                planItem.ASI_CRM_CN_TP_LPP_Price_App__c = keyLPPIdMap.get(subKey).ASI_CRM_CN_TP_LPP_Price__c;
                planItem.ASI_CRM_CN_TP_Benchmark__c = keyLPPIdMap.get(subKey).ASI_CRM_CN_TP_Benchmark__c;
                if (keyLPPIdMap.get(subKey).ASI_CRM_CN_TP_T1_Price__c != null) {
                    planItem.ASI_CRM_CN_TP_T1_Price__c = keyLPPIdMap.get(subKey).ASI_CRM_CN_TP_T1_Price__c;
                }
                
            }
        }
        if (!planItemList.isEmpty()) {
            update planItemList;
        }
        
    }

}