objects/ASI_TH_CRM_Contract__c.object
<CustomObject>
    <description>ASI TH CRM Contract</description>
    <fields>
        <fullName>ASI_TH_CRM_Contract_Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Editing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>New Contract</fullName>
                </value>
                <value>
                    <fullName>Renewal Contract</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Contract Approved</fullName>
                </value>
                <value>
                    <fullName>Contract Rejected</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>SM Approved</fullName>
                </value>
                <value>
                    <fullName>HF Approved</fullName>
                </value>
                <value>
                    <fullName>Mktg Approved</fullName>
                </value>
                <value>
                    <fullName>MD Approved</fullName>
                </value>
                <value>
                    <fullName>GCMD Approved</fullName>
                </value>
                <value>
                    <fullName>Proposal Approved</fullName>
                </value>
                <value>
                    <fullName>Proposal Rejected</fullName>
                </value>
                <value>
                    <fullName>Proposal Converted</fullName>
                </value>
                <value>
                    <fullName>Terminate</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_SG_Complete_Contract_Light_test.cls
@isTest
public class ASI_CRM_SG_Complete_Contract_Light_test {
     @testSetup    
    Public static void testData(){
          Profile p1 = [Select Id from profile where Name = 'System Administrator' limit 1];
        User u1 = new User(Alias = 'newUser', Email='newuser@testorg.com', 
         EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
         LocaleSidKey='en_US',  ProfileId = p1.Id,
         TimeZoneSidKey='America/Los_Angeles', UserName='CaseAR@mail.com.ctr');
         insert u1;
        
    }
    
    public static testMethod void test1(){
        ASI_CRM_SG_Archive_Contract_Ctrl_Test.createTestContractData();
         ASI_TH_CRM_Contract__c contract = [Select Id from ASI_TH_CRM_Contract__c limit 1];       
        test.startTest();
            ASI_CRM_SG_Complete_Contract_Light_Ctrl.validateComplete(contract.Id);
         contract.ASI_TH_CRM_Contract_Status__c = 'Contract Approved';
        update contract;
        ASI_CRM_SG_Complete_Contract_Light_Ctrl.validateComplete(contract.Id);
            String userId = Userinfo.getUserId();
        User u1 = [Select Id from user where UserName='CaseAR@mail.com.ctr' limit 1];
        contract.ownerId = u1.Id;
        
        update contract;
         ASI_CRM_SG_Complete_Contract_Light_Ctrl.validateComplete(contract.Id);
       
        test.stopTest();
    }
}