objects/ASI_MFM_Event__c.object
<CustomObject>
    <description>ASI_MFM_Event
Promotion/marketing events for outlet</description>
    <fields>
        <fullName>ASI_MFM_CN_Completed_Outlet__c</fullName>
        <label>Completed Outlet</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Event_Outlet__c.object
<CustomObject>
    <description>ASI_MFM_Event_Outlet
To indicate the outlets selected for a event</description>
    <fields>
        <fullName>ASI_CRM_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>ASI_CRM_EventOutlet_Customer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Completed__c</fullName>
        <formula>OR(today()&gt; ASI_MFM_End_Date__c, AND(year(today())=year(ASI_MFM_End_Date__c), month(today())=month(ASI_MFM_End_Date__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Event__c</fullName>
        <label>Event</label>
        <referenceTo>ASI_MFM_Event__c</referenceTo>
        <relationshipLabel>Event Outlets</relationshipLabel>
        <relationshipName>Event_Outlets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Outlet</label>
    <nameField>
        <displayFormat>EVENT-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Outlets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_MFM_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Sub_brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-brand</label>
        <referenceTo>ASI_MFM_Sub_brand__c</referenceTo>
        <relationshipName>SKU_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_Sub_brand__c.object
<CustomObject>
    <label>Sub-brand</label>
    <nameField>
        <label>Sub-brand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c.object
<CustomObject>
    <description>ASI_TH_CRM_Stock_In_Trade_Detail</description>
    <fields>
        <fullName>ASI_CRM_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Offtake/Stock-in-Trade Details</relationshipLabel>
        <relationshipName>Offtake_Stock_in_Trade_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Offtake/Stock-in-Trade Details</relationshipLabel>
        <relationshipName>Offtake_Stock_in_Trade_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Offtake/Stock-in-Trade Detail</label>
    <nameField>
        <displayFormat>SIT-{00000}-TH</displayFormat>
        <label>SITD No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offtake/Stock-in-Trade Details</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_SG_WS_Depletion</fullName>
        <active>true</active>
        <label>ASI_CRM_SG_WS_Depletion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_6AM_Schd_Test.cls
/*********************************************************************************
 * Name:ASI_CRM_6AM_Schd_Test
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------
 * 2018-07-27       Calvin Chiu (LAPUTA)    Created
*********************************************************************************/
@isTest
public class ASI_CRM_6AM_Schd_Test {
	static testMethod void TestSchedulableClass() {
        
        Id customerRecTypeId = Schema.SObjectType.ASI_CRM_AccountsAdditionalField__c
                                     .getRecordTypeInfosByName()
                                     .get('Wholesaler (SG)').getRecordTypeId();

        ASI_CRM_AccountsAdditionalField__c testCustomer1 =  new ASI_CRM_AccountsAdditionalField__c(
            Name = 'Testcompany',
            RecordTypeId = customerRecTypeId
        );

        ASI_CRM_AccountsAdditionalField__c testCustomer2 =  new ASI_CRM_AccountsAdditionalField__c(
            Name = 'Testcustomer',
            RecordTypeId = customerRecTypeId
        );
        
        ASI_CRM_AccountsAdditionalField__c testCustomer3 =  new ASI_CRM_AccountsAdditionalField__c(
            Name = 'Testcustomer',
            RecordTypeId = customerRecTypeId
        );

        insert new List<ASI_CRM_AccountsAdditionalField__c> {testCustomer1, testCustomer2, testCustomer3};

        Id subBrandRecTypeId = Schema.SObjectType.ASI_MFM_Sub_brand__c
                                     .getRecordTypeInfosByName()
                                     .get('SG Sub-brand').getRecordTypeId();

        ASI_MFM_Sub_brand__c testSubBrand1 = new ASI_MFM_Sub_brand__c(
            RecordTypeId = subBrandRecTypeId,
            Name = 'TestSubBrand1'
        );
        
        ASI_MFM_Sub_brand__c testSubBrand2 = new ASI_MFM_Sub_brand__c(
            RecordTypeId = subBrandRecTypeId,
            Name = 'TestSubBrand2'
        );

        insert new List<ASI_MFM_Sub_brand__c> {testSubBrand1, testSubBrand2};

        Id skuRecTypeId = Schema.SObjectType.ASI_MFM_SKU_Code__c
                                .getRecordTypeInfosByName()
                                .get('SG SKU').getRecordTypeId();

        ASI_MFM_SKU_Code__c testSku1 = new ASI_MFM_SKU_Code__c(
            RecordTypeId = skuRecTypeId,
            Name = 'Test-Sku-123'
        );
        
        ASI_MFM_SKU_Code__c testSku2 = new ASI_MFM_SKU_Code__c(
            RecordTypeId = skuRecTypeId,
            Name = 'Test-Sku-456'
        );
        
        ASI_MFM_SKU_Code__c testSku3 = new ASI_MFM_SKU_Code__c(
            RecordTypeId = skuRecTypeId,
            Name = 'Test-Sku-456'
        );

        insert new List<ASI_MFM_SKU_Code__c> {testSku1, testSku2, testSku3};

        Id wsDepletionRecTypeId = Schema.SObjectType.ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c
                                        .getRecordTypeInfosByName()
                                        .get('ASI_CRM_SG_WS_Depletion').getRecordTypeId();

        ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c testWsDepletion1 =
            new ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c(
                RecordTypeId = wsDepletionRecTypeId,
                ASI_CRM_Customer__c = testCustomer1.Id,
                ASI_CRM_SKU__c = testSku1.Id,
                ASI_TH_CRM_Date__c = Date.today().addMonths(-2)
            );
            
        ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c testWsDepletion2 =
            new ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c(
                RecordTypeId = wsDepletionRecTypeId,
                ASI_CRM_Customer__c = testCustomer1.Id,
                ASI_CRM_SKU__c = testSku2.Id,
                ASI_TH_CRM_Date__c = Date.today().addMonths(-1)
            );

        ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c testWsDepletion3 =
            new ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c(
                RecordTypeId = wsDepletionRecTypeId,
                ASI_CRM_Customer__c = testCustomer2.Id,
                ASI_CRM_SKU__c = testSku2.Id,
                ASI_TH_CRM_Date__c = Date.today().addMonths(-1)
            );

        ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c testWsDepletion4 =
            new ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c(
                RecordTypeId = wsDepletionRecTypeId,
                ASI_CRM_Customer__c = testCustomer1.Id,
                ASI_CRM_SKU__c = testSku3.Id,
                ASI_TH_CRM_Date__c = Date.today().addMonths(-1)
            );

        insert new List<ASI_TH_CRM_Offtake_Stock_In_Trade_Detail__c> {
            testWsDepletion1, testWsDepletion2, testWsDepletion3, testWsDepletion4};

        String CNEventRecID = Global_RecordTypeCache.getRtId('ASI_MFM_Event__cASI_MFM_CN_Event');
        List<ASI_MFM_Event__c> evt_list = [Select id, name, ASI_MFM_CN_Completed_Outlet__c, 
            	(select id, name, ASI_MFM_Completed__c from ASI_MFM_Event__c.Event_Outlets__r) 
            	from ASI_MFM_Event__c where recordtypeid = :CNEventRecID];
        
        Test.startTest(); // Start Test
    	// Schedule the test job
        Datetime dt = Datetime.now().addMinutes(1);
        String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
        
        String jobId = System.schedule('My batch Job',
                         CRON_EXP, 
                         new ASI_CRM_6AM_Schd());
        
        // To track the progress of the scheduled job.
        CronTrigger ct = [SELECT TimesTriggered
                               , NextFireTime
                               , CronExpression
                            FROM CronTrigger 
                           WHERE Id = :jobId];

        ASI_MFM_EventCompleteCalculation cb = New ASI_MFM_EventCompleteCalculation();
        Database.QueryLocator ql = cb.start(null);
        cb.execute(null,evt_list);
        //cb.Finish(null);
        
        // Verify the expressions are the same
        System.assertEquals(CRON_EXP,
                            ct.CronExpression);
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
      	Test.stopTest(); // End Test
    }
}