objects/ASI_MFM_Item_Group__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Item Group</label>
    <nameField>
        <label>Item Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_HK_CRM_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Item_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Group</label>
        <referenceTo>ASI_MFM_Item_Group__c</referenceTo>
        <relationshipLabel>SKUs</relationshipLabel>
        <relationshipName>SKUs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_MFM_HK_Item_Group_TriggerClass.cls
public class ASI_MFM_HK_Item_Group_TriggerClass {

    public static void routineAfterUpdate(list<ASI_MFM_Item_Group__c> trigger_new, map<id, ASI_MFM_Item_Group__c> trigger_oldMap) {
        
        set<id> itemGroup_set = new set<id>();
        for (ASI_MFM_Item_Group__c ig:trigger_new) { 
            if (ig.ASI_CRM_Active__c == false) {
				itemGroup_set.add(ig.id);
            }
        }
        if(itemGroup_set.size()>0){
         	list<ASI_MFM_SKU_Code__c> skuList = new list<ASI_MFM_SKU_Code__c>([select id, ASI_HK_CRM_Active__c from ASI_MFM_SKU_Code__c where ASI_MFM_Item_Group__c in :itemGroup_set]); 
            list<ASI_MFM_SKU_Code__c> skuUpdatedList = new list<ASI_MFM_SKU_Code__c>();
            for(ASI_MFM_SKU_Code__c sku:skuList){
                sku.ASI_HK_CRM_Active__c = false;
                skuUpdatedList.add(sku);
            }
            if(skuUpdatedList.size()>0){
                update skuUpdatedList;
            }
            
        }
        
    }
}