objects/ASI_eForm_IT_Procurement_Service_Item__c.object
<CustomObject>
    <fields>
        <fullName>ASI_eForm_CIO_Approve_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CIO Approve Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_FD_Approve_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FD Approve Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_IT_Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IT Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Invalid Submission</fullName>
                </value>
                <value>
                    <fullName>Procurement In Progress</fullName>
                </value>
                <value>
                    <fullName>Work In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_eForm_IT_Procurement_Service_Request__c</fullName>
        <label>Procurement &amp; Service Request</label>
        <referenceTo>ASI_eForm_IT_Procurement_Service_Request__c</referenceTo>
        <relationshipLabel>Procurement &amp; Service Items</relationshipLabel>
        <relationshipName>IT_Procurement_Service_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Procurement &amp; Service Item</label>
    <nameField>
        <displayFormat>ITPSI-{00000000}</displayFormat>
        <label>Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procurement &amp; Service Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_eForm_IT_Procurement_Service_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASI_eForm_CIO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CIO Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IT_Procurement_Service_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_Finance_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IT_Procurement_Service_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_eForm_IT_Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IT Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Invalid Submission</fullName>
                </value>
                <value>
                    <fullName>Procurement In Progress</fullName>
                </value>
                <value>
                    <fullName>Work In Progress</fullName>
                    <default>true</default>
                    <label>Work In Progress</label>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_eForm_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Procurement &amp; Service Request</label>
    <nameField>
        <displayFormat>ITPSF-{0000000}</displayFormat>
        <label>Form No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Procurement &amp; Service Requests</pluralLabel>
    <recordTypes>
        <fullName>ASI_eForm_HK_Hardware_Software_Request_Final</fullName>
        <active>true</active>
        <label>Hardware &amp; Software Request Final (HK)</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_eForm_HK_IT_Service_Request_Final</fullName>
        <active>true</active>
        <label>IT Service Or Mobile Device Request Final (HK)</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_eForm_ITPSR_TriggerTest.cls
@isTest
private class ASI_eForm_ITPSR_TriggerTest
{

    @isTest
    public static void testITProcServiceItemsAfterUpdate()
    {
      User user = ASI_eForm_TestClassHelper.createUser();
        Map<String,User> userMap = new Map<String,User>();
        userMap.put('owner',user);
        
           ASI_eForm_TestClassHelper.createPrefillCustomSetting();
        ASI_eForm_TestClassHelper.createRouteTypeDetails(userMap);
        
        ASI_eForm_IT_Procurement_Service_Request__c  itpsr =
            ASI_eForm_TestClassHelper.createITPSRServiceRequest(userMap);        
     
      List<ASI_eForm_IT_Procurement_Service_Item__c> itpsrItems =
       ASI_eForm_TestClassHelper.createITPSRServiceRequestItem(itpsr);
        
      itpsr.ASI_eForm_CIO__c = user.Id; 
      itpsr.ASI_eForm_Finance_Director__c= user.Id;      
      RecordType itpsrRTFinal = [SELECT Id from RecordType where DeveloperName = 'ASI_eForm_HK_IT_Service_Request_Final'];
      itpsr.RecordTypeId = itpsrRTFinal.Id;
      itpsr.ASI_eForm_Status__c = 'Final';  
      update itpsr;
      
      itpsrItems.get(0).ASI_eForm_FD_Approve_Required__c =true;        
      itpsrItems.get(0).ASI_eForm_CIO_Approve_Required__c = true;
      itpsrItems.get(0).ASI_eForm_IT_Action__c = 'Invalid Submission';
      update itpsrItems;         
               
    }
    
    @isTest
    public static void testITProcHardwareAfterUpdate()
    {
      ASI_eForm_TestClassHelper.assignToPublicGroup();
      
      User user = ASI_eForm_TestClassHelper.createUser();
        Map<String,User> userMap = new Map<String,User>();
        userMap.put('owner',user);
        
           ASI_eForm_TestClassHelper.createPrefillCustomSetting();
        ASI_eForm_TestClassHelper.createRouteTypeDetails(userMap);
        
        ASI_eForm_IT_Procurement_Service_Request__c  itpsr =
            ASI_eForm_TestClassHelper.createITPSRHardware(userMap);        
     
      List<ASI_eForm_IT_Procurement_Service_Item__c> itpsrItems =
       ASI_eForm_TestClassHelper.createITPSRHardwareItem(itpsr);
        
      itpsr.ASI_eForm_CIO__c = user.Id; 
      itpsr.ASI_eForm_Finance_Director__c= user.Id;      
      RecordType itpsrRTFinal = [SELECT Id from RecordType where DeveloperName = 'ASI_eForm_HK_Hardware_Software_Request_Final'];
      itpsr.RecordTypeId = itpsrRTFinal.Id;
      itpsr.ASI_eForm_Status__c = 'Final';  
      update itpsr;      
               
    }
    
    @isTest
    public static void testITProcServiceItem()
    {
      User user = ASI_eForm_TestClassHelper.createUser();
        Map<String,User> userMap = new Map<String,User>();
        userMap.put('owner',user);
        
           ASI_eForm_TestClassHelper.createPrefillCustomSetting();
        ASI_eForm_TestClassHelper.createRouteTypeDetails(userMap);
        
        ASI_eForm_IT_Procurement_Service_Request__c  itpsr =
            ASI_eForm_TestClassHelper.createITPSRServiceRequest(userMap);
        
      ASI_eForm_IT_Procurement_Service_Request__c  itProcServiceReq =
        ASI_eForm_TestClassHelper.createITPSRServiceRequest(userMap);
      
      List<ASI_eForm_IT_Procurement_Service_Item__c> itpsrItems =
       ASI_eForm_TestClassHelper.createITPSRServiceRequestItem(itProcServiceReq );
        
      itpsrItems.get(0).ASI_eForm_FD_Approve_Required__c =true;        
      itpsrItems.get(0).ASI_eForm_CIO_Approve_Required__c = true;
      update itpsrItems;
      
      itpsr.ASI_eForm_CIO__c = user.Id; 
      itpsr.ASI_eForm_Finance_Director__c= user.Id;
      //itpsr.ASI_eForm_FD_Approve_Required__c = true;
      
      update itpsr;
      
      itpsr.ASI_eForm_CIO__c = user.Id; 
      update itpsr;
     
      delete itpsrItems;             
      delete itpsr;         
    }

}