objects/ASI_HK_CRM_Visitation_Plan__c.object
<CustomObject>
    <description>ASI HK CRM - Visitation Plan</description>
    <fields>
        <fullName>ASI_CRM_Month_Number__c</fullName>
        <formula>CASE( TEXT(ASI_HK_CRM_Month__c), 
&apos;January&apos;,&apos;1&apos;,
&apos;February&apos;,&apos;2&apos;,
&apos;March&apos;,&apos;3&apos;,
&apos;April&apos;,&apos;4&apos;,
&apos;May&apos;,&apos;5&apos;,
&apos;June&apos;,&apos;6&apos;,
&apos;July&apos;,&apos;7&apos;,
&apos;August&apos;,&apos;8&apos;,
&apos;September&apos;,&apos;9&apos;,
&apos;October&apos;,&apos;10&apos;,
&apos;November&apos;,&apos;11&apos;,
&apos;December&apos;,&apos;12&apos;,
&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month (Number)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                    <default>true</default>
                    <label>January</label>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Year__c</fullName>
        <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Visitation Plan</label>
    <nameField>
        <label>Visitation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitation Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Visitation_Plan_Detail__c.object
<CustomObject>
    <description>ASI HK CRM - Visitation Plan Detail</description>
    <fields>
        <fullName>ASI_CRM_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_MY_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipLabel>Visitation Plan Details</relationshipLabel>
        <relationshipName>Visitation_Plan_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Achieved</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Ad-hoc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Visitation_Plan__c</fullName>
        <label>Visitation Plan</label>
        <referenceTo>ASI_HK_CRM_Visitation_Plan__c</referenceTo>
        <relationshipName>ASI_HK_CRM_Visitation_Plan_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visitation Plan Detail</label>
    <nameField>
        <displayFormat>VPD-{00000}</displayFormat>
        <label>Visitation Plan Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visitation Plan Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CRM_VisitationPlanCtrl.cls
public with sharing class ASI_CRM_VisitationPlanCtrl {

    public static List<String> PH_CUSTOMER_RECORD_TYPE_NAME_LIST = new List<String> {
        'ASI_CRM_PH_Customer', 'ASI_CRM_PH_Potential_Outlet'
    };

    public static Id PH_VISITATION_PLAY_DETAIL_RECORD_TYPE_ID = Schema.SObjectType.ASI_HK_CRM_Visitation_Plan_Detail__c.RecordTypeInfosByName.get('PH Visitation Plan Detail').RecordTypeId;

    @AuraEnabled
    public static void savePHVisitationPlanDetail(String insertDetailListJson, 
                                                  String updateDetailListJson, 
                                                  String deleteDetailIdListJson) {
        saveVisitationPlanDetail(insertDetailListJson, updateDetailListJson, deleteDetailIdListJson, PH_VISITATION_PLAY_DETAIL_RECORD_TYPE_ID);                                                                                                  
    }

    private static void saveVisitationPlanDetail(String insertDetailListJson, 
                                                String updateDetailListJson, 
                                                String deleteDetailIdListJson,
                                                Id recordTypeId) {
                                                    
    	List<ASI_HK_CRM_Visitation_Plan_Detail__c> insertDetailList = (List<ASI_HK_CRM_Visitation_Plan_Detail__c>) 
            	JSON.deserialize(insertDetailListJson, List<ASI_HK_CRM_Visitation_Plan_Detail__c>.class);
                                                    
    	List<ASI_HK_CRM_Visitation_Plan_Detail__c> updateDetailList = (List<ASI_HK_CRM_Visitation_Plan_Detail__c>) 
            	JSON.deserialize(updateDetailListJson, List<ASI_HK_CRM_Visitation_Plan_Detail__c>.class);
                                                    
    	List<String> deleteDetailIdList = (List<String>) 
            	JSON.deserialize(deleteDetailIdListJson, List<String>.class);
                                                    
    	Savepoint sp = Database.setSavepoint();
        
        try {
            if(deleteDetailIdList != null && 
               deleteDetailIdList.size() != 0) {
                List<ASI_HK_CRM_Visitation_Plan_Detail__c> deleteDetailList = new List<ASI_HK_CRM_Visitation_Plan_Detail__c>();
            	
           		for(String detailId : deleteDetailIdList) {
                	deleteDetailList.add(new ASI_HK_CRM_Visitation_Plan_Detail__c(id = detailId));	       
            	}
                
            	delete deleteDetailList;        
        	}
            
            if(updateDetailList != null && 
               updateDetailList.size() != 0) {
            	update updateDetailList;        
            }
            
            if(insertDetailList != null && 
               insertDetailList.size() != 0) {
           		for(ASI_HK_CRM_Visitation_Plan_Detail__c insertDetail : insertDetailList) {
                	insertDetail.RecordTypeId = recordTypeId;
           		}        
            	insert insertDetailList;       
        	}
        } catch (Exception e) {
            Database.rollback(sp);

            throw e;
        }                                            
    }

    @AuraEnabled
    public static CustomVisitationPlan getCustomVisitationPlan(String recordId){
        ASI_HK_CRM_Visitation_Plan__c visitationPlan = getVisitationPlanRecord(recordId);
        List<ASI_HK_CRM_Visitation_Plan_Detail__c> visitationPlanDetailList = getVisitationPlanDetailRecord(recordId);
        
        return new CustomVisitationPlan(visitationPlan, visitationPlanDetailList);
    }
    
    private static ASI_HK_CRM_Visitation_Plan__c getVisitationPlanRecord(String recordId) {
		return [SELECT Id, 
                		Name, 
                		ASI_HK_CRM_Year__c, 
                		ASI_HK_CRM_Month__c, 
                		ASI_CRM_Month_Number__c, 
                		ASI_HK_CRM_Confirmed__c
                    FROM ASI_HK_CRM_Visitation_Plan__c 
                	WHERE Id = :recordId];
    }

    private static List<ASI_HK_CRM_Visitation_Plan_Detail__c> getVisitationPlanDetailRecord(String recordId) {
		return [SELECT Id, 
                		Name, 
                        ASI_HK_CRM_Visit_Date__c, 
                        ASI_HK_CRM_Status__c,
                        ASI_CRM_Locked__c,
                		ASI_CRM_MY_Customer__r.id, 
                		ASI_CRM_MY_Customer__r.Name, 
                		ASI_CRM_MY_Customer__r.RecordType.Name 
                	FROM ASI_HK_CRM_Visitation_Plan_Detail__c 
            		WHERE ASI_HK_CRM_Visitation_Plan__c = :recordId 
            			LIMIT 1000];
    }

    @AuraEnabled 
    public static Integer getPHCustomCustomerCount(String customerName, 
                                                   Boolean isOwned) {
        List<String> specialQueryList = new List<String>();
        if(String.isNotBlank(customerName))
            specialQueryList.add('(Name LIKE \'%' + customerName + '%\')');

        if(isOwned == true) 
            specialQueryList.add('(OwnerId = \'' + UserInfo.getUserId() + '\')');

        String specialQuery = '';
        if(specialQueryList.size() != 0) 
            specialQuery = String.join(specialQueryList, ' AND ');

    	return getCustomerCount(PH_CUSTOMER_RECORD_TYPE_NAME_LIST, specialQuery);                                                   
    }
    
    @AuraEnabled
    public static List<ASI_CRM_AccountsAdditionalField__c> getPHCustomCustomerList(String customerName,
                                                                                   Boolean isOwned,
                                                                                   Integer pageSize,
                                                                                   Integer pageNo) {
        List<String> specialQueryList = new List<String>();
        if(String.isNotBlank(customerName))
            specialQueryList.add('(Name LIKE \'%' + customerName + '%\')');

        if(isOwned == true) 
            specialQueryList.add('(OwnerId = \'' + UserInfo.getUserId() + '\')');

        String specialQuery = '';
        if(specialQueryList.size() != 0) 
            specialQuery = String.join(specialQueryList, ' AND ');

        List<ASI_CRM_AccountsAdditionalField__c> customerList = getCustomerList(PH_CUSTOMER_RECORD_TYPE_NAME_LIST,
                                                                                specialQuery,
                                                                                pageSize,
                                                                                pageNo);
                                                                    
        return customerList;
    }

    private static Integer getCustomerCount(List<String> recordTypeDeveloperNameList, 
                                            String specialQuery) {
        String selectQuery = 'SELECT count() FROM ASI_CRM_AccountsAdditionalField__c ' 
                           + genCustomerWhereClause(recordTypeDeveloperNameList, 
                                                    specialQuery);
            
    	return database.countQuery(selectQuery);
    }

    private static List<ASI_CRM_AccountsAdditionalField__c> getCustomerList(List<String> recordTypeDeveloperNameList, 
                                                                            String specialQuery,
                                                               				Integer pageSize,
                                                                            Integer pageNo) {
        String selectQuery = 'SELECT Id, '
                           + 'Name, '
                           + 'RecordTypeId, '
                           + 'RecordType.Name, ' 
                           + 'RecordType.DeveloperName, '
                           + 'ASI_CRM_SG_Area__c, '
                           + 'ASI_CRM_VN_Channel__c, '
                           + 'ASI_CRM_JP_City_Ward__c, '
                           + 'ASI_CRM_JP_Town__c, '
                           + 'OwnerId, '
                           + 'Owner.Id, '
                           + 'Owner.Name '
                           + 'FROM ASI_CRM_AccountsAdditionalField__c ';
        
      	selectQuery += genCustomerWhereClause(recordTypeDeveloperNameList, 
                                              specialQuery);
        
        selectQuery += 'ORDER BY Name ASC ';
                                                                                
        if(pageSize != null && 
          	pageSize != 0 && 
          	pageNo != null && 
          	pageNo != 0)
            selectQuery += 'LIMIT ' + pageSize + ' OFFSET ' + ((pageNo - 1) * pageSize);
                                                                                
        return Database.query(selectQuery);
    }

    private static String genCustomerWhereClause(List<String> recordTypeDeveloperNameList, 
                                                String specialQuery) {
        List<String> queryStringList = new List<String>();
        queryStringList.add('ASI_CRM_CN_Inactive_Flag__c = FALSE');
                                                                                
        if(recordTypeDeveloperNameList.size() > 0) {
        	List<String> recordTypeQueryStringList = new List<String>();
            for(String recordTypeDeveloperName : recordTypeDeveloperNameList) {
                recordTypeQueryStringList.add('RecordType.DeveloperName = \'' + recordTypeDeveloperName + '\'');
            }
            queryStringList.add('(' + String.join(recordTypeQueryStringList, ' OR ') + ')');
        }
                                                     
        if(String.isNotBlank(specialQuery))
        	queryStringList.add(specialQuery);                                      
        
        if(queryStringList.size() > 0)                                     
    		return 'WHERE ' + String.join(queryStringList, ' AND ') + ' ';
    	else 
            return '';
    }

    public class CustomVisitationPlan {
        @AuraEnabled  
        public ASI_HK_CRM_Visitation_Plan__c visitationPlan {get; set;}
        @AuraEnabled 
        public List<ASI_HK_CRM_Visitation_Plan_Detail__c> visitationPlanDetailList {get; set;}
        
        public CustomVisitationPlan(ASI_HK_CRM_Visitation_Plan__c visitationPlan, 
                                    List<ASI_HK_CRM_Visitation_Plan_Detail__c> visitationPlanDetailList) {
            this.visitationPlan           = visitationPlan;
            this.visitationPlanDetailList = visitationPlanDetailList;
        }
        
    }

}