objects/ASI_CRM_ContractTarget__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>ASI_TH_CRM_Contract__c</referenceTo>
        <relationshipLabel>Contract Target</relationshipLabel>
        <relationshipName>Contract_Target</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Contract Target</relationshipLabel>
        <relationshipName>Contract_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Target_Total_Bottle__c</fullName>
        <label>Target Total Bottle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contract Target</label>
    <nameField>
        <displayFormat>CTID{00000000}</displayFormat>
        <label>Contract Target ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_CRM_MY_SKUPriceCost__c.object
<CustomObject>
    <description>WS to Outlet Min SP, or IntoGodownCost (IGC)</description>
    <fields>
        <fullName>ASI_CRM_Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>SKU Prices/Costs</relationshipLabel>
        <relationshipName>ASI_CRM_IGCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SKU Price/Cost</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SKU PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SKU Prices/Costs</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_PH_Outlet_Selling_Price</fullName>
        <active>true</active>
        <label>PH CRM Outlet Selling Price</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_CRM_Payment_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>ASI_TH_CRM_Contract__c</referenceTo>
        <relationshipLabel>Payment Schedules</relationshipLabel>
        <relationshipName>Payment_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Sys_Parent_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sys Parent Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Target_End_Date__c</fullName>
        <label>Target End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Target_Start_Date__c</fullName>
        <label>Target Start Date</label>
        <type>Date</type>
    </fields>
    <label>Payment Schedule</label>
    <nameField>
        <label>Payment Schedule ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_PH_Contract_Fund</fullName>
        <active>true</active>
        <label>ASI CRM PH Contract Fund</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_CRM_PH_Purchase_Incentive</fullName>
        <active>true</active>
        <label>ASI CRM PH Purchase Incentive</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Running_Number__c.object
<CustomObject>
    <description>ASI HK CRM - used to keep track of various auto number running numbers</description>
    <fields>
        <fullName>ASI_HK_CRM_Running_Number__c</fullName>
        <label>Running Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Running Number</label>
    <nameField>
        <displayFormat>RN-{000000}</displayFormat>
        <label>Running  Number ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Running Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_MFM_Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <displayFormat>EXR{000000}</displayFormat>
        <label>Exchange Rate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ASI_MFM_SKU_Code__c.object
<CustomObject>
    <description>Shared SKU object with ASI countries</description>
    <fields>
        <fullName>ASI_CRM_Duty_Free__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Duty Free?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_SKU_Code__c</fullName>
        <label>SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_PH_DP_SKU</fullName>
        <active>true</active>
        <label>PH CRM DP SKU</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_Actual_Offtake__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>ASI_TH_CRM_Contract__c</referenceTo>
        <relationshipLabel>Actual Offtake</relationshipLabel>
        <relationshipName>ASI_CRM_Actual_Offtake</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Actual Offtake</relationshipLabel>
        <relationshipName>Actual_Offtake</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Actual Offtake</label>
    <nameField>
        <displayFormat>AO{YY}{MM}-{0000}</displayFormat>
        <label>Actual Offtake Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Offtake</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_PH_Actual_Offtake</fullName>
        <active>true</active>
        <label>ASI CRM PH Actual Offtake</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_Contract__c.object
<CustomObject>
    <description>ASI TH CRM Contract</description>
    <fields>
        <fullName>ASI_CRM_CN_Outlet_WS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5) OR (4 AND 7) OR (8 AND 10) OR (6 AND 9)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM MY Contract, ASI CRM MY Contract (Final)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (MY), Potential Outlet (MY)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.ASI_CRM_CN_Inactive_Flag__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (SG)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM SG 2. Contract, ASI CRM SG Contract (Read-Only), ASI CRM SG Contract (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer (KH)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM SG 1. Proposal, ASI CRM SG Proposal (Read-Only), ASI CRM SG Proposal (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM SG 2. Contract, ASI CRM MY Contract, ASI CRM MY Contract (Final), ASI CRM SG Contract (Read-Only), ASI CRM SG 1. Proposal, ASI CRM SG Proposal (Read-Only), ASI CRM SG Proposal (Snapshot), ASI CRM SG Contract (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM KH Contract, ASI CRM KH Contract (Read-Only)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM KH Contract, ASI CRM KH Contract (Read-Only)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipName>Contracts_CN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_PH_Contract_Read_Only</fullName>
        <active>true</active>
        <label>ASI CRM PH Contract (Read-Only)</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASI_TH_CRM_Contract</fullName>
        <active>true</active>
        <label>ASI TH CRM Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_PaymentRequest__c.object
<CustomObject>
    <fields>
        <fullName>ASI_TH_CRM_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>((1 OR 4 OR 5) AND 2) OR 3 OR 6 OR (7 AND 8)</booleanFilter>
            <filterItems>
                <field>ASI_TH_CRM_Contract__c.ASI_CRM_CN_Contract_Upload__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ASI_TH_CRM_Contract__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>CN Contract</value>
            </filterItems>
            <filterItems>
                <field>ASI_TH_CRM_Contract__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI TH CRM Contract</value>
            </filterItems>
            <filterItems>
                <field>$User.Username</field>
                <operation>contains</operation>
                <value>prasia_soa</value>
            </filterItems>
            <filterItems>
                <field>$Source.ASI_TH_CRM_Status__c</field>
                <operation>equals</operation>
                <value>Approved</value>
            </filterItems>
            <filterItems>
                <field>ASI_TH_CRM_Contract__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM MY Contract, ASI CRM MY Contract (Final)</value>
            </filterItems>
            <filterItems>
                <field>ASI_TH_CRM_Contract__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM SG Contract (Read-Only)</value>
            </filterItems>
            <filterItems>
                <field>ASI_TH_CRM_Contract__c.ASI_TH_CRM_Contract_Status__c</field>
                <operation>notEqual</operation>
                <value>Completed</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>ASI_TH_CRM_Contract__c</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>ASI_TH_CRM_PaymentRequests_Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <label>Payment Request No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_PaymentRequestLineItem__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>ASI_MFM_SKU_Code__c</referenceTo>
        <relationshipLabel>Payment Request Line Items</relationshipLabel>
        <relationshipName>Payment_Request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Request Line Item</label>
    <nameField>
        <displayFormat>{YY}{MM}-{0000}</displayFormat>
        <label>Payment Request Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Request Line Items</pluralLabel>
    <recordTypes>
        <fullName>ASI_CRM_PH_Payment_Request_Detail</fullName>
        <active>true</active>
        <label>ASI CRM PH Payment Request Detail</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASI_CRM_PH_MassUploadByBatchCtrlTest.cls
@isTest
public class ASI_CRM_PH_MassUploadByBatchCtrlTest {

	static final String TEST_ACCOUNT_NAME = 'Test Account';
	static final Date startDate = Date.newInstance(Date.today().Year() - 1, 7, 1);
	static final Date endDate = Date.newInstance(Date.today().Year(), 6, 30);
	static final String OFFTAKE_CSV_FILENAME = 'offtakes.csv';

	@TestSetup
	static void setup() {

		ASI_MFM_Exchange_Rate__c exRate = ASI_CRM_PH_Testfactory.createExchangeRate(Date.newInstance(Date.today().Year() - 1, 9, 1));
        insert exRate;
        
        ASI_HK_CRM_Running_Number__c runningNumber = ASI_CRM_PH_Testfactory.createRunningNumber(Date.today().year() -1);        
        insert runningNumber;
	
        /*
		final ASI_TH_CRM_OutletType__c outletType = new ASI_TH_CRM_OutletType__c();
		outletType.Name = 'test outlet';
		insert outletType;

		final Account account = new Account();
		account.Name = TEST_ACCOUNT_NAME;
		insert account;
		*/

		final ASI_CRM_AccountsAdditionalField__c customer = new ASI_CRM_AccountsAdditionalField__c();
		customer.Name = 'test customer';
		//customer.ASI_CRM_Account__c = account.Id;
		//customer.ASI_TH_CRM_OutletType__c = outletType.Id;
		customer.ASI_CRM_CN_Address__c = 'address';
		customer.ASI_CRM_Duty_Free__c = false;
		customer.ASI_CRM_MY_CustomerCode__c = 'C001';
		customer.recordtypeid = Global_RecordTypeCache.getRtID('ASI_CRM_AccountsAdditionalField__cASI_CRM_PH_Customer');

		insert customer;

		final Id contractRecordTypeId = ASI_CRM_RecordTypeUtil.getRecordTypeIdByApiName(
				ASI_TH_CRM_Contract__c.sObjectType,
				ASI_CRM_RecordTypeApiName.ASI_TH_CRM_Contract.ASI_CRM_PH_Contract_Read_Only.name()
		);

		final ASI_TH_CRM_Contract__c contract = new ASI_TH_CRM_Contract__c(
				ASI_CRM_CN_Outlet_WS__c = customer.Id,
				ASI_TH_CRM_Start_Date__c = startDate,
				ASI_TH_CRM_End_Date__c = endDate,
				recordtypeid = Global_RecordTypeCache.getRtID('ASI_TH_CRM_Contract__cASI_CRM_PH_Contract')
		);
		insert contract;

		contract.RecordTypeId = contractRecordTypeId;
		update contract;

		final Id skuRecordTypeId = ASI_CRM_RecordTypeUtil.getRecordTypeIdByApiName(
				ASI_MFM_SKU_Code__c.sObjectType,
				ASI_CRM_RecordTypeApiName.SkuCode.ASI_CRM_PH_DP_SKU.name()
		);

		final List<ASI_MFM_SKU_Code__c> skus = new List<ASI_MFM_SKU_Code__c>();
		skus.add(new ASI_MFM_SKU_Code__c(
				Name = 'test sku1',
				ASI_MFM_SKU_Code__c = 'AEL275',
				RecordTypeId = skuRecordTypeId
		));
		skus.add(new ASI_MFM_SKU_Code__c(
				Name = 'test sku2',
				ASI_MFM_SKU_Code__c = '01123C',
				RecordTypeId = skuRecordTypeId
		));
		insert skus;

		final Id skuPriceCostRecordTypeId = ASI_CRM_RecordTypeUtil.getRecordTypeIdByApiName(
				ASI_CRM_MY_SKUPriceCost__c.sObjectType,
				ASI_CRM_RecordTypeApiName.ASI_CRM_MY_SKUPriceCost.ASI_CRM_PH_Outlet_Selling_Price.name()
		);

		final List<ASI_CRM_MY_SKUPriceCost__c> skuPriceCosts = new List<ASI_CRM_MY_SKUPriceCost__c>();
		skuPriceCosts.add(new ASI_CRM_MY_SKUPriceCost__c(
				ASI_CRM_SKU__c = skus.get(0).Id,
				ASI_CRM_Cost__c = 90,
				ASI_CRM_Price__c = 100,
				ASI_CRM_EffectiveDate__c = startDate,
				RecordTypeId = skuPriceCostRecordTypeId
		));
		skuPriceCosts.add(new ASI_CRM_MY_SKUPriceCost__c(
				ASI_CRM_SKU__c = skus.get(1).Id,
				ASI_CRM_Cost__c = 90,
				ASI_CRM_Price__c = 100,
				ASI_CRM_EffectiveDate__c = startDate,
				RecordTypeId = skuPriceCostRecordTypeId
		));
		insert skuPriceCosts;

		final List<ASI_CRM_ContractTarget__c> contractTargets = new List<ASI_CRM_ContractTarget__c>();
		contractTargets.add(new ASI_CRM_ContractTarget__c(
				ASI_CRM_Contract__c = contract.Id,
				ASI_CRM_SKU__c = skus.get(0).Id,
				ASI_CRM_Target_Total_Bottle__c = 10,
				recordtypeid = Global_RecordTypeCache.getRtID('ASI_CRM_ContractTarget__cASI_CRM_PH_Contract_Target')

		));
		contractTargets.add(new ASI_CRM_ContractTarget__c(
				ASI_CRM_Contract__c = contract.Id,
				ASI_CRM_SKU__c = skus.get(1).Id,
				ASI_CRM_Target_Total_Bottle__c = 10,
				recordtypeid = Global_RecordTypeCache.getRtID('ASI_CRM_ContractTarget__cASI_CRM_PH_Contract_Target')
		));
		insert contractTargets;

		Id contractFundSchemeRecordTypeId = ASI_CRM_RecordTypeUtil.getRecordTypeIdByApiName(
				ASI_CRM_Payment_Schedule__c.sObjectType,
				ASI_CRM_RecordTypeApiName.ASI_CRM_Payment_Schedule.ASI_CRM_PH_Contract_Fund.name()
		);
		final List<ASI_CRM_Payment_Schedule__c> contractFundSchemes = new List<ASI_CRM_Payment_Schedule__c>();
		contractFundSchemes.add(new ASI_CRM_Payment_Schedule__c(
				ASI_CRM_Contract__c = contract.Id,
				RecordTypeId = contractFundSchemeRecordTypeId
		));

		insert contractFundSchemes;

		Id purchaseIncentiveSchemeRecordTypeId = ASI_CRM_RecordTypeUtil.getRecordTypeIdByApiName(
				ASI_CRM_Payment_Schedule__c.sObjectType,
				ASI_CRM_RecordTypeApiName.ASI_CRM_Payment_Schedule.ASI_CRM_PH_Purchase_Incentive.name()
		);
		final List<ASI_CRM_Payment_Schedule__c> purchaseIncentiveSchemes = new List<ASI_CRM_Payment_Schedule__c>();
		purchaseIncentiveSchemes.add(new ASI_CRM_Payment_Schedule__c(
				ASI_CRM_Contract__c = contract.Id,
				RecordTypeId = purchaseIncentiveSchemeRecordTypeId,
				ASI_CRM_Target_Start_Date__c = startDate,
				ASI_CRM_Target_End_Date__c = endDate,
				ASI_CRM_Sys_Parent_record__c = true
		));
		purchaseIncentiveSchemes.add(new ASI_CRM_Payment_Schedule__c(
				ASI_CRM_Contract__c = contract.Id,
				RecordTypeId = purchaseIncentiveSchemeRecordTypeId,
				ASI_CRM_Target_Start_Date__c = startDate,
				ASI_CRM_Target_End_Date__c = endDate
		));

		insert purchaseIncentiveSchemes;

		final Id offtakeHeaderRecordTypeId = ASI_CRM_RecordTypeUtil.getRecordTypeIdByApiName(
				ASI_CRM_ActualOfftakeHeader__c.sObjectType,
				ASI_CRM_RecordTypeApiName.ActualOfftakeHeader.ASI_CRM_PH_Actual_Offtake_Header.name()
		);
		final ASI_CRM_ActualOfftakeHeader__c offtakeHeader = new ASI_CRM_ActualOfftakeHeader__c(
				RecordTypeId = offtakeHeaderRecordTypeId,
				ASI_CRM_OfftakeDate__c = startDate
		);
		//		ASI_CRM_Year__c = offtakeHeaderYear,
		//		ASI_CRM_Month__c = offtakeHeaderMonth,
		//		ASI_CRM_All_Offtakes_Removed__c = false,
		//		ASI_CRM_Upload_Failed__c = false
		insert offtakeHeader;

		final Id offtakeRecordTypeId = ASI_CRM_RecordTypeUtil.getRecordTypeIdByApiName(
				ASI_TH_CRM_Actual_Offtake__c.sObjectType,
				ASI_CRM_RecordTypeApiName.ActualOfftake.ASI_CRM_PH_Actual_Offtake.name()
		);
		final List<ASI_TH_CRM_Actual_Offtake__c> offtakes = new List<ASI_TH_CRM_Actual_Offtake__c>();
		offtakes.add(new ASI_TH_CRM_Actual_Offtake__c(
				ASI_CRM_ActualOfftakeHeader__c = offtakeHeader.Id,
				ASI_CRM_Contract__c = contract.Id,
				ASI_CRM_SG_Customer__c = customer.Id,
				ASI_TH_CRM_Offtake_G_L_Date__c = startDate.addDays(2),
				RecordTypeId = offtakeRecordTypeId,
				ASI_CRM_SKU__c = skus.get(0).Id,
				ASI_CRM_Original_Quantity__c = 10,
				ASI_CRM_Outlet_Selling_Price__c = 10
		));
		offtakes.add(new ASI_TH_CRM_Actual_Offtake__c(
				ASI_CRM_ActualOfftakeHeader__c = offtakeHeader.Id,
				ASI_CRM_Contract__c = contract.Id,
				ASI_CRM_SG_Customer__c = customer.Id,
				ASI_TH_CRM_Offtake_G_L_Date__c = startDate.addDays(2),
				RecordTypeId = offtakeRecordTypeId,
				ASI_CRM_SKU__c = skus.get(1).Id,
				ASI_CRM_Original_Quantity__c = 10,
				ASI_CRM_Outlet_Selling_Price__c = 10
		));
		insert offtakes;


		final ASI_TH_CRM_PaymentRequest__c paymentRequest = new ASI_TH_CRM_PaymentRequest__c(
				ASI_TH_CRM_Contract__c = contract.Id,
				ASI_TH_CRM_Status__c = 'Draft',
				recordtypeid = Global_RecordTypeCache.getRtID('ASI_TH_CRM_PaymentRequest__cASI_CRM_PH_Payment_Request')
		);
		insert paymentRequest;

		final Id paymentRequestItemRecordTypeId = ASI_CRM_RecordTypeUtil.getRecordTypeIdByApiName(
				ASI_TH_CRM_PaymentRequestLineItem__c.sObjectType,
				ASI_CRM_RecordTypeApiName.ASI_TH_CRM_PaymentRequestLineItem.ASI_CRM_PH_Payment_Request_Detail.name()
		);
		final List<ASI_TH_CRM_PaymentRequestLineItem__c> paymentRequestItems =
				new List<ASI_TH_CRM_PaymentRequestLineItem__c>();
		paymentRequestItems.add(new ASI_TH_CRM_PaymentRequestLineItem__c(
				ASI_CRM_SKU__c = skus.get(0).Id,
				ASI_TH_CRM_Payment_Request__c = paymentRequest.Id,
				RecordTypeId = paymentRequestItemRecordTypeId
		));
		insert paymentRequestItems;
	}

	@isTest
	static void testController() {
		final ASI_CRM_PH_MassUploadByBatchController c = new ASI_CRM_PH_MassUploadByBatchController();

		c.ObjAPIName = 'ASI_TH_CRM_Actual_Offtake__c';
		c.recordtypeName = 'ASI CRM SG Actual Offtake';
		c.defaultValues = 'Type (Uploaded):Off-Trade';
		c.fields = 'Name,ASI_TH_CRM_Quantity__c';
		c.fieldsLabel = 'Name,Quantity';
		c.emailNotification = true;
		c.init();

		c.refreshPage();
		c.refreshPage2();

		ASI_CRM_PH_MassUploadByBatchController.Row r =
				new ASI_CRM_PH_MassUploadByBatchController.Row(new Account(), 'Name', '');

		ASI_CRM_PH_MassUploadByBatchController.Row r1 =
				new ASI_CRM_PH_MassUploadByBatchController.Row(new Account());

		r1.addError('Error');

		System.assert(r != null);
		System.assert(r1 != null);
	}

	@isTest
	static void testControllerWithoutEmailNotification() {
		final ASI_CRM_PH_MassUploadByBatchController c = new ASI_CRM_PH_MassUploadByBatchController();

		c.ObjAPIName = 'ASI_TH_CRM_Actual_Offtake__c';
		c.recordtypeName = 'ASI CRM SG Actual Offtake';
		c.defaultValues = 'Type (Uploaded):Off-Trade';
		c.fields = 'Id,Name';
		c.fieldsLabel = 'Name,Quantity';
		c.emailNotification = false;
		c.init();
	}

	@isTest
	static void testUploadInvalidFile() {

		final ASI_CRM_PH_MassUploadByBatchController c = new ASI_CRM_PH_MassUploadByBatchController();
		c.ObjAPIName = 'ASI_TH_CRM_Actual_Offtake__c';
		c.recordtypeName = 'ASI CRM SG Actual Offtake';
		c.defaultValues = 'Type (Uploaded):Off-Trade';
		c.fields = 'Id,Name';
		c.fieldsLabel = 'Name,Quantity';
		c.emailNotification = false;
		c.init();

		c.fileSize = 100000;
		c.nameFile = 'test';
		c.uploadCSVByBatch();
	}

	@isTest
	static void testUploadCsvByBatch() {

		final List<String> attachmentCsvHeader = new List<String>{
				'Customer',
				'Offtake G/L Date',
				'SKU Code',
				'Invoice No.',
				'Quantity'
				};
		final List<String> attachmentRow = new List<String>();
		attachmentRow.add('C001');
		//		attachmentRow.add(offtakeHeader.ASI_CRM_OfftakeDate__c.format());
		attachmentRow.add('20151010');
		attachmentRow.add('AEL275');
		attachmentRow.add('ABCD123');
		attachmentRow.add('123');

		String attachmentContent = String.join(attachmentCsvHeader, ',') + ASI_CRM_CSVReaderHelper.CRLF;
		attachmentContent += String.join(attachmentRow, ',');

		final ASI_CRM_PH_MassUploadByBatchController c = new ASI_CRM_PH_MassUploadByBatchController();

		c.ObjAPIName = 'ASI_TH_CRM_Actual_Offtake__c';
		c.recordtypeName = 'ASI CRM SG Actual Offtake';
		c.defaultValues = 'Type (Uploaded):Off-Trade';
		c.fields = 'Id,Name';
		c.fieldsLabel = 'Name,Quantity';
		c.emailNotification = false;
		c.init();

		c.fileSize = 1000;
		c.nameFile = 'test.csv';
		c.currentPageURL = '';
		c.contentFile = Blob.valueOf(attachmentContent);

		c.uploadCSVByBatch();

		System.assert(c.StatusMsgs != null);
		System.assert(c.isDisplayErrorLog != null);
	}

	@isTest
	static void forTestCoverage() {
		final ASI_CRM_PH_MassUploadByBatchController c = new ASI_CRM_PH_MassUploadByBatchController();

		c.ObjAPIName = 'ASI_TH_CRM_Actual_Offtake__c';
		c.recordtypeName = 'ASI CRM SG Actual Offtake';
		c.defaultValues = 'Type (Uploaded):Off-Trade';
		c.fields = 'Id,Name';
		c.fieldsLabel = 'Name,Quantity';
		c.emailNotification = false;
		c.init();

		c.inlineVF = true;
		c.recEXID = null;
		c.recEXIDcol = null;
		c.parentObjectAPIName = null;
		c.ParentObjectUploadMsg = null;
		c.noOfLastRowToIgnore = null;
		c.upsertMode = false;
		c.batchMode = true;
		c.opt_allOrNone = true;
		c.containsHeader = true;
		c.dummyVar = false;

		c.objName = 'Account';
		c.LOutputRow = null;
		c.LErrorRows = null;
	}
}