objects/ASI_CRM_Payment_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>ASI_CRM_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>ASI_TH_CRM_Contract__c</referenceTo>
        <relationshipLabel>Payment Schedules</relationshipLabel>
        <relationshipName>Payment_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Percentof_achieved_Sales_Target__c</fullName>
        <label>% of achieved Sales Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Sponsorship__c</fullName>
        <label>Sponsorship</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Contract Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
                <value>
                    <fullName>Bottle</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Schedule</label>
    <nameField>
        <label>Payment Schedule ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ASI_HK_CRM_Running_Number__c.object
<CustomObject>
    <description>ASI HK CRM - used to keep track of various auto number running numbers</description>
    <fields>
        <fullName>ASI_HK_CRM_First_Month_of_Fiscal_Year__c</fullName>
        <label>First Month of Fiscal Year</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Format__c</fullName>
        <label>Format</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ASI_HK_CRM_Running_Number__c</fullName>
        <label>Running Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Running Number</label>
    <nameField>
        <displayFormat>RN-{000000}</displayFormat>
        <label>Running  Number ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Running Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ASI_TH_CRM_Contract__c.object
<CustomObject>
    <description>ASI TH CRM Contract</description>
    <fields>
        <fullName>ASI_CRM_CN_Outlet_WS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5) OR (4 AND 7) OR (8 AND 10) OR (6 AND 9)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM MY Contract, ASI CRM MY Contract (Final)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (MY), Potential Outlet (MY)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.ASI_CRM_CN_Inactive_Flag__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet (SG)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM SG 2. Contract, ASI CRM SG Contract (Read-Only), ASI CRM SG Contract (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>ASI_CRM_AccountsAdditionalField__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer (KH)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM SG 1. Proposal, ASI CRM SG Proposal (Read-Only), ASI CRM SG Proposal (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM SG 2. Contract, ASI CRM MY Contract, ASI CRM MY Contract (Final), ASI CRM SG Contract (Read-Only), ASI CRM SG 1. Proposal, ASI CRM SG Proposal (Read-Only), ASI CRM SG Proposal (Snapshot), ASI CRM SG Contract (Snapshot)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>ASI CRM KH Contract, ASI CRM KH Contract (Read-Only)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>ASI CRM KH Contract, ASI CRM KH Contract (Read-Only)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ASI_CRM_AccountsAdditionalField__c</referenceTo>
        <relationshipName>Contracts_CN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_CN_Sys_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sys Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts_TH1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_SG_Total_Target_Sales_9L_Cases__c</fullName>
        <label>Total Target Sales (9L Cases)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Till_Date_Sales_Volume_9L__c</fullName>
        <label>Till Date Sales Volume (9L)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ASI_CRM_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Incentive</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Key Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Contract_Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Final</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Editing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>New Contract</fullName>
                </value>
                <value>
                    <fullName>Renewal Contract</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Contract Approved</fullName>
                </value>
                <value>
                    <fullName>Contract Rejected</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>SM Approved</fullName>
                </value>
                <value>
                    <fullName>HF Approved</fullName>
                </value>
                <value>
                    <fullName>Mktg Approved</fullName>
                </value>
                <value>
                    <fullName>MD Approved</fullName>
                </value>
                <value>
                    <fullName>GCMD Approved</fullName>
                </value>
                <value>
                    <fullName>Proposal Approved</fullName>
                </value>
                <value>
                    <fullName>Proposal Rejected</fullName>
                </value>
                <value>
                    <fullName>Proposal Converted</fullName>
                </value>
                <value>
                    <fullName>Terminate</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ASI_TH_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ASI_CRM_SG_PymtSchedIssueNotif_BatchTest.cls
/***************************************************************************************************
 * Name : ASI_CRM_SG_PymtSchedIssueNotif_BatchTest
 * Created : DC @04/21/2016 9:30 AM
 * Revision History:
 * 1. 04/21/2016 - [DC 1.0] Created
 **************************************************************************************************/

@isTest
private class ASI_CRM_SG_PymtSchedIssueNotif_BatchTest {
    
    @TestSetup
    private static void setupData() {

        /* Replaced by ASI_CRM_SG_TestClassHelper.createDataSettings();
        ASI_HK_CRM_Running_Number__c runningNumber = new ASI_HK_CRM_Running_Number__c(
            ASI_HK_CRM_Object_Name__c = 'ASI_CRM_SG_Contract_No',
            ASI_HK_CRM_Running_Number__c = 1,
            ASI_HK_CRM_Format__c = 'PRS-{YY}-{0000}',
            ASI_HK_CRM_Fiscal_Year__c = 2016,
            ASI_HK_CRM_First_Month_of_Fiscal_Year__c = 7
        );
        insert runningNumber;
        */

        Profile standardProfile = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        
        User testUser1 = new User(Alias = 'standt', Email='contractowner1@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = standardProfile.Id, ManagerId = UserInfo.getUserId(),
            TimeZoneSidKey='America/Los_Angeles', UserName='contractowner1@testorg.com');

        User testUser2 = new User(Alias = 'standt', Email='contractowner2@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = standardProfile.Id, ManagerId = UserInfo.getUserId(),
            TimeZoneSidKey='America/Los_Angeles', UserName='contractowner2@testorg.com');

        insert new List<User> {testUser1, testUser2};

        Id contractRecTypeId = Schema.SObjectType.ASI_TH_CRM_Contract__c 
                                                 .getRecordTypeInfosByName()
                                                 .get('ASI CRM SG 2. Contract').getRecordTypeId();

        
        ASI_CRM_SG_TestClassHelper.createDataSettings();
        ASI_CRM_SG_TestClassHelper.customerData customerC = new ASI_CRM_SG_TestClassHelper.customerData(true);
        

        ASI_TH_CRM_Contract__c contractInstance1 = new ASI_TH_CRM_Contract__c(
            ASI_TH_CRM_Start_Date__c = Date.today().addMonths(-4),
            RecordTypeId = contractRecTypeId,
            ASI_TH_CRM_Contract_Status__c = 'Contract Approved',
            OwnerId = testUser1.Id,
            ASI_CRM_CN_Sys_Approver_2__c = testUser2.Id,
            ASI_CRM_Till_Date_Sales_Volume_9L__c = 30,
            ASI_CRM_SG_Total_Target_Sales_9L_Cases__c = 20,
            ASI_CRM_CN_Outlet_WS__c = customerC.customer.id
        );

        ASI_TH_CRM_Contract__c contractInstance2 = new ASI_TH_CRM_Contract__c(
            ASI_TH_CRM_Start_Date__c = Date.today().addMonths(-2),
            RecordTypeId = contractRecTypeId,
            ASI_TH_CRM_Contract_Status__c = 'Contract Approved',
            OwnerId = testUser2.Id,
            ASI_CRM_CN_Sys_Approver_2__c = testUser1.Id,
            ASI_CRM_Till_Date_Sales_Volume_9L__c = 40,
            ASI_CRM_SG_Total_Target_Sales_9L_Cases__c = 10,
            ASI_CRM_CN_Outlet_WS__c = customerC.customer.id
        );

        insert new List<ASI_TH_CRM_Contract__c> {contractInstance1, contractInstance2};

        Id paymentRecTypeId = Schema.SObjectType.ASI_CRM_Payment_Schedule__c 
                                                .getRecordTypeInfosByName()
                                                .get('ASI CRM SG Payment Schedule').getRecordTypeId();

        List<ASI_CRM_Payment_Schedule__c> lstTestPaymentSchedules =
            new List<ASI_CRM_Payment_Schedule__c>();

        lstTestPaymentSchedules.add( new ASI_CRM_Payment_Schedule__c(
            ASI_CRM_Contract__c = contractInstance1.Id,
            ASI_CRM_Schedule_Date__c = Date.today().addMonths(1),
            ASI_CRM_Sponsorship__c = 100,
            ASI_CRM_Type__c = 'Cash Sponsorship',
            RecordTypeId = paymentRecTypeId
        ));

        lstTestPaymentSchedules.add( new ASI_CRM_Payment_Schedule__c(
            ASI_CRM_Contract__c = contractInstance1.Id,
            ASI_CRM_Sponsorship__c = 200,
            ASI_CRM_Percentof_achieved_Sales_Target__c = '15',
            ASI_CRM_Type__c = 'Cash Sponsorship',
            RecordTypeId = paymentRecTypeId
        ));



        lstTestPaymentSchedules.add( new ASI_CRM_Payment_Schedule__c(
            ASI_CRM_Contract__c = contractInstance2.Id,
            ASI_CRM_Schedule_Date__c = Date.today().addMonths(1),
            ASI_CRM_Sponsorship__c = 300,
            ASI_CRM_Type__c = 'Cash Sponsorship',
            RecordTypeId = paymentRecTypeId
        ));

        lstTestPaymentSchedules.add( new ASI_CRM_Payment_Schedule__c(
            ASI_CRM_Contract__c = contractInstance2.Id,
            ASI_CRM_Sponsorship__c = 400,
            ASI_CRM_Percentof_achieved_Sales_Target__c = '15',
            ASI_CRM_Type__c = 'Cash Sponsorship',
            RecordTypeId = paymentRecTypeId
        ));

        insert lstTestPaymentSchedules;
    }

    static testMethod void testBatchWithData() {
        System.Test.startTest();
            Database.executeBatch(new ASI_CRM_SG_PymtSchedIssuanceNotif_Batch());
        System.Test.stopTest();
    }
}