objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>CSE_1_AccountAlteration_ARG</fullName>
        <active>true</active>
        <businessProcess>Account Alteration ARG</businessProcess>
        <label>Account Alteration ARG</label>
    </recordTypes>
    <recordTypes>
        <fullName>CSE_2_AccountAlteration_URU</fullName>
        <active>true</active>
        <businessProcess>Account Alteration ARG</businessProcess>
        <label>Account Alteration URU</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_ACCOUNT__c.object
<CustomObject>
    <label>LAT_ACCOUNT</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>LAT_ACCOUNT Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LAT_ACCOUNT</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_Case__c.object
<CustomObject>
    <fields>
        <fullName>LAT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LAT Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LAT_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abatimento de contrato não registrado</fullName>
                </value>
                <value>
                    <fullName>Abatimento parcial de devolução</fullName>
                </value>
                <value>
                    <fullName>Alt. agendamento</fullName>
                </value>
                <value>
                    <fullName>Alt. Bandeira</fullName>
                </value>
                <value>
                    <fullName>Alt. cliente pai</fullName>
                </value>
                <value>
                    <fullName>Alt. condição e instrumento de pagamento</fullName>
                </value>
                <value>
                    <fullName>Alt. dados bancários</fullName>
                </value>
                <value>
                    <fullName>Alt. descarga</fullName>
                </value>
                <value>
                    <fullName>Alt. e-mail da NFE</fullName>
                </value>
                <value>
                    <fullName>Alt. endereço faturamento</fullName>
                </value>
                <value>
                    <fullName>Alt. G/L cliente</fullName>
                </value>
                <value>
                    <fullName>Alt. informações de pedidos</fullName>
                </value>
                <value>
                    <fullName>Alt. inscrição estadual</fullName>
                </value>
                <value>
                    <fullName>Alt. janela de pedidos</fullName>
                </value>
                <value>
                    <fullName>Alt. limite de crédito</fullName>
                </value>
                <value>
                    <fullName>Alt. nome fantasia</fullName>
                </value>
                <value>
                    <fullName>Alt. Organização</fullName>
                </value>
                <value>
                    <fullName>Alt. paletização especial</fullName>
                </value>
                <value>
                    <fullName>Alt. prioridade faturamento</fullName>
                </value>
                <value>
                    <fullName>Alt. processo EDI</fullName>
                </value>
                <value>
                    <fullName>Alt. Proprietário</fullName>
                </value>
                <value>
                    <fullName>Alt. razão social</fullName>
                </value>
                <value>
                    <fullName>Alt. recebimento carga</fullName>
                </value>
                <value>
                    <fullName>Alt. Regional de Vendas</fullName>
                </value>
                <value>
                    <fullName>Alt. tipo de canal</fullName>
                </value>
                <value>
                    <fullName>Alt. tipo de veículo</fullName>
                </value>
                <value>
                    <fullName>Alt. transportadora</fullName>
                </value>
                <value>
                    <fullName>Alt. unidade de negócio</fullName>
                </value>
                <value>
                    <fullName>Análise/complementação de dados</fullName>
                </value>
                <value>
                    <fullName>Atraso na entrega</fullName>
                </value>
                <value>
                    <fullName>Solicitação de inativação de cliente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LAT_Case</label>
    <nameField>
        <label>Demanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT_Cases</pluralLabel>
    <recordTypes>
        <fullName>CSE_1_AccountAlteration_ARG</fullName>
        <active>true</active>
        <label>Account Alteration ARG</label>
    </recordTypes>
    <recordTypes>
        <fullName>CSE_2_AccountAlteration_URU</fullName>
        <active>true</active>
        <label>Account Alteration URU</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LAT_AR_Case_Update_Owner.cls
public class LAT_AR_Case_Update_Owner {

    /***
     * Nombre del metodo: UpdateCaseOwner
     * Descripcion: Cuando un Caso de inactivacion de cliente es creado por Inteligencia Comercial, 
     *              se debe cambiar el Owner al dueño de la Account
     * Desarrollador: nico@zimmic.com
     * Fecha: 21/08/2014
     * Modo: after insert
     ***/
     /********************************************************************************
    * 
    * MIGRACION LICENCIAS 
    * AUTHOR: ZIMMIC                     DATE: 02/11/2016
    * AUTHOR: ZIMMIC                     DATE: 05/12/2016
    *
    ********************************************************************************/
    public static void UpdateCaseOwner (List<Case> triggerNew){
         String recordTypeARG = Global_RecordTypeCache.getRtId('Case' + 'CSE_1_AccountAlteration_ARG');
         String recordTypeUY = Global_RecordTypeCache.getRtId('Case' + 'CSE_2_AccountAlteration_URU');
         String profileName = [SELECT Id, Name FROM Profile WHERE Id =: UserInfo.getProfileId()].Name;
         
         if(profileName.equals('ARG_Int Comercial') || profileName.equals('LAT_AR2_IntComercial')){
             List<id> tmpIds = new List<id>();
             List<CaseShare> toUpdate = new List<CaseShare>();
             
             for (Case c : triggerNew){
                 tmpIds.add(c.id);
             }
             List<Case> cases = [Select id,reason, RecordTypeId,Account.OwnerId from Case where id in: tmpIds];
             
             for (Case c : cases){
                 if ((recordTypeARG.equals(c.RecordTypeId)|| recordTypeUY.equals(c.RecordTypeId))
                     && (profileName.equals('ARG_Int Comercial') || profileName.equals('LAT_AR2_IntComercial')) 
                     && 'Solicitação de inativação de cliente'.equals(c.reason)) {
                         CaseShare newCaseShare = new CaseShare(
                            UserOrGroupId = c.Account.OwnerId,
                            CaseAccessLevel='Read',
                            CaseId = c.id
                        );
                        toUpdate.add(newCaseShare);
                 }
             }  
             insert toUpdate;
         }
         
    }


    //MIGRATED 02/11/2016 
    public static void UpdateCaseOwner (List<Lat_Case__c> triggerNew){
         String recordTypeARG = Global_RecordTypeCache.getRtId('LAT_Case__c' + 'CSE_1_AccountAlteration_ARG');
         String recordTypeUY = Global_RecordTypeCache.getRtId('LAT_Case__c' + 'CSE_2_AccountAlteration_URU');
         String profileName = [SELECT Id, Name FROM Profile WHERE Id =: UserInfo.getProfileId()].Name;
         
         if(profileName.equals('ARG_Int Comercial') || profileName.equals('LAT_AR2_IntComercial')){
             List<id> tmpIds = new List<id>();
             List<LAT_Case__Share> toUpdate = new List<LAT_Case__Share>();
             
             for (Lat_Case__c c : triggerNew){
                 tmpIds.add(c.id);
             }
             List<Lat_Case__c> cases = [Select id,LAT_Reason__c, RecordTypeId,LAT_Account__c,LAT_Account__r.OwnerId from Lat_Case__c where id in: tmpIds];
             
             for (Lat_Case__c c : cases){
                if ((recordTypeARG.equals(c.RecordTypeId)|| recordTypeUY.equals(c.RecordTypeId))
                 && (profileName.equals('ARG_Int Comercial') || profileName.equals('LAT_AR2_IntComercial'))
                 && 'Solicitação de inativação de cliente'.equals(c.LAT_Reason__c)) {
                    LAT_Case__Share newCaseShare = new LAT_Case__Share();
                    newCaseShare.UserOrGroupId = c.LAT_Account__r.OwnerId;
                    newCaseShare.AccessLevel='Read';
                    newCaseShare.ParentId  = c.id;
                    toUpdate.add(newCaseShare);
                 }
             }  
             insert toUpdate;
         }
         
    }

    public static void shareRecordsWithAccountOwner(List<Lat_Case__c> triggerNew){
            
        List<id> tmpIds = new List<id>();
        List<LAT_Case__Share> toUpdate = new List<LAT_Case__Share>();

        for (Lat_Case__c c : triggerNew){
             tmpIds.add(c.id);
        }
        List<Lat_Case__c> cases = [Select id, LAT_Account__c, LAT_Account__r.OwnerId from Lat_Case__c where id in: tmpIds];
         
        for (Lat_Case__c c : cases){
            LAT_Case__Share jobShr = new LAT_Case__Share();
            jobShr.ParentId  = c.id;
            jobShr.UserOrGroupId = c.LAT_Account__r.OwnerId;
            jobShr.AccessLevel='Read';
            jobShr.RowCause = 'Manual';
            toUpdate.add(jobShr);
        }

        if (!toUpdate.isEmpty()){

            try{
                Database.insert(toUpdate,false);
            }catch(exception ex){
                LAT_DebugUtil debugUtil = new LAT_DebugUtil();
                debugUtil.addData('Exception:' + ex.getMessage() + ' Line: ' + ex.getLineNumber() + ' Cause: ' + ex.getCause());
                debugUtil.setOrigin('LAT CASES');
                debugUtil.insertDebug();
            }
        }
    }

}