objects/Case.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>LAT_MX_CSE_AccountAlterationCreditAndCollections</fullName>
        <active>true</active>
        <businessProcess>LAT_MX Account Alteration</businessProcess>
        <label>MX Account Alteration - Credit And Collections</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CS006_DefaultUsers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>LAT_MX_UserName1__c</fullName>
        <inlineHelpText>Username of user from Mexico, that approves the &apos;Credit and Collections&apos; step of the Approval Process of records from Objects &apos;Credit Analysis&apos; and &apos;Case&apos; that are related to Accounts with Channels: WS, NFI, DFR, FEX or OTR.</inlineHelpText>
        <label>UserName 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>CS006 Default Users</label>
</CustomObject>

objects/LAT_ACCOUNT__c.object
<CustomObject>
    <label>LAT_ACCOUNT</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>LAT_ACCOUNT Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LAT_ACCOUNT</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_Case__c.object
<CustomObject>
    <fields>
        <fullName>LAT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LAT Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LAT_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LAT_Origin__c</fullName>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Demanda Interna PRB</fullName>
                    <default>true</default>
                    <label>Demanda Interna PRB</label>
                </value>
                <value>
                    <fullName>SAC</fullName>
                </value>
                <value>
                    <fullName>Solicitação do Cliente</fullName>
                </value>
                <value>
                    <fullName>Integração JDE</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abatimento de contrato não registrado</fullName>
                </value>
                <value>
                    <fullName>Abatimento parcial de devolução</fullName>
                </value>
                <value>
                    <fullName>Alt. agendamento</fullName>
                </value>
                <value>
                    <fullName>Alt. Bandeira</fullName>
                </value>
                <value>
                    <fullName>Alt. cliente pai</fullName>
                </value>
                <value>
                    <fullName>Alt. condição e instrumento de pagamento</fullName>
                </value>
                <value>
                    <fullName>Alt. dados bancários</fullName>
                </value>
                <value>
                    <fullName>Alt. descarga</fullName>
                </value>
                <value>
                    <fullName>Alt. e-mail da NFE</fullName>
                </value>
                <value>
                    <fullName>Alt. endereço faturamento</fullName>
                </value>
                <value>
                    <fullName>Alt. G/L cliente</fullName>
                </value>
                <value>
                    <fullName>Alt. informações de pedidos</fullName>
                </value>
                <value>
                    <fullName>Alt. inscrição estadual</fullName>
                </value>
                <value>
                    <fullName>Alt. janela de pedidos</fullName>
                </value>
                <value>
                    <fullName>Alt. limite de crédito</fullName>
                </value>
                <value>
                    <fullName>Alt. nome fantasia</fullName>
                </value>
                <value>
                    <fullName>Alt. Organização</fullName>
                </value>
                <value>
                    <fullName>Alt. paletização especial</fullName>
                </value>
                <value>
                    <fullName>Alt. prioridade faturamento</fullName>
                </value>
                <value>
                    <fullName>Alt. processo EDI</fullName>
                </value>
                <value>
                    <fullName>Alt. Proprietário</fullName>
                </value>
                <value>
                    <fullName>Alt. razão social</fullName>
                </value>
                <value>
                    <fullName>Alt. recebimento carga</fullName>
                </value>
                <value>
                    <fullName>Alt. Regional de Vendas</fullName>
                </value>
                <value>
                    <fullName>Alt. tipo de canal</fullName>
                </value>
                <value>
                    <fullName>Alt. tipo de veículo</fullName>
                </value>
                <value>
                    <fullName>Alt. transportadora</fullName>
                </value>
                <value>
                    <fullName>Alt. unidade de negócio</fullName>
                </value>
                <value>
                    <fullName>Análise/complementação de dados</fullName>
                </value>
                <value>
                    <fullName>Atraso na entrega</fullName>
                </value>
                <value>
                    <fullName>Payment Term Modification</fullName>
                </value>
                <value>
                    <fullName>Registration deposit cash payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acordo aprovado</fullName>
                </value>
                <value>
                    <fullName>Acordo rejeitado</fullName>
                </value>
                <value>
                    <fullName>Análise pendente</fullName>
                </value>
                <value>
                    <fullName>Aprovado</fullName>
                </value>
                <value>
                    <fullName>Cancelamento aprovado pelo cliente</fullName>
                </value>
                <value>
                    <fullName>Cancelamento encaminhado ao coordenador</fullName>
                </value>
                <value>
                    <fullName>Cancelamento encaminhado ao gerente</fullName>
                </value>
                <value>
                    <fullName>Cancelamento encaminhado ao Jurídico</fullName>
                </value>
                <value>
                    <fullName>Carta de não renovação entregue</fullName>
                </value>
                <value>
                    <fullName>Cláusulas encaminhadas para o gerente</fullName>
                </value>
                <value>
                    <fullName>Contrato não renovado</fullName>
                </value>
                <value>
                    <fullName>Contrato prorrogado</fullName>
                </value>
                <value>
                    <fullName>Distrato assinado encaminhado regional</fullName>
                </value>
                <value>
                    <fullName>Distrato encaminhado p/ diretor</fullName>
                </value>
                <value>
                    <fullName>Distrato encaminhado p/ o consultor</fullName>
                </value>
                <value>
                    <fullName>Distrato encaminhado para o coordenador</fullName>
                </value>
                <value>
                    <fullName>Distrato encaminhado para o gerente</fullName>
                </value>
                <value>
                    <fullName>Distrato entregue p/ assinatura cliente</fullName>
                </value>
                <value>
                    <fullName>Distrato entregue para o cliente</fullName>
                </value>
                <value>
                    <fullName>Doc. de prorrogação entregue ao cliente</fullName>
                </value>
                <value>
                    <fullName>Em análise - Controladoria</fullName>
                </value>
                <value>
                    <fullName>Em análise - Crédito e cobrança</fullName>
                </value>
                <value>
                    <fullName>Em análise - Customer Service</fullName>
                </value>
                <value>
                    <fullName>Em análise - Planejamento Comercial</fullName>
                </value>
                <value>
                    <fullName>Em andamento</fullName>
                </value>
                <value>
                    <fullName>Em aprovação</fullName>
                </value>
                <value>
                    <fullName>Em aprovação - Comercial</fullName>
                </value>
                <value>
                    <fullName>Em aprovação - Crédito e Cobrança</fullName>
                </value>
                <value>
                    <fullName>Em aprovação - Financeiro</fullName>
                </value>
                <value>
                    <fullName>Em aprovação - Vendas</fullName>
                </value>
                <value>
                    <fullName>Novo</fullName>
                    <default>true</default>
                    <label>Novo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alteração - Cadastro de cliente</fullName>
                </value>
                <value>
                    <fullName>Cadastro de clientes</fullName>
                </value>
                <value>
                    <fullName>Cancelamento de contrato</fullName>
                </value>
                <value>
                    <fullName>Inadimplência</fullName>
                </value>
                <value>
                    <fullName>Justificativa de inadimplência</fullName>
                </value>
                <value>
                    <fullName>Pergunta</fullName>
                </value>
                <value>
                    <fullName>Problema</fullName>
                </value>
                <value>
                    <fullName>Proposta de pagamento</fullName>
                </value>
                <value>
                    <fullName>Proposta não realizada</fullName>
                </value>
                <value>
                    <fullName>Solicitação de recurso</fullName>
                </value>
                <value>
                    <fullName>Technical Issue</fullName>
                    <default>true</default>
                    <label>Technical Issue</label>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Documentation</fullName>
                </value>
                <value>
                    <fullName>Question</fullName>
                </value>
                <value>
                    <fullName>Request Feature</fullName>
                </value>
                <value>
                    <fullName>Connection Issue</fullName>
                </value>
                <value>
                    <fullName>Billing Issue</fullName>
                </value>
                <value>
                    <fullName>Technical Issue - Advanced</fullName>
                </value>
                <value>
                    <fullName>Balance Inquiry</fullName>
                </value>
                <value>
                    <fullName>Billing Dispute</fullName>
                </value>
                <value>
                    <fullName>Bill Reprint - Email</fullName>
                </value>
                <value>
                    <fullName>Bill Reprint - Paper</fullName>
                </value>
                <value>
                    <fullName>Account Alteration ARG</fullName>
                </value>
                <value>
                    <fullName>Account Alteration URU</fullName>
                </value>
                <value>
                    <fullName>Overdue to attorneys</fullName>
                </value>
                <value>
                    <fullName>Statistical</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Credits and Collections</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LAT_Case</label>
    <nameField>
        <label>Demanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT_Cases</pluralLabel>
    <recordTypes>
        <fullName>LAT_MX_CSE_AccountAlterationCreditAndCollections</fullName>
        <active>true</active>
        <label>MX Account Alteration - Credit And Collections</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LAT_MX_AP01_Case_TEST.cls
/******************************************************************************
*   Company:Valuenet    Developers:Elena Schwarzböck       Date:09/10/2013    *
*******************************************************************************/
/********************************************************************************
* 
* MIGRACION LICENCIAS 
* AUTHOR: ZIMMIC                     DATE: 21/11/2016
*
********************************************************************************/
@istest
public with sharing class LAT_MX_AP01_Case_TEST {

   static testMethod void unitTest() {

        String rtOffMX = Global_RecordTypeCache.getRtId('Account' + 'LAT_MX_ACC_OffTrade');
        
        String UserId = UserInfo.getUserId();
        
        Account acc = new Account(
            Name = 'TEST',
            AccountNumber = '1000', 
            Type = 'Payer',
            Phone = '1-11-1111-1111',
            Fax = '11-1111-1111',
            Notes__c = 'TEST',
            AddressLine1_AR__c = 'TEST',
            CNPJ__c = 'LOZM701213E52',
            Corporate_Name__c = 'TEST',
            Channel__c = 'WS',
            Segmentation_Type_on_trade__c = 'MOP',
            RecordTypeId = rtOffMX,    
            LAT_MX_CreditAndCollectionsExecutive__c = UserId
        );
        try{insert acc;} catch(exception e){}
        
        String rtCase = Global_RecordTypeCache.getRtId('Case' + 'LAT_MX_CSE_AccountAlterationCreditAndCollections');
        
        Case caso = new Case(
            AccountId = acc.Id,
            RecordTypeId = rtCase,
            Type = 'Credits and Collections',
            Reason = 'Registration deposit cash payment',
            Origin = 'Demanda Interna PRB',
            Status = 'Novo',
            Description = 'test'
        );
        
        try{insert caso;} catch(exception e){}
                
        String userName = UserInfo.getUserName();
        
        CS006_DefaultUsers__c CsUserId = new CS006_DefaultUsers__c(
            Name = 'test',
            LAT_MX_UserName1__c = userName
        );
        
        try{insert CsUserId;} catch(exception e){}
        
        Case caso1 = new Case(
            AccountId = acc.Id,
            RecordTypeId = rtCase,
            Type = 'Credits and Collections',
            Reason = 'Payment Term Modification',
            Origin = 'Demanda Interna PRB',
            Status = 'Novo',
            Description = 'test'
        );
        
        try{insert caso1;} catch(exception e){}
        
        test.startTest();
        
        acc.LAT_MX_CreditAndCollectionsExecutive__c = null;
        acc.Channel__c = 'SS';
        try{update acc;} catch(exception e){}
        
         Case caso2 = new Case(
            AccountId = acc.Id,
            RecordTypeId = rtCase,
            Type = 'Credits and Collections',
            Reason = 'Payment Term Modification',
            Origin = 'Demanda Interna PRB',
            Status = 'Novo',
            Description = 'test'
        );
        
        try{insert caso2;} catch(exception e){}   
        
        test.stopTest();        
              
   }
   //MIGRATED 21/11/2016
   static testMethod void unitTestLATCase() {

        String rtOffMX = Global_RecordTypeCache.getRtId('Account' + 'LAT_MX_ACC_OffTrade');
        
        String UserId = UserInfo.getUserId();
        
        Account acc = new Account(
            Name = 'TEST',
            AccountNumber = '1000', 
            Type = 'Payer',
            Phone = '1-11-1111-1111',
            Fax = '11-1111-1111',
            Notes__c = 'TEST',
            AddressLine1_AR__c = 'TEST',
            CNPJ__c = 'LOZM701213E52',
            Corporate_Name__c = 'TEST',
            Channel__c = 'WS',
            Segmentation_Type_on_trade__c = 'MOP',
            RecordTypeId = rtOffMX,    
            LAT_MX_CreditAndCollectionsExecutive__c = UserId
        );
        try{insert acc;} catch(exception e){}
        
        String rtCase = Global_RecordTypeCache.getRtId('LAT_Case__c' + 'LAT_MX_CSE_AccountAlterationCreditAndCollections');
        
        LAT_Case__c caso = new LAT_Case__c(
            LAT_Account__c = acc.Id,
            RecordTypeId = rtCase,
            LAT_Type__c = 'Credits and Collections',
            LAT_Reason__c = 'Registration deposit cash payment',
            LAT_Origin__c = 'Demanda Interna PRB',
            LAT_Status__c = 'Novo',
            LAT_Description__c = 'test'
        );
        
        try{insert caso;} catch(exception e){}
                
        String userName = UserInfo.getUserName();
        
        CS006_DefaultUsers__c CsUserId = new CS006_DefaultUsers__c(
            Name = 'test',
            LAT_MX_UserName1__c = userName
        );
        
        try{insert CsUserId;} catch(exception e){}
        
        LAT_Case__c caso1 = new LAT_Case__c(
            LAT_Account__c = acc.Id,
            RecordTypeId = rtCase,
            LAT_Type__c = 'Credits and Collections',
            LAT_Reason__c = 'Payment Term Modification',
            LAT_Origin__c = 'Demanda Interna PRB',
            LAT_Status__c = 'Novo',
            LAT_Description__c = 'test'
        );
        
        try{insert caso1;} catch(exception e){}
        
        test.startTest();
        
        acc.LAT_MX_CreditAndCollectionsExecutive__c = null;
        acc.Channel__c = 'SS';
        try{update acc;} catch(exception e){}
        
         LAT_Case__c caso2 = new LAT_Case__c(
            LAT_Account__c = acc.Id,
            RecordTypeId = rtCase,
            LAT_Type__c = 'Credits and Collections',
            LAT_Reason__c = 'Payment Term Modification',
            LAT_Origin__c = 'Demanda Interna PRB',
            LAT_Status__c = 'Novo',
            LAT_Description__c = 'test'
        );
        
        try{insert caso2;} catch(exception e){}   
        
        test.stopTest();        
              
   }
}