objects/Checklist_de_visita__c.object
<CustomObject>
    <fields>
        <fullName>LAT_BR_ValidOnTradeChecklistGE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate whether this checklist has the valid GE for this month/client or not.</description>
        <label>Valid On Trade GE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Visita__c</fullName>
        <label>Visita</label>
        <referenceTo>Visitas__c</referenceTo>
        <relationshipLabel>Checklist de Visitas</relationshipLabel>
        <relationshipName>Planos_de_A_o_das_Visitas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Checklist de Visita</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist de Visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Gabarito_de_Execucao__c.object
<CustomObject>
    <fields>
        <fullName>Checklist_de_Visita__c</fullName>
        <label>Checklist de Visita</label>
        <referenceTo>Checklist_de_visita__c</referenceTo>
        <relationshipLabel>Gabaritos de Execução</relationshipLabel>
        <relationshipName>Gabaritos_de_Execucao</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ritual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Backbar__c</fullName>
        <label>Backbar</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Glorifier</fullName>
                </value>
                <value>
                    <fullName>Garrafão</fullName>
                </value>
                <value>
                    <fullName>Paredão</fullName>
                </value>
                <value>
                    <fullName>Barmat</fullName>
                </value>
                <value>
                    <fullName>Luminoso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Brigade_Persuasion__c</fullName>
        <label>Brigade Persuasion</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incentivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Brigade__c</fullName>
        <label>Brigade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Uniforme (Avental, Camiseta)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Cabin__c</fullName>
        <label>Cabin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mobiliário</fullName>
                </value>
                <value>
                    <fullName>Almofada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Embassy__c</fullName>
        <formula>IF( TEXT(Checklist_de_Visita__r.Visita__r.Conta__r.Segmentation_Type_on_trade__c) = &apos;Bar Agitado&apos;,
    IF( TEXT(LAT_BR_GDE_Products_Listed_on_Menues__c) = &apos;Sim&apos;
        &amp;&amp; LAT_BR_GDE_Visibility__c = 5
        &amp;&amp; LAT_BR_GDE_Persuation__c = 2 ,1,0)
,
    IF( TEXT(LAT_BR_GDE_Products_Listed_on_Menues__c) = &apos;Sim&apos;
        &amp;&amp; LAT_BR_GDE_Visibility__c = 4
        &amp;&amp; LAT_BR_GDE_Persuation__c = 2 ,1,0)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Embassy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_General_Enviroment__c</fullName>
        <label>General Enviroment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Luminoso</fullName>
                </value>
                <value>
                    <fullName>Outro Material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Menu__c</fullName>
        <formula>IF( TEXT(LAT_BR_GDE_Products_Listed_on_Menues__c) = &apos;Sim&apos; , 1, 0 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Menu</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Not_Listed_Brands__c</fullName>
        <label>Not Listed Brands</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABSOLUT</fullName>
                </value>
                <value>
                    <fullName>ELYX</fullName>
                </value>
                <value>
                    <fullName>CHIVAS</fullName>
                </value>
                <value>
                    <fullName>JAMESON</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Persuation__c</fullName>
        <formula>IF ( TEXT(LAT_BR_GDE_Brigade_Persuasion__c) != &apos;&apos; ,1,0 ) +
IF ( TEXT(LAT_BR_GDE_Action__c ) != &apos;&apos; ,1,0 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Persuation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Products_Listed_on_Menues__c</fullName>
        <description>Responder &quot;Sim&quot; se Absolut, Chivas, Elyx ou Jameson estão listados no cardápio. Caso contrário responder &quot;Não&quot; e informar os produtos no campo &quot;Qual marca não está listada?&quot;</description>
        <inlineHelpText>Responder &quot;Sim&quot; se Absolut, Chivas, Elyx ou Jameson estão listados no cardápio. Caso contrário responder &quot;Não&quot; e informar os produtos no campo &quot;Qual marca não está listada?&quot;</inlineHelpText>
        <label>Products Listed on Menues</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sim</fullName>
                </value>
                <value>
                    <fullName>Não</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Stage_DJBooth__c</fullName>
        <label>Stage / DJ Booth</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Luminoso</fullName>
                </value>
                <value>
                    <fullName>Garrafão</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Table__c</fullName>
        <label>Table</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Table Tent</fullName>
                </value>
                <value>
                    <fullName>Porta-Guardanapo</fullName>
                </value>
                <value>
                    <fullName>Balde</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_BR_GDE_Visibility__c</fullName>
        <formula>IF( TEXT(LAT_BR_GDE_General_Enviroment__c) != &apos;&apos; , 1, 0 ) +
IF( TEXT(LAT_BR_GDE_Backbar__c) != &apos;&apos; , 1, 0 ) +
IF( TEXT(LAT_BR_GDE_Stage_DJBooth__c) != &apos;&apos; , 1, 0 ) +
IF( TEXT(LAT_BR_GDE_Table__c) != &apos;&apos; , 1, 0 ) +
IF( TEXT(LAT_BR_GDE_Brigade__c) != &apos;&apos; , 1, 0 ) +
IF( TEXT(LAT_BR_GDE_Cabin__c) != &apos;&apos; , 1, 0 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Visibility</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Gabarito de Execução</label>
    <nameField>
        <displayFormat>GE{0000000}</displayFormat>
        <label>Nome do Gabarito de Execução</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gabaritos de Execução</pluralLabel>
    <recordTypes>
        <fullName>LAT_BR_GDE_On_Trade</fullName>
        <active>true</active>
        <label>LAT_BR On Trade</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_CRP_Custom_Report__c.object
<CustomObject>
    <fields>
        <fullName>LAT_ReportName__c</fullName>
        <label>Report Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_VisualForceName__c</fullName>
        <label>VisualForceName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Custom Report</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Custom Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Planejamento__c.object
<CustomObject>
    <fields>
        <fullName>Ano_de_Referencia__c</fullName>
        <label>Ano de Referência</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                    <default>true</default>
                    <label>2014</label>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>M_s_de_Ref_rencia__c</fullName>
        <label>Mês de Referência</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Janeiro</fullName>
                </value>
                <value>
                    <fullName>Fevereiro</fullName>
                </value>
                <value>
                    <fullName>Março</fullName>
                </value>
                <value>
                    <fullName>Abril</fullName>
                </value>
                <value>
                    <fullName>Maio</fullName>
                </value>
                <value>
                    <fullName>Junho</fullName>
                </value>
                <value>
                    <fullName>Julho</fullName>
                </value>
                <value>
                    <fullName>Agosto</fullName>
                </value>
                <value>
                    <fullName>Setembro</fullName>
                </value>
                <value>
                    <fullName>Outubro</fullName>
                </value>
                <value>
                    <fullName>Novembro</fullName>
                </value>
                <value>
                    <fullName>Dezembro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Planejamento de Visita</label>
    <nameField>
        <label>Nome do Planejamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planejamentos de Visitas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Visitas__c.object
<CustomObject>
    <description>Visita de cliente</description>
    <label>Visita</label>
    <nameField>
        <label>Nome da Visita</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LAT_BR_VFC27_OnTradeExecution.cls
public with sharing class LAT_BR_VFC27_OnTradeExecution {

	private Map<Integer, String> monthOfYear = new Map<Integer, String>{1 => 'Janeiro', 2 => 'Fevereiro',3 => 'Março',
															4 => 'Abril',5 => 'Maio',6 => 'Junho',7 => 'Julho',
															8 => 'Agosto',9 => 'Setembro',10 => 'Outubro',11 => 'Novembro',
															12 => 'Dezembro'};
	String rtOffBRGab = Global_RecordTypeCache.getRtId('Gabarito_de_Execucao__c' + 'LAT_BR_GDE_On_Trade');
														
	public Account dummyAccountFilters {get; set;}
	public Planejamento__c dummyPlanFilters {get; set;}
	
	public transient Boolean ran {get;set;}
	public transient String reportName {get;set;}
	
    public Boolean ExportToExcel {get;set;}
	public Boolean hasAccess {get;set;}

	public List<Gabarito_de_Execucao__c> geList {get; set;}

	public LAT_BR_VFC27_OnTradeExecution() {
		ran = false;
        hasAccess = false;
        this.ExportToExcel = false;
        string idFromReport = ApexPages.currentPage().getParameters().get('IdRep');
        
        LAT_CRP_Custom_Report__c crp;
        try{crp = [SELECT Id, LAT_VisualForceName__c, LAT_ReportName__c FROM LAT_CRP_Custom_Report__c WHERE id =: idFromReport];}catch(Exception e){}
        if(crp != null && crp.LAT_VisualForceName__c == 'LAT_BR_VFP27_OnTradeExecution'){
            hasAccess = true;
            reportName = crp.LAT_ReportName__c;
        }else{
            return;
        }

		this.dummyAccountFilters = new Account(OwnerId = UserInfo.getUserId());
		this.dummyPlanFilters = new Planejamento__c(OwnerId = UserInfo.getUserId(), 
													Ano_de_Referencia__c = String.valueOf(Date.today().year()),
													M_s_de_Ref_rencia__c = monthOfYear.get(Date.today().month()));

		this.calculateReport();		
	}

	public PageReference calculateReport() {
		this.geList = this.getRecords(dummyAccountFilters.LAT_BR_RegionalClientOnPremise__c);
		return null;
	}

	public List<Gabarito_de_Execucao__c> getRecords(string regional) {
		String baseQuery = 'SELECT id, Name, Checklist_de_Visita__r.Visita__r.Conta__r.LAT_BR_RegionalClientOnPremise__c, Checklist_de_Visita__r.Visita__r.Conta__r.Owner.Name, ' +
								' Checklist_de_Visita__r.Visita__r.Conta__r.Revenue_City__r.Name,  Checklist_de_Visita__r.Visita__r.Conta__r.Revenue_UF__c,' + 
								' Checklist_de_Visita__r.Visita__r.Conta__r.Name, Checklist_de_Visita__r.Visita__r.Conta__r.Subtype__c, Checklist_de_Visita__r.Visita__r.Conta__r.Segmentation_Type_on_trade__c,' + 
								' Checklist_de_Visita__r.Visita__r.Conta__r.Rating, Checklist_de_Visita__r.Visita__r.Name, Checklist_de_Visita__r.Visita__c,' + 
								' Checklist_de_Visita__r.Visita__r.Conta__r.Sub_Channel_Rating__r.Name, Checklist_de_Visita__r.Visita__r.Conta__r.Type,' +
								' LAT_BR_GDE_General_Enviroment__c, LAT_BR_GDE_Backbar__c, LAT_BR_GDE_Stage_DJBooth__c, LAT_BR_GDE_Table__c, LAT_BR_GDE_Brigade__c,' +
								' LAT_BR_GDE_Cabin__c, LAT_BR_GDE_Brigade_Persuasion__c, LAT_BR_GDE_Action__c, LAT_BR_GDE_Products_Listed_on_Menues__c,' +
								' LAT_BR_GDE_Not_Listed_Brands__c, LAT_BR_GDE_Visibility__c, LAT_BR_GDE_Persuation__c, LAT_BR_GDE_Menu__c, LAT_BR_GDE_Embassy__c,' +
								' Checklist_de_Visita__r.Visita__r.Conta__r.Rating_segmentation_targert_market__c' +
							' FROM Gabarito_de_Execucao__c WHERE' +
								' RecordTypeId = \'' + rtOffBRGab + '\'' +
								' AND Checklist_de_Visita__r.LAT_BR_ValidOnTradeChecklistGE__c = true' +
								' AND Checklist_de_Visita__r.Visita__r.Planejamento__r.M_s_de_Ref_rencia__c = \'' + dummyPlanFilters.M_s_de_Ref_rencia__c + '\'' +
								' AND Checklist_de_Visita__r.Visita__r.Planejamento__r.Ano_de_Referencia__c = \'' + dummyPlanFilters.Ano_de_Referencia__c + '\'';
								

		if (dummyAccountFilters.Regional_Manager__c != null) {
			baseQuery += ' AND Checklist_de_Visita__r.Visita__r.Planejamento__r.OwnerId = \'' + dummyAccountFilters.Regional_Manager__c + '\'';
		}
		if (regional != null && regional != '') {
			baseQuery += ' AND Checklist_de_Visita__r.Visita__r.Conta__r.LAT_BR_RegionalClientOnPremise__c = \'' + regional + '\'';
		}

		return Database.query(baseQuery);
	}


	public PageReference exportToExcel() {
		this.ExportToExcel = true;
		return null;
	}
}