objects/CLV_ChecklistVisita_ARG__c.object
<CustomObject>
    <fields>
        <fullName>Visit_AR__c</fullName>
        <label>Visit</label>
        <referenceTo>Visitas__c</referenceTo>
        <relationshipLabel>Checklist de Visitas ARG</relationshipLabel>
        <relationshipName>LAT_Checklist_de_Visitas_ARG</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Checklist de Visita ARG</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Nombre de Checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist de Visitas ARG</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visitas__c.object
<CustomObject>
    <description>Visita de cliente</description>
    <label>Visita</label>
    <nameField>
        <label>Nome da Visita</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitas</pluralLabel>
    <recordTypes>
        <fullName>LAT_MX_VTS_ClosedVisit</fullName>
        <active>true</active>
        <label>MX Closed Visit</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LAT_MX_VFC07_ChecklistDeleteValExt.cls
/********************************************************************
* Company: Valuenet 
* Desarrollador: Elena J. Schwarzböck
* Nombre del pagina: LAT_MX_VFP07_ChecklistDeleteValidation
* Descripcion: extencion de la pagina LAT_MX_VFP07_ChecklistDeleteValidation
* Fecha: 14/03/2014 
*********************************************************************/

public with sharing class LAT_MX_VFC07_ChecklistDeleteValExt{

    public LAT_MX_VFC07_ChecklistDeleteValExt(ApexPages.StandardController controller){
    
    }

    public PageReference doValidationDelete(){
    
        String checkId = ApexPages.currentPage().getParameters().get('id');
        String retURL = ApexPages.currentPage().getParameters().get('retURL');        
        String pageURL = ApexPages.currentPage().getURL();
        
        PageReference returnURL = new PageReference(retURL);

        CLV_ChecklistVisita_ARG__c check = [SELECT Id, RecordTypeId, Visit_AR__r.RecordTypeId FROM CLV_ChecklistVisita_ARG__c WHERE Id =: checkId];
        
        if(check.Visit_AR__r.RecordTypeId == Global_RecordTypeCache.getRtId('Visitas__c' + 'LAT_MX_VTS_ClosedVisit')){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, label.LAT_MX_VFP07_00001));
            //LAT_MX_VFP07_00001: No se puede eliminar el checklist si la visita esta cerrada.
            returnURL = null;   
        }else{
            try{
                delete check;
            }catch(DMLException e){
                ApexPages.addMessages(e);
                return null;
            }
        }
       return returnURL; 
    }

}