objects/CS001_JDEInterfaceCredentials__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>UseIMM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Usage of IMM if unchecked use ME</description>
        <inlineHelpText>Usage of IMM if unchecked use ME</inlineHelpText>
        <label>UseIMM</label>
        <type>Checkbox</type>
    </fields>
    <label>CS001_JDEInterfaceCredentials</label>
</CustomObject>

objects/LAT_Contract__c.object
<CustomObject>
    <description>New LAT Object for Contracts</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Em elaboração</fullName>
                </value>
                <value>
                    <fullName>Em aprovação</fullName>
                </value>
                <value>
                    <fullName>Aprovado</fullName>
                </value>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Aditado</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
                <value>
                    <fullName>Em cancelamento</fullName>
                </value>
                <value>
                    <fullName>Finalizado</fullName>
                </value>
                <value>
                    <fullName>Não aprovado</fullName>
                </value>
                <value>
                    <fullName>Contrato Prorrogado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BR Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>LAT_Contracts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_ContractWorflow__c.object
<CustomObject>
    <fields>
        <fullName>WF__c</fullName>
        <label>Tipo WF</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkflowNumber__c</fullName>
        <label>Nr Atividade</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Atividades IMM</label>
    <nameField>
        <displayFormat>ACTIMM-{000000}</displayFormat>
        <label>ID Atividade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Atividades IMM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LAT_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Ammount__c</fullName>
        <label>Valor</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApprovedPayment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pagamento aprovado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EventPaymentCreatedAfterSigning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EventPaymentCreatedAfterSigning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IDMe__c</fullName>
        <label>IDPagoIMM</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDPagoJDE__c</fullName>
        <label>ID Pago JDE</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_Contract__c</fullName>
        <label>Número do contrato</label>
        <referenceTo>LAT_Contract2__c</referenceTo>
        <relationshipLabel>Investimentos, Bonificações e Pagamentos</relationshipLabel>
        <relationshipName>LAT_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LAT_IsCommCondParentPayment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Parent Commercial Condition Payment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ParentPayment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ParentPayment</label>
        <referenceTo>LAT_Payment__c</referenceTo>
        <relationshipLabel>Investimentos, Bonificações e Pagamentos</relationshipLabel>
        <relationshipName>Investimentos_Bonifica_es_e_Pagamentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentDateDone__c</fullName>
        <label>Data de pagamento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agrupamento de produto</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LAT_ReferenceProductGrouping__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Pagamento Produto</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LAT_ReferenceProductGrouping__c</referenceTo>
        <relationshipLabel>Investimentos, Bonificações e Pagamentos</relationshipLabel>
        <relationshipName>LAT_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sku_at_Integration__c</fullName>
        <label>SKU Referência</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_IMM_Linea__c</fullName>
        <label>Status Linha JDE</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>C</fullName>
                    <label>Cancelado</label>
                </value>
                <value>
                    <fullName>E</fullName>
                    <label>Efetivo</label>
                </value>
                <value>
                    <fullName>Em Aprovação</fullName>
                </value>
                <value>
                    <fullName>Erro Integração</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Integrado</label>
                </value>
                <value>
                    <fullName>Pago</fullName>
                    <isActive>false</isActive>
                    <label>Pago</label>
                </value>
                <value>
                    <fullName>P</fullName>
                    <default>true</default>
                    <label>Pendente</label>
                </value>
                <value>
                    <fullName>Previsto</fullName>
                    <isActive>false</isActive>
                    <label>Previsto</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>Reprovado</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volumen__c</fullName>
        <label>Volume (CA\BT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WF__c</fullName>
        <formula>IF(NOT(ISNULL(WorkflowME__c)), IF(NOT(ISBlank(WorkflowME__r.WF__c)),WorkflowME__r.WF__c,&apos;Sem DA cadastrada no CRM&apos; ), &apos;Sem DA cadastrada no CRM&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tipo Workflow</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkflowME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ID Atividade</label>
        <referenceTo>LAT_ContractWorflow__c</referenceTo>
        <relationshipLabel>Investimentos, Bonificações e Pagamentos</relationshipLabel>
        <relationshipName>Investimentos_Bonifica_es_e_Pagamentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>productValue__c</fullName>
        <label>Valor Produto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Investimentos, Bonificações e Pagamentos</label>
    <nameField>
        <displayFormat>IBP-{0000}</displayFormat>
        <label>ID Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investimentos, Bonificações e Pagamentos</pluralLabel>
    <recordTypes>
        <fullName>LAT_PagamentoDinheiro</fullName>
        <active>true</active>
        <label>Pagamento Dinheiro</label>
    </recordTypes>
    <recordTypes>
        <fullName>LAT_PagamentoProduto</fullName>
        <active>true</active>
        <label>Pagamento Produto</label>
    </recordTypes>
    <recordTypes>
        <fullName>LAT_PaymentGroup</fullName>
        <active>true</active>
        <description>Grouping of payments to approve payments in the external service</description>
        <label>Payment Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_Product__c.object
<CustomObject>
    <fields>
        <fullName>LAT_ProductCode__c</fullName>
        <description>Product Code</description>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LAT Product</label>
    <nameField>
        <label>LAT Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LAT_ReferenceProduct__c.object
<CustomObject>
    <fields>
        <fullName>LAT_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Products selected</description>
        <label>SKU Ref</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LAT_Product__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>BRA Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LAT_Product__c</referenceTo>
        <relationshipLabel>LAT_Reference Products</relationshipLabel>
        <relationshipName>LAT_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReferenceGrouping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agrupamento</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8) OR (9 AND 10)</booleanFilter>
            <filterItems>
                <field>LAT_ReferenceProductGrouping__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Coleta SellOut (OFF)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Coleta SellOut (OFF)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Coleta Volume (ON)</value>
            </filterItems>
            <filterItems>
                <field>LAT_ReferenceProductGrouping__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Coleta Volume (ON)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volume Contrato</value>
            </filterItems>
            <filterItems>
                <field>LAT_ReferenceProductGrouping__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Volume Contrato</value>
            </filterItems>
            <filterItems>
                <field>LAT_ReferenceProductGrouping__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Coleta NF (ON)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Coleta NF (ON)</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Pagamento Produto</value>
            </filterItems>
            <filterItems>
                <field>LAT_ReferenceProductGrouping__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Pagamento Produto</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LAT_ReferenceProductGrouping__c</referenceTo>
        <relationshipLabel>Reference Products</relationshipLabel>
        <relationshipName>LAT_ReferenceProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Product</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LAT_ReferenceProductGrouping__c.object
<CustomObject>
    <label>Agrupamento Produtos</label>
    <nameField>
        <label>Product Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agrupamentos Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LAT_CheckPaymentStatusOnME_Batch.cls
global class LAT_CheckPaymentStatusOnME_Batch implements Database.Batchable < sObject > ,
Database.AllowsCallouts {

	String query;
	

	global LAT_CheckPaymentStatusOnME_Batch() {

}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		CS001_JDEInterfaceCredentials__c setting = CS001_JDEInterfaceCredentials__c.getInstance('Brasil');
		if (!setting.UseIMM__c) {
			query = 'SELECT Id, Status__c, IDMe__c,';
            query+= 'ApprovedPayment__c, LAT_Contract__c, RecordType.DeveloperName, WorkflowME__r.WorkflowNumber__c, WorkflowME__r.WF__c ';
			query+= 'FROM LAT_Payment__c where IDMe__c <> null AND Status__c <> \'E\' ';
		} else {
			//query = 'SELECT Id, Status__c, IDMe__c,IDPagoJDE__c, ApprovedPayment__c,productValue__c, LAT_Contract__c, (Select id, ProductGroup__r.name, ProductGroup__c,productValue__c, Volumen__c,Status__c, IDMe__c,IDPagoJDE__c, recordType.DeveloperName from Investimentos_Bonifica_es_e_Pagamentos__r), RecordType.DeveloperName, WorkflowME__r.WorkflowNumber__c, WorkflowME__r.WF__c FROM LAT_Payment__c where IDMe__c <> null AND Status__c <> \'E\' ';
            query = 'SELECT Id, Status__c,Sku_at_Integration__c, ';
            query+= 'IDMe__c,Status_IMM_Linea__c,IDPagoJDE__c,Ammount__c, ApprovedPayment__c,productValue__c, LAT_Contract__c,';
            query+= '(Select id,Name, ProductGroup__r.name, ProductGroup__c,productValue__c, Volumen__c,Status__c, IDMe__c,IDPagoJDE__c, recordType.DeveloperName,Status_IMM_Linea__c,Sku_at_Integration__c, EventPaymentCreatedAfterSigning__c, LAT_IsCommCondParentPayment__c from Investimentos_Bonifica_es_e_Pagamentos__r), ';
            query+= 'RecordType.DeveloperName, WorkflowME__r.WorkflowNumber__c, WorkflowME__r.WF__c FROM LAT_Payment__c where (ParentPayment__c = null or (LAT_IsCommCondParentPayment__c =true and EventPaymentCreatedAfterSigning__c = true)) and IDMe__c!=null and IDMe__c!=\'\' AND Status__c <> \'E\'';
		
		}

		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List < sObject > scope) {

		CS001_JDEInterfaceCredentials__c setting = CS001_JDEInterfaceCredentials__c.getInstance('Brasil');
		List < LAT_Payment__c > pagamentos = 
            (List < LAT_Payment__c > ) scope;
		List < LAT_Payment__c > toUpdate = 
            new List < LAT_Payment__c > ();

		system.debug('scope++' + pagamentos);
		for (LAT_Payment__c p: pagamentos) {

			System.debug('%%%%%%%%%%%%  pagamhento : ' + p);
			String statusME;
			if (p.RecordType.DeveloperName == 'LAT_PagamentoDinheiro') {
				//Consulto el servicio de ME para Payments del tipo Check
				if (!setting.UseIMM__c) {
					LAT_CheckStatusPaymentMoneyWS.WSConsultarPagtoChequeSoapBindingQSPort request = 
                        new LAT_CheckStatusPaymentMoneyWS.WSConsultarPagtoChequeSoapBindingQSPort();
					request.timeout_x = 120000;

					LAT_CheckStatusPaymentMoneyWS.SdtMsg message 
                        = new LAT_CheckStatusPaymentMoneyWS.SdtMsg();
					LAT_CheckStatusPaymentMoneyWS.WSConsultarPagtoCheque_ExecuteResponse_element responseHandler = new LAT_CheckStatusPaymentMoneyWS.WSConsultarPagtoCheque_ExecuteResponse_element();
					responseHandler = request.Execute(1, 81, p.WorkflowME__r.WF__c, Integer.valueOf(p.WorkflowME__r.WorkflowNumber__c), Integer.valueOf(p.IDMe__c));
					//responseHandler = request.Execute(1, 81, 'CI', 224, Integer.valueOf(p.IDMe__c));
					//(Integer Paicod,Integer Empcod,String Tdocod,Integer Domnro,Integer Seqreq)
					System.debug('=======================\n message Money: ' + responseHandler + '\n=======================');
					if (!Test.isRunningTest()) {
						if (responseHandler.Status != null && responseHandler.Status != '') {
							statusME = responseHandler.Status;
						}
					} else {
						statusME = 'E';
					}
				} else {
					try {
						LAT_BR_IMM_RestCallHandler.GenericBodyIMM resp = LAT_BR_IMM_RestCallHandler.getCashPayment(p.IDMe__c);

						if (LAT_IMM_IntegrateService.updatePaymentFields(resp, p)){
							toUpdate.add(p);
							System.debug('%%% agrego a toUpdate p.Id: ' + p.Id);
							for (LAT_Payment__c childpay: p.Investimentos_Bonifica_es_e_Pagamentos__r) {
								System.debug('%%% agrego a toUpdate p.Id: ' + childpay.Id);
								toUpdate.add(childpay);
							}
						}

					} catch (LAT_BR_IMM_RestCallHandler.IMMException e){
						system.debug('Error en obtener Datos: +' + p.Id);
					} catch (Exception e) {
						system.debug('Error desconocido para: +' + p.Id);
						system.debug('Error desconocido para: +' + e.getStackTraceString());
					}
					// CALL IMMM SERV
				}

			} else if (p.RecordType.DeveloperName == 'LAT_PagamentoProduto') {
				system.debug('LAT_PagamentoProduto++');
				if (!setting.UseIMM__c) {
					//Consulto el servicio de ME para Payments del tipo Producto
					LAT_CheckStatusPaymentProductWS.WSConsultarPagtoProdutoSoapBindingQSPort request = 
                        new LAT_CheckStatusPaymentProductWS.WSConsultarPagtoProdutoSoapBindingQSPort();
					request.timeout_x = 120000;
					LAT_CheckStatusPaymentProductWS.SdtMsg message = new LAT_CheckStatusPaymentProductWS.SdtMsg();
					LAT_CheckStatusPaymentProductWS.WSConsultarPagtoProduto_ExecuteResponse_element responseHandler = 
                        new LAT_CheckStatusPaymentProductWS.WSConsultarPagtoProduto_ExecuteResponse_element();
					// to do, add try catch
					responseHandler = request.Execute(1, 81, p.WorkflowME__r.WF__c, Integer.valueOf(p.WorkflowME__r.WorkflowNumber__c), Integer.valueOf(p.IDMe__c));
					//responseHandler = request.Execute(1, 81, 'CI', 224, Integer.valueOf(p.IDMe__c));
					System.debug('=======================\n message Prod: ' + responseHandler + '\n=======================');
					if (!Test.isRunningTest()) {
						if (responseHandler.Produtos.Produtos_ProdutosItem != null) {
							statusME = responseHandler.Produtos.Produtos_ProdutosItem[0].Status;
						}
					} else {
						statusME = 'E';
					}
				} else {

					try{
						LAT_BR_IMM_RestCallHandler.GenericBodyIMM resp = LAT_BR_IMM_RestCallHandler.getFreeGood(p.IDMe__c);
						if (LAT_IMM_IntegrateService.updatePaymentFields(resp, p)){
							System.debug('%%% agrego a toUpdate p.Id: ' + p.Id);
							toUpdate.add(p);
						}
					} catch (LAT_BR_IMM_RestCallHandler.IMMException e){
						system.debug('Error en obtener Datos: +' + p.Id);
					} catch (Exception e) {
						system.debug('Error desconocido para: +' + p.Id);
						system.debug('Error desconocido para: +' + e.getStackTraceString());
					}
					// call imm service
				}

			} else if (setting.UseIMM__c && p.RecordType.DeveloperName == 'LAT_PaymentGroup') {
				system.debug('paymentGroup++');
				if (p.Ammount__c != null && p.Ammount__c != 0) {
					system.debug('amonnt no zer++');
					try {
						LAT_BR_IMM_RestCallHandler.GenericBodyIMM resp = LAT_BR_IMM_RestCallHandler.getCashPayment(p.IDMe__c);
						if (LAT_IMM_IntegrateService.updatePaymentGroupDinheroFields(resp, p)){
							System.debug('%%% agrego a toUpdate p.Id: ' + p.Id);
							toUpdate.add(p);
						}
						for (LAT_Payment__c childpay: p.Investimentos_Bonifica_es_e_Pagamentos__r) {
								System.debug('%%% agrego a toUpdate childpay: ' + childpay.Id);
								toUpdate.add(childpay);
							}
					} catch (LAT_BR_IMM_RestCallHandler.IMMException e){
						system.debug('Error en obtener Datos: +' + p.Id);
					} catch (Exception e) {
						system.debug('Error desconocido para: +' + p.Id);
						system.debug('Error desconocido para: +' + e.getStackTraceString());
					}

				} else {
					system.debug('amonnt zero++');
					try {
						LAT_BR_IMM_RestCallHandler.GenericBodyIMM resp = LAT_BR_IMM_RestCallHandler.getFreeGood(p.IDMe__c);
						if (LAT_IMM_IntegrateService.updatePaymentGroupProductosFields(resp, p)){
							system.debug('amonnt zero2++');
							System.debug('%%% agrego a toUpdate p.Id: ' + p.Id);
							toUpdate.add(p);
						}	
						for (LAT_Payment__c childpay: p.Investimentos_Bonifica_es_e_Pagamentos__r) {
							System.debug('%%% agrego a toUpdate p.Id: ' + childpay.Id);
							if(childpay.LAT_IsCommCondParentPayment__c && childpay.RecordType.DeveloperName == 'LAT_PagamentoDinheiro'){
								continue;
							}
							toUpdate.add(childpay);
						}
					} catch (LAT_BR_IMM_RestCallHandler.IMMException e){
						system.debug('Error en obtener Datos: +' + p.Id);
					} catch (Exception e) {
						system.debug('Error desconocido para: +' + p.Id);
						system.debug('Error desconocido para: +' + e.getStackTraceString());
					}
					
				}

			}

			// check if update is needed
			if (!setting.UseIMM__c) {
				if (statusME != p.Status__c) {

					p.Status__c = statusME;
					if (statusME == 'E') {
						p.PaymentDateDone__c = Date.today();
					}
					System.debug('%%% agrego a toUpdate p.Id: ' + p.Id);
					toUpdate.add(p);
				}
			}
		}
		Integer i = 0;
		for (LAT_Payment__c toup:toUpdate){
			system.debug('pagamento1++++' + i);
			i++;
			system.debug(toup.Status__c );
			system.debug(toup.Name );
			system.debug(toup.RecordType.DeveloperName );
			system.debug(toup.productValue__c);
		}
		update toUpdate;
	}




	/**public void generateSkuMap(List < LAT_Payment__c > payments) {
		Set < Id > products = new Set < Id > ();
		for (LAT_Payment__c pay: payments) {
			products.add(pay.ProductGroup__c);
		}

		List < LAT_ReferenceProduct__c > referenceProducts = [SELECT Id, Name, LAT_Product__c, LAT_Product__r.LAT_ProductCode__c, ReferenceGrouping__c FROM
		LAT_ReferenceProduct__c where ReferenceGrouping__c IN: products];

		Map < String,
		Integer > productsSKU = new Map < String,
		Integer > ();
		for (LAT_ReferenceProduct__c lrg: referenceProducts) {
			productsSKU.put(lrg.ReferenceGrouping__c, Integer.valueOf(lrg.LAT_Product__r.LAT_ProductCode__c));
		}
	}*/

	global void finish(Database.BatchableContext BC) {
		System.debug('Terminó el Batch de chequeo de Status de Pagamentos en ME/IMM. Gracias por su atención. :) by CantegrileArte & PandaSoft');
	}

	public static LAT_BR_IMM_RestCallHandler.GenericBodyIMM getMockCashPayment(){
    	String json=		'{';
		json +='    "id": 175,';
		json +='    "type": "CP",';
		json +='    "documentType": "CP",';
		json +='    "description": "Lorem Ipsum",';
		json +='    "dateRequest": "2017-09-17T08:00:00.000Z",';
		json +='    "dateApproval": null,';
		json +='    "jdeStatus": "-",';
		json +='    "userName": "BSOUZA01 - Bruno Souza",';
		json +='    "login": "BSOUZA01",';
		json +='    "jdeId": "234234234",';
		json +='    "idErp": null,';
		json +='    "erpDocumentType": null,';
		json +='    "amount": 0,';
		json +='    "indBoi": 0,';
		json +='    "idAttachment": null,';
		json +='    "amountPending": 0,';
		json +='    "amountReceived": 0,';
		json +='    "dateAccount": null,';
		json +='    "accountBatchNumber": null,';
		json +='    "subarea": {';
		json +='        "idSubarea": 9';
		json +='    },';
		json +='    "status": {';
		json +='        "idStatus": 4,';
		json +='        "description": "CRIADO"';
		json +='    },';
		json +='    "activity": {';
		json +='        "idActivity": 1';
		json +='    },';
		json +='    "currency": {';
		json +='        "idCurrency": 1,';
		json +='        "exchangeRate": 1,';
		json +='        "currencyCode": "BRL",';
		json +='        "currencyName": "Brazil - Real"';
		json +='    },';
		json +='    "conceptoGasto": {';
		json +='        "idConceptoGasto": 207,';
		json +='        "description": "SERVICO CRIACAO FOLHETOS SIMPLES POR PAGINA"';
		json +='    },';
		json +='    "provider": {';
		json +='        "id": 51557,';
		json +='        "code": 16274,';
		json +='        "providerName": "CIA BRASILEIRA DE DISTRIBUICAO"';
		json +='    },';
		json +='    "almacen": {';
		json +='        "idAlmacen": 25,';
		json +='        "description": "Sao Paulo"';
		json +='    }';
		json +='}';
		LAT_BR_IMM_RestCallHandler.GenericBodyIMM obj = (LAT_BR_IMM_RestCallHandler.GenericBodyIMM) System.JSON.deserialize(json, LAT_BR_IMM_RestCallHandler.GenericBodyIMM.class);
		return obj;
    }

}