objects/EUR_CRM_PRS_Group_Outlet_Type__c.object
<CustomObject>
    <description>This is created for the new approach for PROS and PROFS -  “PRS” (Pernod-Ricard Segmentation).

PR BG is the first country to use it.</description>
    <fields>
        <fullName>EUR_CRM_PRS_Group_Outlet_Name__c</fullName>
        <label>PRS Group Outlet Type Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Night Club</fullName>
                </value>
                <value>
                    <fullName>High Energy Bar</fullName>
                </value>
                <value>
                    <fullName>Low Energy Bar</fullName>
                </value>
                <value>
                    <fullName>Hyper/Supermarket</fullName>
                </value>
                <value>
                    <fullName>Convenience</fullName>
                </value>
                <value>
                    <fullName>Cash &amp; Carry</fullName>
                </value>
                <value>
                    <fullName>Discounters</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Liquor Specialists</fullName>
                </value>
                <value>
                    <fullName>Traditional Off Trade</fullName>
                </value>
                <value>
                    <fullName>Nightclub</fullName>
                    <isActive>false</isActive>
                    <label>Nightclub</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PRS Group Outlet Type (EU)</label>
    <nameField>
        <displayFormat>PRS-GO-{00000}</displayFormat>
        <label>PRS Group Outlet Type No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRS Group Outlet Types (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_GB_PRS_On_Trade_Group_Outlet_Type</fullName>
        <active>true</active>
        <label>EUR GB PRS On Trade Group Outlet Type</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_PRS_Seg_Aspect__c.object
<CustomObject>
    <description>This is created for the new approach for PROS and PROFS -  “PRS” (Pernod-Ricard Segmentation).


PR BG is the first country to use it.</description>
    <fields>
        <fullName>EUR_CRM_Segmentation_IL_Aspect_Name__c</fullName>
        <label>PRS Segmentation IL Aspect Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Iconic</fullName>
                </value>
                <value>
                    <fullName>Leading</fullName>
                </value>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Mainstream</fullName>
                </value>
                <value>
                    <fullName>Mainstream Standard</fullName>
                </value>
                <value>
                    <fullName>Mainstream Premium</fullName>
                </value>
                <value>
                    <fullName>Mainstream Quality</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PRS Segmentation Aspect (EU)</label>
    <nameField>
        <displayFormat>PRS-SA-{00000000}</displayFormat>
        <label>PRS Segmentation Aspect No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRS Segmentation Aspects (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_GB_PRS_Segmentation_Aspect_Image_Level</fullName>
        <active>true</active>
        <label>EUR GB PRS Segmentation Aspect Image Level</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Affiliate_Code_Picklist__c</fullName>
        <label>Affiliate Code Picklist</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>CH</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DK</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>GB</fullName>
                </value>
                <value>
                    <fullName>KE</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>NG</fullName>
                </value>
                <value>
                    <fullName>PT</fullName>
                </value>
                <value>
                    <fullName>RU</fullName>
                </value>
                <value>
                    <fullName>ZA</fullName>
                </value>
                <value>
                    <fullName>IDL</fullName>
                </value>
                <value>
                    <fullName>DB</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>NL</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>LU</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
                <value>
                    <fullName>CCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EUR_CRM_PRSSegmentationFilterCtrlTest.cls
@IsTest
private class EUR_CRM_PRSSegmentationFilterCtrlTest {

    @IsTest
    private static void getSelectionMethodOptionsTest() {
        System.runAs(makeUser()) {
            List<EUR_CRM_PRSSegmentationFilterCtrl.SelectOptionWrapper> selectionMethods =
                EUR_CRM_PRSSegmentationFilterCtrl.getSelectionMethodOptions();
            System.assertNotEquals(0, selectionMethods.size());

            System.assertEquals(EUR_CRM_PRSSegmentationFilterCtrl.NONE, selectionMethods[0].value);
            System.assertEquals(EUR_CRM_PRSSegmentationFilterCtrl.PROS, selectionMethods[1].value);
//            System.assertEquals(EUR_CRM_PRSSegmentationFilterCtrl.PROFS, selectionMethods[2].value);
        }
    }

    @IsTest
    private static void getPROSTableTest() {
        insert makeGot('EUR_GB_PRS_On_Trade_Group_Outlet_Type');
        insert makeSegAspect('EUR_GB_PRS_Segmentation_Aspect_Image_Level');
        System.runAs(makeUser()) {

        List<EUR_CRM_PRSSegmentationFilterCtrl.PROSWrapperAura> prosTable =
            EUR_CRM_PRSSegmentationFilterCtrl.getPROSTable();
        System.assertNotEquals(0, prosTable.size());
        }
    }

    private static EUR_CRM_PRS_Seg_Aspect__c makeSegAspect(String rt) {
        Id rtId = Schema.SObjectType.EUR_CRM_PRS_Seg_Aspect__c.getRecordTypeInfosByDeveloperName().get(rt).getRecordTypeId();
        return new EUR_CRM_PRS_Seg_Aspect__c(
            RecordTypeId = rtId
        ,   EUR_CRM_Segmentation_IL_Aspect_Name__c = 'Iconic'
        );
    }

    private static EUR_CRM_PRS_Group_Outlet_Type__c makeGot(String rt) {
        Id rtId = Schema.SObjectType.EUR_CRM_PRS_Group_Outlet_Type__c.getRecordTypeInfosByDeveloperName().get(rt).getRecordTypeId();
        return new EUR_CRM_PRS_Group_Outlet_Type__c(
            RecordTypeId = rtId
        ,   EUR_CRM_PRS_Group_Outlet_Name__c = 'Restaurant'
        );
    }

    @IsTest
    private static void getPROFSTest() {
        List<EUR_CRM_PRSSegmentationFilterCtrl.PROFSWrapperAura> profs =
            EUR_CRM_PRSSegmentationFilterCtrl.getPROFS();

        System.assertNotEquals(0, profs.size());
    }


    /* ========================================================= */
    /*     Makers
    /* ========================================================= */
    private static User makeUser() {
        return new User(
            Alias = 'standt'
        ,   Email = 'standarduser@testorg.com'
        ,   EmailEncodingKey = 'UTF-8'
        ,   LastName = 'Testing'
        ,   LanguageLocaleKey = 'en_US'
        ,   LocaleSidKey = 'en_US'
        ,   ProfileId = UserInfo.getProfileId()
        ,   TimeZoneSidKey = 'America/Los_Angeles'
        ,   Username = 'standarduser' + DateTime.now().getTime() + '@testorg.com'
        ,   EUR_CRM_Affiliate_Code_Picklist__c = 'GB'
        );
    }

}