objects/EUR_CRM_ObjPromo__c.object
<CustomObject>
    <description>EUR Universal Sales Activities - Objectives and Promotions</description>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Compliance Evaluation</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Under Evaluation</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Preparation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Objectives / Promotions (EU)</label>
    <nameField>
        <label>Objectives / Promotions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives / Promotions (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Account_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Bypass flag for Mobile app, so it doesn&apos;t need to create Visit Actions against that Promotion for that Account</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <label>Objectives / Promotions</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>EUR_CRM_O_P_Account_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>O/P - Account Mapping (EU)</label>
    <nameField>
        <displayFormat>OP-{0000000000}</displayFormat>
        <label>O/P - Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>O/P - Account Mapping (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EUR_CRM_DE_DeactivateOPAccountMappings.cls
/**
Batchable class to process all visit actions and create achievements
for Objectives & Promotions Module
*/
global class EUR_CRM_DE_DeactivateOPAccountMappings implements Database.Batchable<sObject>{
 
    global String query = ' select id,  EUR_CRM_Is_Active__c from EUR_CRM_ObjPromo_Account_Mapping__c ' +
                   ' where EUR_CRM_ObjPromo__c in (select id from EUR_CRM_ObjPromo__c where EUR_CRM_Status__c in (\'Ended\',\'Deactivated\',\'Under Evaluation\'))' +
                   ' AND EUR_CRM_Is_Active__c = true  ';
    
    global Database.QueryLocator start(Database.BatchableContext BC){  
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject>scope){
        deactivate((List<EUR_CRM_ObjPromo_Account_Mapping__c>) scope);
    }
   
    global void finish(Database.BatchableContext BC){
    
    }
    
    public static void deactivate(List<EUR_CRM_ObjPromo_Account_Mapping__c> scope){
        for(EUR_CRM_ObjPromo_Account_Mapping__c mapping: scope){
            mapping.EUR_CRM_Is_Active__c = false;
        } 
        update scope;
    }
     
}