objects/EUR_CRM_Contract__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Proposal Approved</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Approved-Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Prolongated</fullName>
                </value>
                <value>
                    <fullName>Waiting for sync</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract (EU)</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_PT_Outlet_Contract</fullName>
        <active>true</active>
        <label>EUR PT Outlet Contract</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Activity_Item__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>EUR_CRM_Contract__c</referenceTo>
        <relationshipName>EUR_CRM_Contract_Activity_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Mechanic_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mechanic Type</label>
        <referenceTo>EUR_CRM_Mechanic_Type__c</referenceTo>
        <relationshipName>EUR_CRM_Contract_Activity_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Activity Item (EU)</label>
    <nameField>
        <displayFormat>CA - {0000000000}</displayFormat>
        <label>Contract Activity Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Activity Item (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract_Product_Item__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Brand_Quality_Size__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand-Quality-Size (EU)</label>
        <referenceTo>EUR_CRM_Size__c</referenceTo>
        <relationshipName>Contract_Product_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract_Activity_Item__c</fullName>
        <label>Contract Activity Item</label>
        <referenceTo>EUR_CRM_Contract_Activity_Item__c</referenceTo>
        <relationshipName>Contract_Product_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract__c</fullName>
        <formula>CASESAFEID(EUR_CRM_Contract_Activity_Item__r.EUR_CRM_Contract__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contract Product Item (EU)</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Contract Product Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Product Item (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_GB_Volume_Tracker__c.object
<CustomObject>
    <description>PREU GB Data Model</description>
    <fields>
        <fullName>EUR_CRM_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>EUR_CRM_Contract__c</referenceTo>
        <relationshipLabel>Volume Tracker (EU)</relationshipLabel>
        <relationshipName>EUR_CRM_Volume_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volume Tracker (EU)</label>
    <nameField>
        <displayFormat>VTN-{00000000}</displayFormat>
        <label>Volume Tracker No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Tracker (EU)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EUR_CRM_GB_Volume_Tracker_Line_Item__c.object
<CustomObject>
    <description>PREU GB Data Model</description>
    <fields>
        <fullName>EUR_CRM_Brand_Quality_Size__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand-Quality-Size (EU)</label>
        <referenceTo>EUR_CRM_Size__c</referenceTo>
        <relationshipLabel>Volume Tracker Line Item (EU)</relationshipLabel>
        <relationshipName>Volume_Tracker_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract_Activity_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Activity Item</label>
        <referenceTo>EUR_CRM_Contract_Activity_Item__c</referenceTo>
        <relationshipName>Volume_Tracker_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contract__c</fullName>
        <formula>EUR_CRM_Volume_Tracker__r.EUR_CRM_Contract__c</formula>
        <label>Contract</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Initial_Contract_Volume__c</fullName>
        <label>(Old) Initial Contract Volume</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Volume_Tracker__c</fullName>
        <label>Volume Tracker</label>
        <referenceTo>EUR_CRM_GB_Volume_Tracker__c</referenceTo>
        <relationshipLabel>Volume Tracker Line Item (EU)</relationshipLabel>
        <relationshipName>Volume_Tracker_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Volume Tracker Line Item (EU)</label>
    <nameField>
        <displayFormat>VTL-{0000000000}</displayFormat>
        <label>Volume Tracker Line Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Tracker Line Item (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Mechanic_Type__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <label>Mechanic Type (EU)</label>
    <nameField>
        <label>Mechanic Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mechanic Type (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_PT_ContractCreateVolumeHandler.cls
public class EUR_CRM_PT_ContractCreateVolumeHandler extends EUR_CRM_TriggerAbstract {
    
    public EUR_CRM_PT_ContractCreateVolumeHandler() {
        super('EUR_CRM_PT_ContractCreateVolumeHandler');
    }
    
    private static final Set<String> validContractRecordTypes = new Set<String>{
        'EUR_PT_Outlet_Contract'
    };
    public static Set<String> TargetRecordSet {
        get{
            Set<String> TRt = new Set<String>();
            TRt.addAll(validContractRecordTypes);

            return TRt;
        }private set;
    }
    public override void executeTriggerAction(TriggerAction tAction, List<sObject> sObjList, Map<ID, sObject> newMap, Map<ID, sObject> oldMap){
        List<Recordtype> contractRecordTypes = Global_RecordTypeCache.getRtList('EUR_CRM_Contract__c');
        Map<Id,Recordtype> contractRecordTypesMap = new Map<Id,Recordtype>();
        Set<Id> contractIdSet = new Set<Id>();
        for(Recordtype rt : contractRecordTypes){
           contractRecordTypesMap.put(rt.id,rt);
        }
        
        for(EUR_CRM_Contract__c contract : (List<EUR_CRM_Contract__c>) sObjList){ 
            String devName = contractRecordTypesMap.get(contract.recordTypeId).developername;
            EUR_CRM_Contract__c oldRecord = (EUR_CRM_Contract__c ) oldMap.get(contract.id);
            
            if(validContractRecordTypes.contains(devname) 
                && contract.EUR_CRM_Status__c == 'Activated' &&
                oldRecord.EUR_CRM_Status__c  != contract.EUR_CRM_Status__c){
              contractIdSet.add(contract.Id);
            }   
        }
        
        If(contractIdSet.size() > 0){
            Map<Id, List<EUR_CRM_Contract_Product_Item__c>> productMap = new Map<Id, List<EUR_CRM_Contract_Product_Item__c>>();
            List<EUR_CRM_Contract_Activity_Item__c> acticityList = 
                [Select Id,
                        EUR_CRM_Contract__c,
                        (Select Id,
                                EUR_CRM_Contract_Activity_Item__r.Id,
                                EUR_CRM_Brand_Quality_Size__c,
                                EUR_CRM_Quantity__c
                         From Contract_Product_Items__r
                        )
                 From EUR_CRM_Contract_Activity_Item__c
                 Where EUR_CRM_Mechanic_Type__r.Name = 'Volume Targets and Rebates'
                 AND EUR_CRM_Contract__c In :contractIdSet
                ];


            Map<Id, EUR_CRM_GB_Volume_Tracker__c> volumeMap = new Map<Id, EUR_CRM_GB_Volume_Tracker__c>();
            List<EUR_CRM_GB_Volume_Tracker_Line_Item__c> volumeLineList = new List<EUR_CRM_GB_Volume_Tracker_Line_Item__c>();

            for(EUR_CRM_Contract_Activity_Item__c activity:acticityList){
                for(EUR_CRM_Contract_Product_Item__c item:activity.Contract_Product_Items__r){ 
                    List<EUR_CRM_Contract_Product_Item__c> productList = new List<EUR_CRM_Contract_Product_Item__c>(); 
                    if(productMap.get(activity.EUR_CRM_Contract__c) == null){
                        productList.add(item);
                        productMap.put(activity.EUR_CRM_Contract__c, productList);	
                    }else{
                        productList = productMap.get(activity.EUR_CRM_Contract__c);
                        productList.add(item);
                        productMap.put(activity.EUR_CRM_Contract__c, productList);
                    }	
                }

            }

            for(Id key:productMap.keySet()){
                EUR_CRM_GB_Volume_Tracker__c tracker = new EUR_CRM_GB_Volume_Tracker__c(EUR_CRM_Contract__c = key,recordtypeId = Global_RecordTypeCache.getRtId('EUR_CRM_GB_Volume_Tracker__cEUR_PT_Contract_Volume_Tracker'));	
                volumeMap.put(key, tracker);
            }

            if(volumeMap.values().size() > 0){
              insert volumeMap.values();
            }

            for(Id key:productMap.keySet()){
                for(EUR_CRM_Contract_Product_Item__c lineItem:productMap.get(key)){
                    EUR_CRM_GB_Volume_Tracker_Line_Item__c newItem = new EUR_CRM_GB_Volume_Tracker_Line_Item__c
                    (EUR_CRM_Volume_Tracker__c = volumeMap.get(key).Id,
                     EUR_CRM_Brand_Quality_Size__c = lineItem.EUR_CRM_Brand_Quality_Size__c,
                     EUR_CRM_Initial_Contract_Volume__c = lineItem.EUR_CRM_Quantity__c,
                     EUR_CRM_Contract_Activity_Item__c = lineItem.EUR_CRM_Contract_Activity_Item__r.Id,
                     RecordTypeId = Global_RecordTypeCache.getRtId('EUR_CRM_GB_Volume_Tracker_Line_Item__cEUR_PT_Contract_Volume_Tracker_Line_Item')
                    );
                    volumeLineList.add(newItem);	
                }
            }

            if(volumeLineList.size() > 0){
              insert volumeLineList;
            }
        }
    }
    
}