objects/EUR_CRM_ObjPromo__c.object
<CustomObject>
    <description>EUR Universal Sales Activities - Objectives and Promotions</description>
    <fields>
        <fullName>EUR_CRM_Is_Quota__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Quota</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_OP_Action_List_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>O/P Action List Template</label>
        <referenceTo>EUR_CRM_OP_Action_List_Template__c</referenceTo>
        <relationshipName>EUR_CRM_ObjPromo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Objectives / Promotions (EU)</label>
    <nameField>
        <label>Objectives / Promotions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives / Promotions (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Action__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Can_Reoccur__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can Reoccur</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Entitle_Achievement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Entitle Achievement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_OP_Action_List_Template__c</fullName>
        <label>O/P Action List Template</label>
        <referenceTo>EUR_CRM_OP_Action_List_Template__c</referenceTo>
        <relationshipName>EUR_CRM_OP_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_OP_Sequence_Order__c</fullName>
        <description>Sets the sequence order for a Visit Action for a particular Objective/Promotion</description>
        <label>O/P Sequence Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Stage_Sequence_Order__c</fullName>
        <label>Stage Sequence Order</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Sell</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Evaluation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>O/P Action (EU)</label>
    <nameField>
        <label>O/P Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>O/P Action (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Target__c.object
<CustomObject>
    <description>Child object of the O/P header</description>
    <fields>
        <fullName>EUR_CRM_Actual_Number_of_Commitments__c</fullName>
        <label>Actual Number of Commitments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Actual_Volume_Bottles__c</fullName>
        <label>Actual Volume (Bottles)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_BQS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BQS</label>
        <referenceTo>EUR_CRM_Size__c</referenceTo>
        <relationshipName>O_P_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_BQ__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand-Quality (EU)</label>
        <referenceTo>EUR_CRM_Quality__c</referenceTo>
        <relationshipName>O_P_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Commitment_Target_Dist_to_Goals__c</fullName>
        <description>This is used only for Indicating the Distance to Goals specific to Commitment Targets</description>
        <formula>IF(OR(EUR_CRM_Visit_Targets__c - EUR_CRM_Actual_Number_of_Commitments__c &lt; 0, ISBLANK(EUR_CRM_Actual_Number_of_Commitments__c)), 
IF(ISBLANK(EUR_CRM_Actual_Number_of_Commitments__c), EUR_CRM_Visit_Targets__c - 0, 0 ), EUR_CRM_Visit_Targets__c - EUR_CRM_Actual_Number_of_Commitments__c )</formula>
        <label>Commitments Distance to Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Distance_to_Goal__c</fullName>
        <formula>If( EUR_CRM_ObjPromo__r.RecordType.DeveloperName = &apos;EUR_BE_Off_Trade_Secondary_placement_Spyder_display&apos;,EUR_CRM_Target_Quantity_Spyders__c - EUR_CRM_Actual_Quantity_Spyder__c,  EUR_CRM_Qty_Sell_in_Amount_Bottle__c - EUR_CRM_Actual_Volume_Bottles__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distance to Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Grouping_Type__c</fullName>
        <label>Grouping Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bottle</fullName>
                </value>
                <value>
                    <fullName>Carton</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EUR_CRM_Is_Quota__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Quota</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_O_P_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>O/P Target</label>
        <referenceTo>EUR_CRM_ObjPromo_Target__c</referenceTo>
        <relationshipName>EUR_CRM_O_P_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <label>Objectives / Promotions</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>O_P_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Qty_Sell_in_Amount_Bottle__c</fullName>
        <label>Qty Sell in Amount Bottles</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU</label>
        <referenceTo>EUR_CRM_SKU__c</referenceTo>
        <relationshipName>O_P_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Target_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EUR_CRM_O_P_GenericTargets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Unit_of_Measure__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unit of Measure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Visit_Targets__c</fullName>
        <label>Commitment Targets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>O/P Target (EU)</label>
    <nameField>
        <displayFormat>OPT-{0000000000}</displayFormat>
        <label>O/P Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>O/P Target (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_CRM_Objective_Commitment_Target</fullName>
        <active>true</active>
        <description>Target to record the number of Accounts that have successfully achieved a specific O/P - Objective Level</description>
        <label>Objective Commitment Target</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_CRM_Objective_Product</fullName>
        <active>true</active>
        <label>Objective Product</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_CRM_Objective_Volume_Target</fullName>
        <active>true</active>
        <label>Objective Volume Target (EU)</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_CRM_SR_Commitment_Target</fullName>
        <active>true</active>
        <description>Target to record the number of Accounts that have successfully achieved a specific O/P - Sales Rep Level</description>
        <label>SR Commitment Target</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_CRM_SR_Volume_Target</fullName>
        <active>true</active>
        <label>SR Volume Target (EU)</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_OP_Action_List_Template__c.object
<CustomObject>
    <description>EUR CRM - This object will contain the actions that the SR needs to do on the Mobile App for the Object or Promotional Campaign</description>
    <label>O/P Action List Template (EU)</label>
    <nameField>
        <label>O/P Action List Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>O/P Action List Template (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Quality__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_SKU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SKU (EU)</label>
        <referenceTo>EUR_CRM_SKU__c</referenceTo>
        <relationshipLabel>Brand-Quality (EU)</relationshipLabel>
        <relationshipName>Brand_Quality_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand-Quality (EU)</label>
    <nameField>
        <label>Brand Quality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand-Quality (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Size__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <label>Brand-Quality-Size (EU)</label>
    <nameField>
        <label>Brand Quality Size</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand-Quality-Size (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_SKU__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <label>SKU (EU)</label>
    <nameField>
        <label>Product SKU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKUs (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_FI_ObjectivePromoPageController.cls
public class EUR_CRM_FI_ObjectivePromoPageController{
    private EUR_CRM_ObjPromo__c objPromo;
    
    public List<EUR_CRM_ObjPromo_Target__c> objectiveVolumeTargets {get;set;} //deprecated
    public List<EUR_CRM_ObjPromo_Target__c> objectiveProductVolumeTargets {get;set;}
    public List<EUR_CRM_ObjPromo_Target__c> srVolumeTargets {get;set;}
    public List<EUR_CRM_ObjPromo_Target__c> objectiveCommitmentTarget {get;set;}
    public List<EUR_CRM_ObjPromo_Target__c> srCommitmentTargets {get;set;}
    
    public EUR_CRM_FI_ObjectivePromoPageController(ApexPages.StandardController stdController) { 
     objPromo = (EUR_CRM_ObjPromo__c) stdController.getRecord();
     initTargets();
    }
    public List<EUR_CRM_ObjPromo_Action__c> getActions(){
        
        List<EUR_CRM_ObjPromo_Action__c> actionList = new List<EUR_CRM_ObjPromo_Action__c>();
        actionList = [select id, 
        Name,
        EUR_CRM_Can_Reoccur__c,
        EUR_CRM_Entitle_Achievement__c,
        EUR_CRM_OP_Action_List_Template__c,
        EUR_CRM_Stage__c,
        EUR_CRM_OP_Sequence_Order__c,
        EUR_CRM_Stage_Sequence_Order__c
        from EUR_CRM_ObjPromo_Action__c
        where
        EUR_CRM_OP_Action_List_Template__c =: objPromo.EUR_CRM_OP_Action_List_Template__c
        order by EUR_CRM_OP_Sequence_Order__c ASC];
        
        return actionList;
    }
    void initTargets(){
        objectiveProductVolumeTargets = new List<EUR_CRM_ObjPromo_Target__c>(); 
        objectiveCommitmentTarget = new List<EUR_CRM_ObjPromo_Target__c>();
        srCommitmentTargets = new List<EUR_CRM_ObjPromo_Target__c>();
        srVolumeTargets = new List<EUR_CRM_ObjPromo_Target__c>(); 
        Map<Id, EUR_CRM_ObjPromo_Target__c> targets = new Map<Id, EUR_CRM_ObjPromo_Target__c>([select id,
                    EUR_CRM_BQS__c,
                    Name ,
                    EUR_CRM_BQS__r.name,
                    EUR_CRM_BQ__c,
                    EUR_CRM_Actual_Volume_Bottles__c,
                    EUR_CRM_Actual_Number_of_Commitments__c,
                    EUR_CRM_BQ__r.name,
                    EUR_CRM_SKU__c,
                    recordtype.developername,
                    EUR_CRM_Visit_Targets__c,
                    EUR_CRM_Is_Quota__c,
                    EUR_CRM_Target_Owner__c ,
                    EUR_CRM_Unit_of_Measure__c,
                    EUR_CRM_O_P_Target__c,
                    EUR_CRM_Distance_to_Goal__c,
                    EUR_CRM_Commitment_Target_Dist_to_Goals__c,
                    EUR_CRM_Grouping_Type__c,
                    EUR_CRM_SKU__r.name,EUR_CRM_Qty_Sell_in_Amount_Bottle__c   from EUR_CRM_ObjPromo_Target__c where EUR_CRM_ObjPromo__c =: objPromo.Id
        ]); 
        Map<Id, Set<Id>> superMap = new Map<Id,Set<Id>>();
        for(EUR_CRM_ObjPromo_Target__c target : targets.values()){ 
             if(target.recordtype.developername == 'EUR_CRM_Objective_Commitment_Target')
                objectiveCommitmentTarget.add(target);
             if(target.recordtype.developername == 'EUR_CRM_SR_Commitment_Target')
                srCommitmentTargets.add(target);
             if(target.recordtype.developername == 'EUR_CRM_Objective_Volume_Target' || target.recordtype.developername == 'EUR_CRM_Objective_Product'){
                objectiveProductVolumeTargets.add(target);
                if(superMap.get(target.id) == null)
                    superMap.put(target.id, new Set<Id>());
             }if(target.recordtype.developername == 'EUR_CRM_SR_Volume_Target'){
                srVolumeTargets.add(target);
                if(superMap.get(target.EUR_CRM_O_P_Target__c) == null)
                    superMap.put(target.EUR_CRM_O_P_Target__c, new Set<Id>());
                superMap.get(target.EUR_CRM_O_P_Target__c).add(target.id);
             }
        }
        
        targetWraps = new List<TargetWrapper>();
        
        for(Id key : superMap.keySet()){            
            List<TargetWrapper> subTargets = new  List<TargetWrapper>();
            TargetWrapper targetWrapper =  new  TargetWrapper(targets.get(key),  subTargets);
            for(Id subKey : superMap.get(key)){
                subTargets.add(new TargetWrapper(targets.get(subKey),  null));            
            }
            targetWraps.add(targetWrapper);
        }       
    }
    
    
    public List<TargetWrapper> targetWraps {get;set;}
    public class TargetWrapper{
        public Boolean getHasChild(){
            return this.subTargets != null && this.subTargets.size() > 0;
        }
        public EUR_CRM_ObjPromo_Target__c target {get;set;}
        public List<TargetWrapper> subTargets {get;set;}
        public TargetWrapper(EUR_CRM_ObjPromo_Target__c target, List<TargetWrapper> subTargets) {
            this.target = target;
            this.subTargets = subTargets;
        }  
    }
     
}