objects/EUR_CRM_Budget__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <label>Budget (EU)</label>
    <nameField>
        <displayFormat>BG-{000000}</displayFormat>
        <label>Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Budget_Transaction__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>EUR_CRM_Contract__c</referenceTo>
        <relationshipName>Transactions_Contracts_Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Transaction_Category__c</fullName>
        <label>Transaction Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Load</fullName>
                </value>
                <value>
                    <fullName>Rolling Budget Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Contract Transaction</fullName>
                </value>
                <value>
                    <fullName>Contract Refund</fullName>
                </value>
                <value>
                    <fullName>Draft Contract Transaction</fullName>
                </value>
                <value>
                    <fullName>Adjustment</fullName>
                </value>
                <value>
                    <fullName>Draft Spend Transaction</fullName>
                </value>
                <value>
                    <fullName>Spend Transaction</fullName>
                </value>
                <value>
                    <fullName>Adjustment Invoice Tracker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Budget Transaction (EU)</label>
    <nameField>
        <displayFormat>TRS-{00000000}</displayFormat>
        <label>Budget Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Transactions (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Contract__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <errorMessage>Chain contract cannot be created for an Outlet account.</errorMessage>
            <filterItems>
                <field>EUR_CRM_Account__c.EUR_CRM_Business_Type__c</field>
                <operation>equals</operation>
                <value>Head Office</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>EUR FI Chain Contract</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>EUR FI Chain Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For the following affiliate/s:
1. DE</description>
        <label>Budget (EU)</label>
        <referenceTo>EUR_CRM_Budget__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>EUR_CRM_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contract (EU)</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EUR_CRM_DE_TestContract_BeforeDelete.cls
@isTest
public class EUR_CRM_DE_TestContract_BeforeDelete{
    private static EUR_CRM_Account__c accountEU;
    private static EUR_CRM_Contract__c contract;
    private static EUR_CRM_Contract__c contract2;
    private static EUR_CRM_Budget__c budget;
    private static String FY_STR = 'FY15';
    private static String EXTERNAL_ID = 'TEST_'+FY_STR;
    private static Decimal ALLOCATED_BUDGET = 10000;
    private static Decimal CARRY_FWD = 0;
    private static EUR_CRM_Budget_Transaction__c initialLoadTransaction;
    private static EUR_CRM_Budget_Transaction__c initialLoadTransaction2;

/* Hidden by Laputa Hugo Cheung 26/09/2016
    static void dataInsert1(){
        //Create account
        EUR_CRM_DE_TestClassUtilityHelper.initData();
        accountEU = EUR_CRM_DE_TestClassUtilityHelper.euAccount;

         //Create Contract
        contract = EUR_CRM_TestClassUtilityHelper.createContracts(1, EUR_CRM_DE_TestClassUtilityHelper.DE_CONTRACT_RECORD_TYPE, accountEU.Id, date.today(), date.today().addDays(30))[0];
        insert contract;

        contract2 = EUR_CRM_TestClassUtilityHelper.createContracts(1, EUR_CRM_DE_TestClassUtilityHelper.DE_CONTRACT_RECORD_TYPE, accountEU.Id, date.today(), date.today().addDays(30))[0];
        insert contract2;
        //Create Budget
        budget = EUR_CRM_DE_TestClassUtilityHelper.createBudget(EUR_CRM_DE_TestClassUtilityHelper.DE_BUDGET_RECORD_TYPE,
                                                    UserInfo.getUserId(), 
                                                    determineFiscalYear(contract.EUR_CRM_Start_Date__c), EXTERNAL_ID,
                                                    ALLOCATED_BUDGET, CARRY_FWD);
        insert budget;
        
        //Create Transaction Initial Budget Load
        initialLoadTransaction = EUR_CRM_DE_TestClassUtilityHelper.createBudgetInitialLoad('DE On Trade WKZ- Draft Transaction',
                                    budget.Id, 10000);
        initialLoadTransaction.EUR_CRM_Transaction_Category__c = 'Draft Contract Transaction';
        initialLoadTransaction.EUR_CRM_Contract__c = contract.id;
        insert initialLoadTransaction;

        initialLoadTransaction2 = EUR_CRM_DE_TestClassUtilityHelper.createBudgetInitialLoad('DE On Trade WKZ- Draft Transaction',
                                    budget.Id, 10000);
        initialLoadTransaction2.EUR_CRM_Transaction_Category__c = 'Draft Contract Transaction';
        initialLoadTransaction2.EUR_CRM_Contract__c = contract2.id;
        insert initialLoadTransaction2;


        delete contract;
        delete contract2;
    }
 */
    static testMethod void contractDeleteTest(){
        EUR_CRM_DE_TestClassUtilityHelper.initUsersOntrade();
        system.runAs(EUR_CRM_DE_TestClassUtilityHelper.regionalUser){
            
            test.StartTest();
                //Create account
                EUR_CRM_DE_TestClassUtilityHelper.initData();
                accountEU = EUR_CRM_DE_TestClassUtilityHelper.euAccount;
        
                 //Create Contract
                contract = EUR_CRM_TestClassUtilityHelper.createContracts(1, EUR_CRM_DE_TestClassUtilityHelper.DE_CONTRACT_RECORD_TYPE, accountEU.Id, date.today(), date.today().addDays(30))[0];
                insert contract;
        
                contract2 = EUR_CRM_TestClassUtilityHelper.createContracts(1, EUR_CRM_DE_TestClassUtilityHelper.DE_CONTRACT_RECORD_TYPE, accountEU.Id, date.today(), date.today().addDays(30))[0];
                insert contract2;
                //Create Budget
                budget = EUR_CRM_DE_TestClassUtilityHelper.createBudget(EUR_CRM_DE_TestClassUtilityHelper.DE_BUDGET_RECORD_TYPE,
                                                            UserInfo.getUserId(), 
                                                            determineFiscalYear(contract.EUR_CRM_Start_Date__c), EXTERNAL_ID,
                                                            ALLOCATED_BUDGET, CARRY_FWD);
                insert budget;
                
                //Create Transaction Initial Budget Load
                initialLoadTransaction = EUR_CRM_DE_TestClassUtilityHelper.createBudgetInitialLoad('DE On Trade WKZ- Draft Transaction',
                                            budget.Id, 10000);
                initialLoadTransaction.EUR_CRM_Transaction_Category__c = 'Draft Contract Transaction';
                initialLoadTransaction.EUR_CRM_Contract__c = contract.id;
                insert initialLoadTransaction;
        
                initialLoadTransaction2 = EUR_CRM_DE_TestClassUtilityHelper.createBudgetInitialLoad('DE On Trade WKZ- Draft Transaction',
                                            budget.Id, 10000);
                initialLoadTransaction2.EUR_CRM_Transaction_Category__c = 'Draft Contract Transaction';
                initialLoadTransaction2.EUR_CRM_Contract__c = contract2.id;
                insert initialLoadTransaction2;
        
            test.StopTest();
            delete contract;
            delete contract2;
        }    
    }

    static String determineFiscalYear(Date contractStartDate){
        if (contractStartDate != null){
        Integer contractYear = contractStartDate.year();
        Integer contractMonth = contractStartDate.month();

        Integer FiscalYearStartMonth = [select FiscalYearStartMonth from Organization where id=:Userinfo.getOrganizationId()].FiscalYearStartMonth;
        
        if (contractMonth>=FiscalYearStartMonth){
            return 'FY'+ String.valueOf(contractYear+1).substring(2);
        }else{
            return 'FY' + String.valueOf(contractYear).substring(2);
        }
        }
        return null;
    }
}