objects/EUR_CRM_Region__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <label>Region (EU)</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Territory__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Region__c</fullName>
        <label>Region</label>
        <referenceTo>EUR_CRM_Region__c</referenceTo>
        <relationshipName>Territories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Territory_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory (EU)</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EUR_CRM_Baltics_TerritoryAssignmentTest.cls
@isTest
private class EUR_CRM_Baltics_TerritoryAssignmentTest {

    static testMethod void myUnitTest() {
        EUR_CRM_Region__c region = new EUR_CRM_Region__c(name='test region');
        insert region;
        EUR_CRM_Territory__c terri = new EUR_CRM_Territory__c(name='test territory');
        terri.EUR_CRM_Region__c = region.Id;
        terri.EUR_CRM_Territory_Owner__c = UserInfo.getUserId();
        insert terri;
        EUR_CRM_Territory__c terri2 = new EUR_CRM_Territory__c(name='test territory 2');
        terri2.EUR_CRM_Region__c = region.Id;
        terri2.EUR_CRM_Territory_Owner__c = UserInfo.getUserId();
        insert terri2;
        
        EUR_CRM_Account__c acct =  (EUR_CRM_TestClassUtilityHelper.createAccountsEU(1, 'EE Indirect - On Trade')).get(0);// new EUR_CRM_Account__c(name='test acct');
    	test.startTEst();
        insert acct;
        test.stoptest();
        acct.EUR_CRM_Territory__c = terri2.Id;
        update acct;
        
        EUR_CRM_Account__c acct2 = (EUR_CRM_TestClassUtilityHelper.createAccountsEU(1, 'EE Indirect - On Trade')).get(0);

        acct2.EUR_CRM_Territory__c = terri.Id;
        insert acct2;
    }
}