objects/EUR_CRM_Group_Outlet_Type__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Group_Outlet_Name__c</fullName>
        <label>Group Outlet Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Nightclub</fullName>
                </value>
                <value>
                    <fullName>Low Energy Bar</fullName>
                </value>
                <value>
                    <fullName>High Energy Bar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Group Outlet Type (EU)</label>
    <nameField>
        <displayFormat>GO-{00000}</displayFormat>
        <label>Group Outlet Type No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Outlet Type (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Image_Level__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Group_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Outlet Type</label>
        <referenceTo>EUR_CRM_Group_Outlet_Type__c</referenceTo>
        <relationshipName>EUR_CRM_Image_Levels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Min_Weight__c</fullName>
        <label>Minimum Weight</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Image Level (EU)</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Image Level No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image Level (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Image_Level_Threshold__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Group_Outlet_Type__c</fullName>
        <label>Group Outlet Type</label>
        <referenceTo>EUR_CRM_Group_Outlet_Type__c</referenceTo>
        <relationshipName>EUR_Image_Level_Thresholds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Image_Level__c</fullName>
        <label>Image Level</label>
        <referenceTo>EUR_CRM_Image_Level__c</referenceTo>
        <relationshipName>EUR_Image_Level_Thresholds</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Is_Weight_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Weight Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Min_Weight__c</fullName>
        <label>Minimum Weight</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>EUR Image Level Threshold (EU)</label>
    <nameField>
        <displayFormat>ILT-{0000}</displayFormat>
        <label>EUR Image Level Threshold Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EUR Image Level Threshold (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Pros_Segmentation__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Group_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Outlet Type</label>
        <referenceTo>EUR_CRM_Group_Outlet_Type__c</referenceTo>
        <relationshipName>Pros_Segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Image_Level_Threshold__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Image Level Threshold</label>
        <referenceTo>EUR_CRM_Image_Level_Threshold__c</referenceTo>
        <relationshipName>Pros_Segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Image_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Image Level</label>
        <referenceTo>EUR_CRM_Image_Level__c</referenceTo>
        <relationshipName>Pros_Segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pros Segmentation (EU)</label>
    <nameField>
        <displayFormat>PS-{0000000000}</displayFormat>
        <label>PROS ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pros Segmentation (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_DE_PROS_Segmentation</fullName>
        <active>true</active>
        <label>EUR_DE_PROS_Segmentation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_ImageLevelThresholdMasUpdateTest.cls
/*
*    Description : Test class for EUR_CRM_ImageLevelThresholdMassUpdate
*
*    Version    Author        Date        Description
*    1.0        Sid           01/22/2105  Initial Draft
*/

@isTest
public class EUR_CRM_ImageLevelThresholdMasUpdateTest {

    private static List<EUR_CRM_Pros_Segmentation__c> prosSegmentationList = new List<EUR_CRM_Pros_Segmentation__c>();
    private static List<EUR_CRM_Image_Level__c> imageLevelList = new List<EUR_CRM_Image_Level__c>();
    private static List<EUR_CRM_Group_Outlet_Type__c> groupOutletTypeList = new List<EUR_CRM_Group_Outlet_Type__c>();
    private static List<EUR_CRM_Image_Level_Threshold__c> imageLevelThresholdList = new List<EUR_CRM_Image_Level_Threshold__c>();

    //Method to create test data
    public static void insertTestData(){
    
        //Create Group Outlet Type
        groupOutletTypeList = EUR_CRM_TestClassUtilityHelper.createGroupOutletType(1, 'EUR DE Group Outlet', '', null, null);
        for(EUR_CRM_Group_Outlet_Type__c objGroupOutletType : groupOutletTypeList){
            objGroupOutletType.EUR_CRM_Group_Outlet_Name__c = 'NightClub';
        }
        insert groupOutletTypeList;
        
        //Create Image Level Record
        imageLevelList = EUR_CRM_TestClassUtilityHelper.createImageLevel(1, 'DE Image Level', '', null, 'Nightclub');
        insert imageLevelList;        
        
        //Create Image Level Threshold
        imageLevelThresholdList = EUR_CRM_TestClassUtilityHelper.createImageLevelThreshold(1, groupOutletTypeList[0].Id, imageLevelList[0].Id);
        for(EUR_CRM_Image_Level_Threshold__c objImgLvlThrshold : imageLevelThresholdList){
            
            objImgLvlThrshold.EUR_CRM_Min_Weight__c = 50;
            objImgLvlThrshold.EUR_CRM_Is_Weight_Changed__c = true;
        }
        insert imageLevelThresholdList;
        
        //Create PROS Segmentation
        prosSegmentationList = EUR_CRM_TestClassUtilityHelper.createProsSegmentation(1, 'EUR_DE_PROS_Segmentation', 
                                                                                     '', null, 
                                                                                     groupOutletTypeList[0].Id, null, 
                                                                                     null, null, null);
                                                                                     
        for(EUR_CRM_Pros_Segmentation__c objProsSeg : prosSegmentationList){
            
            objProsSeg.EUR_CRM_Image_Level_Threshold__c = imageLevelThresholdList[0].Id;
            objProsSeg.EUR_CRM_Image_Level__c = imageLevelList[0].Id;
        }                                                                                     
        insert prosSegmentationList;        
    }

    //Test Method to test Batch
    static testMethod void executeBatchTest() {
        
        insertTestData();
        test.startTest();
            EUR_CRM_ImageLevelThresholdMassUpdate oEUR_CRM_ImageLevelThresholdMassUpdate = new EUR_CRM_ImageLevelThresholdMassUpdate('DE');
            database.executeBatch(oEUR_CRM_ImageLevelThresholdMassUpdate);
        test.stopTest();
    }
}