objects/EUR_CRM_Brand__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand (EU)</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo__c.object
<CustomObject>
    <description>EUR Universal Sales Activities - Objectives and Promotions</description>
    <fields>
        <fullName>EUR_CRM_Active_End_Date__c</fullName>
        <label>Active End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Active_Start_Date__c</fullName>
        <label>Active Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Evaluation_Period_End_Date__c</fullName>
        <label>Evaluation Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EUR_CRM_OP_Action_List_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>O/P Action List Template</label>
        <referenceTo>EUR_CRM_OP_Action_List_Template__c</referenceTo>
        <relationshipName>EUR_CRM_ObjPromo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Compliance Evaluation</fullName>
                </value>
                <value>
                    <fullName>Ended</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Under Evaluation</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Preparation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Objectives / Promotions (EU)</label>
    <nameField>
        <label>Objectives / Promotions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives / Promotions (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_BE_On_Trade_Promo_Kit_Activation</fullName>
        <active>true</active>
        <label>BE On Trade- Promo Kit Activation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Account_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <label>Account (EU)</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>O/P - Account Mapping (EU)</relationshipLabel>
        <relationshipName>O_P_Account_Mappings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Evaluation_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Evaluation Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Bypass flag for Mobile app, so it doesn&apos;t need to create Visit Actions against that Promotion for that Account</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <label>Objectives / Promotions</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>EUR_CRM_O_P_Account_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>O/P - Account Mapping (EU)</label>
    <nameField>
        <displayFormat>OP-{0000000000}</displayFormat>
        <label>O/P - Account Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>O/P - Account Mapping (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_BE_O_P_Account_Mapping</fullName>
        <active>true</active>
        <label>BE O/P - Account Mapping</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Action__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EUR_CRM_OP_Action_List_Template__c</fullName>
        <label>O/P Action List Template</label>
        <referenceTo>EUR_CRM_OP_Action_List_Template__c</referenceTo>
        <relationshipName>EUR_CRM_OP_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Sell</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Evaluation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EUR_CRM_Visit_Action_RecordType_DevName__c</fullName>
        <description>Specifies the Record Type Developer Name of the matching Visit Action so the Mobile App can create the correct Visit Action for the SR to fill out</description>
        <label>Visit Action RecordType DevName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>O/P Action (EU)</label>
    <nameField>
        <label>O/P Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>O/P Action (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_ObjPromo_Target__c.object
<CustomObject>
    <description>Child object of the O/P header</description>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PR PT is the 1st country using this field.</description>
        <label>Account (EU)</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>O/P Target (EU)</relationshipLabel>
        <relationshipName>O_P_Target_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_BQ__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand-Quality (EU)</label>
        <referenceTo>EUR_CRM_Quality__c</referenceTo>
        <relationshipName>O_P_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand (EU)</label>
        <referenceTo>EUR_CRM_Brand__c</referenceTo>
        <relationshipLabel>O/P Target (EU)</relationshipLabel>
        <relationshipName>OP_Target_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EUR_CRM_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Initially for PR DK - Effects Manager Interface - to reflect changes in Product changes in Effects Manager</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_O_P_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>O/P Target</label>
        <referenceTo>EUR_CRM_ObjPromo_Target__c</referenceTo>
        <relationshipName>EUR_CRM_O_P_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <label>Objectives / Promotions</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>O_P_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Target_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EUR_CRM_O_P_GenericTargets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>O/P Target (EU)</label>
    <nameField>
        <displayFormat>OPT-{0000000000}</displayFormat>
        <label>O/P Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>O/P Target (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_BE_Objective_Volume_Target</fullName>
        <active>true</active>
        <label>BE Objective Volume Target</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_SE_Objective_Listing_Target</fullName>
        <active>true</active>
        <label>EUR SE Objective Listing Target</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_OP_Action_List_Template__c.object
<CustomObject>
    <description>EUR CRM - This object will contain the actions that the SR needs to do on the Mobile App for the Object or Promotional Campaign</description>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>O/P Action List Template (EU)</label>
    <nameField>
        <label>O/P Action List Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>O/P Action List Template (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Quality__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated to Brand object for product heirarchy</description>
        <label>Brand</label>
        <referenceTo>EUR_CRM_Brand__c</referenceTo>
        <relationshipName>EUR_CRM_Qualities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand-Quality (EU)</label>
    <nameField>
        <label>Brand Quality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand-Quality (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_Visit_Action__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (EU)</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipName>EUR_CRM_Visit_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand (EU)</label>
        <referenceTo>EUR_CRM_Brand__c</referenceTo>
        <relationshipLabel>Visit Action (EU)</relationshipLabel>
        <relationshipName>Visit_Action_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>O/P Target</label>
        <referenceTo>EUR_CRM_ObjPromo_Target__c</referenceTo>
        <relationshipName>EUR_CRM_Visit_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_ObjPromo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Objective / Promotion</label>
        <referenceTo>EUR_CRM_ObjPromo__c</referenceTo>
        <relationshipName>EUR_CRM_Visit_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-sell</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Evaluation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Visit Action (EU)</label>
    <nameField>
        <displayFormat>VACT-{0000000000}</displayFormat>
        <label>Visit Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Action (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_SE_ON_Listing_Agree_To_List</fullName>
        <active>true</active>
        <label>SE ON Trade - Listing Campaign - Agree to List</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_SE_AccrueAchievementsTest.cls
@IsTest
private class EUR_CRM_SE_AccrueAchievementsTest {

    @IsTest
    private static void test1() {
        EUR_CRM_OP_Action_List_Template__c actionListTemp = new EUR_CRM_OP_Action_List_Template__c(Name = 'Promo Action List Template 1', EUR_CRM_External_ID__c = 'BE_On_Trade_Promo_Kit_Activation');
        insert actionListTemp;

        EUR_CRM_ObjPromo_Action__c promoAction = new EUR_CRM_ObjPromo_Action__c(EUR_CRM_Visit_Action_RecordType_DevName__c = 'EUR_CRM_OFF_Follow_Up', EUR_CRM_OP_Action_List_Template__c = actionListTemp.Id);
        insert promoAction;

        EUR_CRM_Account__c acc = new EUR_CRM_Account__c(Name = 'Tester1',   EUR_CRM_Postal_Code__c = '1122'
                ,   RecordTypeId = EUR_CRM_RecordTypeHelper_v2.getRTByDevName('EUR_CRM_Account__c', 'EUR_LV_DIR_OFF_Trade'));
        insert acc;

        EUR_CRM_ObjPromo__c objAndProm = new EUR_CRM_ObjPromo__c(
            RecordTypeId = Schema.SObjectType.EUR_CRM_ObjPromo__c.getRecordTypeInfosByDeveloperName().get('EUR_BE_On_Trade_Promo_Kit_Activation').getRecordTypeId()
        ,   Name = 'TestObjPromo'
        ,   EUR_CRM_Active_Start_Date__c = Date.today().addDays(-1)
        ,   EUR_CRM_Active_End_Date__c = Date.today().addDays(360)
        ,   EUR_CRM_Evaluation_Period_End_Date__c = Date.today().addDays(20)
        );
        insert objAndProm;

        EUR_CRM_ObjPromo_Account_Mapping__c objPromoAccMapping = new EUR_CRM_ObjPromo_Account_Mapping__c(
            RecordTypeId = Schema.SObjectType.EUR_CRM_ObjPromo_Account_Mapping__c.getRecordTypeInfosByDeveloperName().get('EUR_BE_O_P_Account_Mapping').getRecordTypeId()
        ,   EUR_CRM_Account__c = acc.Id
        ,   EUR_CRM_ObjPromo__c = objAndProm.Id
        ,   EUR_CRM_Is_Active__c = true
        ,   EUR_CRM_Evaluation_Required__c = false
        );
        insert objPromoAccMapping;



        EUR_CRM_Brand__c testBrand = new EUR_CRM_Brand__c(Name = 'TestBrand');
        insert testBrand;

        EUR_CRM_Quality__c testBrandQuality = new EUR_CRM_Quality__c(EUR_CRM_Brand__c = testBrand.Id);
        insert testBrandQuality;

        Test.startTest();
        EUR_CRM_ObjPromo_Target__c testTargetParent = new EUR_CRM_ObjPromo_Target__c(
            RecordTypeId = Schema.SObjectType.EUR_CRM_ObjPromo_Target__c.getRecordTypeInfosByDeveloperName().get('EUR_BE_Objective_Volume_Target').getRecordTypeId()
        ,   EUR_CRM_ObjPromo__c = objAndProm.Id
        ,   EUR_CRM_Target_Owner__c = UserInfo.getUserId()
        ,   EUR_CRM_Brand__c = testBrand.Id
        ,   EUR_CRM_BQ__c = testBrandQuality.Id
        );
        insert testTargetParent;

        EUR_CRM_ObjPromo_Target__c testTarget = new EUR_CRM_ObjPromo_Target__c(
            RecordTypeId = Schema.SObjectType.EUR_CRM_ObjPromo_Target__c.getRecordTypeInfosByDeveloperName().get('EUR_SE_Objective_Listing_Target').getRecordTypeId()
        ,   EUR_CRM_ObjPromo__c = objAndProm.Id
        ,   EUR_CRM_O_P_Target__c = testTargetParent.Id
        ,   EUR_CRM_Target_Owner__c = null
        ,   EUR_CRM_Brand__c = testBrand.Id
        ,   EUR_CRM_BQ__c = testBrandQuality.Id
        );
        insert testTarget;

        RecordType visitAction = [SELECT Id,SobjectType,Name,DeveloperName FROM RecordType WHERE SobjectType = 'EUR_CRM_Visit_Action__c' AND DeveloperName = 'EUR_SE_ON_Listing_Agree_To_List' LIMIT 1][0];
        EUR_CRM_Visit_Action__c newVisit = new EUR_CRM_Visit_Action__c(
            EUR_CRM_ObjPromo__c = objAndProm.Id
        ,   EUR_CRM_Stage__c = 'Execution'
        ,   EUR_CRM_Status__c = 'Yes'
        ,   RecordTypeId = visitAction.Id
        ,   EUR_CRM_Is_Accrued__c = false
        ,   EUR_CRM_Account__c = acc.Id
        ,   EUR_CRM_Brand__c = testBrand.Id
        ,   EUR_CRM_Brand_Quality__c = testBrandQuality.Id
        ,   EUR_CRM_Sell_In_Volume_Bottles__c = 50
        ,   EUR_CRM_ObjPromo_Target__c = testTarget.Id
        );

        objAndProm.Name = 'Test1';
        objAndProm.EUR_CRM_Status__c = 'Published';
        update objAndProm;

        insert newVisit;

        Database.executeBatch(new EUR_CRM_SE_AccrueAchievements(), 200);
//        EUR_CRM_SE_AccrueAchievements.accrue(new List<EUR_CRM_Visit_Action__c> { newVisit });
        Test.stopTest();
    }
}