objects/EUR_CRM_Contract__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <errorMessage>Chain contract cannot be created for an Outlet account.</errorMessage>
            <filterItems>
                <field>EUR_CRM_Account__c.EUR_CRM_Business_Type__c</field>
                <operation>equals</operation>
                <value>Head Office</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>EUR FI Chain Contract</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>EUR FI Chain Contract</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>Contracts (Account)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.EUR_CRM_Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.EUR_CRM_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(CONTAINS( MID(RecordType.DeveloperName,5,3) , &apos;_&apos;),MID(RecordType.DeveloperName,5,2), MID(RecordType.DeveloperName,5,3))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_End_Date__c</fullName>
        <defaultValue>IF ( Today()&lt; Date(YEAR(TODAY()), 06, 30), Date(YEAR(TODAY()), 06, 30), Date(YEAR(TODAY())+1, 06, 30)
)</defaultValue>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Include_VAT__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field created to select the FI PDF Template</description>
        <label>Include VAT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Is_this_contract_material__c</fullName>
        <label>Is this contract material?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Is_this_contract_profitable__c</fullName>
        <label>Is this contract profitable enough?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Proposal Approved</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
                <value>
                    <fullName>Approved-Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Prolongated</fullName>
                </value>
                <value>
                    <fullName>Waiting for sync</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract (EU)</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_FI_Chain_Contract</fullName>
        <active>true</active>
        <label>EUR FI Chain Contract</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Size__c.object
<CustomObject>
    <description>PREU Data Model</description>
    <label>Brand-Quality-Size (EU)</label>
    <nameField>
        <label>Brand Quality Size</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand-Quality-Size (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(OR(CONTAINS(UserRole.DeveloperName  ,&apos;IDL&apos;),CONTAINS(UserRole.DeveloperName  ,&apos;IDG&apos;)),&apos;IDL&apos;,
IF(CONTAINS(UserRole.DeveloperName, &apos;EUR_We&apos;), &apos;DE&apos;, 
IF(CONTAINS(UserRole.DeveloperName, &apos;EUR_CCA&apos;), &apos;CCA&apos;,  
IF(BEGINS(UserRole.DeveloperName, &apos;EUR_&apos;), RIGHT(LEFT(UserRole.DeveloperName, 6), 2),

IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;AO&quot;), &quot;AO;&quot;,&quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;BE&quot;), &quot;BE;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;BG&quot;), &quot;BG;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;CH&quot;), &quot;CH;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;DE&quot;), &quot;DE;&quot;,&quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;DK&quot;), &quot;DK;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;FI&quot;), &quot;FI;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;GB&quot;), &quot;GB;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;KE&quot;), &quot;KE;&quot;,&quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;MA&quot;), &quot;MA;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;NG&quot;), &quot;NG;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;PT&quot;), &quot;PT;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;RU&quot;), &quot;RU;&quot;,&quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;ZA&quot;), &quot;ZA;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;IDL&quot;), &quot;IDL;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;DB&quot;), &quot;DB;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;IT&quot;), &quot;IT;&quot;,&quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;SE&quot;), &quot;SE;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;NL&quot;), &quot;NL;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;AT&quot;), &quot;AT;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;CCA&quot;), &quot;CCA;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;DO&quot;), &quot;DO;&quot;, &quot;&quot;)
))))</formula>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EUR_CRM_FI_TestContract_PDF_Ext.cls
@isTest
public class EUR_CRM_FI_TestContract_PDF_Ext{
    
    static User eurSysUser;
    static EUR_CRM_Size__c bqs;
    static void setUser(){
        Profile p = [SELECT Id FROM Profile WHERE Name ='EUR System Admin']; 
        UserRole r = [select id from UserRole where Developername ='EMEA'];
        eurSysUser = new User(Alias = 'standt', Email='userEmail1234aoke@test.com', userroleid=r.id,
        EmailEncodingKey='UTF-8', LastName='userEmail1234aokelastName', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='userEmail1234aoke@test.com');
        insert eurSysUser;
    }

    /**
       EUR_CRM_FI_ContractBuilderController
    */
    static testMethod  void testTrigger(){
        setUser();
        System.runAs(eurSysUser){
            //create eu account, contact, contract
            Id fiOnAccountRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Account__c' ,'EUR_FI_Direct_On_Trade');
            Id fiOnContactRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('Contact' ,'EUR_Contact_FI');         
            Id fiOnContractRecordTypeId = EUR_CRM_TestClassUtilityHelper.getRecordTypeId('EUR_CRM_Contract__c' ,'EUR_FI_Chain_Contract');
         
            EUR_CRM_Account__c headOffice = new EUR_CRM_Account__c(recordtypeid = fiOnAccountRecordTypeId,
            name = 'test',EUR_CRM_Business_Type__c = 'Head Office');
            insert headOffice ;
           //  Contact contact = new Contact (EUR_CRM_Account__c = headOffice.id, recordtypeid = fiOnContactRecordTypeId, lastname='test');
           //  insert contact;
         Test.startTest();           
            // START TEST ---    
            EUR_CRM_Account__c outlet = new EUR_CRM_Account__c(recordtypeid = fiOnAccountRecordTypeId,
            name = 'test', EUR_CRM_Parent_Account__c = headOffice.id);
            insert outlet;   
            EUR_CRM_Contract__c contract = new EUR_CRM_Contract__c(
                 recordtypeid = fiOnContractRecordTypeId,
                 EUR_CRM_Account__c = headOffice.id,
           //      EUR_CRM_Contact__c = contact.id,
                 EUR_CRM_Start_Date__c = System.today(),
                 EUR_CRM_End_Date__c = System.today(),
                 EUR_CRM_Status__c = 'Draft'
            ); 
              insert contract;
             contract = [select id,    EUR_CRM_Status__c , EUR_CRM_Include_VAT__c,EUR_CRM_Contact__c,EUR_CRM_Account__c,EUR_CRM_Account__r.ownerid ,EUR_CRM_Is_this_contract_material__c,EUR_CRM_Is_this_contract_profitable__c,RecordType.developername,EUR_CRM_Country_Code__c
                             from  EUR_CRM_Contract__c where id=:contract.id];
        
            ApexPages.StandardController sc = new ApexPages.StandardController(contract);
            EUR_CRM_FI_Contract_PDF_Ext con = new EUR_CRM_FI_Contract_PDF_Ext(sc);
            con.getSRContact();
            con.getAccountContact();
            con.getDraftDate(); 
            system.assert(con.getHasSubOutlets());
            Test.stopTest();           
            // STOP TEST ---
        }
    }
}