objects/EUR_CRM_AccountGroupUser__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Record shared</fullName>
                </value>
                <value>
                    <fullName>To Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Group User (EU)</label>
    <nameField>
        <displayFormat>AGU-{000000000}</displayFormat>
        <label>Account Group User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Group Users (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EUR_CRM_AccountGroupUserDeletionExt.cls
public with sharing class EUR_CRM_AccountGroupUserDeletionExt {

    public String message { get; set; }

    private ApexPages.StandardController standardController;

    @TestVisible
    private static final String TO_DELETE_STATUS = 'To Delete';

    @TestVisible
    private static final String CANNOT_DELETE_RECORD_MANUALLY =
        'Cannot delete a record manually. Please, press a button "Mark \'To Delete\'" to start a deletion process.';
    @TestVisible
    private static final String RECORD_ALREADY_MARKED =
        'A record already marked \'To Delete\'.';


    public EUR_CRM_AccountGroupUserDeletionExt(ApexPages.StandardController standardController) {
        this.standardController = standardController;

        Id recordId = this.standardController.getId();

        List<EUR_CRM_AccountGroupUser__c> accountGroupUsers = this.selectAccountGroupUsersWhereId(recordId);
        if (accountGroupUsers.isEmpty()) { return ; }

        if ( ! accountGroupUsers[0].EUR_CRM_Status__c.equalsIgnoreCase('To Delete')) {
            this.message = CANNOT_DELETE_RECORD_MANUALLY;
        } else {
            this.message = RECORD_ALREADY_MARKED;
        }
    }


    /* ========================================================= */
    /*     SOQL Selectors
    /* ========================================================= */
    private List<EUR_CRM_AccountGroupUser__c> selectAccountGroupUsersWhereId(Id recordId) {
        return [
            SELECT Id
            ,   EUR_CRM_Status__c
            FROM EUR_CRM_AccountGroupUser__c
            WHERE Id = :recordId
                AND EUR_CRM_Status__c != NULL
        ];
    }

}