objects/EUR_ISP_Settlement__c.object
<CustomObject>
    <description>In use for iSpend</description>
    <label>Settlement (EU)</label>
    <nameField>
        <displayFormat>SE-{00000000}</displayFormat>
        <label>Settlement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Country_Code__c</fullName>
        <formula>IF(OR(CONTAINS(UserRole.DeveloperName  ,&apos;IDL&apos;),CONTAINS(UserRole.DeveloperName  ,&apos;IDG&apos;)),&apos;IDL&apos;,
IF(CONTAINS(UserRole.DeveloperName, &apos;EUR_We&apos;), &apos;DE&apos;, 
IF(CONTAINS(UserRole.DeveloperName, &apos;EUR_CCA&apos;), &apos;CCA&apos;,  
IF(BEGINS(UserRole.DeveloperName, &apos;EUR_&apos;), RIGHT(LEFT(UserRole.DeveloperName, 6), 2),

IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;AO&quot;), &quot;AO;&quot;,&quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;BE&quot;), &quot;BE;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;BG&quot;), &quot;BG;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;CH&quot;), &quot;CH;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;DE&quot;), &quot;DE;&quot;,&quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;DK&quot;), &quot;DK;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;FI&quot;), &quot;FI;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;GB&quot;), &quot;GB;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;KE&quot;), &quot;KE;&quot;,&quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;MA&quot;), &quot;MA;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;NG&quot;), &quot;NG;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;PT&quot;), &quot;PT;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;RU&quot;), &quot;RU;&quot;,&quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;ZA&quot;), &quot;ZA;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;IDL&quot;), &quot;IDL;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;DB&quot;), &quot;DB;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;IT&quot;), &quot;IT;&quot;,&quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;SE&quot;), &quot;SE;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;NL&quot;), &quot;NL;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;AT&quot;), &quot;AT;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;CCA&quot;), &quot;CCA;&quot;, &quot;&quot;)
&amp;
IF( INCLUDES(EUR_CRM_Affiliate_Code_Picklist__c , &quot;DO&quot;), &quot;DO;&quot;, &quot;&quot;)
))))</formula>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EUR_ISP_SettlementEditExtension.cls
/**
 * Custom AccountEU Lookup for Settlement Edit / Create page for iSPend APP
 *
 * @author afi
 * @copyright PARX
 */
public without sharing class EUR_ISP_SettlementEditExtension
{
	private ApexPages.StandardController stdConroller;
	public EUR_ISP_SettlementEditExtension(ApexPages.StandardController stdConroller)
	{
		this.stdConroller = stdConroller;
	}

	public PageReference init()
	{
		User theUser = EUR_ISP_HomeController.getCurrentUserInfo();
		final String countryCode = Test.isRunningTest() ? EUR_ISP_Utils.COUNTRY_CODE_DE : theUser.EUR_CRM_Country_Code__c;
		if (countryCode != EUR_ISP_Utils.COUNTRY_CODE_DE || Test.isRunningTest())
		{
			Map<String, String> params = ApexPages.currentPage().getParameters();
			if (this.stdConroller.getId() == null)
			{

				PageReference createView = new PageReference('/' + EUR_ISP_Settlement__c.sObjectType.getDescribe().getKeyPrefix() + '/e?' );
				if (params.containsKey('retURL'))
				{
					createView.getParameters().put('retURL', params.get('retURL'));
				}
				if (params.containsKey('RecordType'))
				{
					createView.getParameters().put('RecordType', params.get('RecordType'));
				}
				if (params.containsKey('ent'))
				{
					createView.getParameters().put('ent', params.get('ent'));
				}
				createView.getParameters().put('nooverride', '1');
				return createView;
			}
			else
			{
				PageReference editView = this.stdConroller.edit();
				if (params.containsKey('retURL'))
				{
					editView.getParameters().put('retURL', params.get('retURL'));
				}
				editView.getParameters().put('nooverride', '1');
				return editView;
			}
		}
		return null;
	}

	public PageReference customSave()
	{
		sObject obj = stdConroller.getRecord();
		if (obj != null)
		{
			upsert obj;
			return new ApexPages.StandardController(obj).view();
		}
		return null;
	}
}