objects/EUR_CRM_Image_Level__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Image Level (EU)</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Image Level No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Image Level (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_PRS_Group_Outlet_Type__c.object
<CustomObject>
    <description>This is created for the new approach for PROS and PROFS -  “PRS” (Pernod-Ricard Segmentation).

PR BG is the first country to use it.</description>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PRS Group Outlet Type (EU)</label>
    <nameField>
        <displayFormat>PRS-GO-{00000}</displayFormat>
        <label>PRS Group Outlet Type No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRS Group Outlet Types (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_PRS_Outlet_Type__c.object
<CustomObject>
    <description>This is created for the new approach for PROS and PROFS -  “PRS” (Pernod-Ricard Segmentation).

PR BG is the first country to use it.</description>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EUR_CRM_PRS_Group_Outlet_Type__c</fullName>
        <label>PRS Group Outlet Type</label>
        <referenceTo>EUR_CRM_PRS_Group_Outlet_Type__c</referenceTo>
        <relationshipLabel>PRS Outlet Types (EU)</relationshipLabel>
        <relationshipName>EUR_CRM_PRS_Outlet_Type</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PRS Outlet Type (EU)</label>
    <nameField>
        <displayFormat>PRS-O-{00000}</displayFormat>
        <label>PRS Outlet Type No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRS Outlet Types (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_PRS_Segmentation__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_Account__c</fullName>
        <label>Account (EU)</label>
        <referenceTo>EUR_CRM_Account__c</referenceTo>
        <relationshipLabel>PRS Segmentation (EU)</relationshipLabel>
        <relationshipName>EUR_CRM_PRS_Segmentation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Image_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Image Level</label>
        <referenceTo>EUR_CRM_PRS_Seg_Aspect__c</referenceTo>
        <relationshipLabel>PRS Segmentation (EU) (Image Level)</relationshipLabel>
        <relationshipName>PRS_Segmentation_EU1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_PRS_Group_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Outlet Type</label>
        <referenceTo>EUR_CRM_PRS_Group_Outlet_Type__c</referenceTo>
        <relationshipLabel>PRS Segmentation (EU)</relationshipLabel>
        <relationshipName>EUR_CRM_PRS_Segmentation_5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_PRS_Outlet_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outlet Type</label>
        <referenceTo>EUR_CRM_PRS_Outlet_Type__c</referenceTo>
        <relationshipLabel>PRS Segmentation (EU)</relationshipLabel>
        <relationshipName>EUR_CRM_PRS_Segmentation_6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EUR_CRM_Volume_Potential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volume Potential</label>
        <referenceTo>EUR_CRM_PRS_Seg_Aspect__c</referenceTo>
        <relationshipLabel>PRS Segmentation (EU) (Volume Potential)</relationshipLabel>
        <relationshipName>PRS_Segmentation_EU</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PRS Segmentation (EU)</label>
    <nameField>
        <displayFormat>PRS-{0000000000}</displayFormat>
        <label>PRS Segmentation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRS Segmentation (EU)</pluralLabel>
    <recordTypes>
        <fullName>EUR_PRS_Segmentation_Off_Trade</fullName>
        <active>true</active>
        <label>EUR PRS Segmentation - Off Trade</label>
    </recordTypes>
    <recordTypes>
        <fullName>EUR_PRS_Segmentation_On_Trade</fullName>
        <active>true</active>
        <label>EUR PRS Segmentation - On Trade</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EUR_CRM_Volume_Potential__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Volume Potential (EU)</label>
    <nameField>
        <displayFormat>V-{00000}</displayFormat>
        <label>Volume Potential No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Potential (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EUR_CRM_PrsFromAccountMigratingBatchTest.cls
@IsTest
private class EUR_CRM_PrsFromAccountMigratingBatchTest {
    @IsTest
    private static void prosToPrsMigratingBatchTest() {
        EUR_CRM_PRS_Group_Outlet_Type__c prsgot = new EUR_CRM_PRS_Group_Outlet_Type__c(EUR_CRM_External_ID__c = 'DE_GOT_RST');
        insert prsgot;

        EUR_CRM_Account__c acc = new EUR_CRM_Account__c(
                EUR_CRM_PRS_Group_Outlet_Type__c = prsgot.Id,
                Name = 'Test Name',
                EUR_CRM_Channel__c = 'ON TRADE',
                EUR_CRM_Postal_Code__c = '02568',
                RecordTypeId = Schema.SObjectType.EUR_CRM_Account__c.getRecordTypeInfosByDeveloperName().get('EUR_DE_On_Trade_B2B').getRecordTypeId()
        );
        insert acc;

        Map<String, String> accountToPrsSegmentationMapping = new Map<String, String> {
            'EUR_CRM_PRS_Group_Outlet_Type__c' => 'EUR_CRM_PRS_Group_Outlet_Type__c',
            'EUR_CRM_PRS_Outlet_Type__c' => 'EUR_CRM_PRS_Outlet_Type__c',
            'EUR_CRM_PRS_Image_Level__c' => 'EUR_CRM_Image_Level__c',
            'EUR_CRM_PRS_Volume_Potential__c' => 'EUR_CRM_Volume_Potential__c'
        };

        Map<String, String> channelToRecordTypeMapping = new Map<String, String>{
                'OFF TRADE'  => 'EUR_PRS_Segmentation_Off_Trade',
                'ON TRADE'  => 'EUR_PRS_Segmentation_On_Trade'
        };

        Test.startTest();
        Database.executeBatch(new EUR_CRM_PrsFromAccountMigratingBatch(accountToPrsSegmentationMapping, channelToRecordTypeMapping));
        Test.stopTest();

        List<EUR_CRM_PRS_Segmentation__c> prsSegmentations = [SELECT Id FROM EUR_CRM_PRS_Segmentation__c WHERE EUR_CRM_Account__c = :acc.Id AND EUR_CRM_PRS_Group_Outlet_Type__c = :prsgot.Id];
        System.assertEquals(1, prsSegmentations.size());
    }
}