objects/EUR_CRM_AccountGroup__c.object
<CustomObject>
    <label>Account Group (EU)</label>
    <nameField>
        <displayFormat>AG-{000000}</displayFormat>
        <label>Account Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Groups (EU)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EUR_CRM_AccountGroupUser__c.object
<CustomObject>
    <fields>
        <fullName>EUR_CRM_AccountGroup__c</fullName>
        <label>Account Group (EU)</label>
        <referenceTo>EUR_CRM_AccountGroup__c</referenceTo>
        <relationshipLabel>Account Group Users (EU)</relationshipLabel>
        <relationshipName>EUR_CRM_AccountGroupUsers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Group User (EU)</label>
    <nameField>
        <displayFormat>AGU-{000000000}</displayFormat>
        <label>Account Group User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Group Users (EU)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EUR_CRM_AccountEUSharingWebService.cls
//noinspection ApexUnusedDeclaration
global class EUR_CRM_AccountEUSharingWebService {

    @TestVisible
    private static final String SUCCESSFULLY_RUN_MIGRATION = 'A batch successfully run. Data will be migrated in few minutes. ' +
        'You will receive an email message when migration is finished.';

    @TestVisible
    private static final String SUCCESSFULLY_RUN_DATA_SHARING = 'A batch successfully run. Data will be shared in few minutes. ' +
        'You will receive an email message when data sharing is finished.';


    webService static String run_EUR_CRM_AccountEUShareBatch(Id accountId) {
        System.debug('\n\n accountId => ' + JSON.serializePretty(accountId) + '\n');

        Database.executeBatch(new EUR_CRM_AccountEUShareBatch(accountId), 200);

        return SUCCESSFULLY_RUN_MIGRATION;
    }

    webService static String run_EUR_CRM_AccGroupUserSharingBatch_for_AG(Id accountGroupId) {
        System.debug('\n\n accountGroupId => ' + JSON.serializePretty(accountGroupId) + '\n');

        Database.executeBatch(new EUR_CRM_AccGroupUserSharingBatch(selectAccountGroupUserById(accountGroupId).keySet()), 200);

        return SUCCESSFULLY_RUN_DATA_SHARING;
    }

    webService static String run_EUR_CRM_AccGroupUserSharingBatch_for_AGU(Id accountGroupUserId) {
        System.debug('\n\n accountGroupUserId => ' + JSON.serializePretty(accountGroupUserId) + '\n');

        Database.executeBatch(new EUR_CRM_AccGroupUserSharingBatch(accountGroupUserId), 200);

        return SUCCESSFULLY_RUN_DATA_SHARING;
    }


    /* ========================================================= */
    /*     SOQL Selectors
    /* ========================================================= */
    private static Map<Id, EUR_CRM_AccountGroupUser__c> selectAccountGroupUserById(Id agId) {
        return new Map<Id, EUR_CRM_AccountGroupUser__c>([
            SELECT Id
            FROM EUR_CRM_AccountGroupUser__c
            WHERE EUR_CRM_AccountGroup__c = :agId
        ]);
    }

}