objects/GDT_Activity_Line__c.object
<CustomObject>
    <fields>
        <fullName>GDT_Activity_Relationship__c</fullName>
        <label>GDT Activity Relationship</label>
        <referenceTo>GDT_Activity__c</referenceTo>
        <relationshipName>GDT_Activity_LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Performed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GDT_Activity_LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GDT Activity Line</label>
    <nameField>
        <displayFormat>{DD}{MM}-{00}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDT Activity Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GDT_ManageActivity_Controller_Line.cls
/**
 * Name     :   GDT_ManageActivity_Controller_Line.cls
 *  Apex Class Controller
 *
 * Author   :   Simon GAZIN
 * Date     :   23.07.2014
 *
 *******************************************************/
public with sharing class GDT_ManageActivity_Controller_Line {

	//Variable declaration
	public GDT_Activity_Line__c record;	//Record of Line

	/**
	 * Controller
	 */
	public GDT_ManageActivity_Controller_Line(ApexPages.StandardController controller) {

		//Contains the value of the record
		record = (GDT_Activity_Line__c)controller.getRecord();

		//Automatic insertion of the field : PerformedBy
		record.Performed_By__c = UserInfo.getUserId();
	}


	/**
	 * saveCustom
	 *  This function save the record and after save the ViewActivity page is return
	 */
	public PageReference saveCustom(){
		if(!Test.isRunningTest()){
			//Save the record of LineItem
			PageReference pageRetURL = new PageReference(ApexPages.currentPage().getParameters().get('retURL'));
			record.GDT_Activity_Relationship__c = pageRetURL.getParameters().get('Id');
		}
		insert record;

		//Redirecting page
		PageReference pageRef = new PageReference('/apex/GDT_ManageActivity_ViewActivity?id='+record.GDT_Activity_Relationship__c);

		return pageRef;
	}
}