objects/LAT_ACCOUNT__c.object
<CustomObject>
    <label>LAT_ACCOUNT</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>LAT_ACCOUNT Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LAT_ACCOUNT</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LAT_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LAT Opportunities</relationshipLabel>
        <relationshipName>LAT_Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_CDAction__c</fullName>
        <description>U: Update
C: Cancel
I: Insert</description>
        <inlineHelpText>U: Update
C: Cancel
I: Insert</inlineHelpText>
        <label>Código ação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_CloseDate__c</fullName>
        <label>Close Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LAT_Country__c</fullName>
        <label>País</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_DSMessage1__c</fullName>
        <label>Mensagem 1 para Nota Fiscal</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_DSMessage2__c</fullName>
        <label>Mensagem 2 para Nota Fiscal</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_DTDelivery__c</fullName>
        <label>Data de entrega</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LAT_EstimatedDeliveryDate__c</fullName>
        <description>Data calculada pela inclusão de itens através do calendário PERNOD. Esta informação é calculada enquanto o pedido não é enviado ao JDE.</description>
        <label>Data entrega sugerida</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LAT_FreightFormulaDisplay__c</fullName>
        <label>% Freight Formula Display</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LAT_FreightPercent__c</fullName>
        <label>% Frete</label>
        <summarizedField>LAT_OpportunityLineItem__c.LAT_FreightPercent__c</summarizedField>
        <summaryForeignKey>LAT_OpportunityLineItem__c.LAT_Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>LAT_MX_OrderPaymentPeriodReference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New payment condition applied to the current order</description>
        <label>Order payment period reference</label>
        <referenceTo>UDC__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>LAT_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_MX_PurchaseOrderSince__c</fullName>
        <label>Purchase Order (Since)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LAT_MX_PurchaseOrderUntil__c</fullName>
        <label>Purchase Order (Until)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LAT_NRCustomerOrder__c</fullName>
        <label>Número do pedido do cliente</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_OrderOrigin__c</fullName>
        <label>Origem do pedido</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CRM</fullName>
                    <default>true</default>
                    <label>CRM</label>
                </value>
                <value>
                    <fullName>EDI</fullName>
                </value>
                <value>
                    <fullName>JDE</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_Pallet_Quantity__c</fullName>
        <label>Pallet Quantity</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_StageName__c</fullName>
        <label>Stage Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Novo pedido</fullName>
                </value>
                <value>
                    <fullName>Pedido enviado para o JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido cancelado no JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido com erro no JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido processado no JDE</fullName>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Needs Analysis</fullName>
                </value>
                <value>
                    <fullName>Value Proposition</fullName>
                </value>
                <value>
                    <fullName>Id. Decision Makers</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Negotiation/Review</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Pedido con descuento en aprobación</fullName>
                </value>
                <value>
                    <fullName>Pedido con descuento aprobado</fullName>
                </value>
                <value>
                    <fullName>Payment period approval</fullName>
                </value>
                <value>
                    <fullName>Approval rejected</fullName>
                </value>
                <value>
                    <fullName>Approval pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Mobile Order</fullName>
                </value>
                <value>
                    <fullName>Moblie Order Sent To JDE</fullName>
                </value>
                <value>
                    <fullName>Pedido Ofrecido en aprobación</fullName>
                </value>
                <value>
                    <fullName>Pedido Ofrecido aprobado</fullName>
                </value>
                <value>
                    <fullName>Pedido Reprovado</fullName>
                </value>
                <value>
                    <fullName>Totally billed</fullName>
                </value>
                <value>
                    <fullName>Partially billed</fullName>
                </value>
                <value>
                    <fullName>EDI Order Approved</fullName>
                </value>
                <value>
                    <fullName>EDI Order Rejected</fullName>
                </value>
                <value>
                    <fullName>EDI Em Aprovação</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Empresa existente</fullName>
                </value>
                <value>
                    <fullName>Nova empresa</fullName>
                </value>
                <value>
                    <fullName>Add-On Business</fullName>
                </value>
                <value>
                    <fullName>New Business</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>SO - Standard Order</fullName>
                </value>
                <value>
                    <fullName>SV - Free Goods (Sales)</fullName>
                </value>
                <value>
                    <fullName>SF - Border Order</fullName>
                </value>
                <value>
                    <fullName>SD - Post Delivery Billing</fullName>
                </value>
                <value>
                    <fullName>SG - No Charge FC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LAT Opportunity</label>
    <nameField>
        <label>Pedido</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_OpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>LAT_AR_Discount__c</fullName>
        <label>Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_AR_SentToApproveDiscount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent to Approve Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_AR_UOM__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PL</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>BT</fullName>
                </value>
                <value>
                    <fullName>BX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_CDAction__c</fullName>
        <inlineHelpText>U: Update
C: Cancel
I: Insert</inlineHelpText>
        <label>Código ação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_FreightPercent__c</fullName>
        <label>% Frete</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_NROrderLine__c</fullName>
        <label>Número da linha de pedido JDE</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>LAT_Opportunity__c</referenceTo>
        <relationshipLabel>OpportunityLineItems</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LAT_Pallet_Total_Quantity__c</fullName>
        <label>Pallet Total Quantity</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_PaymentCondition__c</fullName>
        <label>Payment condition</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_PercentualOfBonus__c</fullName>
        <label>% Bonif</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>LAT_Product__c</referenceTo>
        <relationshipLabel>OpportunityLineItems</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_QTBonus__c</fullName>
        <label>Qt Bonif</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_Remover__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_SkuText__c</fullName>
        <label>Sku</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_UnitCode__c</fullName>
        <label>Unit code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_UnitPrice__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LAT Opportunity Product</label>
    <nameField>
        <label>LAT Opportunity Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_Product__c.object
<CustomObject>
    <fields>
        <fullName>LAT_Country__c</fullName>
        <externalId>true</externalId>
        <label>Código de país</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LAT Product</label>
    <nameField>
        <label>LAT Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LAT_Rest_Opportunities.cls
@RestResource(urlMapping='/LAT_Rest_Opportunities/*')
global with sharing class LAT_Rest_Opportunities {
    
    @HttpPost
    global static void POST() {
    	LAT_Opportunity__c opp = new LAT_Opportunity__c();
    	RestRequest req = RestContext.request;
        LAT_OpportunityHandlerJSON pedido = (LAT_OpportunityHandlerJSON)System.JSON.deserialize(req.requestBody.toString(), LAT_OpportunityHandlerJSON.class);
        System.debug('Pedido : ' + pedido);
        System.debug('Pedido.account : ' + pedido.header.account);

        String response = insertOpportunity(pedido, opp);

        ServiceResponse res = new ServiceResponse(opp.Id, response, response =='');

        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody   = Blob.valueOf(JSON.serialize(res));
        if (res.success) {
            RestContext.response.statusCode     = 200;
        } else {
            RestContext.response.statusCode     = 400;
        }
    }

    @HttpPut
    global static void PUT() {
    	
    	RestRequest req = RestContext.request;
        LAT_OpportunityHandlerJSON pedido = (LAT_OpportunityHandlerJSON)System.JSON.deserialize(req.requestBody.toString(), LAT_OpportunityHandlerJSON.class);
        System.debug('Pedido : ' + pedido);
        System.debug('Pedido.ID : ' + pedido.header.Id);
        LAT_Opportunity__c opp = [SELECT Id, LAT_Account__c FROM LAT_Opportunity__c Where Id =:pedido.header.Id];
        Boolean isCancel = false;
        String response;

        pedido.header.account = opp.LAT_Account__c;

        for (LAT_OpportunityHandlerJSON.Detail oppItem: pedido.detail) {
        	System.debug('oppItem.actionCode  : ' + oppItem.actionCode);
        	if(pedido.header.actionCode == 'C'){
        		oppItem.actionCode = 'C';
        	}
        	if(oppItem.actionCode != null){
        		if(oppItem.actionCode == 'C'){
        			isCancel = true;
        		}
        	}
        }
        if(isCancel){
        	response = cancelOpportunity(pedido);
        } else {
        	response = updateOpportunity(pedido, opp);
        }
        

        ServiceResponse res = new ServiceResponse(opp.Id, response, response =='');

        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody   = Blob.valueOf(JSON.serialize(res));
        if (res.success) {
            RestContext.response.statusCode     = 200;
        } else {
            RestContext.response.statusCode     = 400;
        }
    }

    public static String insertOpportunity(LAT_OpportunityHandlerJSON pedido, LAT_Opportunity__c opp) {
    	String retorno = '';
    	String accId = pedido.header.account;
    	System.debug('%%% accId : ' + accId);
 		Account acc = [SELECT Id, CurrencyIsoCode, Client_country_An8__c FROM Account WHERE Id = :accId];
 		if(acc == null) {
 			return 'Cliente no encontrado.';
 		}
 		try{
	        opp.Name                            = pedido.header.name;
	        opp.CurrencyIsoCode                 = acc.CurrencyIsoCode;
	        opp.LAT_Account__c                  = pedido.header.account;
	        opp.LAT_NRCustomerOrder__c          = pedido.header.customerOrderNr;
	        opp.LAT_DSMessage1__c               = pedido.header.message1;
	        opp.LAT_DSMessage2__c               = pedido.header.message2;
	        opp.LAT_OrderOrigin__c              = 'APP';
	        
	        if(pedido.header.type_Z.equalsIgnoreCase('SJ')){
				opp.LAT_Type__c = 'SJ - Ofrecidos de Ventas por Acuerdos';
			} else  if(pedido.header.type_Z.equalsIgnoreCase('SH')) {
				opp.LAT_Type__c = 'SH - Ofrecidos de Ventas por Acuerdos Comerciales';
			} else {
				opp.LAT_Type__c = pedido.header.type_Z;
			}

	        //opp.LAT_Type__c                     = pedido.header.type_Z;

	        if(pedido.header.stage != null)
	        	opp.LAT_StageName__c                = pedido.header.stage;
	        opp.LAT_CloseDate__c                = Date.valueOf(pedido.header.closeDate);
	        
	        
	        if(pedido.header.deliveryDate != null && pedido.header.deliveryDate != '') {
	            opp.LAT_DTDelivery__c               = Date.valueOf(pedido.header.deliveryDate);
	            if(acc.Client_country_An8__c.startsWith('1-'))
	            	opp.LAT_EstimatedDeliveryDate__c    = Date.valueOf(pedido.header.deliveryDate);
	        }

	        if(acc.Client_country_An8__c.startsWith('1-')){
	        	opp.LAT_FreightFormulaDisplay__c    	  = pedido.header.totalFreightPercent;
	        	opp.LAT_Pallet_Quantity__c          	  = pedido.header.totalPalletQuantity;
	        }
	        if(acc.Client_country_An8__c.startsWith('12-')){
                if(pedido.header.mxPurchaseOrderSince != null && pedido.header.mxPurchaseOrderSince != '')
	        	opp.LAT_MX_PurchaseOrderSince__c = Date.valueOf(pedido.header.mxPurchaseOrderSince);
                if(pedido.header.mxPurchaseOrderUntil != null && pedido.header.mxPurchaseOrderUntil != '')
	        	opp.LAT_MX_PurchaseOrderUntil__c = Date.valueOf(pedido.header.mxPurchaseOrderUntil);
	        	opp.LAT_MX_OrderPaymentPeriodReference__c = pedido.header.mxPaymentCondition;
	        }
	        insert opp;

			List<LAT_OpportunityLineItem__c> lines = new List<LAT_OpportunityLineItem__c>();
	        for (LAT_OpportunityHandlerJSON.Detail oppItem: pedido.detail) {
	            LAT_OpportunityLineItem__c line = new LAT_OpportunityLineItem__c();
	            if(acc.Client_country_An8__c.startsWith('1-')){
	            	line.LAT_PaymentCondition__c        = oppItem.paymentCondition;
	            	line.LAT_UnitCode__c                = oppItem.measurementUnit;
	            	if(oppItem.quantityBonus != null) {
	            		if(oppItem.quantityBonus > 0)line.LAT_QTBonus__c	= oppItem.quantityBonus;
	            	}
	            	if(oppItem.sendDicountToApproval != null)
	            		line.LAT_AR_SentToApproveDiscount__c= oppItem.sendDicountToApproval;
	            	line.LAT_FreightPercent__c          = oppItem.skuFreightPercent;
	            	line.LAT_Pallet_Total_Quantity__c   = oppItem.skuPalletQuantity;
	            }
	            if(acc.Client_country_An8__c.startsWith('12-')){
	            	line.LAT_AR_UOM__c					= oppItem.measurementUnit;
	            }
	            if(acc.Client_country_An8__c.startsWith('6-') || acc.Client_country_An8__c.startsWith('5-')){
	            	line.LAT_PaymentCondition__c        = oppItem.paymentCondition;
	            	line.LAT_AR_UOM__c					= oppItem.measurementUnit;
	            	if(oppItem.sendDicountToApproval != null)
	            		line.LAT_AR_SentToApproveDiscount__c= oppItem.sendDicountToApproval;
	            }
	            line.LAT_AR_Discount__c             = oppItem.discount;
	            line.LAT_Quantity__c                = oppItem.quantity;
	            line.LAT_UnitPrice__c               = oppItem.unitPrice;
				line.LAT_Product__c                 = oppItem.PriceBookEntryId;            
				line.LAT_SkuText__c					= oppItem.productSKU;
				
				//line.LAT_NROrderLine__c = String.valueOf(lines.size()); //DEBEN SER VALORES INCREMENTALES
	            if(oppItem.percentualBonus != null) {
	            	if(oppItem.percentualBonus > 0)	line.LAT_PercentualOfBonus__c = oppItem.percentualBonus;
	            }
	            line.LAT_Opportunity__c             = opp.Id;
				lines.add(line);
				
	        } 
	        if(lines.size() > 0) {
	            insert lines;
	        }
	    } catch (Exception e) {
			System.debug('EXCEPCION : ---->' + e.getStackTraceString() + '<-----');
	    	retorno = e.getMessage();
	    }
    	return retorno;
    }

    public static String updateOpportunity(LAT_OpportunityHandlerJSON pedido, LAT_Opportunity__c opp) {
    	String retorno = '';
    	String accId = pedido.header.account;
    	System.debug('%%% accId : ' + accId);
    	
 		Account acc = [SELECT Id, CurrencyIsoCode, Client_country_An8__c FROM Account WHERE Id = :accId];

 		if(acc == null) {
 			return 'Cliente no encontrado.';
 		}
 		try{
	        opp.Name                            = pedido.header.name;
	        opp.CurrencyIsoCode                 = acc.CurrencyIsoCode;
	        opp.LAT_Account__c                  = pedido.header.account;
	        opp.LAT_NRCustomerOrder__c          = pedido.header.customerOrderNr;
	        opp.LAT_DSMessage1__c               = pedido.header.message1;
	        opp.LAT_DSMessage2__c               = pedido.header.message2;
	        opp.LAT_OrderOrigin__c              = 'APP';
	        opp.LAT_Type__c                     = pedido.header.type_Z;
	        if(pedido.header.stage != null)
	        	opp.LAT_StageName__c                = pedido.header.stage;

	        if(pedido.header.closeDate != null)
	        opp.LAT_CloseDate__c                = Date.valueOf(pedido.header.closeDate);
	        
	        
	        if(pedido.header.deliveryDate != null) {
	            opp.LAT_DTDelivery__c               = Date.valueOf(pedido.header.deliveryDate);
	            if(acc.Client_country_An8__c.startsWith('1-'))
	            	opp.LAT_EstimatedDeliveryDate__c    = Date.valueOf(pedido.header.deliveryDate);
	        }

	        if(acc.Client_country_An8__c.startsWith('1-')){
	        	opp.LAT_FreightFormulaDisplay__c    	  = pedido.header.totalFreightPercent;
	        	opp.LAT_Pallet_Quantity__c          	  = pedido.header.totalPalletQuantity;
	        }
	        if(acc.Client_country_An8__c.startsWith('12-')){
	        	opp.LAT_MX_PurchaseOrderSince__c = Date.valueOf(pedido.header.mxPurchaseOrderSince);
	        	opp.LAT_MX_PurchaseOrderUntil__c = Date.valueOf(pedido.header.mxPurchaseOrderUntil);
	        	opp.LAT_MX_OrderPaymentPeriodReference__c = pedido.header.mxPaymentCondition;
	        }
	        update opp;

	        List<LAT_OpportunityLineItem__c> lines = new List<LAT_OpportunityLineItem__c>();
	        for (LAT_OpportunityHandlerJSON.Detail oppItem: pedido.detail) {
	            LAT_OpportunityLineItem__c line = new LAT_OpportunityLineItem__c();
	            if(oppItem.Id.startsWith('aPV')) {
	            	line.Id 	= oppItem.id;
	            } else {
	            	line.LAT_Opportunity__c = opp.Id;
	            }
	            if(acc.Client_country_An8__c.startsWith('1-')){
	            	line.LAT_PaymentCondition__c        = oppItem.paymentCondition;
	            	line.LAT_UnitCode__c                = oppItem.measurementUnit;
	            	if(oppItem.quantityBonus != null) {
	            		if(oppItem.quantityBonus > 0)line.LAT_QTBonus__c	= oppItem.quantityBonus;
	            	}
	            	if(oppItem.sendDicountToApproval != null)
	            		line.LAT_AR_SentToApproveDiscount__c= oppItem.sendDicountToApproval;
	            	line.LAT_FreightPercent__c          = oppItem.skuFreightPercent;
	            	line.LAT_Pallet_Total_Quantity__c   = oppItem.skuPalletQuantity;
	            }
	            if(acc.Client_country_An8__c.startsWith('12-')){
	            	line.LAT_AR_UOM__c					= oppItem.measurementUnit;
	            }

	            if(acc.Client_country_An8__c.startsWith('6-') || acc.Client_country_An8__c.startsWith('5-')){
	            
	            	line.LAT_PaymentCondition__c        = oppItem.paymentCondition;
	            	line.LAT_AR_UOM__c					= oppItem.measurementUnit;
	            	if(oppItem.sendDicountToApproval != null)
	            		line.LAT_AR_SentToApproveDiscount__c= oppItem.sendDicountToApproval;
	            }

	            line.LAT_AR_Discount__c             = oppItem.discount;
	            line.LAT_Quantity__c                = oppItem.quantity;
	            line.LAT_UnitPrice__c               = oppItem.unitPrice;
				line.LAT_Product__c                 = oppItem.PriceBookEntryId;            
	            
	            if(oppItem.percentualBonus != null) {
	            	if(oppItem.percentualBonus > 0)	line.LAT_PercentualOfBonus__c = oppItem.percentualBonus;
	            }
	            
	            lines.add(line);
	        } 
	        if(lines.size() > 0) {
	            upsert lines;
	        }
	    } catch (Exception e) {
	    	retorno = e.getMessage();
	    }
    	return retorno;
    }

    public static String cancelOpportunity(LAT_OpportunityHandlerJSON pedido){
    	String retorno = '';
    	try{
    		List<LAT_OpportunityLineItem__c> toUpdate = new List<LAT_OpportunityLineItem__c>();
	    	for(LAT_OpportunityHandlerJSON.Detail oppItem: pedido.detail) {
	    		if(oppItem.Id.startsWith('aPV')) {
	    			if(oppItem.actionCode == 'C') {
	    				LAT_OpportunityLineItem__c nuevo = new LAT_OpportunityLineItem__c();
						nuevo.Id = oppItem.Id;
						nuevo.LAT_CDAction__c = oppItem.actionCode;
						nuevo.LAT_Remover__c = true;
						toUpdate.add(nuevo);
	    			}
					 

	    		}
	    		 
	    	}
	    	if(toUpdate.size() > 0) {
	    		LAT_Opportunity__c opp = [SELECT Id,LAT_Country__c FROM LAT_Opportunity__c WHERE Id=:pedido.header.Id ];
	    		//update opp;
	    		update toUpdate;
	    		if(opp.LAT_Country__c == 1){
					SalesOrderHandlerInterface.LAT_SalesOrderInterfaceFuture(pedido.header.Id);
				} else if(opp.LAT_Country__c == 5 || opp.LAT_Country__c == 6){
					WS03_SalesOrderHandlerInterface_AR.LAT_SalesOrderInterfaceFuture(pedido.header.Id);
				}
	    		

	    	}
    	} catch (Exception e) {
	    	retorno = e.getMessage();
	    }
	    return retorno;
    }

    public class ServiceResponse {
        
        public String Id;
        public Boolean success;
        public String message;
        public String errorCode;

        public ServiceResponse(String idOpp, String msg, Boolean bool) {
            success = bool;
            message = msg;
            Id = idOpp;
        }
    }
}