objects/LAT_ACCOUNT__c.object
<CustomObject>
    <fields>
        <fullName>LAT_MX_AttendingKAM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ejecutivo que lo atiende</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>LAT_MX2_OnPremise</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>LAT_MX2_Vendedor_OnPremise</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>LAT_MX2_Coordinador_CRM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>LAT_ACCOUNT</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LAT_ACCOUNT</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>LAT_ACCOUNT Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LAT_ACCOUNT</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_Case__c.object
<CustomObject>
    <fields>
        <fullName>LAT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LAT Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LAT_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_TotalValue__c</fullName>
        <formula>LAT_GroupingFiscalYear__r.valor_total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Value ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LAT_Case</label>
    <nameField>
        <label>Demanda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT_Cases</pluralLabel>
    <recordTypes>
        <fullName>B2B_New_Account</fullName>
        <active>true</active>
        <description>Create a new account through the B2B community</description>
        <label>B2B New Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LAT_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LAT Opportunities</relationshipLabel>
        <relationshipName>LAT_Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_CreationDateTime__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Data hora criação</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LAT_TotalValue__c</fullName>
        <label>Valor</label>
        <summarizedField>LAT_OpportunityLineItem__c.LAT_PriceTotal__c</summarizedField>
        <summaryForeignKey>LAT_OpportunityLineItem__c.LAT_Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>LAT Opportunity</label>
    <nameField>
        <label>Pedido</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Titulos__c.object
<CustomObject>
    <label>Título em aberto</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Número do título em aberto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Títulos em aberto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LAT_DNI__c</fullName>
        <label>LAT DNI</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LAT_CTY_B2B_MyAccountController.cls
public with sharing class LAT_CTY_B2B_MyAccountController {
    private static final String TITULO_API_NAME = 'Titulos__c';

    @AuraEnabled
    public static void updateUserEmailPreferences (boolean emailOptOut) {
        //Contact c = getContact();
        //c.HasOptedOutOfEmail = !emailOptOut;
        //update c;
        //return emailOptOut;
        // el contacto no puede actualiuzar por tema permisos, usamos al usuario
        final String userId = UserInfo.getUserId();
        User u = [SELECT Id, ContactId FROM User WHERE Id = :userId];
        u.ReceivesInfoEmails = emailOptOut;
        update u;
    }
    
    @AuraEnabled
    public static boolean getUserEmailPreferences() {
        final String userId = UserInfo.getUserId();
        final User u = [SELECT Id, ContactId, ReceivesInfoEmails FROM User WHERE Id = :userId];
        return u.ReceivesInfoEmails;
    }
    
    @AuraEnabled
    public static List<ListView> getTitulosListViewNames () {
        List<ListView> listNames = [SELECT DeveloperName FROM ListView WHERE SObjectType = 'Titulos__c' AND DeveloperName = 'b2b' limit 1];
        return listNames;
    }
    
    @AuraEnabled
    public static String getAccountIdFromUser() {
        return LAT_CTY_B2B_MyAccountController.getContact().Account.Id;
    }
    
    @AuraEnabled
    public static String getAccountDetail() {
        return JSON.serialize(LAT_WS_GetAvailableCredit.getAvailableCredit(getContact().account.Client_country_AN8__c));
    }


    @AuraEnabled
    public static String getLastOpportunity() {
        try{
            Contact c = getContact();
            LAT_Opportunity__c latOpportunity= [SELECT Name, LAT_TotalValue__c FROM LAT_Opportunity__c WHERE LAT_Account__r.Id = :c.AccountId ORDER BY LAT_CreationDateTime__c DESC LIMIT 1];
            Opportunity opp = new Opportunity(latOpportunity.Name, latOpportunity.LAT_TotalValue__c);
            return JSON.serialize(opp);
        } catch (Exception ex) {
            return JSON.serialize(getContact());
        } 
        
    }
    
    @AuraEnabled
    public static List<Contact> getRelatedContacts() {
            Contact c = getContact();
            List<Contact> lista= [SELECT Name, Title, Phone, MobilePhone, LAT_DNI__c, Birthdate, Email FROM Contact WHERE accountId = :c.Account.Id ORDER BY name];
        	System.debug('Lista a enviar:' + lista);
            return lista; 
    }
    
    @AuraEnabled
    public static Contact getContact(){
        system.debug('ON getContact');
        final String userId = UserInfo.getUserId();
        system.debug('userId ' + userId);
        User u = [SELECT Id, ContactId FROM User WHERE Id = :userId];
        system.debug('USER ' + u);
        Contact c = [SELECT Account.Id, Account.Client_country_AN8__c FROM Contact WHERE  Id = :u.ContactId LIMIT 1];
        system.debug('Contact ' + c);
        return c;
    }
    
    @AuraEnabled
    public static String getCaseAccountRegistrationRTId(){
        
        return Global_RecordTypeCache.getRtId('LAT_Case__c'+'B2B_New_Account');
    }
    Public class Opportunity {
        public final Decimal value;
        public final String name;

        public Opportunity (String name, Decimal value) {
            this.value = value;
            this.name = name;
        }
    } 
}