objects/LAT_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LAT_CDAction__c</fullName>
        <description>U: Update
C: Cancel
I: Insert</description>
        <inlineHelpText>U: Update
C: Cancel
I: Insert</inlineHelpText>
        <label>Código ação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_CancelOrder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_ItemsCanceled__c</fullName>
        <label>Tem item cancelado</label>
        <summaryFilterItems>
            <field>LAT_OpportunityLineItem__c.LAT_Remover__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>LAT_OpportunityLineItem__c.LAT_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>LAT Opportunity</label>
    <nameField>
        <label>Pedido</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Bloqueia_alteracao</fullName>
        <active>true</active>
        <label>Bloqueia alteração</label>
    </recordTypes>
    <recordTypes>
        <fullName>Bloqueia_alteracao_do_cabecalho</fullName>
        <active>true</active>
        <label>Bloqueia alteração do cabeçalho</label>
    </recordTypes>
    <recordTypes>
        <fullName>Nova_oportunidade</fullName>
        <active>true</active>
        <label>Nova oportunidade</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_OpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>LAT_CDAction__c</fullName>
        <inlineHelpText>U: Update
C: Cancel
I: Insert</inlineHelpText>
        <label>Código ação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>LAT_Opportunity__c</referenceTo>
        <relationshipLabel>OpportunityLineItems</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LAT_Remover__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelar</label>
        <type>Checkbox</type>
    </fields>
    <label>LAT Opportunity Product</label>
    <nameField>
        <label>LAT Opportunity Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LAT_LATOpportunity_CodigoAcaoCancelado.cls
//LAT_Opportunity__c TRIGGER
/********************************************************************************
*
* MIGRACION LICENCIAS
* AUTHOR: ZIMMIC                     DATE: 08/11/2016
*
********************************************************************************/

public with sharing class LAT_LATOpportunity_CodigoAcaoCancelado  {

	public static void execute(){
		//    Check if this trigger is bypassed by SESAME (data migration Brazil)
		if((UserInfo.getProfileId()!='00eM0000000QNYPIA4') && (UserInfo.getProfileId()!= '00eD0000001AnFlIAK')) {
		 if(Trigger.isUpdate && Trigger.isBefore){
		    //Declaração de variáveis
		    Set< Id > setRecTypeOpp = new Set< Id >();
		    setRecTypeOpp.add( RecordTypeForTest.getRecType('LAT_Opportunity__c', 'Bloqueia_alteracao'));
		    setRecTypeOpp.add( RecordTypeForTest.getRecType('LAT_Opportunity__c', 'Bloqueia_alteracao_do_cabecalho'));
		    setRecTypeOpp.add( RecordTypeForTest.getRecType('LAT_Opportunity__c', 'Nova_oportunidade'));

			//Se campo Cancelamento_aprovado__c é marcado como TRUE pelo processo de aprovação, copia C para
			//Codigo de acao para os itens de pedido cancelados
			List< String > lListOppId = new List< String >();
		    for ( LAT_Opportunity__c lOpp : LAT_OpportunityTriggerHandler.triggerNew ){
				if( !setRecTypeOpp.contains( lOpp.RecordTypeId )) continue;

				if ( lOpp.LAT_CancelOrder__c )
					lOpp.LAT_CDAction__c = 'C';
				
				if ( lOpp.LAT_ItemsCanceled__c > LAT_OpportunityTriggerHandler.mapOld.get(lOpp.id).LAT_ItemsCanceled__c) {
					lListOppId.add( lOpp.Id );
					lOpp.RecordTypeId = RecordTypeForTest.getRecType('LAT_Opportunity__c', 'Bloqueia_alteracao_do_cabecalho');


				}
		 }
		}
	   if(Trigger.isAfter && Trigger.isUpdate){
	   // if ( lListOppId.size() > 0 ){
	   //
	    	List< String > lListOppId = new List< String >();
	    	for (LAT_Opportunity__c op : LAT_OpportunityTriggerHandler.triggerNew){
	    		if ( op.LAT_ItemsCanceled__c > LAT_OpportunityTriggerHandler.mapOld.get(op.id).LAT_ItemsCanceled__c){
						lListOppId.add( op.Id );
	    		}
	    	}

			if(!lListOppId.isEmpty()){
				List< LAT_OpportunityLineItem__c > lListOppItem = [ SELECT Id, LAT_Opportunity__c, LAT_Remover__c, LAT_CDAction__c FROM LAT_OpportunityLineItem__c WHERE LAT_Opportunity__c =:lListOppId AND LAT_Remover__c = True ];
			    	if ( lListOppItem.size() > 0 ){
			    		for ( LAT_OpportunityLineItem__c lItem : lListOppItem )
			    			//if(trigger.newMap.get(lItem.Id) != null)
			    				lItem.LAT_CDAction__c = 'C';
			    		update lListOppItem;
			    	}
			    }
			}

		}

	}
}