objects/LAT_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LAT_CDAction__c</fullName>
        <description>U: Update
C: Cancel
I: Insert</description>
        <inlineHelpText>U: Update
C: Cancel
I: Insert</inlineHelpText>
        <label>Código ação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>LAT Opportunity</label>
    <nameField>
        <label>Pedido</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Bloqueia_alteracao</fullName>
        <active>true</active>
        <label>Bloqueia alteração</label>
    </recordTypes>
    <recordTypes>
        <fullName>Bloqueia_alteracao_do_cabecalho</fullName>
        <active>true</active>
        <label>Bloqueia alteração do cabeçalho</label>
    </recordTypes>
    <recordTypes>
        <fullName>Nova_oportunidade</fullName>
        <active>true</active>
        <label>Nova oportunidade</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_1_NewOrder_ARG</fullName>
        <active>true</active>
        <label>1 - New Order ARG</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_2_NewOrder_URU</fullName>
        <active>true</active>
        <label>2 - New Order URU</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_3_HeaderBlocked_ARG</fullName>
        <active>true</active>
        <label>3 - Header Blocked ARG</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_4_HeaderBlocked_URU</fullName>
        <active>true</active>
        <label>4 - Header Blocked URU</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_5_OrderBlocked_ARG</fullName>
        <active>true</active>
        <label>5 - Order Blocked ARG</label>
    </recordTypes>
    <recordTypes>
        <fullName>OPP_6_OrderBlocked_URU</fullName>
        <active>true</active>
        <label>6 - Order Blocked URU</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LAT_OpportunityLineItem__c.object
<CustomObject>
    <fields>
        <fullName>LAT_CDAction__c</fullName>
        <inlineHelpText>U: Update
C: Cancel
I: Insert</inlineHelpText>
        <label>Código ação</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LAT_OpportunityRecordTypeId__c</fullName>
        <formula>LAT_Opportunity__r.RecordType.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity RecordType Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAT_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>LAT_Opportunity__c</referenceTo>
        <relationshipLabel>OpportunityLineItems</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>LAT Opportunity Product</label>
    <nameField>
        <label>LAT Opportunity Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LAT_BR_OportunidadeAtualizaDataEntrega.cls
//LAT_OpportunityLineItem__c TRIGGER
/********************************************************************************
* 
* MIGRACION LICENCIAS 
* AUTHOR: ZIMMIC                     DATE: 09/11/2016
*
********************************************************************************/

public with sharing class LAT_BR_OportunidadeAtualizaDataEntrega {
	
	public static void execute(){
		
	    if( LAT_SalesOrderReturn.isFirstContextCall ){
        
	        LAT_SalesOrderReturn.isFirstContextCall = false;
	        //    Check if this trigger is bypassed by SESAME (data migration Brazil)
	        if((UserInfo.getProfileId()!='00eM0000000QNYPIA4') && (UserInfo.getProfileId()!= '00eD0000001AnFlIAK')){
	            
	            Set<Id> setOppRt = Global_RecordTypeCache.getRtIdSet('LAT_Opportunity__c',new set<String>{'Bloqueia_alteracao','Bloqueia_alteracao_do_cabecalho','Nova_oportunidade','OPP_1_NewOrder_ARG', 'OPP_2_NewOrder_URU','OPP_3_HeaderBlocked_ARG','OPP_4_HeaderBlocked_URU','OPP_5_OrderBlocked_ARG', 'OPP_6_OrderBlocked_URU'});
	                                                            
	            List<LAT_OpportunityLineItem__c> lItems = new List<LAT_OpportunityLineItem__c>();
	            if(trigger.isInsert || trigger.isUpdate){
	                for(LAT_OpportunityLineItem__c oli: LAT_OpportunityLineItemTriggerHandler.triggerNew){
	                    if(setOppRt.contains(oli.LAT_OpportunityRecordTypeId__c)){
	                        lItems.add(oli);
	                    }
	                }
	            }else{
	                for(LAT_OpportunityLineItem__c oli: LAT_OpportunityLineItemTriggerHandler.triggerOld){
	                    if(setOppRt.contains(oli.LAT_OpportunityRecordTypeId__c)){
	                        lItems.add(oli);
	                    }
	                }
	            }
	            
	            //Si no hay ningun registro de LAT no continua
	            if(!lItems.isEmpty()){
	    	        List< String > lListOppIDs = new List< String >();
	    	        for(LAT_OpportunityLineItem__c x : lItems)
	    	            if(x.LAT_CDAction__c != 'C')
	    	                lListOppIDs.add(x.LAT_Opportunity__c);
	    	        
	    	        if(lListOppIDs.size() > 0){
	    	            OportunidadeDataEntrega lCalcula = new OportunidadeDataEntrega(lListOppIDs);
	    	            List<LAT_Opportunity__c> lListOpps = new List<LAT_Opportunity__c>();
	    	            Set<String> lSetOpp = new Set<String>();
	    	          
	    	            for(LAT_OpportunityLineItem__c x: lItems){
	    	                if(lSetOpp.contains(x.LAT_Opportunity__c)) continue;
	    	                lSetOpp.add(x.LAT_Opportunity__c);
	    	                LAT_Opportunity__c lOpp = lCalcula.LAT_atualizaPedido(x.LAT_Opportunity__c);
	    	                if(lOpp != null ) lListOpps.add(lOpp);
	    	            }
	    	            if(!lListOpps.isEmpty()) update lListOpps;
	    	        }
	            }
	        }

	    }

	    
	    
	}

}