objects/LAT_KAMPOP__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Quantidade</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>HYPERLINK(RegionalPOP__r.product__c, RegionalPOP__r.product__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionalPOP__c</fullName>
        <label>Distribuição Material POP</label>
        <referenceTo>LAT_RegionalPOP__c</referenceTo>
        <relationshipLabel>Distribuições Campo</relationshipLabel>
        <relationshipName>KAMPOP</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Distribuição Campo</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>Código Distribuição Campo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribuições Campo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_Produto_POP__c.object
<CustomObject>
    <fields>
        <fullName>Evidence__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Coletar Evidência?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Realizar Inventário?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Product__c</fullName>
        <label>Material Pai</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sku__c</fullName>
        <label>Código Material</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Material POP</label>
    <nameField>
        <label>Descrição Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materiais POP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LAT_RegionalPOP__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Quantidade</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Descrição Material</label>
        <referenceTo>LAT_Produto_POP__c</referenceTo>
        <relationshipLabel>Distribuição Material POP</relationshipLabel>
        <relationshipName>Distribui_o_Produtos_POP</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sku__c</fullName>
        <formula>product__r.Sku__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código Material</label>
        <type>Text</type>
    </fields>
    <label>Distribuição Material POP</label>
    <nameField>
        <displayFormat>DM-{0000}</displayFormat>
        <label>Código Distribuição Material</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribuição Material POP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SKU__c.object
<CustomObject>
    <label>SKU</label>
    <nameField>
        <label>SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKU</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LAT_KAM_POP_Trigger_Test.cls
@isTest
private class LAT_KAM_POP_Trigger_Test {
	
	@isTest static void KamPOPTriggerTest() {
 		
 		LAT_KAMPOP__c kam = KamPOPCreator();
 		update kam;
 	}

 	public static LAT_Produto_POP__c productoPOPCreator(){
		
		LAT_Produto_POP__c prod = new LAT_Produto_POP__c();
		prod.Sku__c = '12';
		prod.name = 'ABC';
		prod.Evidence__c = true;
		prod.Parent_Product__c = 'ABC';
		prod.Inventory__c = true;
		insert prod;
		return prod;
	}

	public static LAT_KAMPOP__c KamPOPCreator(){
		
		LAT_RegionalPOP__c reg = new LAT_RegionalPOP__c();
		reg.product__c = productoPOPCreator().id;
		reg.Amount__c = Integer.valueOf('5000');
		insert reg;
		LAT_KAMPOP__c kamPop = new LAT_KAMPOP__c();
		kamPop.Amount__c = Integer.valueOf('300');
		kamPop.RegionalPOP__c = reg.id;
		//kamPop.Client__c = accountCreator().id;
		insert kamPop;
		return kamPOP;
	}

	public static Account accountCreator(){
		
		Account Acc = LAT_Account_TestFactory.getAccountOffTradeBraComplete();
    insert Acc;
    return Acc;
	}
}