objects/LAT_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>LAT_FreightFormulaDisplay__c</fullName>
        <label>% Freight Formula Display</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LAT_Freight_Formula__c</fullName>
        <formula>IF ( OR(LAT_FreightFormulaDisplay__c = 0,  ISNULL(LAT_FreightFormulaDisplay__c) ), &apos;BLANK&apos;,
   IF(MOD(LAT_FreightFormulaDisplay__c ,2) = 0, &apos;BLUE&apos;, 

     IF(AND(OR(MOD(LAT_FreightFormulaDisplay__c ,1) = 0, LAT_FreightFormulaDisplay__c &gt; 2),LAT_FreightFormulaDisplay__c = 1), &apos;GREEN&apos;, 

     IF(LAT_FreightFormulaDisplay__c &gt; 1, &apos;YELLOW&apos;, &apos;RED&apos;)     
   ) 

   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>% Freight Formula</label>
        <type>Text</type>
    </fields>
    <label>LAT Opportunity</label>
    <nameField>
        <label>Pedido</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAT Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LAT_BR_VFC33_OppFreightIndicatorCont.cls
public with sharing class LAT_BR_VFC33_OppFreightIndicatorCont {

	public String percent {get;set;}
	public String color {get;set;}

	public LAT_BR_VFC33_OppFreightIndicatorCont(ApexPages.standardController controller) {
		LAT_Opportunity__c opp = [SELECT id, LAT_Freight_Formula__c, LAT_FreightFormulaDisplay__c  FROM LAT_Opportunity__c WHERE id =: controller.getRecord().Id];
		percent = String.valueOf(opp.LAT_FreightFormulaDisplay__c);
		color = opp.LAT_Freight_Formula__c;
	}
}