objects/LAT_AccountInAction__c.object
<CustomObject>
    <fields>
        <fullName>LAT_Account__c</fullName>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LAT_AccountInAction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>LAT_Execute__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cliente Foco</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LAT_PromotionalAction__c</fullName>
        <label>Ação promocional</label>
        <referenceTo>LAT_PromotionalAction__c</referenceTo>
        <relationshipName>LAT_AccountInAction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Clientes Ação Promocional</label>
    <nameField>
        <displayFormat>AIA-{0000}</displayFormat>
        <label>Cliente Foco</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes Ação Promocional</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_ActionKPI__c.object
<CustomObject>
    <fields>
        <fullName>LAT_KPI__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>KPI</label>
        <referenceTo>LAT_ActionKPIMaster__c</referenceTo>
        <relationshipName>LAT_ActionKPIs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_PromotionalAction__c</fullName>
        <label>Ação Promocional</label>
        <referenceTo>LAT_PromotionalAction__c</referenceTo>
        <relationshipName>LAT_ActionKPIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>KPIs da Ação</label>
    <nameField>
        <displayFormat>KPI-{00000}</displayFormat>
        <label>KPIs da ação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPIs da Ação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_ActionKPIMaster__c.object
<CustomObject>
    <label>KPI´s Ação Promocional</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPI´s Ação Promocional</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LAT_ClientActionKPI__c.object
<CustomObject>
    <fields>
        <fullName>LAT_AccountInAction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Foco</label>
        <referenceTo>LAT_AccountInAction__c</referenceTo>
        <relationshipLabel>Action KPI Clients</relationshipLabel>
        <relationshipName>LAT_ActionKPIClients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAT_ActionKPI__c</fullName>
        <label>Action KPI</label>
        <referenceTo>LAT_ActionKPI__c</referenceTo>
        <relationshipLabel>Action KPI Clients</relationshipLabel>
        <relationshipName>LAT_ActionKPIClients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>LAT_Done__c</fullName>
        <label>Realizado</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_Provided__c</fullName>
        <label>Previsto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAT_RealGoal__c</fullName>
        <formula>IF(AND(!ISNULL(LAT_Provided__c ),LAT_Provided__c != 0), LAT_Done__c / LAT_Provided__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meta Real (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Action KPI Client</label>
    <nameField>
        <displayFormat>CKPI-{0000}</displayFormat>
        <label>LAT_ClientActionKPI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action KPI Clients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LAT_PromotionalAction__c.object
<CustomObject>
    <fields>
        <fullName>LAT_ActionKPI__c</fullName>
        <label>KPIs da ação</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LAT_ActionKPI</valueSetName>
        </valueSet>
    </fields>
    <label>Ação Promocional</label>
    <nameField>
        <label>Ação Promocional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ações Promocionais</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/LAT_ActionKPI.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PDV Executado</fullName>
    </customValue>
    <customValue>
        <fullName>Abordagem Consumidor Misterioso</fullName>
    </customValue>
    <customValue>
        <fullName>Cobertura</fullName>
    </customValue>
    <customValue>
        <fullName>Meta Volume</fullName>
    </customValue>
    <masterLabel>Action KPI</masterLabel>
</GlobalValueSet>

classes/LAT_VFC15_APActionKPIController.cls
public with sharing class LAT_VFC15_APActionKPIController {

	public List<rowWrapper> rows {get; set;}
	public List<LAT_ActionKPI__c> headers {get; set;}

	public LAT_VFC15_APActionKPIController() {
		this.rows = new List<rowWrapper>();
		Map<String,String> params = ApexPages.currentPage().getParameters();
		String paId = params.get('id');

		List<LAT_AccountInAction__c> aiaList = [SELECT id, LAT_Account__r.Name, (Select id, LAT_ActionKPI__c, LAT_ActionKPI__r.LAT_KPI__r.Name,
																										 LAT_AccountInAction__c, LAT_Done__c, LAT_Provided__c, LAT_RealGoal__c
																										 from LAT_ActionKPIClients__r)
																							FROM LAT_AccountInAction__c
																							WHERE LAT_PromotionalAction__c =: paId AND LAT_Execute__c = true];
		Map<id, LAT_ActionKPI__c> actionKPIMap = new Map<id, LAT_ActionKPI__c>([SELECT id, Name, LAT_KPI__r.Name FROM LAT_ActionKPI__c WHERE LAT_PromotionalAction__c =: paId ORDER BY LAT_KPI__r.Name]);
		this.headers = actionKPIMap.values();
		for (LAT_AccountInAction__c aiac: aiaList) {
			this.rows.add(new rowWrapper(aiac, aiac.LAT_ActionKPIClients__r));
		}
		/*for (LAT_AccountInAction__c aiac: aiaList) {
			if (aiac.LAT_ActionKPIClients__r.isEmpty()) {
				List<LAT_ClientActionKPI__c> clientKpis = new List<LAT_ClientActionKPI__c>();
				for (LAT_ActionKPI__c kpi: actionKPIMap.values()) {
					clientKpis.add(new LAT_ClientActionKPI__c(LAT_ActionKPI__c = kpi.id, LAT_AccountInAction__c = aiac.id));
				}
				this.rows.add(new rowWrapper(aiac, aiac.LAT_ActionKPIClients__r));
			} else if (actionKPIMap.values().size() == aiac.LAT_ActionKPIClients__r.size()) {
				this.rows.add(new rowWrapper(aiac, aiac.LAT_ActionKPIClients__r));
			} else if (actionKPIMap.values().size() > aiac.LAT_ActionKPIClients__r.size()){
				List<LAT_ClientActionKPI__c> clientKpis = new List<LAT_ClientActionKPI__c>();
				Set<String> addedKpis = new Set<String>();
				for (LAT_ClientActionKPI__c caKpi: aiac.LAT_ActionKPIClients__r) {
					clientKpis.add(caKPI);
					addedKpis.add(caKpi.LAT_ActionKPI__c);
				}

				for (LAT_ActionKPI__c kpi: actionKPIMap.values()) {
					if (!addedKpis.contains(kpi.id)) {
						clientKpis.add(new LAT_ClientActionKPI__c(LAT_ActionKPI__c = kpi.id, LAT_AccountInAction__c = aiac.id));
					}
				}
				this.rows.add(new rowWrapper(aiac, clientKpis));
			}
		}*/
	}

	public class rowWrapper {
		public LAT_AccountInAction__c aia {get; set;}
		public List<LAT_ClientActionKPI__c> clientKPIs {get; set;}

		public rowWrapper (LAT_AccountInAction__c aia, List<LAT_ClientActionKPI__c> clientKPIs){
			this.aia = aia;
			this.clientKPIs = clientKPIs;
		}
	}
}