objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>RIC Plann&apos;R - Workflow OPP &amp; Produits Finis
Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Projet</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipName>Project_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Phase</label>
    <nameField>
        <label>Nom de la Phase</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Milestone1_Project__c.object
<CustomObject>
    <description>RIC Plann&apos;R - Workflow OPP &amp; Produits finis</description>
    <fields>
        <fullName>RIC_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marque</label>
        <referenceTo>RIC_Brand__c</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RIC_Status__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En création</fullName>
                    <default>true</default>
                    <label>En création</label>
                </value>
                <value>
                    <fullName>En attente de validation</fullName>
                </value>
                <value>
                    <fullName>Validé</fullName>
                </value>
                <value>
                    <fullName>En cours</fullName>
                </value>
                <value>
                    <fullName>A clôturer</fullName>
                </value>
                <value>
                    <fullName>Clôturé</fullName>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
                <value>
                    <fullName>Refusé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RIC Projet</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RIC Projets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Milestone1_Task__c.object
<CustomObject>
    <description>RIC Plann&apos;R - Workflow OPP &amp; Produits finis</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigné à</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Tasks_Assigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Date d&apos;échéance</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <label>Phase</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(LEFT($Api.Partner_Server_URL_320,FIND( &apos;/services&apos;, $Api.Partner_Server_URL_320)) &amp; &quot;/&quot; &amp; Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name, Project_Milestone__r.Project__r.Name)</formula>
        <label>Projet</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RIC_Status__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non diffusé</fullName>
                    <default>true</default>
                    <label>Non diffusé</label>
                </value>
                <value>
                    <fullName>En cours</fullName>
                </value>
                <value>
                    <fullName>Réalisé</fullName>
                </value>
                <value>
                    <fullName>Réalisé - à finaliser</fullName>
                    <label>À finaliser</label>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
                <value>
                    <fullName>Non réalisé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <label>RIC Action</label>
    <nameField>
        <label>Nom de l&apos;action</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RIC Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RIC_Brand__c.object
<CustomObject>
    <description>RIC Plann&apos;R - Workflow OPP &amp; Produits finis
Table de référence JDE 41_S4</description>
    <fields>
        <fullName>RIC_Code_Marque__c</fullName>
        <description>Utilisé comme préfixe des codes de Projets</description>
        <externalId>true</externalId>
        <label>Code Marque</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RIC_Prefixe__c</fullName>
        <label>Préfixe projet</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RIC Marque</label>
    <nameField>
        <label>Marque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RIC Marques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RIC_Batch_UpdateEcheance_Test.cls
@isTest
private class RIC_Batch_UpdateEcheance_Test {
    static testMethod void testPrimaryAddressBatch(){
        user u=new user(id=UserInfo.getUserId());
        u.alias = 'jmsal';
        update u;
        RIC_Brand__c marque = new RIC_Brand__c(RIC_Code_Marque__c='123',Name='test',RIC_Prefixe__c='123');
        insert marque;
        Milestone1_Project__c proj =new Milestone1_Project__c(Name='test',RIC_Brand__c=marque.Id,RIC_Status__c='En cours');
        insert proj;
        Milestone1_Milestone__c phase =new Milestone1_Milestone__c( Name='test',Project__c=proj.Id);
        insert phase;
        Milestone1_Task__c task = new Milestone1_Task__c(Name='test', Assigned_To__c=u.id,Project_Milestone__c=phase.Id,RIC_Status__c='En cours',Start_Date__c=date.newInstance(2017, 10, 2017),Due_Date__c=date.newInstance(2017, 10, 2017) );
        insert task;
        update task;
        
        Database.executeBatch(new RIC_Batch_UpdateEcheance());
        
    }
}