objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>RIC Plann&apos;R - Workflow OPP &amp; Produits Finis
Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Date d&apos;échéance</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <label>Date de démarrage</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Predecessor_Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Phase prédécesseur</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Milestone1_Milestone__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipName>Successor_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Projet</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipName>Project_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Phase</label>
    <nameField>
        <label>Nom de la Phase</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Milestone1_Project__c.object
<CustomObject>
    <description>RIC Plann&apos;R - Workflow OPP &amp; Produits finis</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>What date should this project start?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RIC_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marque</label>
        <referenceTo>RIC_Brand__c</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RIC Projet</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RIC Projets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Milestone1_Task__c.object
<CustomObject>
    <description>RIC Plann&apos;R - Workflow OPP &amp; Produits finis</description>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <label>Phase</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(LEFT($Api.Partner_Server_URL_320,FIND( &apos;/services&apos;, $Api.Partner_Server_URL_320)) &amp; &quot;/&quot; &amp; Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name, Project_Milestone__r.Project__r.Name)</formula>
        <label>Projet</label>
        <type>Text</type>
    </fields>
    <label>RIC Action</label>
    <nameField>
        <label>Nom de l&apos;action</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RIC Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RIC_Brand__c.object
<CustomObject>
    <description>RIC Plann&apos;R - Workflow OPP &amp; Produits finis
Table de référence JDE 41_S4</description>
    <label>RIC Marque</label>
    <nameField>
        <label>Marque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RIC Marques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Milestone2_Charts_GanttController_TEST.cls
/* Test class for Milestone2_Charts_GanttController */
/* christophe.averseng@bluewolf.com - 24/06/2015    */

    @istest
    private class Milestone2_Charts_GanttController_TEST
    {
        static testmethod void Milestone2_Charts_GanttController_TEST()
        {
            // Create a sample Project with one Milestone and one Task
            RIC_Brand__c brand = new RIC_Brand__c(Name='Ricard');
            insert brand;
            Milestone1_Project__c project = new Milestone1_Project__c(RIC_Brand__c = brand.Id, Name='Test project');
            insert project;
            Milestone1_Milestone__c milestone = new Milestone1_Milestone__c(Name='Test Phase',Project__c=project.Id,KickOff__c=Date.Today(),Deadline__c=Date.Today()+10);
            insert milestone;
            Milestone1_Milestone__c milestone2 = new Milestone1_Milestone__c(Name='Test Phase 2',Project__c=project.Id,KickOff__c=Date.Today()+11,Deadline__c=Date.Today()+20, Predecessor_Milestone__c=milestone.Id);
            insert milestone2;
            Milestone1_Task__c task = new Milestone1_Task__c(Name='Test Task',Project_Milestone__c=milestone.Id);
            insert task;
            
            Test.startTest();
            
            // Display gantt chart at Project level
            PageReference m2 = Page.Milestone2_Charts_GanttMilestones;
            Test.setCurrentPage(m2);
            ApexPages.currentPage().getParameters().put('Id', project.Id);
            Milestone2_Charts_GanttController m2c = new Milestone2_Charts_GanttController();
            m2c.myTarget = project.Id;
            m2c.Init();
            
            // Display gantt chart at Milestone level
            PageReference m3 = Page.Milestone2_Charts_GanttMilestones;
            Test.setCurrentPage(m3);
            ApexPages.currentPage().getParameters().put('Id', milestone.Id);
            Milestone2_Charts_GanttController m3c = new Milestone2_Charts_GanttController();
            m3c.myTarget = milestone.Id;
            m3c.Init();
            
            Test.stopTest();
        }
    }