objects/Milestone1_Project__c.object
<CustomObject>
    <description>RIC Plann&apos;R - Workflow OPP &amp; Produits finis</description>
    <fields>
        <fullName>RIC_Code_article__c</fullName>
        <inlineHelpText>Code de l&apos;article principal du projet</inlineHelpText>
        <label>Code article</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>RIC Projet</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RIC Projets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RIC_Article__c.object
<CustomObject>
    <description>RIC Plann&apos;R - Workflow OPP &amp; Produits finis</description>
    <fields>
        <fullName>RIC_Code_Article__c</fullName>
        <description>Alias JDE = LITM</description>
        <externalId>true</externalId>
        <label>Code Article</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RIC_Description_2__c</fullName>
        <description>Alias JDE = DSC2</description>
        <label>Description 2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RIC_Duplique__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Cette case cochée déclenche la duplication des valeurs sur le projet</inlineHelpText>
        <label>Objet master dupliqué</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RIC_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projet</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipName>Articles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RIC_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A finaliser</fullName>
                    <default>true</default>
                    <label>A finaliser</label>
                </value>
                <value>
                    <fullName>A créer partiellement</fullName>
                </value>
                <value>
                    <fullName>A créer</fullName>
                </value>
                <value>
                    <fullName>Créé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RIC_Tech_LockingUser__c</fullName>
        <label>RIC_Tech_LockingUser</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RIC_Tech_isLocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RIC_Tech_isLocked</label>
        <type>Checkbox</type>
    </fields>
    <label>RIC Article</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RIC Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>BypassVR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, user will bypass all validation rules and all look-up filters.</description>
        <inlineHelpText>If checked, user will bypass all validation rules and all look-up filters.</inlineHelpText>
        <label>Bypass Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/RIC_AP02_RIC_Article_TEST.cls
@isTest
private class RIC_AP02_RIC_Article_TEST {
    private static Id Produit_Fini= Schema.SObjectType.RIC_Article__c.getRecordTypeInfosByName().get('Produit Fini').getRecordTypeId();
    private static testMethod void myTestMethod() {
        user u=new user(id=UserInfo.getUserId());
        u.BypassVR__c=true;
        update u;
        Test.startTest();
        Milestone1_Project__c p1 = Milestone1_Test_Utility.sampleProjectActive('test');
        insert p1;
        
        RIC_Article__c article = new RIC_Article__c();
        article.RIC_Project__c = p1.Id;
        article.RecordTypeId=Produit_Fini;
        article.RIC_Duplique__c=true;
        article.RIC_Code_Article__c='12';
        article.RIC_Statut__c = 'A finaliser/';
        article.RIC_Description_2__c = 'Test'; 
        article.RIC_Tech_isLocked__c = true;
        
        article.RIC_Tech_LockingUser__c = UserInfo.getUserId();
        insert article;
        article.RIC_Code_Article__c='1';
        update article;
        RIC_Article__c article1 = new RIC_Article__c();
        article1.RIC_Project__c = p1.Id;
        article1.RecordTypeId=Produit_Fini;
        article1.RIC_Statut__c = 'A finaliser/';
        article1.RIC_Description_2__c = 'Test'; 
        article1.RIC_Tech_isLocked__c = true;
        article1.RIC_Tech_LockingUser__c = UserInfo.getUserId();
        Database.insert(article1, false) ; 
        
        article1.RIC_Duplique__c=true;
        Database.update(article1, false) ; 
        Test.stopTest();
    }
}