objects/Planejamento__c.object
<CustomObject>
    <fields>
        <fullName>Ano_de_Referencia__c</fullName>
        <label>Ano de Referência</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                    <default>true</default>
                    <label>2014</label>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Aprovado_semana_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Aprovado mensal (+semana 1)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>M_s_de_Ref_rencia__c</fullName>
        <label>Mês de Referência</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Janeiro</fullName>
                </value>
                <value>
                    <fullName>Fevereiro</fullName>
                </value>
                <value>
                    <fullName>Março</fullName>
                </value>
                <value>
                    <fullName>Abril</fullName>
                </value>
                <value>
                    <fullName>Maio</fullName>
                </value>
                <value>
                    <fullName>Junho</fullName>
                </value>
                <value>
                    <fullName>Julho</fullName>
                </value>
                <value>
                    <fullName>Agosto</fullName>
                </value>
                <value>
                    <fullName>Setembro</fullName>
                </value>
                <value>
                    <fullName>Outubro</fullName>
                </value>
                <value>
                    <fullName>Novembro</fullName>
                </value>
                <value>
                    <fullName>Dezembro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solicitar_aprova_o_para__c</fullName>
        <label>Solicitar aprovação para</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planejamento mensal (+semana 1)</fullName>
                    <default>true</default>
                    <label>Planejamento mensal (+semana 1)</label>
                </value>
                <value>
                    <fullName>Planejamento semana 2</fullName>
                </value>
                <value>
                    <fullName>Planejamento semana 3</fullName>
                </value>
                <value>
                    <fullName>Planejamento semana 4 (até o fim do mês)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_do_Planejamento__c</fullName>
        <label>Status do Planejamento</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Encerrado</fullName>
                </value>
                <value>
                    <fullName>Não Iniciado</fullName>
                    <default>true</default>
                    <label>Não Iniciado</label>
                </value>
                <value>
                    <fullName>Rejeitado (Aprovação Mensal)</fullName>
                </value>
                <value>
                    <fullName>Aguardando Aprovação</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Modification proposed</fullName>
                </value>
                <value>
                    <fullName>Ok para solicitar Aprovação</fullName>
                </value>
                <value>
                    <fullName>Visitas nao agendadas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Planejamento de Visita</label>
    <nameField>
        <label>Nome do Planejamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planejamentos de Visitas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Visitas__c.object
<CustomObject>
    <description>Visita de cliente</description>
    <fields>
        <fullName>Data_da_Visita__c</fullName>
        <label>Data da Visita</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hora_da_Visita__c</fullName>
        <label>Hora da Visita</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>00:00</fullName>
                </value>
                <value>
                    <fullName>01:00</fullName>
                </value>
                <value>
                    <fullName>02:00</fullName>
                </value>
                <value>
                    <fullName>03:00</fullName>
                </value>
                <value>
                    <fullName>04:00</fullName>
                </value>
                <value>
                    <fullName>05:00</fullName>
                </value>
                <value>
                    <fullName>06:00</fullName>
                </value>
                <value>
                    <fullName>07:00</fullName>
                </value>
                <value>
                    <fullName>08:00</fullName>
                </value>
                <value>
                    <fullName>08:30</fullName>
                </value>
                <value>
                    <fullName>09:00</fullName>
                </value>
                <value>
                    <fullName>09:30</fullName>
                </value>
                <value>
                    <fullName>10:00</fullName>
                </value>
                <value>
                    <fullName>10:30</fullName>
                </value>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
                <value>
                    <fullName>15:00</fullName>
                </value>
                <value>
                    <fullName>15:30</fullName>
                </value>
                <value>
                    <fullName>16:00</fullName>
                </value>
                <value>
                    <fullName>16:30</fullName>
                </value>
                <value>
                    <fullName>17:00</fullName>
                </value>
                <value>
                    <fullName>17:30</fullName>
                </value>
                <value>
                    <fullName>18:00</fullName>
                </value>
                <value>
                    <fullName>19:00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planejamento__c</fullName>
        <label>Planejamento</label>
        <referenceTo>Planejamento__c</referenceTo>
        <relationshipLabel>Visitas</relationshipLabel>
        <relationshipName>Visitas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Resumo_da_Visita__c</fullName>
        <label>Action Plan / Visit Goal</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planejada</fullName>
                    <default>true</default>
                    <label>Planejada</label>
                </value>
                <value>
                    <fullName>Encerrada</fullName>
                </value>
                <value>
                    <fullName>Visit not made</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_do_Planejamento__c</fullName>
        <formula>Planejamento__r.Planning_Status_Translate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status do Planejamento</label>
        <type>Text</type>
    </fields>
    <label>Visita</label>
    <nameField>
        <label>Nome da Visita</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LAT_BR_AP01_Planejamento_TEST.cls
/****************************************************
 Dev: Denis Aranda  Version: 1  Consulting: Valuenet
****************************************************/

@isTest
public with sharing class LAT_BR_AP01_Planejamento_TEST {
	
	static testMethod void UnitTest2(){
		User usuario;
	    try{usuario = [SELECT Id, Name, ProfileId FROM User WHERE IsActive = true LIMIT 1];}catch(Exception e){}
			
		Planejamento__c plan0 = new Planejamento__c(Name = 'Test0', Ano_de_Referencia__c = '2012', M_s_de_Ref_rencia__c = 'Dezembro', Solicitar_aprova_o_para__c = 'Planejamento semana 2', Aprovado_semana_1__c = true, OwnerId = usuario.id );
		insert plan0;
			
		Visitas__c vis = new Visitas__c(Name = 'testVis', Planejamento__c = plan0.id, Hora_da_Visita__c = '01:00', Data_da_Visita__c = date.today().addDays(-3), Resumo_da_Visita__c = '123', Status__c = 'Planejada' );
		insert vis;
		
		plan0.Status_do_Planejamento__c = 'Aguardando Aprovação';
		
		//a fail message should appear
		try{update plan0;}catch(Exception e){}
	}
	
	static testMethod void UnitTest4(){
		
		User usuario;
	    try{usuario = [SELECT Id, Name, ProfileId FROM User WHERE IsActive = true LIMIT 1];}catch(Exception e){}
			
		Planejamento__c plan0 = new Planejamento__c(Name = 'Test0', Ano_de_Referencia__c = '2012', M_s_de_Ref_rencia__c = 'Dezembro', OwnerId = usuario.id );
		insert plan0;
		
		Planejamento__c plan = new Planejamento__c(Name = 'Test', Ano_de_Referencia__c = '2013', M_s_de_Ref_rencia__c = 'Janeiro', OwnerId = usuario.id );
		insert plan;
			
		Visitas__c vis = new Visitas__c(Name = 'testVis', Planejamento__c = plan0.id, Hora_da_Visita__c = '01:00', Data_da_Visita__c = date.today().addDays(-3), Resumo_da_Visita__c = '123', Status__c = 'Planejada' );
		insert vis;
		
		plan0.Status_do_Planejamento__c = 'Aguardando Aprovação';
		//a fail message should appear
		try{update plan0;}catch(Exception e){}
		
		plan.Status_do_Planejamento__c = 'Aguardando Aprovação';
		//a fail message should appear
		try{update plan;}catch(Exception e){}
	}

	static testMethod void testMonthlyPlanGenerator(){
		LAT_BR_Planejamento_Scheduler scheduler = new LAT_BR_Planejamento_Scheduler();
		scheduler.execute(null);

		

		Account braOnTrade               = LAT_Account_TestFactory.getAccountOnTradeBraComplete();
		braOnTrade.OwnerId               = UserInfo.getUserId();
		insert braOnTrade;

		LAT_BR_Planejamento_Batch batch = new LAT_BR_Planejamento_Batch();
		Database.QueryLocator qLocator = batch.start(null);

		batch.execute(null, Database.Query(qLocator.getQuery()));

	}
	
}