objects/User.object
<CustomObject>
    <fields>
        <fullName>ASI_MFM_Bypass_Callouts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ASI MFM Bypass Callouts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ASI_MFM_Country__c</fullName>
        <label>ASI MFM Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TW</fullName>
                </value>
                <value>
                    <fullName>HK</fullName>
                </value>
                <value>
                    <fullName>GF</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>RM</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TR</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>PH</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>VN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BypassTriggers__c</fullName>
        <description>User will bypass selected triggers.</description>
        <inlineHelpText>User will bypass selected triggers.</inlineHelpText>
        <label>Bypass Triggers</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Autofollow_User_InsertUpdate</fullName>
                </value>
                <value>
                    <fullName>AutoJoin_User_InsertUpdate</fullName>
                </value>
                <value>
                    <fullName>ChatterEmailSettings</fullName>
                </value>
                <value>
                    <fullName>ESNProjectTrigger</fullName>
                </value>
                <value>
                    <fullName>AP01</fullName>
                </value>
                <value>
                    <fullName>ASI_HK_CRM_SalesOrderAssignApprover</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_ValidateSubBrandCode</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_GF_LockPOLine</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_GF_POTypeChange</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_CN_AccountsCRMCodeAutoNumber</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_TW_AccountMovement_TgrHdlr</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_CN_AccountsAdditional_TriggerCls</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_CN_ContractPONoAutoNumber</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_CN_GenPhPayeeLnItmNo_TgrHdlr</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_CN_Contract_TriggerClass</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_TR_ByPassTrigger</fullName>
                </value>
                <value>
                    <fullName>ASI_GiftBox_VN_HR_User</fullName>
                </value>
                <value>
                    <fullName>ASI_TnE_HK_ClaimHeaderUpdatePO</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_JP_Payment</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_JP_JDE_Accruals</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_KR_ChangeSupplier</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_TH_PlanAmountChecking</fullName>
                </value>
                <value>
                    <fullName>ASI_MFM_PaymentLineItem_TriggerClass</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_TW_FreeGoodsRequest_TriggerCls</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_TW_PAF_TriggerCls</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_TW_RequestItem_TriggerCls</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_JP_SOLineItemSetAvailability</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_JP_SOLineItemCalUnitPrice</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_SG_FOC_ValidationHelper_V2</fullName>
                </value>
                <value>
                    <fullName>ASI_CRM_SG_FOC_ValidationHelper_V3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ASI_CRM_CN_Function.cls
public without sharing class ASI_CRM_CN_Function{
    
    public class CRMException extends Exception {}
 
    
    private static map<Id, User> MUserID = new map<Id, User>();
    private static list<user> LUser = new list<user>();
    static{
        LUser = [Select id, name, BypassTriggers__c, username from user where BypassTriggers__c != null];
        
        MUserID = new Map<id,user>(LUser);
        // Uncomment by Michael Yip (Introv) 08Aug2014
        for(User u : LUser){
            MUserID.put(u.id,u);
        }
    }

    public static User getSystemAdminUser(){      
        list<User> users = [SELECT Id, Name, Managerid, ASI_MFM_Bypass_Callouts__c, ASI_MFM_Country__c, UserRole.DeveloperName 
                            FROM User 
                            WHERE Profile.Name = 'System Administrator' AND IsActive = TRUE
                            LIMIT 1];      
        return users.size()>0 ? users[0] : null;
    }
    
    public static user getUser(id UserID){
        return MUserID.get(UserID);
    }
    public static List<user> getUserList(){
        return LUser;
    }
    
    private static set<string> m_BypassedTriggers = null;
    public static set<string> BypassedTriggers {
        get {
            if(m_BypassedTriggers==null) {
                m_BypassedTriggers = new set<String>();
                list<User> users = [SELECT Id, BypassTriggers__c FROM User WHERE Id = :UserInfo.getUserId()];
                System.debug(users[0]);
                if (users.size() > 0 && users[0].BypassTriggers__c != null) {
                    String bypassTriggerWholeStr = users[0].BypassTriggers__c;                    
                    List<String> bypassTriggerStrs = bypassTriggerWholeStr.split(';', 0);
                    System.debug(bypassTriggerStrs );
                    for (String bypassTriggerStr : bypassTriggerStrs) {
                    system.debug(bypassTriggerStr.toLowerCase());
                        m_BypassedTriggers.add(bypassTriggerStr.toLowerCase());
                    }
                }
            }    
            return m_BypassedTriggers;
        }
    }
    public static boolean IsBypassTrigger(string triggerKey) {
        set<string> tempBypassedTriggers = BypassedTriggers;
        system.debug(tempBypassedTriggers);
        system.debug(triggerKey);
        return tempBypassedTriggers!=null && tempBypassedTriggers.contains(triggerKey.toLowerCase());
    }

    public static string getFiscalYear(date d) {
        if(d.month()<=6)
            return string.valueOf(d.year()-1) + '/' + string.valueOf(d.year());
        else
            return string.valueOf(d.year()) + '/' + string.valueOf(d.year()+1);
    }
}